### ISSUE TITLE
Unable to access Contacts Report

### ISSUE THREAD

**Issue by baileydoestech** [putyourlightson/craft-campaign#1]
Enjoying the new plugin so far but keep seeing the following database exception when trying to access the Contacts report.

Currently running Craft 3 RC15 on Homestead Laravel 

![image](https://user-images.githubusercontent.com/3185073/37393885-4f70e19c-276a-11e8-813b-2dd1b56477b4.png)

**Comment by putyourlightson** [comment]
Thanks, will fix this in the next release. 

If you you need this to work until then, you can edit your my.cnf file and remove the  ONLY_FULL_GROUP_BY option from sql_mode, as explained [here](https://craftcms.stackexchange.com/a/12106/180).

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/b40ad25f390bd0f545de8c4fa77ff2c88d479b6d.
