### ISSUE TITLE
Can't send test email

### ISSUE THREAD

**Issue by harispepic** [putyourlightson/craft-campaign#10]
Hello

I can't send a test email. I've setup everything like in the docs but I'm always getting this error.

`POST http://craft.local/index.php?p=admin/actions/campaign/campaigns/send-test 500 (Internal Server Error) 
CampaignEdit.js?v=1530856147:19 Uncaught TypeError: Cannot read property 'success' of null
    at CampaignEdit.js?v=1530856147:19
    at Object.error (Craft.js:361)
    at c (jquery.js:3317)
    at Object.fireWith [as rejectWith] (jquery.js:3447)
    at l (jquery.js:9274)
    at XMLHttpRequest.<anonymous> (jquery.js:9514)`

Can anyone help me out?

Regards

**Comment by putyourlightson** [comment]
Have you set up and tested your _Transport Type_ correctly in the plugin's _Email Settings_?

**Comment by putyourlightson** [comment]
Closing as no response.
