### ISSUE TITLE
New 'alert/notification' sendout type

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#102]
### Is your feature request related to a problem? Please describe.

Sometimes there is a need to send out notification/alert emails to mailing list members, e.g. a new job or event entry has been posted or a member's data has changed. 

It feels counter-intuitive to have a separate system to manage these because:
- you may be using HTML emails and want to leverage existing campaign templates
- you may want some degree of Craft data in the emails
- they get sent to mailing list members
- members can control what alerts they want to receive via custom fields and segments
- admins may want to be able to manage the alert email content within the CMS

### Describe the solution you would like
I propose a new type of sendout called 'alert' or 'notification'. It would probably need:
- trigger/s to queue the sendout, e.g. new entry posted of type X or custom field changed to X
- ability to send multiple times to the same members
- no limits on sending per day (dictated by event trigger instead)
- ability to pass in event variable that triggered the email - giving access to 'object', e.g. job entry or user

### Describe alternatives you have considered
Currently achievable with custom module/plugin and standard campaign but would have been difficult for a non-developer to set up. In addition, does create lots of campaigns and sendouts in the list - a dedicated singular alert/notification sendout would be preferable (in same way as automated/recurring).

Posting this to start a conversation to see if worthwhile feature to flesh out and consider, from https://github.com/putyourlightson/craft-campaign/issues/100 :)

**Comment by bencroker** [comment]
Thanks Keir, we'll add this to the list of feature considerations and let you know when we have more to report.

**Comment by daveyjones** [comment]
Oh man...this is exactly what I need. I've been trying all kinds of hacks to get something like this to work.

Here's my use case. We're building a site where end users are submitting applications. The content manager can mark an application as accepted by changing a dropdown field in the control panel. We need an email to be sent to the applicant when this happens. I have a segment that identifies users who have an accepted application, but I can't seem to find a way to actually get the emails to send.

Is there a way to get this working in the context of the current feature set?

**Comment by iamkeir** [comment]
@daveyjones the custom module/plugin code is probably the way to go in the absence of a native feature, you can do almost anything. @bencroker was brilliant in guiding us through our implementation, hopefully if you are a developer/have access to a developer, you could take a similar approach. Apologies I can't give more insight as the project was from a long while back!

**Comment by daveyjones** [comment]
Thanks @iamkeir, we may end up needing to do that. I'm a developer, but I'm hoping to find a solution that can be understood and configured by our non-technical client if at all possible. Note that my use case does not require multiple sendouts of the same campaign. Rather, I just need the campaign sent once a user is added to a segment. I think an automated sendout is very close to what I need, except we have no control over what the trigger is. Currently, the only trigger is if the contact is added to the mailing list, but if I could select the trigger to be when the contact is added to a segment, then my use case would be satisfied.

@bencroker Would this make sense to open up as a separate enhancement request?

**Comment by daveyjones** [comment]
@bencroker Please ignore my previous comment. In talking with the client, we determined that having these notifications go out once per day at a specific time is actually fine, which is covered by recurring sendouts. It may still be useful to others to be able to trigger a sendout immediately from a segment change, but it's no longer necessary for our use case.

**Comment by bencroker** [comment]
Instant notifications is not a use-case that is particularly well suited to the Campaign plugin, as in most cases you would want to be able to define custom rule-sets. Glad to hear that a daily sendout met your client's needs @daveyjones.

**Comment by bencroker** [comment]
I'm closing this out, since version 2.0.0 adds the ability to add custom condition rules to recurring sendouts, so it is now possible to create a daily recurring sendout that is sent only if one or more condition rules (if a new was was posted in the past 24 hours, for example) hold true. 

See the relevant issue at https://github.com/putyourlightson/craft-campaign/issues/305. Example condition rules are available at https://github.com/putyourlightson/craft-campaign/tree/v2/examples/conditions/sendouts

The recipients of the sendout can also be segmented using custom condition rules, another 2.0.0 feature.

<img width="834" alt="165372313-9475351a-ff36-4087-89f5-082566cc9d99" src="https://user-images.githubusercontent.com/57572400/166819300-c3d1eb0d-aba9-4451-bafc-de01367ea58c.png">
