### ISSUE TITLE
Amazon SES Webhook not working

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-campaign#103]
The Amazon SES webhook has been reported as not working. Assigning myself to look into this and fix.

**Comment by philipboomy** [comment]
Info to help troubleshooting this:

Using Amazon SNS for pinging the webhook
Have enabled full headers

**Comment by benface** [comment]
I have the same issue. Bounces and complaints are showing 0 in Campaign even though I see in the SES dashboard that there have been.

**Comment by bencroker** [comment]
Fixed in 1.15.3.
