### ISSUE TITLE
Sending of the sendout X failed after 3 send attempt(s)

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#104]
### Describe the bug
Despite people receiving our sendout emails, the `campaign.log` still has plenty of info logs in the form of: `2019-12-22 18:24:06 [][][info] Sending of the sendout X failed after 3 send attempt(s). Please check that your Campaign email settings are correctly configured and check the error in the Craft log.`

Which Craft log does this refer to? And should we be concerned? 

As I say, the emails seem to be sent - although it seems to fail when it logs out this message, then attempts the sendout again...

Because of that I have a feeling it is linked to https://github.com/putyourlightson/craft-campaign/issues/40 perhaps in that it fails when it reaches a certain email, then stops, then retries from the next email up until it hits a failing email again.

### Versions
- Plugin version: 1.12.4
- Craft version: Craft Pro 3.3.18.4

**Comment by bencroker** [comment]
This log message indicates that the plugin could not connect to the email delivery service after 3 attempts. This number is configurable with the [maxSendAttempts](https://github.com/putyourlightson/craft-campaign/blob/1.12.4/src/config.php#L64) config setting.

If it is working on the next retry and emails are being sent then there is nothing to be concerned about. Your email delivery service is probably just throttling the number of emails that is allows to be sent in a given time.

**Comment by iamkeir** [comment]
That sounds like the problem - I’ll check with my host. Thank you for such
a swift response.

**Comment by bencroker** [comment]
Sure thing!
