### ISSUE TITLE
Doesn't use the mailer component?

### ISSUE THREAD

**Issue by jaydensmith** [putyourlightson/craft-campaign#105]
I have a client that requires emails to be sent using their own SMTP server for privacy reasibs - that uses a self-signed cert. This works fine with Craft by overriding the mailer component, however, this plugin does not seem to use the mailer component so the emails fail to send:

```php
'components' => [
    'mailer' => function() {
        // Get the stored email settings
        $settings = App::mailSettings();

        $config = App::mailerConfig($settings);

        $config['transport']['streamOptions'] = [
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true,
            ]
        ];

        return Craft::createObject($config);
    }
]
```

**Comment by bencroker** [comment]
The Campaign plugin has its own email settings under _Settings → Email_ so that it can be configured to use a different transport type than Craft. 

You can configure the transport type and its settings to your specific needs in the config settings:
https://github.com/putyourlightson/craft-campaign/blob/1.13.2/src/config.php#L33-L37

**Comment by jaydensmith** [comment]
Hey @bencroker, thanks for this, but I don't see how this will let me configure `streamOptions`.
```php
'streamOptions' => [
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true,
    ],
],
```

**Comment by jaydensmith** [comment]
@bencroker, for now, I have gotten around this by subclassing `craft\mail\transportadapters\Smtp`.

**Comment by bencroker** [comment]
Oh nice, well that's probably a better solution anyway!
