### ISSUE TITLE
Getting an error "Email has already been taken" after deleting a contact, and then re-creating with same email id

### ISSUE THREAD

**Issue by hashtagerrors** [putyourlightson/craft-campaign#106]
Steps to reproduce the error:

1.  Create a contact with any email address (for e.g. test@gmail.com).
2.  Delete the Contact through "admin/campaign/contacts/view" page.
3.  Create a contact with same email address used before. In this case test@gmail.com

Craft PRO Version : 3.3.20.1
Campaign Lite Version : 1.13.1

**Comment by bencroker** [comment]
The contact is put in a `Trashed` state after being deleted. Filter by that status and you will see it.
More on Craft CMS Garbage collection [here](https://docs.craftcms.com/v3/gc.html).
