### ISSUE TITLE
Dashboard Widget

### ISSUE THREAD

**Issue by DaveBeirne** [putyourlightson/craft-campaign#107]
### Question
Sorry if this is the incorrect category but is there a way to show subscribers on the dashboard via widget (new sign ups / campaigns opened etc)

Perhaps this is a feature request

### Additional context
Great plugin BTW

**Comment by bencroker** [comment]
A dashboard widget would be a feature request. Can you provide some more details as to what specifically you can imagine being useful information to have?

**Comment by DaveBeirne** [comment]
Hi Ben,
 A widget to show on dashboard:

-  Number value for New Subscribers / Unsubscribes
-  Last Campaign Sent : Opened / Clicked 
-  Click Through Rate

Mostly stats that you already provide but to show on the dashboard  :)

it is a "nice to have" feature for clients :)

**Comment by DaveBeirne** [comment]
Dukt Analytics  plugin does this nicely with charts (think it is chartjs they are using )
![Screenshot 2020-02-18 at 12 56 57](https://user-images.githubusercontent.com/1081103/74738170-44000480-524e-11ea-8526-230f65ff4d77.png)

**Comment by bencroker** [comment]
Thanks Dave, will consider this for a future release.

**Comment by DaveBeirne** [comment]
Great Ben !

**Comment by migmake** [comment]
I would love to see that!

**Comment by bencroker** [comment]
What are the most important stats you would like to have available in a dashboard widget?

**Comment by migmake** [comment]
For me that would be the mailing list subscribers count.
Like here with the number of users.

**Comment by bencroker** [comment]
@migswd Which mailing lists though? There could be many. Do you have a visual comp in mind?

**Comment by migmake** [comment]
Perhaps in the widget we could choose which mailing list to display ?

**Comment by bencroker** [comment]
So are you thinking that each dashboard widget would show a different mailing list?

**Comment by migmake** [comment]
Hum not sure to understand what you mean sorry.

I just imagined something like here where I can choose a user group to display :
(same for choosing a mailing list to show)

**Comment by bencroker** [comment]
Your attachments are not working when you respond via email, it seems.

**Comment by migmake** [comment]
Sorry here it is.
![CleanShot 2022-10-12 at 12 15 35@2x](https://user-images.githubusercontent.com/3531623/195316836-c2572864-917d-4bab-922f-bfce379ae10f.jpg)
![CleanShot 2022-10-12 at 12 16 04@2x](https://user-images.githubusercontent.com/3531623/195316907-116e58ad-0ce9-499e-9d80-e5cb24637d9f.jpg)

**Comment by bencroker** [comment]
I've added two dashboard widgets for the upcoming 2.4.0 release. Any thoughts on these?

<img width="847" alt="Screenshot 2023-01-07 at 19 38 41" src="https://user-images.githubusercontent.com/57572400/211177051-6093fa58-2598-4f19-a15a-3d76d3fc8c78.png">

<img width="848" alt="Screenshot 2023-01-07 at 19 38 52" src="https://user-images.githubusercontent.com/57572400/211177060-e772698a-63bd-457e-b836-1ffa04c3951f.png">

**Comment by migmake** [comment]
Hi Ben.

Thats great thank you.

It would be awesome also to have a graph to see the evolution of the email base :)
￼

Best.

**Comment by bencroker** [comment]
I personally love charts, _provided_ they offer useful data. Are you able to show me an example of a New Users widget that provides value, as a comparison? I'm not convinced that it offers any benefits over the numerical data shown above.

**Comment by bencroker** [comment]
Released in version 2.4.0.
