### ISSUE TITLE
Email Favicon / Profile Image

### ISSUE THREAD

**Issue by DaveBeirne** [putyourlightson/craft-campaign#108]
### Question
Is it possible to set the email image icon which some email clients now support ? 

### Additional context
Currently it is using the Favicon on general settings e.g.
<img width="306" alt="Screenshot 2020-02-24 at 11 26 17" src="https://user-images.githubusercontent.com/1081103/75149244-6e900880-56f9-11ea-9f19-09a6712f7feb.png">

And we want the campaigns to be more personable and use an image of a real person without changing the Craftcms General Favicon

**Comment by bencroker** [comment]
I believe the email clients that support such images grab them from Gravatar or Google accounts, so the best way to achieve this would be to use a new email address to send campaigns from and give that email address its own image. As to how to do that, there is very limited literature to be found online, but these articles might help:
https://medium.com/@JamesCridland/how-to-get-your-logo-or-picture-to-appear-with-your-emails-in-gmail-and-inbox-by-gmail-if-you-89650077be7
https://customer.io/docs/adding-sender-image
