### ISSUE TITLE
Amazon SES not sending

### ISSUE THREAD

**Issue by dgrigg** [putyourlightson/craft-campaign#109]
### Question
Trying out your plugin with Amazon SES and I'm getting this error after adding my AWS key and hitting the 'test email' button I get this error message:

"There was an error testing your email settings."

I went through the log files trying to find something, no luck. Any ideas. I have the AWS region, key and secret set. Is there something I'm missing?

**Comment by bencroker** [comment]
Can you test the same SES credentials with Craft's email settings, to help narrow it down? If it doesn't work there either then this may be an issue with your credentials or the Amazon SES plugin.

**Comment by dgrigg** [comment]
It's not working from the Craft email settings either. Is there something special I need to setup in SES besides having my AWS key/secret/region?

**Comment by bencroker** [comment]
Are you using AWS Identity and Access Management (IAM) user access keys? What region are you using?

**Comment by dgrigg** [comment]
I'm using access keys. us-east-1 for region

**Comment by dgrigg** [comment]
<img width="787" alt="Screen Shot 2020-02-25 at 9 35 58 PM" src="https://user-images.githubusercontent.com/166361/75306375-dab45e80-5816-11ea-812e-ad0f851f83a6.png">

**Comment by dgrigg** [comment]
<img width="787" alt="Screen Shot 2020-02-25 at 9 35 58 PM" src="https://user-images.githubusercontent.com/166361/75306424-fc154a80-5816-11ea-8d32-21b5af85efa7.png">

**Comment by dgrigg** [comment]
Does being in sandbox mode on SES cause issues?

**Comment by bencroker** [comment]
Possibly, this really isn't a Campaign issue though. Can you test it out of sandbox mode and if it still does not work then please create an issue in the the Amazon SES plugin repo.
