### ISSUE TITLE
Postgresql case sensitivity issue

### ISSUE THREAD

**Issue by matevisky** [putyourlightson/craft-campaign#11]
Hi

The plugin is not working at all under postgresql database:
https://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive

Example:
```
SQLSTATE[42703]: Undefined column: 7 ERROR: column campaign_mailinglists.mailinglisttypeid does not exist
LINE 5: ...ilinglisttypes" ON campaign_mailinglisttypes.id = campaign_m...
^
HINT: Perhaps you meant to reference the column "campaign_mailinglists.mailingListTypeId".
```

Can you fix this, we are planing to use this plugin

Thank you

**Comment by putyourlightson** [comment]
Yes, we're working on a fix for this.

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/f20beba116afcb87e1b765b5ed6446ef67d342f8
