### ISSUE TITLE
Can't save Subscribe Success Template

### ISSUE THREAD

**Issue by jules1091** [putyourlightson/craft-campaign#110]
I tried to save the the "Subscribe Verification Email Template", the "Subscribe Verification Success Template" and the "Subscribe Success Template" in the Mailing List Settings but the "Subscribe Success Template" was not saved. I didn't get any errors on save and the other two templates were saved correctly. 
![image](https://user-images.githubusercontent.com/59639959/75668859-43b62f00-5c7a-11ea-88e3-e1823a9ed0e4.png)

### Versions
- Plugin version: 1.13.2 lite
- Craft version: 3.3.18

**Comment by bencroker** [comment]
I can't replicate this locally. Does it not save the value on subsequest saves either?

**Comment by jules1091** [comment]
No. Only the values of "Subscribe Verification Email Template" and "Subscribe Verification Success Template". The value of "Subscribe Success Template" is always empty. I tried to save it multiple times.

**Comment by bencroker** [comment]
That's strange. Can you please send login credentials to info@putyourlightson.net (assuming this is available online) and we'll look into it?

**Comment by bencroker** [comment]
Fixed in version 1.13.3. Thanks for helping me resolve the issue!
