### ISSUE TITLE
Contact unable to add an email previously deleted

### ISSUE THREAD

**Issue by DaveBeirne** [putyourlightson/craft-campaign#111]
### Question
Hi i am having an issue where all contacts were deleted and i am unable to add same ones again.
I use 2 language sites but i checked both versions and no contacts in All / Trash etc..

I have done the following:
- ./craft gc ( all garbage collection done )
- Removed all mailing lists and added them again
- Removed all contact lists and added them again
- Updated Craftcms to 3.4.9
- Campaign 1.13.3
- Checked import history and removed them
- Cleared all caches

I can add new contact with **no issue**, I now i am not sure why it still says email already exists...

### Additional context
![Screenshot 2020-03-04 at 14 08 36](https://user-images.githubusercontent.com/1081103/75887604-f5dc2b00-5e21-11ea-849d-5f17fb962466.png)

**Comment by DaveBeirne** [comment]
Also i did an export of new mailing lists to confirm and they are empty

**Comment by DaveBeirne** [comment]
Another thing i tried:
- I added a new email ( never used before )
- Deleted the email
- Deleted email was showing in trash
- Then in terminal ran ./craft gc 
- Collection done
- Tried added same email again and it added without any issue
- Tried old email from the previous group and it still says already exists ...

So i am not sure where is getting cached or saved

**Comment by DaveBeirne** [comment]
Reports > contacts showing the subscribers which is also weird as they dont exist

![Screenshot 2020-03-04 at 14 37 11](https://user-images.githubusercontent.com/1081103/75890025-b1528e80-5e25-11ea-96ef-e93632c0a536.png)

**Comment by DaveBeirne** [comment]
Uninstalling the plugin and reinstalling fixed the issue but a pain if you have alot of data and it happens

**Comment by bencroker** [comment]
Contacts are put in a `Trashed` state after being deleted. Filter by that status and you will see them.

For reference:
https://github.com/putyourlightson/craft-campaign/issues/106
https://github.com/putyourlightson/craft-campaign/issues/89
https://github.com/putyourlightson/craft-campaign/issues/52

**Comment by DaveBeirne** [comment]
Hi Ben,

If you read the message you will see that it wasnt the case above!

**Comment by DaveBeirne** [comment]
This is a bug

**Comment by bencroker** [comment]
Hmm, what was the error message that appeared when contacts were not saved?

**Comment by DaveBeirne** [comment]
it gave the normal **Email XXX@XXX.com has already been taken.**

For some reason, it saved the old or cached the trashed emails even after collecting garage on terminal..It did not show them in trashed list but they were there somewhere.... very odd bug, uninstalling and reinstalling Campaign was the only fix.

i did all the steps above in first message and still happened

**Comment by bencroker** [comment]
I cannot replicate the issue locally. Note that running garbage collection will not delete all trashed items by default. You can either enter `yes` if prompted, or run `./craft gc --delete-all-trashed=1` to force deletion. After doing so it is possible to create a new contact with the deleted contact's email address.
https://docs.craftcms.com/v3/gc.html#forcing-garbage-collection
