### ISSUE TITLE
Deleting a Contact does not update subscription count

### ISSUE THREAD

**Issue by christophpaster** [putyourlightson/craft-campaign#112]
### Describe the bug
When manually deleting a contact without unsubscribing it before, the subscription-count remains the same. This results in unfinished sendouts, as more recipients are estimated than really exist. 

### To reproduce
Steps to reproduce the behaviour:
1. Have a test-mailing list with a few subscribers
2. Delete 2 contacts directly without unsubscribing them
3. Check subscription count — still the same
4. Do a test-sendout: wrong recpients estimated, sendout is never finished

### Expected behaviour
When deleting a user, the unsubscribe-function should be triggered to keep the subscription-count correct. Also with sendouts, rather do count the existing users in the mailing list then using an extra count-variable. 

### Versions
- Plugin version: 1.13.2
- Craft version: 3.3.18.1

**Comment by bencroker** [comment]
My guess is that the contact still exists in the trashed state, but I agree that the subscription count and sendout recipients need to be fixed, thanks for raising the issue.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/aede3b02ddfffb6ef983455f37a5bfb34bd20872 for the next release.
