### ISSUE TITLE
Subscribe to list on other website (on multisite setup)

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#113]
Hi

I'd like to create a subscribe form on website B for a mailing list that is created on website A. If I do
`{% set mailingList = craft.campaign.mailingLists.id(2900).one() %}`
I get an error message saying that mailing list does not exist. (It's created on site A, and the subscribe form is on site B.)

It's a multilingual website but the mailing list is one list in one language, so only created on one site.

**Comment by bencroker** [comment]
Can you try specifying the handle of the site in which the mailing list exists, as the current site is used by default.

```
{% set mailingList = craft.campaign.mailingLists.id(2900).site('siteA').one() %}
```

**Comment by bartrylant** [comment]
That works for displaying the form, but as soon as I try to subscribe, I get a 404 error saying
"Mailing list not found."

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/3d3b3407faa86d36746eb3a55779f80e2123fd4d for the next release.
