### ISSUE TITLE
Changes to the project config are not possible while in read-only mode

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#114]
When pushing a local dev site with Campaign installed, to a staging site (where admin changes are not allowed) I get this error:

`Changes to the project config are not possible while in read-only mode`

**Comment by bencroker** [comment]
What version of Craft and Campaign are you running in both environments?

**Comment by bencroker** [comment]
Any update on this @bartrylant?

**Comment by bencroker** [comment]
Closing due to lack of response.
