### ISSUE TITLE
Clicking on unsubscribe url in email causes error

### ISSUE THREAD

**Issue by PixelGarden** [putyourlightson/craft-campaign#116]
When a user clicks on the unsubscribe url in an email an error is thrown, this didn't happen in previous versions.

PDOException: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous.

Looks to be related to this query:

```
SELECT `campaign_contacts`.*
FROM `campaign_contacts`
INNER JOIN `elements` `element` ON `campaign_contacts`.`id` = `element`.`id`
WHERE (`element`.`dateDeleted` IS NULL) AND (`id`='12345')
```

Craft Pro 3.4.9
Campaign 1.14.0

**Comment by bencroker** [comment]
Thanks for reporting this, fixed in 1.14.1.
