### ISSUE TITLE
Contact not saving

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#118]
### Describe the bug
A contact will not save after manual creation or import from user list (running on postgres 11 database 

### To reproduce
Contacts -> new contact -> contact created -> OK
Contact -> edit contact -> save contact -> not OK 

### Expected behaviour
Contact should save and display success message 

### Screenshots
![image](https://user-images.githubusercontent.com/3259752/77110980-c2ef8500-6a26-11ea-999a-7a311d3f322c.png)

### Versions
- Plugin version: latest dev 
- Craft version: Craft Pro 3.4.10.1

**Comment by bencroker** [comment]
Turned out this was a Postgres issue after all! Fixed in https://github.com/putyourlightson/craft-campaign/commit/a8f4efe71f573bfd388b3d9e9aff14e3ef25ae03.

**Comment by bartroelands** [comment]
Ok, thx will check and let you know.

**Comment by bartroelands** [comment]
tested and OK. Will continue setup test run tonight.

**Comment by bencroker** [comment]
Glad to hear it!
