### ISSUE TITLE
Remove Postmark recommendation from docs

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-campaign#119]
I see [in the documentation](https://putyourlightson.com/plugins/campaign#email-delivery) that Postmark is one of the recommended services/plugins to use with Campaign, but Postmark [explicitly forbids bulk email](https://postmarkapp.com/support/article/831-why-cant-i-send-bulk-emails). So I think that recommendation should either be removed from the documentation, or a note should be added.

**Comment by bencroker** [comment]
You're right about Postmark's policy, but many people use the Campaign plugin to send transactional email (which Postmark allows) to their users. I've added a note to the docs:
https://putyourlightson.com/plugins/campaign#email-delivery
