### ISSUE TITLE
Graph in Campaigm > Report wont update

### ISSUE THREAD

**Issue by PopaWeb** [putyourlightson/craft-campaign#120]
### Describe the bug
I have a campaign that was sent on march 24. Some of the email have been open on the 25 and 26 but not show in the graph.

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Campaign"
2. Click on the campaign that was sent
3. Click on "Report" tab

### Expected behaviour
Updating graph on email opened, clicks....

### Screenshots
![Screen Shot 2020-03-26 at 08 05 24](https://user-images.githubusercontent.com/28791029/77645505-30287c00-6f39-11ea-8dae-ad86d500526c.png)

### Versions
- Plugin version: 1.14.2
- Craft version: Craft Pro 3.4.10.1

**Comment by bencroker** [comment]
Since you are viewing hours, only the first 24 hours of actions are displayed. Change to days and you should see the missing actions from the subsequent days.
