### ISSUE TITLE
Create and edit contact

### ISSUE THREAD

**Issue by leightonhughes** [putyourlightson/craft-campaign#121]
### Describe the bug
When creating a new contact or editing a contact I'm getting an error saying 'Invalid field handle: firstName'  I have added a plain text field with a handle of firstName and another of lastName and added in the settings area of Campaign.

### Error message
---

if (!$field) {
            throw new Exception('Invalid field handle: ' . $fieldHandle);
        }

---

$this->normalizeFieldValue($fieldHandle);

---
### Versions
- Plugin version: 1.14.2
- Craft version: 3.4.11

**Comment by bencroker** [comment]
Thanks, fixed in version 1.14.3.
