### ISSUE TITLE
New users are automatically subscribed to all synced mailing lists with unsubscribe form enabled

### ISSUE THREAD

**Issue by BrandKits** [putyourlightson/craft-campaign#123]
### Describe the bug
We have multiple mailing lists synced to a user group so that if a user is logged in we can show the lists they are subscribed to, with an unsubscribe option.

However, when a new user registers, they are automatically subscribed to all synced mailing lists (where unsubscribe form enabled). This is a GDPR issue as they haven't actively given consent.

This may be intended behaviour of the sync feature, if so, is there another way to relate the contact to the user to show subscription status, and enable subscribe/unsubscribe? 

### To reproduce
Steps to reproduce the behaviour:
1. Add mailing list type with unsubscribe forms allowed
2. Add mailing lists and sync to user group
3. Add new user
4. Check Contact > Mailing Lists and see all lists with unsubscribe form allowed are already subscribed to

### Expected behaviour
Mailing lists are synced to user group (so contact and user are related), but observe active subscription consent.

### Screenshots
https://www.dropbox.com/s/78t1vwytqv3a7s6/Screenshot%202020-03-31%2010.12.31.png?dl=0
https://www.dropbox.com/s/hvk7us74802uxm0/Screenshot%202020-03-31%2010.06.30.png?dl=0
https://www.dropbox.com/s/097ra8vvtsnanws/Screenshot%202020-03-31%2010.02.11.png?dl=0

### Versions
- Plugin version: 1.14.1
- Craft version: 3.4.10.1

**Comment by bencroker** [comment]
This isn't a bug but expected behaviour. Since you have synced a user group with a mailing list, a new user in that user group will automatically be subscribed to that mailing list.

To achieve your desired behaviour, couldn't you create a mailing list that exists only for the purposes of syncing users, for example `All Collectors`? New users would be synced with contacts and subscribed only to that mailing list that is never actually sent to.

**Comment by BrandKits** [comment]
And that's all it took... thank you. One 'master' list to sync contacts/users, and then the users can subscribe/unsubscribe to the rest of the lists. Loving this plugin.

**Comment by bencroker** [comment]
Excellent, glad to hear it!
