### ISSUE TITLE
Server Error opening contacts settings and import/export 

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#124]
Hello,

You fixed a couple of bugs related to postgres last week. In the mean time upgraded Campaign to the latest production versions. Initial tests and setups on my local dev machine went well. I pushed already to my staging machine which runs in the cloud (GCP - Postgres 11). However when I go on the staging site in CP to Settings -> Contact Settings I get an internal server error. Same happens when I go to menu Contacts and press the Import/Export tabs ... Stacktrace from web.log attached below. 

No custem user fields are there. I also tried to clean up all settings in dev and push to staging again with blanco setup issue remains. 

Stacktrace in web.log 

`2020-04-01 00:26:40 [-][1][kmts1bcmero5fgivo4blga9vsa][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Invalid field layout ID: 53 in /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/behaviors/FieldLayoutBehavior.php:124
Stack trace:
#0 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Extension/CoreExtension.php(1499): craft\behaviors\FieldLayoutBehavior->getFieldLayout()
#1 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/helpers/Template.php(96): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\behaviors\FieldLayoutBehavior), 'getFieldLayout', Array, 'method', false, false)
#2 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/7f/7f127dd6f6143323c3e7a6c3c46e0dfade2ea803c0bcf69e2f43e96426a60bf8.php(84): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\behaviors\FieldLayoutBehavior), 'getFieldLayout', Array, 'method')
#3 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(184): __TwigTemplate_8dacb42024028c85c1e9ccc9c17379669716aab0f3d99e1f18ff182dd47d873e->block_content(Array, Array)
#4 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/bf/bfa81ba72380213c97dab68d4cf73984321c538018d9e8c80b79d7f61ae15ea4.php(411): Twig\Template->displayBlock('content', Array, Array)
#5 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(184): __TwigTemplate_35f0fcf8a64fa4fcee0851d5adefb9c1fd1da6c26446c3efb4de0ebabce454a6->block_main(Array, Array)
#6 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/bf/bfa81ba72380213c97dab68d4cf73984321c538018d9e8c80b79d7f61ae15ea4.php(266): Twig\Template->displayBlock('main', Array, Array)
#7 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(184): __TwigTemplate_35f0fcf8a64fa4fcee0851d5adefb9c1fd1da6c26446c3efb4de0ebabce454a6->block_body(Array, Array)
#8 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/5d/5dbb771ce590a683bf43515cfe3c5dc4ffd873f3a5ce9f4dc11b0b7117d520f4.php(75): Twig\Template->displayBlock('body', Array, Array)
#9 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_7ce811708734def5dbd39cd4500183104b8b5b97e133e316d8a4cf40bd38da78->doDisplay(Array, Array)
#10 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/03/03182583e802648e84927abacf5c3fd5dd6778332257a2c8e5e12704177ca931.php(56): Twig\Template->display(Array, Array)
#12 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_1be97f8294ae96d1f35388b937972db43859994c779b05c89c36874797d73aaa->doDisplay(Array, Array)
#13 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/bf/bfa81ba72380213c97dab68d4cf73984321c538018d9e8c80b79d7f61ae15ea4.php(138): Twig\Template->display(Array, Array)
#15 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_35f0fcf8a64fa4fcee0851d5adefb9c1fd1da6c26446c3efb4de0ebabce454a6->doDisplay(Array, Array)
#16 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/64/6478ae97633062c76f6fc9873de5e787383d4d10a062bd5b1f54390f45a44e7b.php(274): Twig\Template->display(Array, Array)
#18 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_c203e36efef20dd9827c3aa08895338949335a46418b96241e9be75e207c3c56->doDisplay(Array, Array)
#19 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/19/19433a3bc98cd3ce9fdfb53319695ca5dfd2e8299392cce0a7993c5bd31b9ab0.php(53): Twig\Template->display(Array, Array)
#21 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_81dfe36a86cc4a28b9476d87625a97b036377f216a228e28dca153fb3b23d134->doDisplay(Array, Array)
#22 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/storage/runtime/compiled_templates/7f/7f127dd6f6143323c3e7a6c3c46e0dfade2ea803c0bcf69e2f43e96426a60bf8.php(55): Twig\Template->display(Array, Array)
#24 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(407): __TwigTemplate_8dacb42024028c85c1e9ccc9c17379669716aab0f3d99e1f18ff182dd47d873e->doDisplay(Array, Array)
#25 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#27 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#28 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#29 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/View.php(397): Twig\Environment->render('campaign/settin...', Array)
#30 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/View.php(458): craft\web\View->renderTemplate('campaign/settin...', Array)
#31 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/Controller.php(235): craft\web\View->renderPageTemplate('campaign/settin...', Array, 'cp')
#32 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/putyourlightson/craft-campaign/src/controllers/SettingsController.php(157): craft\web\Controller->renderTemplate('campaign/settin...', Array)
#33 [internal function]: putyourlightson\campaign\controllers\SettingsController->actionEditContact(Object(putyourlightson\campaign\models\SettingsModel))
#34 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#35 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#36 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('edit-contact', Array)
#37 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-contact', Array)
#38 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('campaign/settin...', Array)
#39 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('campaign/settin...', Array)
#40 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/craftcms/cms/src/web/Application.php(276): yii\web\Application->handleRequest(Object(craft\web\Request))
#41 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#42 /usr/share/craft/releases/0f5279aa6d2afc914f5ff46b701bdf5c450492f4/web/index.php(21): yii\base\Application->run()
#43 {main}
2020-04-01 00:26:39 [-][1][kmts1bcmero5fgivo4blga9vsa][info][application] $_GET = [] `

### Versions
- Plugin version: 1.14.4
- Craft version: Craft Pro 3.4.12

**Comment by bencroker** [comment]
It sounds like your environments may not have properly synced. 
Regardless, I have added a fix in https://github.com/putyourlightson/craft-campaign/commit/bb253e2535b8b28eb3b1571cd8101e38aa42c159.

**Comment by bartroelands** [comment]
Hello,

Just tested sync with staging. The problem is resolved for the contacts
screen in settings. However, stil having the same issue in the
Export/Import tabs in the Contacts menu:

2020-04-01 20:40:50
[-][1][4f7cli3mp1pc9ug1ae0r2obeau][error][yii\base\InvalidConfigException]
yii\base\InvalidConfigException: Invalid field layout ID: 53 in
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/behaviors/FieldLayoutBehavior.php:124
Stack trace:
#0
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/putyourlightson/craft-campaign/src/services/ImportsService.php(70):
craft\behaviors\FieldLayoutBehavior->getFieldLayout()
#1
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/putyourlightson/craft-campaign/src/variables/CampaignVariable.php(289):
putyourlightson\campaign\services\ImportsService->getContactFields()
#2
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/Extension/CoreExtension.php(1499):
putyourlightson\campaign\variables\CampaignVariable->getContactFields()
#3
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/helpers/Template.php(96):
twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source),
Object(putyourlightson\campaign\variables\CampaignVariable),
'getContactField...', Array, 'method', false, false)
#4
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/storage/runtime/compiled_templates/74/74ed6d7778aaf7d62518b734302c1984494d7ff8423d22df41f44eb48921f4d0.php(57):
craft\helpers\Template::attribute(Object(craft\web\twig\Environment),
Object(Twig\Source),
Object(putyourlightson\campaign\variables\CampaignVariable),
'getContactField...', Array, 'method')
#5
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/Template.php(407):
__TwigTemplate_31f5f5e860b310b6456aea546041878b60f34f16fc0f7f9ae5b77d3c3e7cfab9->doDisplay(Array,
Array)
#6
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/Template.php(380):
Twig\Template->displayWithErrorHandling(Array, Array)
#7
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/Template.php(392):
Twig\Template->display(Array)
#8
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/TemplateWrapper.php(45):
Twig\Template->render(Array, Array)
#9
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/twig/twig/src/Environment.php(318):
Twig\TemplateWrapper->render(Array)
#10
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/View.php(397):
Twig\Environment->render('campaign/contac...', Array)
#11
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/View.php(458):
craft\web\View->renderTemplate('campaign/contac...', Array)
#12
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/Controller.php(235):
craft\web\View->renderPageTemplate('campaign/contac...', Array, 'cp')
#13
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php(64):
craft\web\Controller->renderTemplate('campaign/contac...')
#14 [internal function]:
putyourlightson\campaign\controllers\ImportsController->actionIndex(NULL)
#15
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)
#16
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/yiisoft/yii2/base/Controller.php(157):
yii\base\InlineAction->runWithParams(Array)
#17
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/Controller.php(178):
yii\base\Controller->runAction('index', Array)
#18
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/yiisoft/yii2/base/Module.php(528):
craft\web\Controller->runAction('index', Array)
#19
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/Application.php(291):
yii\base\Module->runAction('campaign/import...', Array)
#20
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/yiisoft/yii2/web/Application.php(103):
craft\web\Application->runAction('campaign/import...', Array)
#21
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/craftcms/cms/src/web/Application.php(276):
yii\web\Application->handleRequest(Object(craft\web\Request))
#22
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/vendor/yiisoft/yii2/base/Application.php(386):
craft\web\Application->handleRequest(Object(craft\web\Request))
#23
/usr/share/craft/releases/e9b521def3fec681cada9f4bffd8cd0d47f535e6/web/index.php(21):
yii\base\Application->run()
#24 {main}
2020-04-01 20:40:49 [-][1][4f7cli3mp1pc9ug1ae0r2obeau][info][application]
$_GET = []

**Comment by bencroker** [comment]
Ok, did some further refactoring in https://github.com/putyourlightson/craft-campaign/commit/7558ec904296cecfcf6541f90a7324ce92bd3801 to ensure that this bug is finally squashed. Can you please check if it is resolved for you?

**Comment by bartroelands** [comment]
Success !

Issue resolved. Thanks for the quick fix. Will try to get further config
and setup done this weekend and hopefully migrate to production next week.

**Comment by bencroker** [comment]
Glad to hear it and thanks for the help troubleshooting.

**Comment by bencroker** [comment]
Released in 1.14.5.
