### ISSUE TITLE
Campaign Reports can only be seen for default site when using multi-site setup

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#125]
### Describe the bug
Campaign Reports can only be seen for default site when using multi-site setup. Only campaigns, that are created among the default site, can be seen in "Reports". The only way to see other campaign reports is changing the default site to another one.

### To reproduce
Steps to reproduce the behaviour:
1. setup 2 sites
2. setup 2 campaign in each site
3. create 2 sendout for each campaign
4. go to reports and try to find the campaign report for the campaign which is not among the default site

### Expected behaviour
Campaign reports should show all campaigns no matter what site they are from, or a site-switcher should be implemented.

### Versions
- Plugin version: 1.14.4
- Craft version: 3.4.12

**Comment by bencroker** [comment]
Thanks, you're right that this is missing, will add for the next release.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/7ee900fb6eda77c1b75be9afb3bbff1f6aedb005.
