### ISSUE TITLE
Import of contacts to multiple lists

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-campaign#126]
### Is your feature request related to a problem? Please describe.
When importing contacts from a CSV file I would like to be able to assign them to multiple lists. I have a client that has three different mailing lists with overlapping subscribers. I can assign the imported contacts one-by-one to more than one list, but that is not feasible for >1000 subscribers.

### Describe the solution you would like
Allow to select more than one mailing list during import.

### Describe alternatives you have considered
Allow batch editing multiple contacts at once and subscribing them to lists.

**Comment by luke-nehemedia** [comment]
Found a **workaround** by importing the exact same file twice. However, being able to select multiple lists during the first import would still be much nicer.

**Comment by bencroker** [comment]
Thanks, we'll consider making it possible to import to multiple mailing lists in one go.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/4b86e7dcfaf5c572058bd85aa628fb61e05fa597.
