### ISSUE TITLE
Contact field layout is not saved in project config

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-campaign#129]
Only the `contactFieldLayoutId` is saved, but that won't sync the field layout itself to other environments.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/85f0340a3688a79610e0f9898f1d5e40ea084796. You may need to save the contact field layout for the changes to take effect.

**Comment by benface** [comment]
Thank you @bencroker! 🙌
