### ISSUE TITLE
Support for own templates as verification email and verified message

### ISSUE THREAD

**Issue by zauni** [putyourlightson/craft-campaign#13]
Hi @putyourlightson 

first of all: thanks for this wonderful plugin! It's great to handle all of this newsletter stuff inside Craft.

My only problem is that I want to have my own template for the verification email and for the message which is shown after you click on the verification link. Maybe you have plans to add settings for these kind of templates? Or no settings but triggering an event and other plugins could than tell your plugin which template it should render?

The template for the verified message is maybe a bit easier to change, when I extend your TrackerController, maybe something like this

```php
class MyOwnTrackerController extends TrackerController
{
    public function actionVerifyEmail(): Response
    {
        $response = super::actionVerifyEmail();

        if ($response instanceof Response) {
            // everything went okay
            return $this->renderTemplate('my-own-template');
        }
    }
}
```

But for the email template you use your contacts service `Campaign::$plugin->contacts->sendVerificationEmail($pendingContact);` and I don't know how to extend that. Do you have an idea how to do that?

Thanks in advance for any tips or advice! 👍

**Comment by putyourlightson** [comment]
It is not currently possible but we'll consider it as a feature request. We have a few new features coming soon so hope to fit this in as well.

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/10494ce20d3b73db75dc2898e0552829c041eb75. You'll find the new fields in the mailing list type settings.

**Comment by zauni** [comment]
Wow, that was fast! Thank you very much for the new settings! 💯
