### ISSUE TITLE
[Feature Request] Bridge between contacts and users

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-campaign#131]
### Is your feature request related to a problem? Please describe.
Not exactly a problem, other than the fact that it's currently annoying to not know at a quick glance whether a given Craft user is subscribed to a Campaign mailing list, or whether a Campaign contact has a Craft user account.

### Describe the solution you would like
In the Contact details page, it would be nice to have an "Associated User" field that would link to the user if there is one. For the other way around I suppose it's more complicated, but maybe there could be a special "Associated Campaign Contact" field type that could be added to the User field layout to do the same thing?

### Describe alternatives you have considered
An alternative is to create a Users field with a limit of 1 and put it in the Contact field layout, and create a Campaign Contacts field with a limit of 1 as well and put it in the User field layout. However it requires custom code or a lot of manual work to keep them in sync.

Thank you!

**Comment by bencroker** [comment]
Thanks for the suggestion, added in https://github.com/putyourlightson/craft-campaign/commit/8e913a68517391b14ff0b5e3f2bb1aca76c57c3b.

![Screenshot 2020-04-15 at 10 08 39](https://user-images.githubusercontent.com/57572400/79313772-232bf680-7f01-11ea-8d51-868d985bd31b.png)

**Comment by benface** [comment]
@bencroker Thank you. I just tested this, and it's not exactly what I meant. I am not using the "sync" feature, but even if I was, it looks like this only works for new contacts. Would there be a way to show the equivalent user (same email address) even if they were not synced? And what about showing the equivalent contact on a user's profile? Maybe this is not something you want to support, in which case I perfectly understand, but I think it would be a great addition to this great plugin.

**Comment by bencroker** [comment]
Ok, so I implemented your suggestions in https://github.com/putyourlightson/craft-campaign/commit/31fd411dd9110677ded8f171b48f6fca6e343b95. The user/contact is displayed if it exists and the `refresh` icon is displayed if the user is synced.

**Contact edit page:**

![Screenshot 2020-04-21 at 10 20 32](https://user-images.githubusercontent.com/57572400/79850636-81a31a00-83c4-11ea-8941-44da6593fa07.png)

**User edit page:**

![Screenshot 2020-04-21 at 11 27 18](https://user-images.githubusercontent.com/57572400/79850642-849e0a80-83c4-11ea-8246-802cbc6e92d5.png)

**Comment by benface** [comment]
Awesome @bencroker! Thank you very much!
