### ISSUE TITLE
Contact is not unsubscribed from mailinglist

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#132]
Hi,

During further testing I saw some strange behaviour unsubscribing users via the generate `unsubcribeUrl` twig variable. In one occasion the user was unsubscribed from an other mailingList. A new test did not unsubscribe the user at all.

### To reproduce
1. created new campaign type : `Type A`
2. created two mailinglist types: `List A` and `List B`
3. created mail template with `unsubcribeUrl` in to test
4. created two mailing lists based in type A & B: `mailingList A` and `mailingList B`
5. put same contact in list A & B
6. created a new campaign based on campaign type A: `Campaign A`
7. created a new sendout for `Campaign A` on `mailingList A`
8. pushed sendOut mail file generated in storage/runtime/mail 
9. clicked unsubscribed link in mail.eml
10. got redirected to unscubscribe template

### Expected behaviour
I would expect the user to be unsubscribed from `mailinglist A`, but user still shows as subscribed in mailingList A. In the report however the unsubscribe count shows as 1. 

### Screenshots

generated mail with unsubscribe url 
![image](https://user-images.githubusercontent.com/3259752/79102573-46bd3880-7d6b-11ea-8b3a-d2d3ffab87e2.png)

mailing list A
![image](https://user-images.githubusercontent.com/3259752/79102688-808e3f00-7d6b-11ea-9331-06bce229fb4b.png)

report campaign A
![image](https://user-images.githubusercontent.com/3259752/79102872-ea0e4d80-7d6b-11ea-8926-339f2a5473fe.png)

### Versions
- Plugin version: latest development 
- Craft version: Craft Pro 3.4.15

**Comment by bencroker** [comment]
Thanks for reporting this, it should be fixed in https://github.com/putyourlightson/craft-campaign/commit/e2b2e1fc45dbd9f333c93b122665f38e849dc3c1.

**Comment by bartroelands** [comment]
Tested and working now ... thx

br/Bart
