### ISSUE TITLE
Error in mailing list report (postgres related ?)

### ISSUE THREAD

**Issue by bartroelands** [putyourlightson/craft-campaign#135]
### Describe the bug
When I open the report tab on the mailing list CP screen, no data is shown , only running spinner and http 500 errors showing in browser dev console. Web.log shows database query errors:

`LINE 7: WHERE ("mailingListId"=$1) AND ("campaign_contacts_mailingli...
                                        ^ in /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT *\nFROM (...')
#2 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(401): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/services/ReportsService.php(580): yii\db\ActiveQuery->all()
#6 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/services/ReportsService.php(459): putyourlightson\campaign\services\ReportsService->_getChartData('putyourlightson...', Array, Array, 'minutes')
#7 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/controllers/ReportsController.php(76): putyourlightson\campaign\services\ReportsService->getMailingListChartData(1544, 'minutes')
#8 [internal function]: putyourlightson\campaign\controllers\ReportsController->actionGetMailingListChartData()
#9 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('get-mailing-lis...', Array)
#12 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-mailing-lis...', Array)
#13 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('campaign/report...', Array)
#14 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('campaign/report...', Array)
#15 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/Bart/Development/psychologennet-portal-1.0/web/index.php(21): yii\base\Application->run()
#18 {main}

Next yii\db\Exception: SQLSTATE[42P01]: Undefined table: 7 ERROR:  missing FROM-clause entry for table "campaign_contacts_mailinglists"
LINE 7: WHERE ("mailingListId"=$1) AND ("campaign_contacts_mailingli...
                                        ^
The SQL being executed was: SELECT *
FROM (SELECT "campaign_contacts_mailinglists".*
FROM "campaign_contacts_mailinglists"
INNER JOIN "elements" "contactElement" ON "contactElement"."id" = "contactId"
INNER JOIN "elements" "mailingListElement" ON "mailingListElement"."id" = "mailingListId"
WHERE ("contactElement"."dateDeleted" IS NULL) AND ("mailingListElement"."dateDeleted" IS NULL)) "0"
WHERE ("mailingListId"=1544) AND ("campaign_contacts_mailinglists"."dateCreated" < '2020-04-16 22:07:58')
ORDER BY "dateCreated" in /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'SELECT *\nFROM (...')
#1 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(1159): yii\db\Command->internalExecute('SELECT *\nFROM (...')
#2 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Command.php(401): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/Query.php(237): yii\db\Command->queryAll()
#4 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
#5 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/services/ReportsService.php(580): yii\db\ActiveQuery->all()
#6 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/services/ReportsService.php(459): putyourlightson\campaign\services\ReportsService->_getChartData('putyourlightson...', Array, Array, 'minutes')
#7 /Users/Bart/Development/psychologennet-portal-1.0/vendor/putyourlightson/craft-campaign/src/controllers/ReportsController.php(76): putyourlightson\campaign\services\ReportsService->getMailingListChartData(1544, 'minutes')
#8 [internal function]: putyourlightson\campaign\controllers\ReportsController->actionGetMailingListChartData()
#9 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('get-mailing-lis...', Array)
#12 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-mailing-lis...', Array)
#13 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('campaign/report...', Array)
#14 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('campaign/report...', Array)
#15 /Users/Bart/Development/psychologennet-portal-1.0/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Users/Bart/Development/psychologennet-portal-1.0/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/Bart/Development/psychologennet-portal-1.0/web/index.php(21): yii\base\Application->run()
#18 {main}
Additional Information:
Array
(
    [0] => 42P01
    [1] => 7
    [2] => ERROR:  missing FROM-clause entry for table "campaign_contacts_mailinglists"
LINE 7: WHERE ("mailingListId"=$1) AND ("campaign_contacts_mailingli...
                                        ^
)

2020-04-16 23:09:30 [-][1][-][info][application] $_GET = [
    'p' => 'beheersconsole/actions/campaign/reports/get-mailing-list-chart-data'
    'mailingListId' => '1544'
    'interval' => 'minutes'
]
`

### To reproduce
Steps to reproduce the behaviour:
1. Mailing Lists in CP panel
2. Select mailing list
3. Select report tab

### Screenshots
![image](https://user-images.githubusercontent.com/3259752/79507597-4d340480-8038-11ea-92f8-c8e4a175af71.png)

### Versions
- Plugin version: 1.15.0
- Craft version: Craft Pro 3.4.15

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/08c4286022bbc4b9efa75780c593b99bf72cec0f.
