### ISSUE TITLE
Unable to add new Craft user

### ISSUE THREAD

**Issue by martinleveille** [putyourlightson/craft-campaign#136]
### Describe the bug
When you try to create a new Craft user, Campaign try to get the contact by email, but the email is null because we are trying to create a new Craft user.

Argument 1 passed to putyourlightson\campaign\services\ContactsService::getContactByEmail() must be of the type string, null given, called in /**/vendor/putyourlightson/craft-campaign/src/Campaign.php on line 560

### Versions
- Plugin version: Pro 1.15.1
- Craft version: Pro 3.4.17.1

**Comment by bencroker** [comment]
Thanks for reporting this, we're working on releasing a fix.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/1b65670839a5ba4f87e6d005fbfc77b2a9b16ae6 and released in 1.15.2.
