### ISSUE TITLE
Preview target for plain text email

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#137]
### Is your feature request related to a problem? Please describe.
At the moment, there's no obvious way to preview the plain text version of a campaign

### Describe the solution you would like
I'd like there to be a choice between then HTML and plaintext versions as preview targets

### Describe alternatives you have considered
Manually changing the html template to the text one for a little bit, but that's gross and could lead to errors with actual sendouts if careless.

...let me know if I am missing something obvious!

**Comment by bencroker** [comment]
Currently a plain text version preview is only available on the sendout page, in the _Preview_ tab.

![Screenshot 2020-05-12 at 09 25 03](https://user-images.githubusercontent.com/57572400/81650847-8e9ab280-9432-11ea-8196-6e3d3074560e.png)

We'll consider this a feature request for Campaign 2.0, since preview targets are not yet a universal thing in Craft. Thanks for the suggestion!

**Comment by bossanova808** [comment]
Ah right - I am still implementing things, so am just previewing in the campaign at this stage.

I think it would be a good addition.

Also - while I have your attention...what I _really_ want is to not have a plain text template _at all_ - rather be able to easily pipe the html through e.g. https://github.com/soundasleep/html2text - and generate the text version (like e.g. Mailchimp can).   In all honesty, the only reason I bother with them at all is because it apparently increases email deliverability...for the tiny tiny fraction of plaintext using folks, and auto conversion is probably good enough.

(I am planning on creating my own template variable to do just that and make my plain text template just something that renders the html version and then pipes it through a conversion...or something like that...)

**Comment by bencroker** [comment]
Campaign actually includes a `|html_to_plaintext` filter, which appears to not yet be documented, but you can use as follows:

```twig
{{ campaign.bodyText|html_to_plaintext }}
```

**Comment by bossanova808** [comment]
Ah good to know.

I'm using a pretty full on matrix content builder for the html (mjml) side of things, but will check that out and see if that works for something a but more complex than just a rich text block or whatever.

**Comment by bencroker** [comment]
It essentially just strips out HTML tags and deals with line breaks.

**Comment by bossanova808** [comment]
So just as a report:

I gave Campaign's filter a whirl but it only removes valid html tags, thus can't work with mjml emails and doesn't really do that much in terms of whitespace handling.

The one I mentioned above, html2text - does a fair bit better - removes the mjml tags at least (basically any `<whatever>content</whatever>` -> `content`  ...but isn't smart enough to find links (which are mjml-buttons usually) - etc.

So in the end I wrote my own quick library of macros to output plaintext from my blocks...but Twig's whitespace generation and handling is so spectacularly crap, that doesn't work wonderfully well either....so finally I wrote my own filter to tidy up the twig output further...basically removing excess whitespace, and decoding some html chars etc.

At the end of it, a nice plain text email... for the 0.01 of folks that actually need it, and for better deliverability (easier for spam filters to scan apparently).

**Comment by bencroker** [comment]
The HTML filter is really only intended to remove tags that are generated by rich text fields (Redactor for example). Any other tags, including MJML tags, should really be taken out of the plain text version. It sounds like you might be making things harder for yourself by trying the use the HTML template for the plain text version.

**Comment by bencroker** [comment]
Here's how I generally approach the email templates:

```twig
{# HTML template #}

<h1>Your newsletter is here!</h1>
<div class="text">{{ campaign.richText }}</div>


{# Plaintext template #}

Your newsletter is here!
---
{{ campaign.richText|html_to_plaintext }}
```

**Comment by bossanova808** [comment]
Well, I'm not trying to do that per se.  

What I'm really trying to do is avoid double work - generating the plain text from the HTML, because the plain text version is, ultimately, of low interest (especially as we're a visual arts business, and thus by definition almsot everyone we're working with is a photographer/graphic designer etc, and thus uses html emails).  Really, we're only producing it for deliverability reasons, ultimately.

So really I am just trying to do that the easiest way.   But our newsletter is a lot fancier than just a rich text field allows...(following your own principle with Cmapaign - of re-using our nice content!)....so it's a little more complex (using a bunch of matrix blocks) - than that example in practise.

Anyway, I've got a decent solution now & many thanks for your help & suggestions.

**Comment by bencroker** [comment]
Yeah I guess there's no silver bullet for this one!
