### ISSUE TITLE
Truncated import

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#139]
### Describe the bug
Imports only 7100 of 8156 contacts on a Mailchimp list.

Searching for contacts at the end of the list shows they have indeed not been added and the import appears to have stopped as the numbers aren't climbing anymore.

### To reproduce
Importing a Mailchimp list of 8156 contacts resulted in only ~7100 in Campaign's list.
No errors in campaign.log or queue.log to be seen.

I am importing email address, first name, last name, and the CONFIRM_TIME column (so I have a record of when they originally joined the list)

### Expected behaviour

Import them all, or give messages as to why some failed to import.

### Versions
- Plugin version: 1.15.2 (LITE, unlicensed until my testing is complete, will buy PRO).
- Craft version: 3.4.18

(...I also am wondering if I should so anything with the other lists one gets from Mailchimp - I am guessing just ignore them as they don't really provide anything all that useful)

(Also - I initially wrote a little console controller do do this import as I was worried about server impact, but the forms service subscribe calls getUserAgent so that doesn't work...but it seems you've written a nice import system ..( not withstanding the missing 1000 contacts at least! ;) )

(Also, apologies for raising issues before buying the plugin but I need to be sure it's all going to work, hence all this testing!  As long as it all works for us, I am super keen to get it going!)

**Comment by bossanova808** [comment]
A re-import of the same file also results in odd behaviour - about 1500 contacts updates then nothing further - and no new ones added...

![image](https://user-images.githubusercontent.com/731309/81778722-aeb39a00-9536-11ea-99e2-1771c4970023.png)

**Comment by bencroker** [comment]
If no fails are reported then perhaps the queue job never fully completed? Can you check the status of the import job under _Utilities > Queue Manager_ when running the import again? If that is the case then you could try splitting the CSV file into two files with at most 4,000 subscribers per file, or install https://plugins.craftcms.com/async-queue.

**Comment by bossanova808** [comment]
Ok, I'm an idiot.  That's where the errors are to be found! Can't believe I didn't look there first.  Forest/trees and all that...

So yeah, looks like it is hitting a 600 second limit.  

I see this in the failure...
```
The process "'/usr/bin/php7.4' '/var/www/vhosts/c3-dev/craft' 'queue/exec' '36' '600' '1' '0' '--verbose=1' '--color='" exceeded the timeout of 600 seconds. 
```

I'm not precisely sure where that limit comes from - I take it you're spawning a CLI process...and I am wondering if that `600` up there is the issue?  I don't think that is configurable, is it?   

My dev server is a lot slower than production, but even so that might still be an issue when I do this 'for real'.  Thus I guess splitting the file is the way to go...probably err on 2000s just to be sure?

(I do actually use a systemd queue runner - following Andrew's excellent article on the topic...)

**Comment by bencroker** [comment]
The CLI process is most likely being spawned by the systemd queue runner. Campaign itself does not change the queue job behaviour.

**Comment by bossanova808** [comment]
Right you are.  And I've found the 600, too.

Thanks again for your help, I should be fine from here.
