### ISSUE TITLE
Blacklist a contact

### ISSUE THREAD

**Issue by DaveBeirne** [putyourlightson/craft-campaign#140]
### Question
Is there a way to blacklist a contact?

### Additional context
We have a number of email we do not want resubscribing to mailing lists and we want to black list them from both web signup and also manual imports from CSV.

**Comment by bencroker** [comment]
There is not, but if you go into the contact edit page then you can mark a contact as `bounced`, which _should_ prevent them from being sent to in the future.

![Screenshot 2020-05-13 at 17 24 56](https://user-images.githubusercontent.com/57572400/81832388-bb3bf080-953e-11ea-8473-8607d2f36189.png)

**Comment by DaveBeirne** [comment]
Thanks Ben,

It might be nice to have a black list as to prevent a contact being added manually through import from a user if import large lists of CSV contacts also  from  e.g. hubspot or a CRM. 

This would ensure a user from being reactived again ?

Thanks again

**Comment by bencroker** [comment]
That's a good suggestion, marking this as a feature request.

**Comment by bencroker** [comment]
Added this in https://github.com/putyourlightson/craft-campaign/commit/3fa46f6f60d86d815eccedab0487932666978f6a for the next release, using the terminology "block" instead of "blacklist".

**Comment by bencroker** [comment]
Released in 1.18.0.
