### ISSUE TITLE
Better error than Internal Server Errro if you don't choose a mailing list on import

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#141]
### Is your feature request related to a problem? Please describe.

If you neglect top choose a mailing list when importing contacts from a CSV (which I have, embarrassingly, managed to do twice!) - you get a big 'Internal Server Error' message without any further explanation.  It's a bit alarming.

### Describe the solution you would like

Can I suggest you validate this at the front end, require at least one list be selected before the form can be submitted.

Just a UI/UX improvement...

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/498368193cbff3df7ee8438f2e3f6eee32933591, thanks!
