### ISSUE TITLE
Pre Purchase Enquiry - Recurring, Sync and Segments

### ISSUE THREAD

**Issue by nevsie** [putyourlightson/craft-campaign#142]
### Question
Currently building out a subscriber members website for a client... Built using Craft Commerce, all fine there...
We would like the following:
1 - Periodic sending of email with latest advice to subscribers - (recurring does this?)
2 - Sync with all users, to confirm sync could access Craft Commerce Subscriber information for active members only (for example). I believe sync could handle this?
3 - Segments - could these also have access to Craft Commerce info - assuming sync sent across... i.e. send only to active members?

Thanks. N

### Additional context
None

**Comment by bencroker** [comment]
1. Yes, recurring sendouts would be recommended if the sending should happen at regular intervals (if not then regular/scheduled sendouts would work).

2. It is possible to sync contacts in mailing lists with users in user groups. Provide you handle updating a user's user group (through Commerce for example), sync should handle the rest.

3. I'm unsure of how you're trying to connect users with Commerce info, so I can't give a clear response to this. What are you trying achieve?

FYI you can evaluate the Campaign plugin for free before buying if you want to ensure that it's a good fit for the site.

**Comment by nevsie** [comment]
Hi And thanks...
In Craft Commerce Subscriber they get the subscriber status - I just wondered if this was something you had intentionally connected to in your segements:
https://docs.craftcms.com/commerce/v3/subscriptions.html#subscription-statuses

**Comment by bencroker** [comment]
A Commerce subscription is different to a Campaign subscription so I'm not sure they could be connected. The easiest way would be through the user's user group.

**Comment by nevsie** [comment]
Hi Ben, Thanks,
Yes I appreciate that, was purely thinking through sync that comes with Pro...
I will investigate more, thanks. Can close now.
