### ISSUE TITLE
Could `campaign.type` return the campaign type handle?

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#145]
For code readability, I prefer to use handles to Ids, when possible.

I.e. I think that this:

`{% if campaign.campaignTypeId==2 %}`

would be better / more readable as

`{% if campaign.type=="newsletter" %}`

...if `campaign.type` returned the handle.

**Comment by bencroker** [comment]
You can use `campaign.getCampaignType()` or `campaign.campaignType` to get the campaign's [CampaignTypeModel](https://github.com/putyourlightson/craft-campaign/blob/1.15.3/src/models/CampaignTypeModel.php), on which you can get any value.

```twig
{{ campaign.campaignType.id }}
{{ campaign.campaignType.name }}
{{ campaign.campaignType.handle }}
```

**Comment by bossanova808** [comment]
Ah, sorry - I saw the private `campaignType` and somehow looked over the method to get it...thanks again.
