### ISSUE TITLE
`isLivePreview` is deprecated

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#146]
I note I still need to use `craft.app.request.isLivePreview` in my newsletter templates.

Per this thread:
https://github.com/craftcms/cms/issues/4565

..that is retired, and the new hotness is apparently `craft.app.request.isPreview`

Just FYI should you want to move to that at some point.

**Comment by bencroker** [comment]
That is correct, however to avoid introducing breaking changes, Campaign will continue use the old live preview feature (as still used by categories) until the next major version (2.0.0).
