### ISSUE TITLE
Send to single email

### ISSUE THREAD

**Issue by j2is** [putyourlightson/craft-campaign#15]
I understand it is currently possible to send to an individual mailing list Is there a method to send to individual email addresses? Or a workaround to make that possible? For example selecting all mailing lists and then only including an email address.

**Comment by putyourlightson** [comment]
Segments allow you to filter your recipients by various things. One option is by email address, so you could use that to send to a single email address.

![](https://raw.githubusercontent.com/putyourlightson/craft-campaign/develop/docs/images/segment-conditions-1.2.0.png)

**Comment by j2is** [comment]
Ah thanks that makes sense I thought there must be a way!
