### ISSUE TITLE
FR: Activity Report per contact  (e.g. all emails sent, opens, etc) 

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#150]
### Is your feature request related to a problem? Please describe.

I would love to be able to click on a contact and see all the history related to that particular contact - what emails they have been sent, which have been opened etc.  So that there is one consolidated place, per contact, to see our marketing relationship with that person.

**Comment by bencroker** [comment]
Have you seen the Report tab when viewing/editing a contact?

![Screenshot 2020-06-15 at 17 17 26](https://user-images.githubusercontent.com/57572400/84675226-3cb2e400-af2c-11ea-8320-d5936eb8ba61.png)

**Comment by bossanova808** [comment]
I have, but unless I am missing something, that shows those details (browser etc), but doesn't show a log of the actual emails sent, opens etc?  

Ideally, I'd like to see that here, per contact, vs. in the sendout reports - if that is possible.  It just seems the more logical place to check our communications with a particular customer.

**Comment by bencroker** [comment]
That same report has a section for Campaign Activity and one for Mailing List Activity too...

**Comment by bossanova808** [comment]
LOL, how can I delete this.... so much shame.

Must have looked at a new subscriber...

**Comment by bencroker** [comment]
No worries :)
