### ISSUE TITLE
CP css rule affecting campaign entry form

### ISSUE THREAD

**Issue by ockam** [putyourlightson/craft-campaign#151]
### Describe the bug
A CP css rule of Campaign is affecting campaign entry form

See line 188 of `/src/resources/css/cp.css`
```
.element.hasthumb .elementthumb {
    background: url('../images/user.svg');
    background-size: cover;
}
```

### To reproduce
Steps to reproduce the behaviour:
1. In a campaign, add a resource field with a thumbnail preview
2. Go to the campaign edit form and select a (image) resource
3. See the user.svg showing behind your image

### Expected behaviour
The user.svg background should not be visible. Campaign css rules should be more narrowly scoped.

### Versions
- Plugin version: 1.15.4
- Craft 3.4.25:

**Comment by bencroker** [comment]
Thanks, I'm guessing this bug was introduced in one of the recent 3.4.x releases of Craft. Will investigate further.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/307d1bcdac3c0dd22327e8eac3cf8057b43473a0.
