### ISSUE TITLE
Q: How to post to front end form from separate url 

### ISSUE THREAD

**Issue by j2is** [putyourlightson/craft-campaign#152]
### Question
A question about the plugin or how it works. We are diligent about documentation so please check the plugin docs before submitting your question.
What would be the best way to make a POST request to campaign/forms/subscribe from another url, in a headless setup where I'm submitting to the Craft website from another url
### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
Do you have any working examples of doing this with any other Craft controller endpoint? It will be much the same, with the action set to `campaign/forms/subscribe`.

Check the form fields for the naming conventions to follow:
https://putyourlightson.com/plugins/campaign#subscribe-form

**Comment by j2is** [comment]
Ok, thanks Ben!!
