### ISSUE TITLE
Contacts and mailing lists issue in multisite

### ISSUE THREAD

**Issue by JeanLucEsser** [putyourlightson/craft-campaign#153]
### Describe the bug

Multisite mailing lists breaks contacts list and contacts import.

When listing contacts and connected with a site specific user, only the mailing list type from the primary site is listed as a filter. When importing contacts, no matter the user, only mailing lists from the primary site can be selected.

### To reproduce

Create two sites, Site A (primary) and Site B.
Create FirstUser as admin (all sites) and SecondUser (Site B only).

Let's say you have 2 mailing lists types, one for Site A and one for Site B and one mailing list for each type.

### Expected behaviour

When connecting with FirstUser and navigating to contacts, you should be able to use Craft's site dropdown to switch mailing lists type filter depending on which is for which site. That works. When connecting with SecondUser, you should be able to do the same but Craft's site dropdown does not behave as expected and you're stuck with the mailing list types of the primary site and this one only.

When navigating to contacts and go to the import tab (or export or sync), it doesn't matter which user you're connected with, Craft's site dropdown does not work at all. When trying to select a mailing list for import (or export or sync), you can't see any other lists than the one from the primary site.

### Versions

- Plugin version: Latest
- Craft version: 3.5 beta 3

### Note

I think it would be great if you handled contacts in multi site the same way you are with campaigns, mailing lists, segments and sendouts. I'm currently using multisite as a way to deal with user specific campaigns and contacts (for a new client) but I'd argue that's not the best way of doing it. Would be nice to be able to have CRUD permissions on campaigns, contacts and mailing lists on a per user basis. I'll try to spend a few days imagining what that could be like and report back as an enhancement proposition. Maybe you are already working on this topic.

**Comment by bencroker** [comment]
Thanks for the detailed report. Can you please clarify the point below? To the best of my knowledge users are not site-specific.

> Create FirstUser as admin (all sites) and SecondUser (Site B only).

**Comment by JeanLucEsser** [comment]
@bencroker sure, it looks like you can assign users to sites so that the user can only access and edit elements from that site. See attached screen capture below. That's what I meant here (I didn't mean that users are site specific per se).

<img width="297" alt="Capture d’écran 2020-07-03 à 12 47 11" src="https://user-images.githubusercontent.com/14908712/86462296-ab18e400-bd2b-11ea-9b47-d795401746a9.png">

I can share more captures to try and illustrate the full issue should you need them.

**Comment by bencroker** [comment]
That would be helpful if you could...

**Comment by JeanLucEsser** [comment]
Sure! Sorry for the delay.

So let's start by creating SiteA (primary) and SiteB.

<img width="670" alt="Capture d’écran 2020-07-03 à 13 24 48" src="https://user-images.githubusercontent.com/14908712/86924708-1e599600-c130-11ea-8918-86ee54ce2aa0.png">

Then we assign Second User to SiteB (First User being admin).

<img width="275" alt="Capture d’écran 2020-07-03 à 13 26 47" src="https://user-images.githubusercontent.com/14908712/86924851-4e089e00-c130-11ea-8ba3-40c1caf82956.png">

Next we define two mailing lists types, one for each site.

<img width="1184" alt="Capture d’écran 2020-07-03 à 13 32 20" src="https://user-images.githubusercontent.com/14908712/86924907-6973a900-c130-11ea-8744-6f0a36fc2124.png">

After creating one mailing list for each type and subscribing some contacts to them, the issues start arising.

When connected as First User (admin), navigating the contacts for each site seems to work as expected:
Switching from Site A to Site B shows the relevant mailing lists and we can always see all contacts.

<img width="776" alt="Capture d’écran 2020-07-03 à 13 52 25" src="https://user-images.githubusercontent.com/14908712/86925298-fae31b00-c130-11ea-8e9a-3a8b850163e8.png">

<img width="759" alt="Capture d’écran 2020-07-03 à 13 52 45" src="https://user-images.githubusercontent.com/14908712/86925309-fdde0b80-c130-11ea-846f-78108333ed6f.png">

But then it falls apart:

Switching sites from any other tab (import / export / sync) is broken (should it even be possible?).

<img width="586" alt="Capture d’écran 2020-07-03 à 13 54 27" src="https://user-images.githubusercontent.com/14908712/86925698-76dd6300-c131-11ea-8fae-7cbee999233c.png">

And accessing the mailing lists modal from either tab (import / export / sync) shows only the mailing lists types from the primary site preventing access to the mailing list from SiteB. Although we can create a new mailing list for SiteB from the modal!

<img width="971" alt="Capture d’écran 2020-07-03 à 13 54 56" src="https://user-images.githubusercontent.com/14908712/86925981-d0459200-c131-11ea-9121-4243b9ea3bee.png">

--

When connecting with Second User, we get stuck with the primary site (SiteA although user permissions are set to edit SiteB only), not only on import / export / sync, but also on the first tab of contacts (view).

Does it help?

**Comment by bencroker** [comment]
Yes, thanks for the screenshots and explanations, will look into the issues and see what we can do.

**Comment by bencroker** [comment]
Fixed and released in version 1.16.0.
