### ISSUE TITLE
Unable to resolve the request: campaign/contacts/delete-contact?hard=1

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#154]
### Describe the bug
Trying to permanently delete a contact. Clicking on _Delete permanently_ in contact page ({{ cpTrigger }}/campaign/contacts/{{ 
contact.id }}) results in a 404. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to a contact page.
2. Click on the cog in the right sidebar. Click on Delete permanently. 
3. See error message "Unable to resolve the request: campaign/contacts/delete-contact?hard=1"

### Expected behaviour
The contact should be deleted instead of the error page appearing. 

### Screenshots

![screencast](https://user-images.githubusercontent.com/9061795/87395493-c6001980-c5b1-11ea-966c-177c6f412c17.gif)

### Versions
- Plugin version: 1.15.4
- Craft version: Craft Pro 3.4.27

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/829f26c5a418c7855559139db1db7110a55694c1 for the next release.
