### ISSUE TITLE
Couldn't save general settings

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-campaign#155]
Installed to test it out. Went to switch to test mode and get "general settings could not be saved" error message. No fields highlighting as errors. Not sure where to test from here?

This was on a local and hosted dev environment.
### Versions
- Plugin version: 1.15.4
- Craft version: 3.4.27

**Comment by bencroker** [comment]
Are you able to successfully save the general settings with test mode disabled? Are all required fields populated?

**Comment by shornuk** [comment]
Hi @bencroker 

No, it still gives the error when test mode is disabled. All fields are filled out, the only required field on general settings is the API right?

**Comment by shornuk** [comment]
Just been testing this further. It appears that an issue was caused in the Email Settings pane. The sender name and email were set to environment variables. When I hardcode them, it saves. General setting save too.

**Comment by bencroker** [comment]
Great, glad to hear it!

**Comment by shornuk** [comment]
Just to clarify on this, should you be able to use environment variables within the `From Names and Emails` field?

**Comment by bencroker** [comment]
No, only fields that display the `This can be set to an environment variable.` message can use environment variables.

**Comment by shornuk** [comment]
OK. I think that's where I got confused. The placeholder that was in there looked exactly like an environment variable, and in other places when an environment variable is set, the `This can be set to an environment variable` message is not shown (the API field in general setting for example). Perhaps it's worth changing so as to not mix them up? 

Another small UX suggestion. I'm guessing GeoIP and reCAPTCHA are optional? Feels a bit odd to have a required field asterisk. Just a small niggle, but thought you might like the feedback. Still working though the setup now, but getting there 👍

**Comment by bencroker** [comment]
There is no placeholder in the email settings:

<img width="783" alt="Screenshot 2020-07-20 at 17 15 07" src="https://user-images.githubusercontent.com/57572400/87954511-c23a2e80-caac-11ea-9403-0105821fd755.png">

> The placeholder that was in there looked exactly like an environment variable, and in other places when an environment variable is set, the This can be set to an environment variable message is not shown (the API field in general setting for example). Perhaps it's worth changing so as to not mix them up?

The message is only shown if the field is not already populated with an environment variable. This is a native Craft UI decision, not Campaign.

<img width="617" alt="Screenshot 2020-07-20 at 17 22 24" src="https://user-images.githubusercontent.com/57572400/87955134-99666900-caad-11ea-97be-d044a9430fac.png">

> Another small UX suggestion. I'm guessing GeoIP and reCAPTCHA are optional? Feels a bit odd to have a required field asterisk. Just a small niggle, but thought you might like the feedback. Still working though the setup now, but getting there 👍

Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/42ad11d4aec2e13652c228ac9ea6aa631677f7f5.

**Comment by shornuk** [comment]
> Thanks, fixed in 42ad11d.

Great!

> There is no placeholder in the email settings:

How strange. I had `$SYSTEM_EMAIL_ADDRESS` & `$SYSTEM_EMAIL_NAME` pre-populated in there after installing. 🤷‍♂️
