### ISSUE TITLE
sequential queuing of concurrent sendouts

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#156]
### Is your feature request related to a problem? Please describe.
We have a multisite setup and the newsletters get sendout in many languages. There a lots of subscribers. There are also hourly limits at the ISP for sending emails. We would like to enable customers to schedule the newsletters for all languages e.g. at night time at one specific time, not calculating the sendout time for each newsletter - to avoid hitting the ISP-sending limits.

### Describe the solution you would like
the solution would be e.g. an alternative function in ```src/console/controllers/SendoutsController.php``` calling another function ```queuePendingSendouts()```  in ```src/services/SendoutsService.php```
Here is a possible solution for sequential queuing: 

```
    /**
     * Queues pending sendouts sequentially
     *
     * @return int
     * @throws Throwable
     */
    public function queuePendingSendouts(): int
    {
        $limit = 1;
        $sending = 0;
        $sendouts = [];
        $now = new DateTime();

        // Get sites to loop through so we can ensure that we get all sendouts
        $sites = Craft::$app->getSites()->getAllSites();

        foreach ($sites as $site) {
            $sendingSendoutsCount = SendoutElement::find()
                ->site($site)
                ->status(SendoutElement::STATUS_SENDING)
                ->count();
            $sending += $sendingSendoutsCount;
        }

        // if we are already sending
        if ($sending >= $limit) return 0;

        foreach ($sites as $site) {
            // Find pending sendouts whose send date is in the past
            /** @var SendoutElement $_sendout */
            $_sendout = SendoutElement::find()
                ->site($site)
                ->status(SendoutElement::STATUS_PENDING)
                ->where(Db::parseDateParam('sendDate', $now, '<='))
                ->orderBy('sendDate ASC')
                ->one();

            if ($_sendout !== null) $sendouts[] = $_sendout;
        }

        // if we dont have any pending sendouts
        if (empty($sendouts)) return 0;

        /** @var SendoutElement $sendout */
        $sendout = $sendouts[0];

        // Queue regular and scheduled sendouts, automated and recurring sendouts if pro version and the sendout can send now
        if ($sendout->sendoutType == 'regular' || $sendout->sendoutType == 'scheduled'
            || (($sendout->sendoutType == 'automated' || $sendout->sendoutType == 'recurring')
                && Campaign::$plugin->getIsPro() && $sendout->getCanSendNow()
            )
        ) {
            /** @var Queue $queue */
            $queue = Craft::$app->getQueue();

            // Add sendout job to queue
            $queue->push(new SendoutJob([
                'sendoutId' => $sendout->id,
                'title' => $sendout->title,
            ]));

            $sendout->sendStatus = SendoutElement::STATUS_QUEUED;

            $this->_updateSendoutRecord($sendout, ['sendStatus']);
        }

        return 1;
    }
```

**Comment by bencroker** [comment]
Have you considered using a dedicated email sending service such as Mailgun, Sendgrid, etc? Depending on an ISP to send to large mailing lists is unreliable for this exact reason and I'm not sure that sequential queueing of sendouts would even solve the issue.

**Comment by krizzzly** [comment]
Hello, thx for your answer. Dedicated email services are not an option for data-privacy reasons, also we are sending about 4000 mails per hour. The solution that I have posted is already in production and works well. On the other hand its better for me, if this will be a feature in future, so i dont have to maintain the code to keep it working with campaign plugin code.

Best regards

Chris

**Comment by bencroker** [comment]
I understand that your solution works well for your use-case, but what would happen if your ISP had a limit of 400 emails per hour, then the proposed solution doesn't really work, right? I just need to consider whether this actually solves the issue of send rate limiting, or simply mitigates it.

**Comment by krizzzly** [comment]
Hello, we can calculate the per hour sending by setting the number of emails sent per batch. 
In ```config/campaign.php``` we can set ```maxBatchSize``` and the frequency we set via the cron when calling our new ```run-pending-sendouts``` from console.

**Comment by bencroker** [comment]
While I see how you are handling this, it still requires some customisation and tweaking, so not something I would consider adding to core at this stage. 

FYI Mailgun is quite good with their data privacy and documenting how they comply with GDPR (https://www.mailgun.com/gdpr/).
