### ISSUE TITLE
Bounce and compliant issues

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-campaign#158]
Hi, 

Firstly, great plugin overall. I'm working through testing and it's generally really good, but having a few minor issues. 

Initially I set up with Sendgrid. The sending with this is fine, but it appears bounce and complaints aren't getting reported back to it at all. They're showing in Sendgrid, but nothing comes though to Campaign. (I've added the Webhooks).

Thought I'd try Mailgun (as that's what you recommend). Set up generally was straightforward. I set up the webook for `complained` and `permanent_fail`.

Firstly, bounces.
I've created a test mailing list that includes two emails that I know will bounce. Tested, they bounce in Mailgun, and they get pulled through to Campaign. The only issue is the 'Bounced' figure on the Campaign Details view is wrong. I only have two bounces, but it's showing as 8? When I click the 8 to show the Contact Activity for the campaign, it just shows the two bounces.

Secondly, complaints.
How are these reported to Mailgun? My understanding was that this is when the user marks an email as spam within their email client? I've done this and it's not showing in Mailgun. Any way to test this further?

### Versions
- Plugin version: 1.15.4
- Craft version: 3.4.29.1

**Comment by bencroker** [comment]
> I've created a test mailing list that includes two emails that I know will bounce. Tested, they bounce in Mailgun, and they get pulled through to Campaign. The only issue is the 'Bounced' figure on the Campaign Details view is wrong. I only have two bounces, but it's showing as 8? When I click the 8 to show the Contact Activity for the campaign, it just shows the two bounces.

This may be a bug, I'll look into it and let you know what I find.

> How are these reported to Mailgun? My understanding was that this is when the user marks an email as spam within their email client? I've done this and it's not showing in Mailgun. Any way to test this further?

According to the Mailgun [docs](https://documentation.mailgun.com/en/latest/api-complaints.html#spam-complaints):

> When recipients of your messages press “Spam” button, Mailgun receives those complaints from ESPs (email service providers).

How exactly ESPs receive those complaints probably depends on the email service you use. Beyond that I can't comment on why they might not be appearing in Mailgun, that's probably something to contact Mailgun support about.

**Comment by bencroker** [comment]
> I've created a test mailing list that includes two emails that I know will bounce. Tested, they bounce in Mailgun, and they get pulled through to Campaign. The only issue is the 'Bounced' figure on the Campaign Details view is wrong. I only have two bounces, but it's showing as 8? When I click the 8 to show the Contact Activity for the campaign, it just shows the two bounces.

Could it be that you tested with the same campaign multiple times? If that's the case then it could be that the bounce count on the campaign is greater than the number of contacts reported as bounced. The easiest way to test this is sending a new campaign to a new mailing list.

**Comment by shornuk** [comment]
> How exactly ESPs receive those complaints probably depends on the email service you use. Beyond that I can't comment on why they might not be appearing in Mailgun, that's probably something to contact Mailgun support about.

That's what I was thinking. My guess is that provided Mailgun receives the complaint, then that should ping across the same way as the bounce. I wasn't thinking there was an issue with Campaign, more just wondering how it works. 

> Could it be that you tested with the same campaign multiple times? If that's the case then it could be that the bounce count on the campaign is greater than the number of contacts reported as bounced. The easiest way to test this is sending a new campaign to a new mailing list.

I have tested the campaign a few times, in actual fact 4 times. I'll try with a new campaign. Either way, there is still only 2 bounces that has made it back to Campaign across all 4 sendouts, so the count would be incorrect. (I was testing bounces and it was only the fourth sendout where the bounce's got reported back.)

**Comment by shornuk** [comment]
Just tested again, but forgot that the two contacts had been marked as bounced previously and I hadn't unmarked them as bounced. 🤦‍♂️

Unmarked them as bounced, tested again, and works ok, count is correct. 

Also, is it recommended to _not_ set up open and link tracking in Mailgun? I've switched them on, but no open/clicks are getting reported.

**Comment by bencroker** [comment]
> Also, is it recommended to not set up open and link tracking in Mailgun? I've switched them on, but no open/clicks are getting reported.

I would probably recommend against setting it up in Mailgun as it will likely manipulate your links, which Campaign does in order to track clicks and opens.

**Comment by shornuk** [comment]
> > Also, is it recommended to not set up open and link tracking in Mailgun? I've switched them on, but no open/clicks are getting reported.
> 
> I would probably recommend against setting it up in Mailgun as it will likely manipulate your links, which Campaign does in order to track clicks and opens.

👍
