### ISSUE TITLE
Saving postmark settings throws 500

### ISSUE THREAD

**Issue by leevigraham** [putyourlightson/craft-campaign#159]
### Describe the bug

`Calling unknown method: craftcms\postmark\Adapter::beforeSave()`

### To reproduce
Steps to reproduce the behaviour:
1. Go to /admin/campaign/settings/email
2. Select "Postmark" under "Transport Type"
3. Enter token
4. Save
5. See error: `Calling unknown method: craftcms\postmark\Adapter::beforeSave()`

![image](https://user-images.githubusercontent.com/25124/88673948-89ddc480-d12c-11ea-9fbf-6d2b1abe3816.png)

### Versions
- Plugin version: `"putyourlightson/craft-campaign": "dev-develop#9ec0bab0075a9054e6ee984c1c7baf44574c76dc",`
- Craft version: 3.5 RC3

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/316da0039e362497b2c9d8f6434965782b80a7f8, thanks!
