### ISSUE TITLE
Mandatory fields for subscribe form

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-campaign#160]
Hello. 

I really like your plugin and use it for multiple clients. 

On one site we have included a checkbox to accept the privacy policy etc. Of course I can validate via javascript by myself but I wonder whether the plugin itself provides any validation. 

In the settings where I can define the contacts, I can mark the field as "required" but it does not seem like the plugin does care about this at all.

Thank you for your help
Lucas

**Comment by bencroker** [comment]
Thanks, will add contact field validation for the next release.

**Comment by bencroker** [comment]
Added in version 1.15.6. See the mailing list subscribe form example for how to output errors:
https://putyourlightson.com/plugins/campaign#subscribe-form
