### ISSUE TITLE
Be able to rename a sent sendout

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#161]
It would be useful to me to be able to rename a sent sendout.  We try and stick to a naming system, but occasionally slip up:

![image](https://user-images.githubusercontent.com/731309/88754891-365a8d80-d1a3-11ea-8030-2d552f6271f8.png)

...once sent, I seem to be unable to change that title.  Would be great if this were possible.

**Comment by bencroker** [comment]
Great suggestion!! Added in https://github.com/putyourlightson/craft-campaign/commit/f7e8c06a31ccc7da6a9716affba5f8336ffee08a.

![Screenshot 2020-07-29 at 09 18 03](https://user-images.githubusercontent.com/57572400/88769758-1e701300-d17d-11ea-890c-e210b566c62d.png)

**Comment by bossanova808** [comment]
I'm sorry for the stupid question, but how do I actually get that ^ to pop up?  I'm on the sendouts index page, but it doesn't seem to be an element index option in the dropdown, and e.g. double clicking goes to the sendout element, but the title is not editable.  

I know I'm missing the obvious, but I just can't see it right now....

**Comment by bencroker** [comment]
This is a Craft thing, you need to double click the green status icon. I've also added an `Edit sendout` action for the next release in https://github.com/putyourlightson/craft-campaign/commit/ee1d33787c5203afe6e4388babef5e19bb48bef8.

**Comment by bossanova808** [comment]
Well good golly... That's...opaque.  Talk about your hidden functionality...

Thanks again, works well!
