### ISSUE TITLE
Sendout getting stuck on getting pending recipients

### ISSUE THREAD

**Issue by shornuk** [putyourlightson/craft-campaign#162]
### Question
I've tested this locally and seems to be working as expected. However when I've pushed this up to a staged environment I'm the plugin is stalling at the point of preparing a sendout.

Once setting up the Subject etc and the mailing list (43K contacts) and then pressing Save and Preview, I get a spinner on the "expected recipients" count. This stays stuck and grinds the site to a halt and it's unusable. Only way to stop it seems to be to reboot NGNIX to get things going again. 

Any idea on what might be causing this, or the best place to start debugging.?

**Comment by bencroker** [comment]
What versions of Campaign and Craft are you on? Are you using segments to filter contacts and if so then please provide the types of segments you are using, as these can slow things down when preparing sendouts.

**Comment by shornuk** [comment]
Hi Ben, latest for both. 1.15.5 for campaign and Craft CMS 3.5.0-RC6 (I know it's not final, but it's pretty close).
Not using any segments at all. Just a single mailing list. 43365 subscribed, 2064 unsubscribed.
Can't figure out why it preps fine on local, but not on staged. I've dug around in the logs, but couldn't find anything.

**Comment by bencroker** [comment]
Hmm that is strange. What kind of hosting setup are you using on your staging environment?

**Comment by shornuk** [comment]
I'm running a Linode box on Laravel Forge. PHP 7.3 (which matches my local Laravel Valet setup.)

Only thing that I can think it different is that I have a daemon set up to listen to the craft queue on the staged env, whereas I don't on local.

**Comment by bencroker** [comment]
> I'm running a Linode box on Laravel Forge. PHP 7.3 (which matches my local Laravel Valet setup.)

Sounds fine.

Can you test it with the browser dev tools open to the Netweork tab and check to see if there's any response from the AJAX request to get the pending recipients count?

**Comment by shornuk** [comment]
It never gets any response. Preview & Response both are blank.

**Comment by bencroker** [comment]
Maybe worth testing in staging without the daemon?

**Comment by shornuk** [comment]
I've done that with no difference. I went back to local to almost start again and try and figure out what's up. Put the local install into test mode and queued up a sendout, this was fine. Ran it in test mode. The first 10 batches ran and I then paused. It reported that it had been sent to 10000 recipients. 

There was however, nothing in my `storage/runtime/debug/mail` folder. I thought it was supposed to write to local files in there?

Edit: I've just seen they've actually gone into the `storage/runtime/mail` folder - might need to update the docs 👍

**Comment by shornuk** [comment]
OK, I've tried everything I can think of. Tried it in a dev env, staging env and pushed to live to test there. In each one it fails to generate the recipient count, hangs and brings the site to a halt. Have tried with the daemon running and without. Have bumped up the `max_execution_time` and `memory_limit` and still no joy. Not sure quite what else I can test?

**Comment by bencroker** [comment]
> Edit: I've just seen they've actually gone into the storage/runtime/mail folder - might need to update the docs 👍

Updated the docs, thanks!

Can you test with a smaller mailing list to eliminate if it is the size of the list that is causing the issue? If not then I can take a closer look if you send CP access credentials and ideally SFTP/SSH access to info@putyourlightson.net.

**Comment by shornuk** [comment]
I only have the main single mailing list. I did create a test list with just one contact and that does work.

**Comment by shornuk** [comment]
Have you got any examples/use cases of it being used in production with lists of 40-50k contacts?

**Comment by bencroker** [comment]
Yes, in use on production with lists of up to 150k. It does seem like the size of the list is impacting the request though. What type of sendout is this?

**Comment by shornuk** [comment]
I’ve tried regular and scheduled. Both with the same result.

**Comment by khalwat** [comment]
I don't think Forge comes with any built-in email support?

**Comment by bencroker** [comment]
@khalwat The Campaign plugin handles the actual sending of emails.

@shornuk As I said above, I can take a closer look if you can provide credentials to your staging server by email.

**Comment by shornuk** [comment]
@bencroker - sent you an email yesterday about getting access. Let me know if you've not got it. 👍
