### ISSUE TITLE
Subscribe action form validation

### ISSUE THREAD

**Issue by theresao** [putyourlightson/craft-campaign#165]
Does the actionSubscribe have a thorough validation of the form data before it is saved to the pendingcontacts database table?
E.g. will firstName and lastName strings be checked / is there a htmlspecialchars validation?

**Comment by bencroker** [comment]
Sounds like a duplicate of https://github.com/putyourlightson/craft-campaign/issues/160?

**Comment by davidhellmann** [comment]
@bencroker 
It looks like there is currently no Backend Form Validation there? 
Maybe it goes hand in hand with the #160 

Do you have a rough date for it?

**Comment by bencroker** [comment]
It's a duplicate. Will look into addressing it today.

**Comment by bencroker** [comment]
Added in version 1.15.6. See the mailing list subscribe form example for how to output errors:
https://putyourlightson.com/plugins/campaign#subscribe-form
