### ISSUE TITLE
Set default test email address

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-campaign#166]
### Is your feature request related to a problem? Please describe.
The test email address on the campaign creation screen currently defaults to the use email address associated with the user account that created the campaign entry. When using services like Litmus to do a number of preflight checks on emails, there's often a unique address that emails can be sent to that will trigger these tests.

As currently configured, this relies on the campaign creator to do the following:
1. change the test email address
1. choose the right test email address
1. send the test email

We're finding users are stumbling over the first two steps in the process, which may be helped by providing a default test address for the campaign type.

### Describe the solution you would like
Provide an option to set a default test email address as part of the campaign type settings screen. There could also be a general settings test email address that would apply to all campaigns by default.

**Comment by bencroker** [comment]
Thanks for the suggestion Matt! Test emails are sent to a "contact" rather than an email address, so it would be possible to add a default contact selector in the plugin settings somewhere. How important would it be to be able to set the default contact on individual campaign types versus a global plugin setting? I assume that your preflight check email is the same regardless of which campaign type is being tested?

**Comment by raptureaid** [comment]
With larger organizations, there may be the possibility of different testers across campaigns. For example, we use campaign types to organize messages by internal departments. As those users are trained to become more self-sufficient with managing their own email campaigns, we would envision handing off the preflight testing to them as well.

So I think having both global and campaign type options as providing the most flexibility.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/b45de549f53095e36f2b3c9e7ccf53790f807f60 for the next release.

**Comment by bencroker** [comment]
Released in version 1.16.0.
