### ISSUE TITLE
actionSubscribe: naming of the return variable for errors

### ISSUE THREAD

**Issue by theresao** [putyourlightson/craft-campaign#167]
Thank you for adding the form validation as requested in #165 
Now I have an issue with the following code block:

`// Send the contact back to the template
Craft::$app->getUrlManager()->setRouteParams([
  'contact' => $contact
]);`

The naming of the returned contact (`contact`) conflicts with one of my global fields.
Could you please name the returned contact more plugin specific to avoid conflicts?

**Comment by bencroker** [comment]
The keyword `contact` is already injected by the plugin into Twig in various places, so while I understand your reasoning for wanting it to be more plugin specific, it cannot be changed without introducing either a breaking change or a new config setting. Considering that other keywords such as `campaign`, `mailingList`, etc. are also injected into Twig and could present the same issues in edge cases, I think my recommendation would be to rename your global set to something more specific (such as `globalContact`, `contactDetails`, or similar). I don't mean to pass the responsibility on to you but I feel like this is a case where changing your global set name makes more sense than adding more code to the plugin.
