### ISSUE TITLE
Be able to sort reports

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#168]
Looking at Campaign reports, the order seems rather random, I can't figure out how they are currently sorted.

Would be great if they were either sorted by title by default, or sortable by clicking on the column headers...

![image](https://user-images.githubusercontent.com/731309/91979647-6c25ff80-ed69-11ea-9270-96736258b837.png)

**Comment by bencroker** [comment]
They are currently sorted by date created descending. Marking this as a feature request.

**Comment by bossanova808** [comment]
Ah right.  

We sometimes develop content over quite a period of time (I suspect others might do this too - basically the newsletter has blocks added to it as things come up, for example) - so the date _created_ is, for us, not really relevant at all (or editable, it seems).

...It's the date of the actual send-out that is logically important, really (as generally we want to review the results of the latest _sent_ things, not _created_ things) - so expect those to be at the top.  Maybe that's the easiest fix, just sort by when it was actually sent out?

(Sorry I deleted the feature request template, I get unreasonably irritated by all that gump in my text-box ;) )

**Comment by bencroker** [comment]
Added ordering of campaigns by last sent descending in https://github.com/putyourlightson/craft-campaign/commit/9b92e1709b3e0b27d897d9e16f44c671115fbe3e for the next release.
