### ISSUE TITLE
Trouble with double opt-in and Office 365 ATP Safe Links

### ISSUE THREAD

**Issue by nilsnh** [putyourlightson/craft-campaign#169]
### Describe the bug

We've experienced that some Office 365 Outlook users report errors when trying to sign up to our newsletters. We have activated [double-opt email verification](https://putyourlightson.com/plugins/campaign#double-opt-in). It seems that [Office 365 ATP Safe Links](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-links) somehow leads to an extra click which results in the user never seeing the verification success screen and instead they see the error "verification link expired" even though they just successfully signed up.

### To reproduce
Steps to reproduce the behaviour:
1. Signup to newsletter with double-opt in activated, using an email that has Office 365 ATP Safe Links protection activated.
2. Click on verification link in email.
3. Get error "verification link expired", possibly because the link was automatically visited more than once by Safe Links. 

### Expected behaviour

Ideally, if the verification link has not expired and the user manages to visit the link more than once within the expiration window it should only show the success screen. 

Additionally, I think any code that hooks into user subscription events should not be triggered more than once, even though a user visits a non-expired verification link multiple times.

### Versions
- Plugin version: 1.15.6
- Craft version: 3.3.20.1

**Comment by bencroker** [comment]
Sounds similar to https://github.com/putyourlightson/craft-campaign/issues/149, will look into how to best solve this, thanks for reporting.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/1148d64b6d7974438c86e6800a97d0853c711ac5 for the next release.

**Comment by bencroker** [comment]
Released in version 1.16.0.
