### ISSUE TITLE
Ability to add SMTP header

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-campaign#171]
### Is your feature request related to a problem? Please describe.
Per a requirement from Postmark, I need to be able to set an SMTP (globally for all email sent by Campaign) to set the message "stream" to "broadcast". This is required in order to send Newsletter type content via Postmark.

### Describe the solution you would like
Add a simple way to set a global SMTP header, via a config file or similar.

I think adding SMTP headers could be helpful to others done the road with other use-cases.

**Comment by bencroker** [comment]
Since this requirement is specific to Postmark, I'm gonna say that it should be added to the Postmark plugin as per your issue at https://github.com/craftcms/postmark/issues/11.

**Comment by codyjames** [comment]
Makes sense to me, thanks @bencroker!

**Comment by bencroker** [comment]
I see that you haven't had a response to your issue in 11 days. If it's something you urgently need then let me know, perhaps I can work on a PR for it.

**Comment by codyjames** [comment]
@bencroker No worries, I actually ended up switching to Mailgun for this project just yesterday which allows me to create multiple endpoints rather than requiring headers to be added. Thanks for the offer though!

**Comment by bencroker** [comment]
Sounds good!
