### ISSUE TITLE
Sendout takes very long (24h)

### ISSUE THREAD

**Issue by tonioseiler** [putyourlightson/craft-campaign#172]
Hi,

We have a list of 3000 contacts. To send a campaign takes approximately 24 hours. Mail Driver is SMTP?
Any ideas what could be the problem?

Regards.

Tonio

**Comment by bencroker** [comment]
First of all I would highly recommend you use an email delivery service such as https://www.mailgun.com/. Besides being much more reliable at delivering email and preventing your servers from being blacklisted, it will use an API for sending which should be faster than SMTP.

Sending to 3,000 contacts will take some time, especially if the email template is complex as it must be individually rendered for each contact, but I'm surprised that it would take that long.
