### ISSUE TITLE
Sendouts based on users timezone

### ISSUE THREAD

**Issue by maurizio-savvy-investor** [putyourlightson/craft-campaign#173]
### Question
As we have members across different timezones, one of our requirements is that for a given email campaign, the actual email sent can be sent in accordance with each users timezone, so for example if we set the sendout time to 11:00am, our users in the US and UK both get their email at 11:00am in their respective timezone. Is there any way this can be achieved with craft-campaign?

Many thanks.

### Additional context
Add any other context or screenshots about the support request here.

**Comment by bencroker** [comment]
Not realistically, no. Contacts do not have any inherent location or timezone. A possible workaround could be to segment your contacts based on a country field, for example, and then schedule a few sendouts to send at different times of the day.

![Screenshot 2020-09-23 at 13 15 28](https://user-images.githubusercontent.com/57572400/94005679-e6610700-fd9e-11ea-8cb7-a9c193c122e4.png)
