### ISSUE TITLE
Easily see the state of contacts on a particular list

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#174]
### Is your feature request related to a problem? Please describe.

I find myself wanting to be able to easily see the list of contacts on a particular list.  In particular I am looking for state information - e.g. I might want to mark some contacts unbounced if I know the issue was a temporary one etc., and just generally to check we're actually mailing out to the precise group of people we think we are.

I understand that I can do that via the 'filter' on the contacts section...but with a lot of lists this soon gets very cluttered.

In our case this column goes for about 4 pages long on a 27" 4K monitor....so it's a lot to wade through to find what you want...

![image](https://user-images.githubusercontent.com/731309/94075825-38596980-fe3f-11ea-8afa-b7a1476a2637.png)

### Describe the solution you would like

I think perhaps something needs to be done generally about this view/approach as it soon becomes impractical if one is using quite a few lists.  We're finding Campaign very handy for both our main newsletter, but also for things like product notifications (back in stocks, or delays or...whatever), so we've got a lot of lists in active use.

I also, logically, find myself looking for this information via the Mailing Lists section, rather than the Contacts section.  I go to the mailing list, and expect to be able to easily see the list of contacts on that list, but one can only see reports there.  Seems to me the logical solution is to make the list of contacts available from the page for the mailing list itself.  

(Thanks for your consideration Ben - I really love Campaign, it's really made a radical difference in how easily/quickly we can prepare these sorts of things...and is also wildly cheaper than Mailchimp.  It's just fabulous!).

**Comment by bencroker** [comment]
> I think perhaps something needs to be done generally about this view/approach as it soon becomes impractical if one is using quite a few lists. We're finding Campaign very handy for both our main newsletter, but also for things like product notifications (back in stocks, or delays or...whatever), so we've got a lot of lists in active use.

How would you suggest this be improved? The mailing lists could be replaced with mailing list types, but then you would lose the ability to filter by specific mailing lists, which seems like the more valuable option of the two.

> I also, logically, find myself looking for this information via the Mailing Lists section, rather than the Contacts section. I go to the mailing list, and expect to be able to easily see the list of contacts on that list, but one can only see reports there. Seems to me the logical solution is to make the list of contacts available from the page for the mailing list itself.

I will consider adding a list of contacts to the mailing list edit page, similar to how mailing lists are listed on the contact edit page.

> Thanks for your consideration Ben - I really love Campaign, it's really made a radical difference in how easily/quickly we can prepare these sorts of things...and is also wildly cheaper than Mailchimp. It's just fabulous!

Thanks for the kind words and glad to hear you're enjoying Campaign!!

**Comment by bossanova808** [comment]
Yeah it's a bit tricky as really Craft has this problem all over the place with larger data sets  - e.g. commerce order statusses are similar if you have a lot of them.  Part of it is the way-too-much spacing between the filters, but it's a fundamental limitation of the approach once you have a lot of filters.

...I think that some sort of live filter becomes desirable once you get beyond a page or two of filter options.  So you could type a partial of the list name you'd be able to select the filter that way maybe?  But of course the search currently is for a contact, which makes sense there.  So I find myself going back to at least making it easier by having the contacts on a list accessible via the mailing lists section..because there you already have that searching.  So you'd type a partial, 'Epson', say, and a much shorter list of lists comes upm you click on the one you want and go to the contacts tab and boom there you are.

**Comment by bencroker** [comment]
Sounds like smart sources (https://github.com/craftcms/cms/issues/1630) may help with that.

**Comment by bencroker** [comment]
Added a contacts tab to the mailing list edit page in https://github.com/putyourlightson/craft-campaign/commit/b442920be277442b8746d8d377729c88bd1f0cc0 for the next release.

**Comment by bencroker** [comment]
Released in version 1.16.0.
