### ISSUE TITLE
Data too long for column 'source'

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-campaign#175]
### Describe the bug
I am using the [Bugsnag](https://plugins.craftcms.com/bugsnag) plugin and it caught the following error, probably when a user tried to subscribe to my mailing list:

```
yii\db\Exception SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'source' at row 1
The SQL being executed was: INSERT INTO `campaign_contacts_mailinglists` (`contactId`, `mailingListId`, `subscribed`, `sourceType`, `source`, `subscriptionStatus`, `dateCreated`, `dateUpdated`, `uid`) VALUES (6252, 1431, '2020-09-23 16:19:20', 'web', 'http://smtp.agglo-pau.fr:32224/?dmVyPTEuMDAxJiY2ZWJlZTc5Mzg1MWIyYTQ2Yz01RjZCNzIwRl83ODczXzQ3MzVfMSYmZjBiOWMzZjMzNTM3NzI0PTEyMzMmJnVybD1odHRwcyUzQSUyRiUyRm5leHQlMkVtYXN0cm9hcHAlMkVjb20lMkZmciUyRnZlcmlmeWVtYWlsJTNGY29kZSUzRE1oU0hwekNmckUxc0NNek9XTE4xZ3UzalBJLWE5MGktJTI2YW1wJTNCaWQlM0Q4ZDc3NWMzNy02OTMxLTRlYjktYjE4Ni0yMzA1NzJiOGQ1NzI=', 'subscribed', '2020-09-23 16:19:20', '2020-09-23 16:19:20', '91947212-8abb-49e4-a3fc-9ab160b5bb9b')
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/Schema.php:677 yii\db\Schema::convertException
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php:1298 yii\db\Command::internalExecute
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/Command.php:1093 yii\db\Command::execute
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/Schema.php:432 yii\db\Schema::insert
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/ActiveRecord.php:600 yii\db\ActiveRecord::insertInternal
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/ActiveRecord.php:566 yii\db\ActiveRecord::insert
    /home/forge/mysite.com/vendor/yiisoft/yii2/db/BaseActiveRecord.php:678 yii\db\BaseActiveRecord::save
    /home/forge/mysite.com/vendor/putyourlightson/craft-campaign/src/services/MailingListsService.php:174 putyourlightson\campaign\services\MailingListsService::addContactInteraction
```

### Versions
- Plugin version: 1.15.6
- Craft version: 3.5.7

**Comment by bencroker** [comment]
Thanks, any idea why an SMTP URL is in the source? Could this be a spam attempt? A web source should reflect the URL of the page on which your mailing list subscription form exists.

**Comment by benface** [comment]
Ooooh sorry @bencroker I think this is my fault. I forgot I was doing something weird, I am adding users to the mailing list manually in a service method:

```php
Campaign::$plugin->forms->subscribeContact($contact, $mailingList, 'web', Craft::$app->getRequest()->getReferrer());
```

I am doing it this way because I wanted to have my own validation and model population logic. So should I be truncating `Craft::$app->getRequest()->getReferrer()` to 255 characters just in case, or use something else as the source?

**Comment by bencroker** [comment]
This is a [known bug](https://github.com/craftcms/cms/issues/3995) in Craft when MySQL is running in "strict mode". In this case, I'm wondering whether it makes more sense to make `source` a `text` column or to truncate the string to 255 characters.

**Comment by benface** [comment]
I'll truncate the value myself for now. Feel free to close this issue if you don't think any change is needed to the plugin. Thanks! :)
