### ISSUE TITLE
Unable to navigate to Reports with 1.16.0

### ISSUE THREAD

**Issue by martinleveille** [putyourlightson/craft-campaign#179]
It's not possible to navigate to Reports section with the version 1.16.0.

We got this error : `Variable "siteId" does not exist` in this file `templates/reports/campaigns/index.html` on line 9.

`{% set data = craft.campaign.reports.getCampaignsReportData(siteId) %}`

### Versions
- Plugin version: 1.16.0
- Craft version: 3.5.12.1

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/7562b2b9e865808cb5113c05503894efb4bcf8e3 and released in 1.16.1.
