### ISSUE TITLE
Feature request: imap bounce handling

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#18]
Hello! I emailed you a while back about the possibility for using IMAP to check bounces. I have now created a craft module that accomplishes this. Maybe this could be implemented in your plugin somehow? (only thing is it depends on the php imap module, which is not a core craft requirement)

https://github.com/phoob/campaignbouncehandlermodule

As stated in the README, it requires the php IMAP module and https://packagist.org/packages/voku/bounce-mail-handler

**Comment by putyourlightson** [comment]
The module looks good, thanks for sharing! From where are you triggering the controller action?

**Comment by phoob** [comment]
Right now, nowhere. I thought maybe setting up a cronjob calling the console controller

**Comment by putyourlightson** [comment]
Hmm, I'm not sure how I feel about adding a script that processes an inbox. I'll need to consider it but will keep this feature request open for now. Thanks for submitting and let me know how it goes with the module you've created and if you need any help from my side.

**Comment by putyourlightson** [comment]
I've decided against adding this to the plugin, thanks for sharing what you've created though!
