### ISSUE TITLE
Regression in Contact element page

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#182]
### Describe the bug
Visiting a Contact element page the Mailing Lists tab list the Contact itself as rows instead of the mailing lists the Contact is subscribed to. 

### To reproduce
Steps to reproduce the behaviour:
1. Go to a Contact element page. 
2. Click on Mailing lists tab.
3. See the Contact repeated for every existing Mailing list. 

### Expected behaviour
This tab should list the mailing lists. 

### Screenshots

![kepernyokep_20201008_155026](https://user-images.githubusercontent.com/9061795/95468141-7f3a7980-097e-11eb-9b50-a3a86d5d80bb.jpg)

### Versions
- Plugin version: 1.16.2
- Craft version: 3.5.12.1

**Comment by bencroker** [comment]
Thanks for the PR, fixed in https://github.com/putyourlightson/craft-campaign/commit/5eeebc657f950b0fdb4ac3678791d27180acca09 and released in 1.16.3.
