### ISSUE TITLE
Sync all users with a mailing list.

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#184]
### Is your feature request related to a problem? Please describe.
We would like to use campaign but it seems like to use users already present in Craft, you have to add them to a member group.
Our users aren't in a member group, so there is no way to get them into Campaign.

### Describe the solution you would like
We would like the ability to sync all users to a mailing list so that new users also get added to this list.

I can anticipate being asked to exclude someone from the mailing list too, so not sure how that could be handled in this scenario.

Cheers Ben!

**Comment by Saboteur777** [comment]
Using a custom module you can automatically sign-up your users to a mailing list on registration with the following code: 

```
        Event::on(
            User::class,
            User::EVENT_AFTER_SAVE,
            function(ModelEvent $event) {
                /**
                 * @var User
                 */
                $user = $event->sender;

                if ($event->isNew) {                    
                    $contactElement = ContactElement::find()
                        ->email($user->email)
                        ->one();

                    if (!$contactElement) {
                        $contactElement = new ContactElement();
                        $contactElement->userId = $user->id;
                        $contactElement->email = $user->email;

                        Craft::$app->elements->saveElement($contactElement);
                    }

                    $mailingList = MailingListElement::find()
                        ->id(123456789)
                        ->one();

                    if (!$mailingList) {
                        return;
                    }

                    if (!$contactElement) {
                        return;
                    }

                    Campaign::getInstance()
                        ->mailingLists
                        ->addContactInteraction($contactElement, $mailingList, 'subscribed');
                }
            }
        );
```

(This is what I do on [Craft Report](https://craft.report), but @bencroker will fixme, if something is wrong with the code).

**Comment by bencroker** [comment]
This feature will be added in a near-future version.

**Comment by johnwbaxter** [comment]
@bencroker I don't suppose you could share a rough timeframe on this one could you please?

**Comment by bencroker** [comment]
I explored your request a bit further and here are some thoughts.

> We would like the ability to sync all users to a mailing list so that new users also get added to this list.

This can already be accomplished by adding all users to a user group that has the sole purpose of being used for syncing users to a mailing list.

> I can anticipate being asked to exclude someone from the mailing list too, so not sure how that could be handled in this scenario.

This would be trivial to do by simply removing the user from the user group. If, on the other hand, you synced all users to a mailing list then there would be no way to exclude specific users from being synced.

So my conclusion is that the current way of handling things in Campaign should work well for your use-case. The only thing you need to do is assign all existing users, as well as all new users, to a user group.

**Comment by johnwbaxter** [comment]
Hi Ben, so the main issue here is that people are coming into the system via a SSO and being added all the time and they aren't being put into any group at all.

If they were going into a group, I would never have asked for this feature as they would already be in a group which your plugin already supports using!

Thanks!

**Comment by bencroker** [comment]
So it sounds like that is the best place to solve the issue. Do you have a default user group for new users selected? Otherwise something along the lines of the following will put all new users into a specific user group.

```php
use Craft;
use craft\elements\User;
use craft\events\ModelEvent;

Event::on(User::class, User::EVENT_AFTER_SAVE, function(ModelEvent $event) {
    if ($event->isNew) {
        /** @var User $user */
        $user = $event->sender;
        
        if (!$user->isInGroup('sync-group-id')) {
            Craft::$app->getUsers()->assignUserToGroups($user, ['sync-group-id']);
        }
    }
});
```
