### ISSUE TITLE
Add contact/subscribe to mailing list from a different site

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#185]
### Question
Is it possible to embed a subscribe form in a completely different site? It seems impossible right now as the `forms/subscribe` action expects a CSRF token, which is unknown for a separate site. 

### Additional context
Slightly related to https://github.com/putyourlightson/craft-campaign/issues/84

**Comment by bencroker** [comment]
You're right that CSRF protection will (intentionally) not allow submitting the form from another site. You could create a custom module/plugin that disables CSRF validation when a POST request is submitted from an allowed site, for example.

```php
public function init()
{
    parent::init();

    if (Craft::$app->request->isPost && Craft::$app->request->referrer == 'your-allowed-site') {
        Craft::$app->request->enableCsrfValidation = false;
    }
}
```

**Comment by Saboteur777** [comment]
Thanks, Ben!
