### ISSUE TITLE
SMS integration

### ISSUE THREAD

**Issue by AndrewMac** [putyourlightson/craft-campaign#189]
I've been through the documentation, so I'm not sure if I've missed something that Campaign can already do, but I'm wondering if (and if so, how) Campaign has any way to send SMS messages in addition to email.

If it's not something that can be supported directly, is there any way to send mailouts to an SMS provider API or something?

Thanks in advance for any help or advice you may be able to give with this.

Andrew

**Comment by bencroker** [comment]
Support for sending SMS is not planned. As the tagline says, "Campaign is an email marketing plugin". You could surely write a module/plugin that adds this kind of functionality to the plugin.
