### ISSUE TITLE
Issue creating and displaying template segments

### ISSUE THREAD

**Issue by willbocc** [putyourlightson/craft-campaign#190]
### Describe the bug
I am getting the following sever error when trying to create and list Template segments.
HTTP 400 – Bad Request – yii\web\BadRequestHttpException
Request must accept JSON in response

### To reproduce
Steps to reproduce the behaviour:
1. "+ new segment" button
2. Complete and save a segment
3. Segments index /admin/campaign/segments/template displays server error

### Versions
- Plugin version: 1.16.3
- Craft version: 3.5.12.1

**Comment by bencroker** [comment]
Can you please paste the rest of the stack trace here?

**Comment by willbocc** [comment]
```
yii\web\BadRequestHttpException: Request must accept JSON in response in /home/forge/xxx.com/vendor/craftcms/cms/src/web/Controller.php:368
Stack trace:
#0 /home/forge/xxx.com/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(94): craft\web\Controller->requireAcceptsJson()
#1 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Controller.php(178): craft\controllers\ElementIndexesController->beforeAction(Object(yii\base\InlineAction))
#2 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('get-elements', Array)
#3 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#4 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('element-indexes...', Array)
#5 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('element-indexes...', Array)
#6 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/forge/xxx.com/web/index.php(22): yii\base\Application->run()
#9 {main}

```

**Comment by bencroker** [comment]
I'm unable to replicate this using Campaign 1.16.5 and Craft 3.5.14. Are you able to update, to help eliminate the possibility of this being a fixed issue?

**Comment by willbocc** [comment]
Getting exactly the same on Campaign 1.16.5 and Craft 3.5.14. 
I thought it could it be to do with creating segments on previous versions of the plugin but have wiped the campaign_segments DB table and the issue still happens in both local and production environments.

```
yii\web\BadRequestHttpException: Request must accept JSON in response in /home/forge/xxx.com/vendor/craftcms/cms/src/web/Controller.php:364
Stack trace:
#0 /home/forge/xxx.com/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(94): craft\web\Controller->requireAcceptsJson()
#1 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Controller.php(178): craft\controllers\ElementIndexesController->beforeAction(Object(yii\base\InlineAction))
#2 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('get-elements', Array)
#3 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('get-elements', Array)
#4 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('element-indexes...', Array)
#5 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('element-indexes...', Array)
#6 /home/forge/xxx.com/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#7 /home/forge/xxx.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#8 /home/forge/xxx.com/web/index.php(22): yii\base\Application->run()
#9 {main}
```

**Comment by bencroker** [comment]
Are you getting this error anywhere else in the CP? 
What browser are you using? 
Can you attach the contents of the full request (in the request tab of the browser's dev tools)?

**Comment by willbocc** [comment]
Only in response to adding a template segment for instance if I try and add a template segment to a sendout.
Using Chrome, but also tried in safari and getting the same issue.

Here is the Request Payload:

{"context":"index","elementType":"putyourlightson\\campaign\\elements\\SegmentElement","source":"segmentTypeId:2","criteria":{"siteId":1,"search":null,"offset":0,"limit":100,"status":null},"disabledElementIds":[],"viewState":{"mode":"table","order":"title","sort":"asc"},"paginated":1}

**Comment by bencroker** [comment]
The request headers would be interesting to see, especially whether `Accept: application/json` exists.

**Comment by willbocc** [comment]
The server error was due to an invalid template segment which had become invalid due to a field (which was used in the template) being deleted.
