### ISSUE TITLE
Shared URLs aren't tokenized, flagged for preview

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-campaign#192]
### Describe the bug
After configuring Cloudflare reverse proxy purging in Blitz, email campaign previews began having issues when using the "Share" button to preview content. Using "live-preview" works as expected.

The recommended Blitz + Cloudflare setup was followed, with the Cloudflare page rule is setup as follows: `www.domain.com/*`

Once the page is viewed via the "Share" button, Cloudflare caches and serves the cache version of the page according to the caching rules. If this were a normal web request for a published/sent message this behavior would be fine, but this is a preview of a message being created.

Checking pages created with Craft standard singles, channels or structures worked as expected when viewing both "live-preview" and "View/Share" versions of the page.

The noticeable difference between a standard Craft shared preview and a campaign preview is the lack of tokenized query string on the campaign share. When using the Share/View button with core Craft entries, a query string with `?x-craft-preview=XXX&token=XXX` is appended to the URL that seems to handle a number of behind the scenes rules for the page.

### Expected behaviour
Using the Share/View button to preview a campaign message in a new tab should work the same way as other Craft pages viewed in this method that includes a query string and rules for bypassing the cache (and anything else that shouldn't apply to a preview).

### Versions
- Plugin version: 1.16.4
- Craft version: 5.6.43
- Blitz: 3.6.11

**Comment by bencroker** [comment]
> When using the Share/View button with core Craft entries, a query string with `?x-craft-preview=XXX&token=XXX` is appended to the URL that seems to handle a number of behind the scenes rules for the page.

This is only the case when editing a draft or an unpublished entry. As soon as you are editing a live entry, the Share/View button redirects to the live URL of the entry.

Since campaigns do not support the concept of drafts, nor do they have a post date, they can always be accessed through their URL. If the URL was to have a token query string appended then it would not be, as the button suggests, a URL that can be shared.

FYI, once a campaign is saved, Blitz will refresh the page's cache, since campaigns are elements.

**Comment by raptureaid** [comment]
Understood. Is it possible to set multiple preview targets in the same way Craft allows for content entries?

The use case, and where we're running into caching issues, is needing multiple views of the campaign entry:

1. A web accessible version of the final email
1. A preflight view of the email showing the email and code output side-by-side - allowing an easy way for editors to copy the email HTML and move to other platforms if necessary.

![Screen Shot 2020-10-28 at 8 56 14 AM](https://user-images.githubusercontent.com/5720326/97438650-7264d200-18fb-11eb-9b01-29f40078a244.png)

We were able to accomplish both on a single template with logic such as:

```
{% if currentUser and not craft.app.request.isActionRequest %}
  {% if not craft.app.request.isLivePreview %}
    EXTRA PREVIEW CONTENT
  {% endif %}
{% endif %}
```

Once Cloudflare is introduced into the equation, the final output (1.) is always returned. Leaving no way for the editor to view the preflight preview.

It is possible to add another page rule to Cloudflare to exclude all emails, but then the final output (1.) would also be excluded - not desired.

Using live preview for the preflight extras is also not an option as links are not fully converted to a final URL - they're still using Craft pointers and such.

As you mentioned previously, it is possible to manually add a `?nocache` string to the URL to bypass the cache, but trying to explain that worked around and extra step to various editors is not viable.

**Comment by bencroker** [comment]
> Is it possible to set multiple preview targets in the same way Craft allows for content entries?

Not currently.

> It is possible to add another page rule to Cloudflare to exclude all emails, but then the final output (1.) would also be excluded - not desired. 

What about having two templates for handling campaigns, one for end-users (that is cached) and one for editors (uncached)? The Share/View button would link to the uncached version, but you would point end-users to the cached version.

There is an item on the [roadmap](https://github.com/putyourlightson/craft-campaign/blob/develop/ROADMAP.md) which may be of interest to you, even if it doesn't quite solve your issue:

> Add campaign share link with token for disabled campaigns

**Comment by raptureaid** [comment]
> What about having two templates for handling campaigns, one for end-users (that is cached) and one for editors (uncached)?
Yes, is that possible and I'm justing missing something? This was why I was initially looking to set an additional preview target.

Maybe its not a caching issue and just the wrong approach? In a way, I'm trying to recreate something similar to the preview tab when creating a sendout. Because some messages are being sent outside of Craft campaign, the editors are only in the campaign section adding content and adjusting the layout of a campaign message. Is there a better way I can offer portability of the HTML/text output of the campaign message for instances where the sendout will not be in Craft.

_I get this isn't the intended use of the plugin, but also think it speaks to the power and flexibility of Craft and the Campaign plugin that users want to leverage the CMS to build emails._

**Comment by bencroker** [comment]
The simplest way of course would be to exclude the preview template from being cached. If caching email templates is important then a different, public-facing URL could be used for the email templates that should be cached.
