### ISSUE TITLE
Add field layout tabs to campaign types

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#198]
We have seen, that its not possible to use tabs in fieldlayout. Thats something we would need for a current project.

**Comment by bencroker** [comment]
Thanks for the suggestion. This is already on our list of things to consider but is of low priority at the moment. If this is a feature you absolutely need then feel free to get in touch with us at info@putyourlightson.net and we can discuss what that might take.

**Comment by rsgd** [comment]
This would be very handy for us too. Plus 1.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/472f61b65060715dfd56226c6c72fa749389a6bd for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
