### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by stovepot** [putyourlightson/craft-campaign#2]
CVS generated lists (Mailchimp) fail to load in import section. Also the field mapping tool only shows one column only.

Running 3.0.0 RC16 on MAMP PRO
![2018-03-25_07-42-28](https://user-images.githubusercontent.com/130454/37868776-30f7ce9e-3000-11e8-8bf0-745c592efba6.jpg)

**Comment by putyourlightson** [comment]
Do you have more columns set up in your contact field layout (Plugin Settings > Contact Settings)? And can you check the contacts of the craft > storage > logs> queue.log file to see if there's a related error there?

**Comment by putyourlightson** [comment]
Can you please let me know the status of this? Would like to ensure that it is fixed for the next release.

**Comment by stovepot** [comment]
All fixed - thank you!
