### ISSUE TITLE
Add Multi-Site Functionality

### ISSUE THREAD

**Issue by putyourlightson** [putyourlightson/craft-campaign#20]
Functionality planned for better multi-site functionality in version 1.4:

1. Ability to define multiple "from name" and "from email" combinations in Settings > Email Settings. Only pre-defined name-email combinations will be available on the sendout edit page.
2. Campaign Types will get a site settings table in which individual sites can be enabled/disabled and each receive unique templates, as in the section settings.
3. Mailing List Types will get a site settings table in which individual sites can be enabled/disabled and each receive unique templates, as in the section settings.
4. The edit sendout page will get a site select field which based on the site selected will determine which campaign types and mailing list types can be selected.

_Please refer to the feature numbers above when giving feedback._

**Comment by philipboomy** [comment]
Looking good.

3) To confirm that this is also where the email from (inputted emails in point 1) will be picked when sending out the double opt-in confirmation email when someone subscribes to a mailing list?

**Comment by putyourlightson** [comment]
3. I hadn't thought of that but yes, I'll need to add a "from" select field to the mailing list types page. Would a single field satisfy it or would one "from" field per site be better in your opinion?

**Comment by philipboomy** [comment]
3) It depends if you are sticking to the idea about about enabling/disabling sites per mailing list type. That gives user a chance to use a mailing list type for multiple sites so it would be smart to allow user to select multiple from email (Otherwise if feels you give them only to take back). Personally I don't and I dont think I would in the future use multiple sites on 1 mailing list type (I like to separate a bit) so in that case 1 single field would be enough for me.

**Comment by putyourlightson** [comment]
3. Well that kind of brings me back to the original idea of the site settings table. A simpler alternative would be to have a select field whereby you can only select a single site for each mailing list type (and campaign type too probably). How does that compare to the original feature description?

**Comment by philipboomy** [comment]
3. I think that makes sense and feels less confusing. So like in the general settings you can set the sites up with from email and from name and then you can select that site when creating the mailing list type.

**Comment by putyourlightson** [comment]
3. Would that be limiting though, as then you can only use a single "from" name and email per site.

**Comment by philipboomy** [comment]
3. If you go with the 

> you can only select a single site for each mailing list type 

Then you could add a field to the mailing list type that would be used to overwrite from name/email for that particular mailing list type.

**Comment by putyourlightson** [comment]
3. Yeah this is where I see things getting either limited or overly complicated. Thanks for your suggestions, I'll need to consider it all together. If anything else comes up in the meantime then feel free to comment.

**Comment by putyourlightson** [comment]
Here is what the UI will look like. I may drop the "Verify Success" field in the Mailing List Type page and simply default to the "Subscribe Success" field value. Any thoughts on this?

![screenshot 2018-10-09 at 22 27 25](https://user-images.githubusercontent.com/2318222/46697429-e0ef6e00-cc14-11e8-9646-c172ed6f15f9.png)

![screenshot 2018-10-09 at 22 31 58](https://user-images.githubusercontent.com/2318222/46697437-e6e54f00-cc14-11e8-8aa1-7e8752dc219a.png)

**Comment by philipboomy** [comment]
Looks good. Personally I would drop the verify successfully as the finally outcome is the same. The user has subscribed. There might be someone who would like the extra feature but imho keep it simple is the best approach.

**Comment by putyourlightson** [comment]
Agreed, thanks for the feedback!

**Comment by putyourlightson** [comment]
After lots of consideration, this feature has been added but with a simpler implementation. As of v1.4, each campaign type, mailing list type and sendout can be assigned to one and only one site.
