### ISSUE TITLE
Creating a segment of emails based on open/non-open/click of a campaign/sendout

### ISSUE THREAD

**Issue by paddling** [putyourlightson/craft-campaign#200]
### Question
We are moving from mailchimp to Campaign plugin and love all the features so far. Is there a way that I can create a segment of email addresses based on whether they open / didn't open / clicked on a particular campaign or send out?

For example, If someone received a sendout but didn't open the message, I want to send them a follow up email but can't figure out how to select just that group.

**Comment by bencroker** [comment]
There isn't, the closest option is probably to check for last activity before a specific date.

![Screenshot 2020-12-10 at 22 16 48](https://user-images.githubusercontent.com/57572400/101830908-8116e980-3b35-11eb-8734-1db9c8b68f07.png)

Also, it's important to remember that many email clients these days block the tracking images sent in emails, so whether or not a contact opened an email (and therefore thier last activity) can never be 100% accurate, meaning there would be a danger of sending follow-up emails to contacts who did in fact already open the message.

**Comment by paddling** [comment]
That's really disappointing - re-engagement campaigns are highly effective for us and while open tracking isn't perfect, it certainly reduces the number of sends to openers.

It seems that since you are tracking opens and clicks that I should be able to filter users on that for a certain campaign.
I'd love to see that as an improvement.

**Comment by paddling** [comment]
Also - could you clarify what would be included/excluded in Last Activity? Are those only measured clicks and opens or are there other things (subscribed, unsubscribed, sendout received, bounced, etc.)

**Comment by bencroker** [comment]
The date timestamp value of `Last Activity` is updated every time a contact subscribes, unsubscribes, opens a sendout and clicks a link in a sendout.
