### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by wedot** [putyourlightson/craft-campaign#205]
- A tag function would be a very useful tool. 
- Like in Mailchimp, so that you can assign tags to individual contacts to be able to use them accordingly when sending. 
- Also it would be little that you can add or remove these tags during import. So that you can control the tags via the import. 
- It would also be good if you could delete the tags globally.

**Comment by bencroker** [comment]
You can already use a custom field on the contacts for this.

![Screenshot 2020-12-14 at 14 17 49](https://user-images.githubusercontent.com/57572400/102085614-2d4b1f80-3e17-11eb-93de-5d0eb7905ee0.png)
