### ISSUE TITLE
Help! Sendout stuck on progress 3%, status of Reserved, Campaign has status of Pending but no idea how to change it?

### ISSUE THREAD

**Issue by blacksaltstudio** [putyourlightson/craft-campaign#207]
### Question
Trying to get my first sendout happening and it is stuck at 3% with a status of Reserved. 

The campaign has a status of Pending but there seems no way to change it, does it need to be changed?

All test emails have been working fine. 

Using Mailgun as the mail service.

**Comment by bencroker** [comment]
After logging in with the credentials you sent, it appears that there is an error in the queue manager that was preventing the sendout from sending.
