### ISSUE TITLE
Add option to disable @web alias warnings

### ISSUE THREAD

**Issue by michaelhue** [putyourlightson/craft-campaign#208]
### Is your feature request related to a problem? Please describe.

When preparing a sendout, a warning is displayed:

>  Alias Check Failed – one of your site or asset volume URLs is using the @web alias.

However, using the `@web` alias is not a problem if it is set explicitly in `config/app.php`, for example using an environment variable:

```php
<?php
// config/app.php
return [
    // ...
    'aliases' => [
        '@web' => getenv('SITE_URL'),
    ],
   // ...
];
``` 

### Describe the solution you would like

It seems difficult to auto-detect if `@web` is set explicility. A simple solution could be a `enableAliasWarning` setting in the plugin's `config.php`.

**Comment by bencroker** [comment]
The `@web` alias warning will now only be displayed when it is not explicitly defined, added in https://github.com/putyourlightson/craft-campaign/commit/c475a0d4a4dd5edf4f4be37e792c7dc5ba51cc6a for the next release.

**Comment by michaelhue** [comment]
Thanks Ben, much appreciated!
