### ISSUE TITLE
Make running queue in pending sendouts controller optional

### ISSUE THREAD

**Issue by kringkaste** [putyourlightson/craft-campaign#209]
### Is your feature request related to a problem? Please describe.
The SendoutController for the console runs pending jobs from the queue. If you have a separate worker, they do run in parallel and your jobs depending on FIFO may break.

### Describe the solution you would like
To be compatible to all existing installations, please add a command switch to disable the running of the queue and only add the pending sendouts to the queue.

**Comment by bencroker** [comment]
Thanks, added `campaign/sendouts/queue` in https://github.com/putyourlightson/craft-campaign/commit/fa6e128815f622bf99f85efda57b2cdfd5909ffe for the next release.

**Comment by kringkaste** [comment]
Thanks for the fast and nice solution :)
