### ISSUE TITLE
Template for when email verification token has been used or is expired. 

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#21]
Right now I can customize the template for “verify-success” and “subscribe-success”, but I would like to also be able to customize failures. Now the user only gets the grey _layouts/message template with no way back to our site.

**Comment by putyourlightson** [comment]
Ok, I'll put this on the list for an upcoming release, thanks!

**Comment by putyourlightson** [comment]
What kind of failures do you mean specifically? If they are Craft errors then it will require creating a template for each of those. See this article on how to do so:
https://nystudio107.com/blog/handling-errors-gracefully-in-craft-cms#handling-exceptions-on-the-frontend

**Comment by putyourlightson** [comment]
Never mind, I just reread the issue title :)

**Comment by putyourlightson** [comment]
Ok, so the verification errors all result in a NotFoundHttpException which returns Craft's 404 template. You can customise this by creating a template called `404.html` or `404.twig` in the root of your tem­plates fold­er, or any­where you want using the [errorTem­platePre­fix](https://docs.craftcms.com/v3/config/config-settings.html#errortemplateprefix) con­fig setting.
