### ISSUE TITLE
Failed unsubscribes – 'Unsubscribe link is invalid'

### ISSUE THREAD

**Issue by BrandKits** [putyourlightson/craft-campaign#210]
### Question
  We're having complaints that the unsubscribe link has stopped working. We're using the same tag, {{ unsubscribeUrl }} on the same template. Seems the SID is being removed from the URL resulting in error 'Unsubscribe link is invalid.'
  
  3/2/21
  Failed unsubscribe
  https://hanguppictures.com/actions/campaign/t/unsubscribe?cid=c5d03ba5a5022eF0r
  [SID s6019365ecda28dyo]
  HTTP 404 – Not Found - 'Unsubscribe link is invalid.'
  
  On testing past campaigns, this was previously working:
  
  27/1/21
  Successful unsubscribe
  https://hanguppictures.com/actions/campaign/t/unsubscribe?cid=c5e77cbe1ef54bIjM&sid=s60114c88702bacva
  [SID s60114c88702bacva]
  
  ### Additional context
  We added the {% cache globally %} tag on 12/1/21, but have tested with and without and doesn't make any difference. Have tested with different email addresses, ensuring they are initially subscribed. Can't isolate a reason why the SID is being removed.
  
  Any suggestions much appreciated. Thanks.

**Comment by bencroker** [comment]
What sendout types and what versions of the plugin were used for each of the campaigns you mention above? Are there any other obvious differences between them that might give us some clues?

**Comment by BrandKits** [comment]
All bar one exception were regular sendouts. I'm not sure of the Campaign version for the first one mentioned above, but the current versions are:

Campaign 1.18.1
Craft CMS 3.5.18

I can't see any obvious differences in the setup. Between these times, a cron job was added, in case that could make any difference.
Thanks

**Comment by bencroker** [comment]
Did this possibly happen when the site URL was still set to `/`, as per our discord conversation? Can you confirm whether this is happening to all contacts or just a few? And are you able to replicate this using your own email address?

**Comment by BrandKits** [comment]
I suspect it may have been an issue with the site URL... initially it worked fine, then we had the issue with the scheduled campaign (no clicks or unsubscribes), but just had a failed regular sendout also. I've replaced the / with an env variable for full domain and on testing to the team all can click and unsubscribe. Doing another sendout to all contacts today so will see.

Thanks for the support.

**Comment by BrandKits** [comment]
Spoke too soon... even after full domain added as site URL, while multiple members of the team can unsubscribe, one just reported that it goes to 404 again, no SID: 

https://hanguppictures.com/actions/campaign/t/unsubscribe?cid=c5ea82c128eb5aWS3

Same mailing list, same sendout, same campaign. Maddening.

**Comment by bencroker** [comment]
Can you forward the email without the SID to info@putyourlightson.net please?
