### ISSUE TITLE
How can i send custom email when user subscribes?

### ISSUE THREAD

**Issue by keyurkadam** [putyourlightson/craft-campaign#213]
I want to send notification email to admin when someone subscribes

**Comment by bencroker** [comment]
Campaign does not provide notifications for each new subscription, however you could do this with a module/plugin if you really wanted to, using the `EVENT_AFTER_SUBSCRIBE_CONTACT` event which is triggered here:
https://github.com/putyourlightson/craft-campaign/blob/61319a7831807288c16187cf331b2c28ffff89cc/src/services/FormsService.php#L195-L200

**Comment by keyurkadam** [comment]
> Campaign does not provide notifications for each new subscription, however you could do this with a module/plugin if you really wanted to, using the `EVENT_AFTER_SUBSCRIBE_CONTACT` event which is triggered here:
> https://github.com/putyourlightson/craft-campaign/blob/61319a7831807288c16187cf331b2c28ffff89cc/src/services/FormsService.php#L195-L200

Can you please help me with this?

**Comment by bencroker** [comment]
Here is a link to a module that will send notifications, just edit the email address, subject and body as needed:
https://gist.github.com/bencroker/168cc9fe4c1431758c05085492d8d0f5

You could also look into https://plugins.craftcms.com/webhooks which allows you to integrate with third-party tools, you might find one for email notifications. 

There is also this plugin which should do what you are asking:
https://github.com/percipioglobal/craft-notifications

Set it up as follows, creating the `ContactSubscribed` class as per the plugin documentation.
```php
<?php 
 
return [
    'notifications' => [
        [
            'class' => \putyourlightson\campaign\services\FormsService::class,
            'event' => \putyourlightson\campaign\services\FormsService::EVENT_AFTER_SUBSCRIBE_CONTACT,
            'notification' => \app\notifications\ContactSubscribed::class,
        ],
    ],
];
```

**Comment by bencroker** [comment]
There is also this plugin which should do what you are asking:
https://github.com/percipioglobal/craft-notifications

Set it up as follows, creating the `ContactSubscribed` class as per the plugin documentation.
```php
<?php 
 
return [
    'notifications' => [
        [
            'class' => \putyourlightson\campaign\services\FormsService::class,
            'event' => \putyourlightson\campaign\services\FormsService::EVENT_AFTER_SUBSCRIBE_CONTACT,
            'notification' => \app\notifications\ContactSubscribed::class,
        ],
    ],
];
```
