### ISSUE TITLE
Saving user gives 'Setting unknown property' error

### ISSUE THREAD

**Issue by tommysvr** [putyourlightson/craft-campaign#214]
### Describe the bug
When saving a user (either on the frontend or backend), I get a `Setting unknown property: craft\behaviors\CustomFieldBehavior::firstName` error.

I was able to reproduce this in a fresh install of Craft + Campaign.

### To reproduce
Steps to reproduce the behaviour:
1. Sync a Mailing List with a User Group
2. Edit & Save any user belonging to the synced User Group
3. See error message `Setting unknown property: craft\behaviors\CustomFieldBehavior::firstName`
4. Removing the Mailing List -> User Group sync resolves the issue

### Versions
- Plugin version: 1.18.2
- Craft version: 3.6.5.1

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/221486c93ca3e41be4b88b2bc37528b5a3512276 for the next release.

**Comment by bencroker** [comment]
Released in version 1.19.0.
