### ISSUE TITLE
Craft-MJML Workflow

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-campaign#216]
### Question
Do y'all know of a good workflow to use this with Craft-MJML? It works sooo nicely if you just use it how that is sorta meant to be used, but I understand (from reading your docs) that isn't very performant. I'd really hate to lose that amazing workflow.

Is there any way to make it more performant? Do folks have a better workflow I'm not thinking of?

**Comment by bencroker** [comment]
In theory you could use the `{% cache %}` tags to prevent the mjml tags from being rendered on each send, see https://putyourlightson.com/plugins/campaign#template-caching

But if your mailing lists are relatively small (in the hundreds) then the performance hit might be acceptable, it really depends on your requirements.

**Comment by codyjames** [comment]
We'll have tens of thousands of folks in the mailing list. Looks like I'll need to run it through MJML early and then store the rendered markup in my template files. Not ideal but not really something Campaign should be responsible for.

**Comment by bencroker** [comment]
Yeah, there's not really anything the plugin can do to help you there.
