### ISSUE TITLE
Override Transport settings via config/campaign.php

### ISSUE THREAD

**Issue by codyjames** [putyourlightson/craft-campaign#217]
### Question
I'm having trouble overriding settings set in the CP with the settings in config. Perhaps I'm doing something wrong here?

Here is what my config/campaign.php file looks like:
```
<?php

$smtpForMailtrap = [
  'transportType' => \craft\mail\transportadapters\Smtp::class,
  'transportSettings' => [
    'useAuthentication' => true,
    'host' => getenv('SMTP_HOST'),
    'port' => getenv('SMTP_PORT'),
    'username' => getenv('SMTP_USERNAME'),
    'password' => getenv('SMTP_PASSWORD'),
  ],
];

return [
  'production' => [
    'transportType' => \craftcms\postmark\Adapter::class,
    'transportSettings' => [
      'token' => getenv('POSTMARK_API_KEY'),
      'messageStream' => getenv('POSTMARK_NEWSLETTER_STREAM_ID'),
    ],
  ],
  'dev' => $smtpForMailtrap,
  'staging' => $smtpForMailtrap,
];

```

**Comment by bencroker** [comment]
What is the trouble exactly?

**Comment by codyjames** [comment]
The settings I have here (in campaign.php) aren't overriding what is set in the CP/DB. Thus, this file has no effect.

**Comment by bencroker** [comment]
The config file needs to have a key `'*' => []` for Craft to recognise it as a mutli-environment config, see https://craftcms.com/docs/3.x/config/#multi-environment-configs

**Comment by codyjames** [comment]
@bencroker D'oh! Sorry for bringing this to you without first double-checking the docs. I really appreciate your amazing plugins!
