### ISSUE TITLE
Sendouts get stuck with unclear reason

### ISSUE THREAD

**Issue by jripmeester** [putyourlightson/craft-campaign#219]
### Question
We use campaign on 2 websites as a test now. Both clients are very satisfied with managing and building the campaigns. But there's one strange behaviour we can't place.
On both websites the sendout blocks with unpredicable behaviour but always with the same error:
_2021-02-26 09:00:07 [][][info] Sending of the sendout "xxxxxxx" to p.xxxx@xxxxx.nl failed after 3 send attempt(s). Please check that your Campaign email settings are correctly configured and check the error in the Craft log._

Checking the web.log from Craft only gave me this error:
_2021-02-26 09:19:02 [-][-][-][warning][yii\web\Response::sendContent] set_time_limit() is not available
2021-02-26 09:19:02 [-][-][-][info][application] $_GET = [
    'p' => '/actions/campaign/t/open'
    'cid' => 'xxxxxx'_
    
After unsubscribing this emailaddress the sendout continues as planned. E-mailaddress does exists and does comply as a correct e-mail address when i test it.

This happens with sendouts of 5500 e-mails but also on sendouts with 400 contacts.
We tried different bulk settings from 50 to 500 to 1500. But on all settings this error occured.

Any ideas on what this could be?

It feels like a timeout after which the timed-out e-mailaddress gives an error on the next try but we can't find evidence for this.

### Additional context
Craft CMS 3.5.14
Postmark 2.0.2 (we use bulk servers from postmark for the sendouts)
Campaign (pro edition) 1.16.4

**Comment by bencroker** [comment]
This log message indicates that the plugin could not connect to your email delivery service after 3 attempts. This number is configurable with the [maxSendAttempts](https://github.com/putyourlightson/craft-campaign/blob/0294dfa15705bfe2f1ebcc268025731ac7c82333/src/config.php#L73) config setting and is generally a sign of the email delivery service throttling the number of emails that is allows to be sent in a given time.

**Comment by jripmeester** [comment]
It seems that Postmark blocks sending to e-mail to hard-bounced addresses. Which sound reasonable.
Is it possible to let campaign continue the sendout after too many failed attempts?

**Comment by bencroker** [comment]
Yes, you can set [maxSendFailsAllowed](https://github.com/putyourlightson/craft-campaign/blob/0294dfa15705bfe2f1ebcc268025731ac7c82333/src/config.php#L76) to a higher value if you wish.

**Comment by jripmeester** [comment]
Alright, will it skip the failing contact after 3 attempts on that specific contact?

**Comment by bencroker** [comment]
I'm not sure what you're asking. Setting `maxSendFailsAllowed` to 3, for example, will tell the plugin to skip at most 3 failed sends. Ideally you would set up webhooks in Postmark so that bounced emails are sent to Campaign, see https://putyourlightson.com/plugins/campaign#bounce-and-complaint-handling
