### ISSUE TITLE
Exporting, importing, and subscribing to lists with a tag or category field

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#22]
we had a problem with subscribe-actions (and possibly import actions) breaking/throwing errors when we had a tag field for contacts. Perhaps some logic could be made so that they are imported/exported by slug/id instead of the entire tag/category object..?

**Reproduce:**
* add a tag field to campaign contacts
* fill in some tags for some contacts

Test one:
* export contacts to csv 

Result: the exported file has serialized tag objects - not very csv friendly. I guess I would have expected a comma separated list of tag slugs or maybe tag ids. 

Test 2:
* try to subscribe a contact using a subscription form

Result: it fails

**Comment by putyourlightson** [comment]
Thanks Peter, I'll fix the tag field in the CSV export. 

For test 2, are you submitting tags in the subscription form and if so then how are you handling the mark-up in HTML?

**Comment by phoob** [comment]
Thanks :) I don’t believe we sent any tags in the subscribe request.

**Comment by phoob** [comment]
You can see the subscription form here: https://dfo.no/kundesider/kundenotater/abonner-pa-kundenotater (this one works by sending one request per checked mailing list)

**Comment by putyourlightson** [comment]
I looked at the form and submitting it worked fine for me. Can you please explain what the failure is and if you're getting any errors? Is the tag field required in the CMS by any chance?

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/f623421dd5802269cc475ae4ffbeba8f4ebf4801
