### ISSUE TITLE
Method putyourlightson\campaign\elements\ContactElement::__toString() must return a string value

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-campaign#220]
I have a campaign that includes the following line of Twig:

```
{{ craft.entries().section("partners").anyStatus().contact(contact).one().uid }}
```

When sending test emails from the campaign editor, the line above renders just fine.

However, when creating any type of sendout using this campaign, I get the following after clicking "Save and Preview":

<img width="1440" alt="Screen Shot 2021-03-06 at 1 23 46 PM" src="https://user-images.githubusercontent.com/2852617/110221256-12210680-7e80-11eb-80bd-6a0a14269384.png">

Any ideas how to fix this?

**Comment by bencroker** [comment]
I'm not sure what the `contact` parameter is meant to do, but it should probably receive a contact ID.
```
.contact(contact.id)
```

**Comment by daveyjones** [comment]
Thanks @bencroker. The `contact` field is a Campaign Contacts field. I had assumed I could pass a contact object in. Changing to only the ID seems to have solved the error. Thanks!
