### ISSUE TITLE
Blank space in campaign contact field when no avatar is available

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-campaign#221]
Only 2% of our contacts have Gravatars, which means the fallback avatar image is used 98% of the time. My guess is that this is fairly common among Campaign users. My preference would be to omit the avatar altogether, but I don't mind the fallback image. However, the Campaign Contact field doesn't show the fallback image—it just shows whitespace instead:

<img width="298" alt="Screen Shot 2021-03-09 at 4 14 11 PM" src="https://user-images.githubusercontent.com/2852617/110556002-8662e080-80f2-11eb-8d69-837c1809c376.png">

Can the avatar be omitted here, or can we use the fallback image there to avoid the blank space?

**Comment by bencroker** [comment]
Thanks, will fix this for the next release.

**Comment by daveyjones** [comment]
One more thought on this—there is also whitespace in entry list views:

<img width="631" alt="Screen Shot 2021-03-11 at 2 53 49 PM" src="https://user-images.githubusercontent.com/2852617/110866247-b092da80-8279-11eb-8932-34f2012a7c7d.png">

I'm not sure if this needs to be addressed separately or not, but I figured I'd point it out.

BTW—my clients love this plugin! Nice work!

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/2c4a259b3ca54199c9bd3e30fec0d1ab5f43a2a9 for the next release.
