### ISSUE TITLE
Sendout pending

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#225]
### Describe the bug
Sendout are in the queue manager for hours and don't continue. All system configs are ready to go. I'm sendung over mailsend, but everything looks good and other email sends over mailsend work fine.

The tool under `/admin/utilities/campaign` don't do any help.

### Screenshots
<img width="794" alt="Bildschirmfoto 2021-04-21 um 21 37 01" src="https://user-images.githubusercontent.com/69263307/115611004-ddf78d00-a2e9-11eb-8ab5-f0613f7c5863.png">
<img width="803" alt="Bildschirmfoto 2021-04-21 um 21 37 10" src="https://user-images.githubusercontent.com/69263307/115611012-e059e700-a2e9-11eb-8747-359a6c6c1ff4.png">
<img width="807" alt="Bildschirmfoto 2021-04-21 um 21 37 17" src="https://user-images.githubusercontent.com/69263307/115611021-e18b1400-a2e9-11eb-96fb-6e6f2bbba64d.png">

### Versions
- Plugin version: Campaign 1.19.1
- Craft version: Craft CMS 3.6.12

**Comment by alexanderloewe** [comment]
Infos from the log
`021-04-21 21:36:49 [][5][info] An exception has been thrown during the rendering of a template ("session_set_cookie_params(): Cannot change session cookie parameters when headers already sent").`

**Comment by bencroker** [comment]
What happens when you restart the queue job? Can you please send the `storage/logs/queue.log` file to info@putyourlightson.com and we'll take a closer look?

**Comment by bencroker** [comment]
Update: I believe this is a session issue that was introduced in Craft 3.6.9 but am waiting for Pixel & Tonic to confirm.

In the meantime, clearing the compiled template caches (in the Cache Utility), restarting FPM if OPcache is enabled and restarting the queue job appears to fix this issue.

**Comment by bencroker** [comment]
Just released version 1.19.2 which should catch template rendering errors, failing the sendout rather than causing the queue job to hang. Still working on a long-term solution to the underlying problem.

**Comment by bencroker** [comment]
I worked with Pixel & Tonic on this and believe that https://github.com/craftcms/cms/commit/8707e2f79bb56c7d2fdad1432701f3dc5b262cdd will solve this issue long-term. It should be released in the next version of Craft.

**Comment by bencroker** [comment]
This fix was released in [Craft 3.6.14](https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#fixed-1).
