### ISSUE TITLE
Export recipients from sendout

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#226]
### Describe the solution you would like
It would be nice to be able to display all email addresses, a sendout was send to.
And then maybe also export them to be able to analyze them.

<img width="369" alt="Bildschirmfoto 2021-04-25 um 21 44 03" src="https://user-images.githubusercontent.com/69263307/116007569-a56cf180-a610-11eb-82a1-c087c57df536.png">

**Comment by bencroker** [comment]
Displaying all email addresses that a sendout was sent to doesn't seem that common a use-case. A more common use-case, which is already possible, is displaying/exporting email addresses in mailing lists.

**Comment by alexanderloewe** [comment]
Yes that would be great.
