### ISSUE TITLE
Collect IP address

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#227]
### Is your feature request related to a problem? Please describe.
I'd like to collect the IP address of the subscribers. Because we make a custom phishing testing with the employees of a company to track how good or bad they can identify a phishing attack. But with GeoIP I only can collect the location of the subscribers/employees.

**Comment by bencroker** [comment]
We can consider a config setting that stores the IP address in addition to GeoIP data that is already collected. Would that help in your use-case?

**Comment by bencroker** [comment]
I don't see why you'd need IP address collection to identify whether contacts clicked on links in the email, as campaign reports already provide this functionality. Since you haven't responded I'm closing this in favour of user privacy.
