### ISSUE TITLE
Include sent emails in campaign activity

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-campaign#228]
As far as I can tell, there's no way to confirm that a campaign has been delivered to a particular contact. The image below shows what the report looks like after a campaign has been delivered (but not yet opened). It's only when the email is opened that the report shows any activity. Would it be possible to add an indicator here that the campaign has been sent? Or is there another way to find that out?

<img width="712" alt="Screen Shot 2021-05-15 at 7 19 36 PM" src="https://user-images.githubusercontent.com/2852617/118383469-cfcc2200-b5b2-11eb-86a7-d3c19c054bb8.png">

**Comment by bencroker** [comment]
The campaign index screen shows the sent status of each campaign.

<img width="340" alt="Screenshot 2021-05-16 at 10 17 08" src="https://user-images.githubusercontent.com/57572400/118392152-54ad4f00-b638-11eb-8e8a-49473ed4442f.png">

The meta panel also shows the status.

<img width="362" alt="Screenshot 2021-05-16 at 10 17 52" src="https://user-images.githubusercontent.com/57572400/118392214-ba99d680-b638-11eb-8d89-0267ea95923b.png">

**Comment by bencroker** [comment]
You're right that it's currently not possible to see sent but unopened campaigns. How would you suggest this be added? I suppose we could add a row indicating "sent" or "unopened".

**Comment by iamkeir** [comment]
+1 for this. Our client is often asking us for send reports from our server in the absence of being able to see this in the Campaign app so would be a useful addition - to see who it was sent to, who it failed with, etc.

I guess it could most logically be part of the sendout page - click on the recipient/fail counts to see more detail.

**Comment by daveyjones** [comment]
@bencroker I think my client was expecting to see something like this:

<img width="960" alt="Screen Shot 2021-06-03 at 5 50 22 AM" src="https://user-images.githubusercontent.com/2852617/120647864-e803c400-c42f-11eb-86ad-f705cc21c2cb.png">

For some background, we're using several automated and scheduled sendouts, so my client is often looking for some assurance that a specific campaign has indeed been sent to a specific contact (even if they haven't opened it yet). So for our use case, having this information on the contact report would be ideal. With the information laid out this way, you can also see how quickly a specific contact opened a specific campaign (in the attached example, the email was opened about 30 minutes after it was received).

**Comment by bencroker** [comment]
@daveyjones We can show when a sendout was "sent" to a contact, but not when it was "received", email just doesn't work that way.

The main reason we are not showing all contacts the sendout was "sent" to is that it doesn't scale well with lists of hundreds of thousands of subscribers. Once we settle on a scalable and usable UI we will be adding this, suggestions welcome.

**Comment by daveyjones** [comment]
@bencroker Yeah I was debating between the word "sent" and "received"—the distinction doesn't matter for our use case. If "sent" is more correct from a technical standpoint, that's totally fine.

I understand the scalability concern. Maybe this could be a global option that is disabled by default.

**Comment by bencroker** [comment]
A global option doesn't address the issue of scalability very well. We'll keep working towards a solution and update here once we settle on something.

**Comment by bencroker** [comment]
I've added the "sent" filter in https://github.com/putyourlightson/craft-campaign/commit/6c6942dbbc8d2c265e355255f199a33fcc182dc1 but am not entirely happy with how this has come out. I wanted to avoid mixing "sent" activity with actual interactions and the dropdown needs to reflect this. Any thoughts on how to improve this?

<img width="690" alt="Screenshot 2021-07-05 at 20 50 24" src="https://user-images.githubusercontent.com/57572400/124509812-d74dc180-ddd2-11eb-9430-1a3e0e559384.png">

**Comment by iamkeir** [comment]
I don't mind it, to be honest. If not, could you have an additional, separate filter called "Filter by activity"? It would probably make sense to have an additional column for Activity here too.

FWIW, I initially went looking here for a more in-depth view of activity... perhaps "recipients" could link directly through to this contact activity view?
![Screenshot 2021-07-06 at 18 03 29](https://user-images.githubusercontent.com/539615/124633022-c9ed1180-de7c-11eb-8c20-a12f70b8c23c.png)

**Comment by bencroker** [comment]
Thanks for the feedback, in the end I decided to make a new dedicated page for displaying campaign recipients.

<img width="1036" alt="Screenshot 2021-07-06 at 19 53 48" src="https://user-images.githubusercontent.com/57572400/124645632-f3fdfe00-de93-11eb-99f1-4c3ca87db7a6.png">

Added in https://github.com/putyourlightson/craft-campaign/commit/e07eecd1b26a02fb994d14e2f12a89138428cb19 for the next release.

**Comment by daveyjones** [comment]
@bencroker Looks great! My client is excited to have this available.

**Comment by bencroker** [comment]
With some help testing we can aim to push this release out this week. You can try it out by requiring the develop branch:
```
composer require putyourlightson/craft-campaign:dev-develop
```

**Comment by iamkeir** [comment]
Brilliant stuff, thanks @bencroker - I'll try and get in some testing this week.

**Comment by daveyjones** [comment]
@bencroker Thanks! I've installed the develop branch and tested it out. Seems to be working great. I sent a message to our client to try it out too.

**Comment by bencroker** [comment]
Released in 1.20.0.

**Comment by iamkeir** [comment]
@bencroker we realised that this doesn't surface the failed recipients (unless we have misunderstood) - is there any capacity to add that? Our client ideally wants to follow-up with failing recipients to try and get them fixed or removed. Thanks.

**Comment by bencroker** [comment]
Possibly, please create a new issue with details and we'll look into it.
