### ISSUE TITLE
Is there a way to preview email with custom field data?

### ISSUE THREAD

**Issue by mark-chief** [putyourlightson/craft-campaign#229]
is there a way when previewing a campaign to include some test data? For example {{ contact.name }} is not displaying in the preview, along with the other fields.

If this is not possible then a feature request would be to send a test of the campaign using a 'pre selected' contact. 

Context: I have a lot of fields that are conditionally displayed in an email but there is no way to page through email previews and see the data pulling through.

Thanks x10

**Comment by bencroker** [comment]
You can already send a test to a contact either in the campaign or sendout edit page, on the right hand side.

<img width="370" alt="Screenshot 2021-05-20 at 19 36 47" src="https://user-images.githubusercontent.com/57572400/119031262-31bdca80-b9ab-11eb-8410-cfa85ee8654d.png">

**Comment by mark-chief** [comment]
Hello. That will send a test to that person. I’d like to be able to send a test to me with another person data in. So I can test.

The equivillant in mailchimp would be to test the merge tags with live data.

Best

**Comment by bencroker** [comment]
Normally if I need to test custom fields then I populate them in my own contact. If you need to test custom field variations then maybe set up some test contacts? But this kind of testing should generally happen in a development environment, where you can use [Mailtrap](https://mailtrap.io/) or [Mailhog](https://github.com/mailhog/MailHog) for testing emails.
