### ISSUE TITLE
Sendout appears stalled if sent two multiple mailing lists, and contact has bounced on just one of them

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#23]
I first sent out a campaign to two mailing lists in one sendout (many of the subscribers appear on both lists). Some of them bounced. But after handling the bounces, I registered that the bounces were only registered for one of the lists.

The next campaign that went out to the same two mailing lists appeared stalled (went back to pending, saying some mails were left unsent) after sending to all contacts. After inspecting the remaining users, I realized that the ones that remained in the sendout queue were ones that had been bounced in one of the lists, but not the others. 

I guess this problem occurs in part because bounces are written to the database both in campaign_contacts, contacts_campaigns and contacts_mailinglists.. maybe bounces should only be registered to - or at least retrieved from - the contact itself?

My solution right now a to run a few sql queries to sync bounce status for all mailinglists based on the status in the contacts model..

Regards, Peter

**Comment by putyourlightson** [comment]
Thanks Peter, I'll look into this and get a few out in the coming days.

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/f623421dd5802269cc475ae4ffbeba8f4ebf4801
