### ISSUE TITLE
Using cache globally shows wrong "in browser" version

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#230]
Not sure if this is a bug or if I'm doing it wrong. I'm building a newsletter based on matrix blocks. These blocks can also just link to an article on the website and include the first paragraph and image from that article. To speed things up when sending. I have put the complete matrix block between `{% cache globally %}` tags since it will be the same for every user. (Like suggested in the docs.)

However, when a user now clicks the "view this mail in the browser" link, it goes to the correct url (domain.com/mailing/this-is-the-correct-uri), but is shows a newsletter from weeks ago. Probably this has to do with the caching. Do I need to do something else? I thought caching globally was still related to the url, so it seems weird that it shows another cached newsletter?

**Comment by bencroker** [comment]
Using the `globally` parameter will cache the output globally rather than on a per-URL basis, so each time the template is rendered, the cached result will be output. What is likely happening in your case is that an old newsletter is being viewed (and cached) and its cached output is being shown for the latest newsletter.

**Comment by bencroker** [comment]
One idea to avoid this would be to add `using key` to the `cache` tag, using the campaign ID as the key.
https://craftcms.com/docs/3.x/dev/tags.html#using-key

**Comment by michaelhue** [comment]
I ran into this myself today. The documentation mentions "caching globally" but I can see now that I didn't use it correctly in my case.

> If there are parts of your campaign template that do not need to be dynamic then you can reduce their rendering time by caching those partials using Craft’s {% cache %} tag with the globally parameter.

https://putyourlightson.com/plugins/campaign#template-caching

**Comment by bencroker** [comment]
Thanks, I've updated the docs with the following example.

```twig
{% cache globally using key 'campaign-' ~ campaign.id %}
    {% for entry in craft.entries.limit(10).all() %}
        {{ entry.title }}
    {% endfor %}
{% endcache %}
```
