### ISSUE TITLE
Truncated Contact Activity Report with no Pagination

### ISSUE THREAD

**Issue by apitel** [putyourlightson/craft-campaign#231]
### Describe the bug
The Contact Activity within Campaign Report only shows 100 results, with no pagination or export options to view more data. 

### To reproduce
Reports > Campaigns > [Select a Campaign] > View All [Under Contact Activity]

### Expected behaviour
Be able to see all the contact activity in a campaign. Being able to sort would be a plus. 

### Versions
- Plugin version: Latest
- Craft version: Latest

**Comment by bencroker** [comment]
Not a bug but the contact activity report is being redesigned to make paginating, filtering and sorting possible, in addition to making https://github.com/putyourlightson/craft-campaign/issues/228 possible.

**Comment by apitel** [comment]
Got it. I had assumed that this was bug, because if such a limitation existed on the reporting, I would've expected to see that limitation documented.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/c204e50f7f053783007729449a9205e74dc905f8 for the next release.

**Comment by bencroker** [comment]
Released in 1.20.0.
