### ISSUE TITLE
Some emojis in subject line are causing errors

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-campaign#233]
### Describe the bug
Some emojis work in the subject line, but others don't. We're using MySQL with `utf8mb4` character set.

### To reproduce
Steps to reproduce the behaviour:
1. Create a new sendout
2. Use the 🛌 emoji in the subject line
3. Get the following PDOException

```
General error: 1366 Incorrect string value: '\xF0\x9F\x9B\x8C' for column 'subject' at row 1
```

Here's a related StackOverflow post: https://stackoverflow.com/questions/54947392/incorrect-string-value-when-trying-to-pass-emoji-to-the-db-encoded-with-utf8mb4

### Expected behaviour
I would expect any emoji to work in the subject line.

### Versions
- Plugin version: 1.19.2
- Craft version: 3.6.17

**Comment by bencroker** [comment]
Campaign uses [LitEmoji](https://github.com/elvanto/litemoji), the same library as Craft uses, to convert emojis to shortcodes. I just tested adding the 🛌 emoji to a regular plaintext field and it fails validation (albeit with a prettier error than Campaign), so perhaps you should raise this issue in Craft core?

**Comment by daveyjones** [comment]
Done.

https://github.com/craftcms/cms/issues/8072
