### ISSUE TITLE
Display an error message if CSV is not included in allowedFileExtensions

### ISSUE THREAD

**Issue by daveyjones** [putyourlightson/craft-campaign#234]
Importing contacts stopped working for us a while back and we couldn't figure out why. I finally spent a couple hours troubleshooting this today and I found out it was related to `allowedFileExtensions` in `config/general.php`. We set `allowedFileExtensions` a while ago to limit the types of files our end users could upload, not realizing that we would need to include `.csv` for Campaign imports to work. This seems obvious in hindsight, but it would be great if a warning or error message could be displayed in this scenario.

**Comment by bencroker** [comment]
Thanks for reporting this, I'll look into how to better handle it in the plugin.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/f08f8bd314aac4b11e556ced122311c81df96056 for the next release.

**Comment by daveyjones** [comment]
Awesome! Thanks @bencroker!

**Comment by bencroker** [comment]
Released in 1.20.0.
