### ISSUE TITLE
[Question] Segments based on Commerce order info.

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#235]
With Pro version, are segments able to use commerce order info?
For example, is it possible to create a segment based on the product purchased by the customer or the billing address?

**Comment by bencroker** [comment]
Template segments allow you to use any twig template code you want, so you could construct a condition to check for products, see https://putyourlightson.com/plugins/campaign#template.

**Comment by watarutmnh** [comment]
Template segments must be versatile.I will see if performance is ok with many users and orders.
Better If I could sync contacts directly with commerce customers, maybe in future.
Thanks!
