### ISSUE TITLE
Individual double-opt-in verify URL – per mailing list inside the mailing lists

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#236]
We offer lead magnets to our visitors. We would love to have the option to use an individual landing page for every mailing list inside the mailing lists.

I can't find a way to do this in the doc. 

Maybe it would be best to use an entry or URL field per mailing list, but how can we inject them in the verify email together with to verify hash for every URL?

**Comment by bencroker** [comment]
I'm not sure I'm following. Are you asking for a way for a contact to subscribe to multiple mailing lists at the same time, and only have to verify their subscription through a single email?

**Comment by alexanderloewe** [comment]
Please excuse me, I was probably too vague. 

What we like to do is to have a custom Verification for every list inside the `subscribe verification email`. The URL in the email is generated by campaign. For example: `/actions/campaign/forms/verify-subscribe?pid=p60feb13471a8acab?`

In the `subscribe verification email` the link can be called with `{{ url }}`. Here, we would love it to have an individual page per list inside a mailing list.

I give you an example:

**Mailinglist 1**
- List 1 => {{ url (/verification/generic) }}
- List 2 => {{ url (/verification/generic) }}
- List 3 => {{ url (/verification/daily-news) }}


**Mailinglist 2**
- List 1 => {{ url (/verification/java-script-basics-in-30-days) }}
- List 2 => {{ url (/verification/html-basics-in-30-days) }}
- List 3 => {{ url (/verification/css-basics-in-30-days) }}

Thanks again for the support. ☺️

**Comment by bencroker** [comment]
The Subscribe Success Template is unique to each Mailing List Type. The template makes the `mailingList` variable available, which you can use to customise the output or even redirect.
```twig
{% if mailingList.handle == 'list1' %}
    {% redirect '/verification/java-script-basics-in-30-days' %} 
{% endif %}
```

<img width="555" alt="Screenshot 2021-07-26 at 18 20 25" src="https://user-images.githubusercontent.com/57572400/127023803-7abc2455-a0be-4b90-8c6c-69bf9c1b1177.png">

**Comment by alexanderloewe** [comment]
Thanks.
