### ISSUE TITLE
Single subscribe/unsubscribe page

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#237]
We use different mailing lists and in these again some lists. Now it would be quite time-consuming to create a separate unsub page for each list and link it to the templates.

My idea is to loop over all mailinglists and the lists contained in them to give the user the choice of subscribing or unsubscribing from all lists or just some of them in one place. Like in the screenshot.

**Mailinglist 1**
- List 1
- List 2
- List 3

**Mailinglist 2**
- List 1
- List 2
- List 3

E-Mail field

<img width="1019" alt="Bildschirmfoto 2021-07-22 um 22 54 48" src="https://user-images.githubusercontent.com/69263307/126708701-c77e842f-0f79-4617-a6cf-129a27a4c439.png">

**Comment by bencroker** [comment]
You can achieve this with a custom controller that subscribes/unsubscribes a contact to mailing lists: https://putyourlightson.com/plugins/campaign#subscribing-a-contact-to-a-mailing-list

Alternatively, if you cannot create a custom controller, then you could implement this on the front-end using JavaScript, by calling the front-end form action endpoints: https://putyourlightson.com/plugins/campaign#front-end-forms

We are aware that this could be made simpler so I'll leave this feature request open and hopefully we can add at some point in future.

**Comment by alexanderbuergin** [comment]
Lately I've been seeing a lot of centralized subscription management for the email settings of newsletter/email marketing tools.

It would be great if we could get this for Craft Campain as well.

<img width="754" alt="Bildschirmfoto 2023-11-24 um 23 30 41" src="https://github.com/putyourlightson/craft-campaign/assets/85960512/4067d6e9-4f85-4b0c-a741-0da004558932">

**Comment by bencroker** [comment]
Added the ability to bulk subscribe/unsubscribe an existing contact from one or more mailing list using a front-end form in [2.14.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.14.0).

```twig
    <h3>Subscribed Mailing Lists:</h3>
    {% for mailingList in craft.campaign.mailingLists.all() %}
        <label for="{{ mailingList.slug }}">{{ mailingList.title }}</label>
        <input type="hidden" name="mailingList[{{ mailingList.id }}]" value="0">
        <input id="{{ mailingList.slug }}" type="checkbox" name="mailingList[{{ mailingList.id }}]" value="1" {{ contact.isSubscribedTo(mailingList) ? 'checked' }}>
    {% endfor %}
```

See the full example in the docs at https://putyourlightson.com/plugins/campaign#contact-update-form
