### ISSUE TITLE
Bug with campaign list field

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#239]
I think I have found a bug in campaign list field. No matter which list I select in the list field, the frontend always displays the same, in my eyes random list.

This code is that I use:
`{{ craft.campaign.mailingLists.id( entry.newsletterLists.id ).one().slug }}`

**Comment by bencroker** [comment]
My guess is that `entry.newsletterLists.id` outputs `null`. Can you test it and if this is the case then I think you need to revisit your code.

**Comment by alexanderloewe** [comment]
Okay, so if the value is `null` campaign takes a list by itself?

**Comment by bencroker** [comment]
Well this is how Craft works, if the `id` is `null` then it will ignore the parameter and just select the first element (mailing list).
