### ISSUE TITLE
Feature request: premailer support

### ISSUE THREAD

**Issue by jcdarwin** [putyourlightson/craft-campaign#24]
The Campaign plugin is great, but we're running into an issue whereby the client wants to create content in rich text (i.e. Redactor) fields on the Campaign.

Given that we need to use inline styles to get a good support of HTML emails across different email clients, is there any way we can use a premailer library (e.g. https://github.com/crossjoin/PreMailer) to process a stylesheet into inline styles before the email is sent out?

This may mean providing a means whereby we can use some form of plugin with Sendouts and test emails.

**Comment by putyourlightson** [comment]
I'm using Redactor fields with the Campaign plugin without any issues. Provided your email template is set up correctly with inline styles, they should also apply to any markup that Redactor outputs. Have you run into any problems with this? I'm open to adding support for premailer would would like to understand what the issue is first so I can address it for you and others too.

**Comment by jcdarwin** [comment]
The boilerplate of my email template is all setup with inline styles and works fine -- the problem is that I've got a `body` field that is a rich text (i.e. redactor) field into which the client can type any combination of HTML (as allowed by redactor). 

I then output this in the template at the appropriate point using `{{ unescape(campaign.body) | raw }}` -- however of course I get HTML but no inline styles.

The main problem here is that the `<p>` tags get rendered using a serif font, but these should be rendered using a particular `font-family` -- with premailer I'd be able to do `<p style="font-family: Calibri, Candara, Segoe, 'Segoe UI', Optima, Arial, sans-serif;>`.

I might be missing something here, but I can't find another way (other than using inline styles on the `<p>` tags) of controlling the `font-family`.

**Comment by phoob** [comment]
I got it to work by using MJML.io and making the styles for refactor fields not inline. As long as the style is not loaded through an external style sheet, it seems to have good cross-client support. 

https://litmus.com/blog/do-email-marketers-and-designers-still-need-to-inline-css

--
Sendt fra min mobil

**Comment by jcdarwin** [comment]
@phoob Thanks for the link! Yep, I've switched to an embedded stylesheet, and it seems to work -- will do some testing across other email clients over the next day or so, but if the email client support for embedded stylesheets is good enough that we can forego inline styles, that'd be fantastic (and there's then no need for premailer)

**Comment by putyourlightson** [comment]
Yep I've heard great things about https://mjml.io/. Let us know how it goes.
