### ISSUE TITLE
CSV import problem

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#240]
### Question
I'm trying to import some CSV files via the Import Contacts tabulation.
I've got an error "The file you selected to upload must be a CSV file". But my files are some perfectly valid CSV one.
I've noticed that the import succeed when the file has fewer than 3 lines of data (header included).
A file with more than 3 lines of data trigger the "The file you selected to upload must be a CSV file" alert when the very same file with just 3 lines of data does not trigger the alert and the import goes flawlessly!

Thanks for your help.

**Comment by bencroker** [comment]
Can you please send a sample file that is failing to info@putyourlightson.com and we'll take a closer look?

**Comment by scandella** [comment]
Hi,
Here's a CSV dummy file with 4 entries (including the header).
When I try to import it, I've got the "The file you selected to upload must be a CSV file" alert.
When I remove the last line, it works.

Same thing with real CSV file with real-world data.

Thanks for your help.

**Comment by bencroker** [comment]
There's no CSV file here...

**Comment by scandella** [comment]
Well, it was enclosed to my mail.
So you'll find it at :
http://navette.scandella.fr/CQwfKIP <http://navette.scandella.fr/CQwfKIP>

Best,

**Comment by bencroker** [comment]
Thanks. FYI these emails are coming through [this GitHub issue](https://github.com/putyourlightson/craft-campaign/issues/240).

**Comment by bencroker** [comment]
I just tested with this file and it worked fine: [import-test.csv](https://github.com/putyourlightson/craft-campaign/files/6879729/import-test.csv)

**Comment by scandella** [comment]
Thanks for your answer. 
Alas, It does not work in my environnement. Is there any log I can send you that can help to resolved the issue?

Cédric Scandella

**Comment by bencroker** [comment]
What environment is this failing in? Can you attach a CSV file that is failing to this GitHub issue?

**Comment by scandella** [comment]
I did some test and it appears that this issue seem to be relative to the PHP version in use.
In my local environment, with PHP 7.4.20 the import works fine.
Switching my local environment to PHP 8.x, the alert  "The file you selected to upload must be a CSV file" is raised.

In my production environnement, where the issue is present, I use:
PHP version	8.0.2
Database driver & version	MySQL 8.0.23
Craft edition & version	Craft Pro 3.7.5
Yii version	2.0.42.1
Twig version	v2.14.6

In my local dev, where the very same file is correctly imported, I use:
PHP version	7.4.20
Database driver & version	MySQL 5.7.32
Craft edition & version	Craft Pro 3.7.5
Yii version	2.0.42.1
Twig version	v2.14.6 

So it might be a Craft/Yii issue, something relative to the type file validator process, and not to your plugin itself…

No need to attach some other CSV file, the dummy CSV file that I've sent you raised the issue in PHP 8.x.

**Comment by bencroker** [comment]
Thanks, the PHP version was indeed the issue. Fixed in https://github.com/putyourlightson/craft-campaign/commit/a2ea98b7d99cd4d66dd088d4f04df6569cb31651 and released in version 1.20.1.
