### ISSUE TITLE
Renaming custom field handle causes 'column not found' error when viewing existing segments

### ISSUE THREAD

**Issue by bliswebagency** [putyourlightson/craft-campaign#242]
### Describe the bug
After renaming a custom field used by the contacts and trying to view the segments a server error occurs in ajax. The ajax response contains error message 'unknown column ', which references the original handle of the field.

``
{"error":"An exception has been thrown during the rendering of a template (\"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'field_theOldFieldName_xbaogzok' in...
``

We have temporarily got around this by removing the segments from the campaign_segments table, and manually re-entering them. 

### To reproduce
Steps to reproduce the behaviour:
1. Create segment which uses custom field
2. Rename custom field
3. Return to segment listing, error occurs and no items listed

### Expected behaviour
Created segments listed

### Versions
- Plugin version: 1.20.2
- Craft version: 3.7.8

**Comment by bencroker** [comment]
Yeah I can why this might be happening, we should really store a reference to the field rather than the field column name, or alternatively update it each time a field is updated. I'll address this for the next release, thanks for reporting!

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/fba248d7edf25e615a25d054f324c00abdcfe72a for the next release.

**Comment by bliswebagency** [comment]
Thank you for the fix!

**Comment by bencroker** [comment]
Released in version 1.21.0.
