### ISSUE TITLE
Deleting segment leaves rows in campaign_segments table

### ISSUE THREAD

**Issue by bliswebagency** [putyourlightson/craft-campaign#243]
### Describe the bug

After deleting segments, the corresponding rows are still in the campaign_segments table.

### To reproduce
Steps to reproduce the behaviour:
1. Remove existing segment from listing
2. Check campaign_segments table
3. The previous removed segments are still present in the table

### Expected behaviour
For each deleted segment, their rows are removed from campaign_segments table

### Versions
- Plugin version: 1.20.2
- Craft version: 3.7.8

**Comment by bencroker** [comment]
Can you please expand on what exactly you mean by "remove existing segment from listing"? Could it be that the element is soft deleted, which is why you are still seeing it in the `campaign_segments` table?

**Comment by bencroker** [comment]
I'm pretty sure that the soft delete is what was confusing you, let me know if you find otherwise.

**Comment by bliswebagency** [comment]
Hi Ben, we were deleting the segments from the "campaign segments" listing view user interface in the CMS. I think you are right that it could just be the soft delete confusing us. We had only inspected the database because of another issue, which you have already fixed, and we thought we would alert you of it. Thank you!
