### ISSUE TITLE
Allow segmenting on campaign activity

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#244]
A client ran a sendout and I was looking at the people that had done various actions such as click, or open etc and I thought, well, it might be nice to send a follow up email to the users that had clicked on the emails.

So, it would be great to be able to access that data in a template segment so that I could say, "send this campaign to all subscribers that have opened, or clicked on a link in, this other campaign".

I think with access to more data in that template segment, I would be able to have more scope to do what I want, and Campaign wouldn't have particularly re-positioned itself as anything more or less than it was before.

**Comment by bencroker** [comment]
Template segments are slow to process compared to regular segments, so regular segments are preferable wherever possible. If you can compile a list of what you think the most common/important things to segment by are then we can consider what might be possible to add.

**Comment by johnwbaxter** [comment]
I understand they're slow to process, but on the other hand, you shouldn't be blitzing out thousands of emails a second anyway, so I'm not sure how much of an issue that would be unless on a very very under resourced server?

At this moment in time, it would be good to just be able to:

Segment by users that clicked on links (other than the unsubscribe link) in a specific campaign. I don't know how feasible it would be to segment by *which* link they clicked on?
Segment by users that opened a campaign
What about *any* custom field on a user profile too? (assuming the mailing list is made up of people from a member group) We are going to have to do that anyway with a template segment as we want to send a mailout to only people with a specific craft commerce subscription plan that we have saved on a users profile in a plain text field.

I think that last option if possible, would open up a lot of possibilities.

Cheers Ben!

**Comment by bencroker** [comment]
> I understand they're slow to process, but on the other hand, you shouldn't be blitzing out thousands of emails a second anyway, so I'm not sure how much of an issue that would be unless on a very very under resourced server?

It slows down the sending process when there are hundreds of thousands of subscribers and a template segment has to be queried against each of them.

Thanks for your suggestions, I'll look into whether adding some of them as regular templates is feasible.

**Comment by johnwbaxter** [comment]
Fair enough!! Thanks Ben!

**Comment by bencroker** [comment]
Added a "Campaign Activity" condition rule for segmenting by contacts who have opened or clicked a link in any or a specific campaign in https://github.com/putyourlightson/craft-campaign/commit/1c6a7b6b292b86233dccb3973e68e39cc7cd117d, released in version 2.0.0-beta.3.

<img width="829" alt="Screenshot 2022-04-26 at 19 48 42" src="https://user-images.githubusercontent.com/57572400/165371227-688362ee-61f0-4a27-9226-232faf6cb2d8.png">

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
