### ISSUE TITLE
Allow exporting from contact activity area

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#245]
It would be great to be able to export contacts from the contact activity page. If I want to export all users that have done an specific action for example. It only lists the users at the moment.

It would be at this URL

https://example.com/lfwacp/campaign/reports/campaigns/999999/contact-activity

**Comment by bencroker** [comment]
Thanks, we'll consider this in v2.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/94b57103b7fa75c3aa4e2cf6cc8e02d2fe100b98 for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
