### ISSUE TITLE
Email verification not working when contact added to mailing list via module

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#247]
I have a module that exposes an action URL to receive email sign ups from a third party service which I then add to Campaign.

This all works well, but even though the mailing list is of a "type" that has email verification enabled, when I add a new user, it doesn't send the email to the user to click on. The user is successfully subscribed to the mailing list, it's just the verification email that doesn't go out.

The code in question:

`Campaign::$plugin->forms->subscribeContact($contact, $mailingList, 'web', $source, true);`

**Comment by bencroker** [comment]
That's right, the `subscribeContact` method on `FormsService` assumes that any required verification has already taken place. If you want to replicate the email verification behaviour of the `subscribe` action of `FormsController` then you can either replicate the logic (https://github.com/putyourlightson/craft-campaign/blob/develop/src/controllers/FormsController.php#L90-L136) or call the controller action from your own controller.

```php
$response = Craft::$app->runAction('campaign/forms/subscribe', [
    'mailingList' => $mailingListSlug,
    'email' => $email,
    // ...
]);
```

**Comment by johnwbaxter** [comment]
Oh interesting ok! I'll give that a whirl, thanks :)

**Comment by johnwbaxter** [comment]
Sorry, just to double check, from the look of things, running that controller action replaces all the code for creating the contact and adding to the mailing list. That one controller action, is all I need in total. Right?

**Comment by bencroker** [comment]
Yes, that's right.
