### ISSUE TITLE
Inconsistent reporting in bounces between report views

### ISSUE THREAD

**Issue by naboo** [putyourlightson/craft-campaign#248]
### Describe the bug
There is inconsistent reporting in bounces between the "Reports -> Contacts" view and "Reports -> Campaign -> CAMPAIGN X" view. I only have one campaign with multiple sendouts and I have some bounces (which you can see below) but the campaign report says "0" bounces.

### Screenshots
![Screenshot 2021-08-12 at 14-02-55 ⚙ Contacts - KÖPA](https://user-images.githubusercontent.com/1220045/129195723-d331cbfa-7ff3-40d0-9b7a-c05e57ceae14.png)
![Screenshot 2021-08-12 at 14-03-08 ⚙ Mattor som den tredje pedagogen - KÖPA](https://user-images.githubusercontent.com/1220045/129195730-ada9e083-9070-4719-bb91-89563137dbe1.png)

### Versions
- Plugin version: 1.20.2
- Craft version: Craft CMS 3.6.15

**Comment by bencroker** [comment]
I just did a local test and can confirm that bounces are being recorded on campaigns correctly.

If you go to _Reports → Campaigns → Your Campaign_ and click on the number of recipients (to see the _Recipients_ report) do you see that the campaign was sent to any of the contacts who bounced?

<img width="900" alt="Screenshot 2021-08-13 at 10 28 45" src="https://user-images.githubusercontent.com/57572400/129328396-dbb0751c-bf58-4f8c-8fa5-fc660c9619de.png">

**Comment by naboo** [comment]
It's a little strange @bencroker. So today I did a new sendout for the same campaign to ~1500 new contacts. When this sendout was completed the report started showing bounces. I have no idea why.

![Screenshot 2021-08-13 at 10-50-03 ⚙ Mattor som den tredje pedagogen - KÖPA](https://user-images.githubusercontent.com/1220045/129331210-2bd794a3-5db5-45aa-b31d-3da77934ec40.png)

You can see in the log from yesterday that bounces were being recorded:

2021-08-11 21:10:52 [][1][info] Sendout "Mattor som den tredje pedagogen (fri. personal)" initiated by "admin".
2021-08-11 21:11:23 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:25 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:26 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:29 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:34 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:36 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:43 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:47 [][][info] Contact **** marked as "bounced".
2021-08-11 21:11:52 [][][info] Contact **** marked as "bounced".
2021-08-11 21:12:01 [][][info] Contact **** marked as "bounced".

**Comment by bencroker** [comment]
Ok, you didn't respond to my question though, so is all good now?

**Comment by naboo** [comment]
Sorry Ben I misread the question.

So this was the first campaign I sent to, so there weren't any bounced
emails before. But when I later looked (as the log displayed) it did indeed
mark some bounces but as you can see in the screenshot they weren't shown.

Now it displays bounces after the second sendout I did this morning. Can't
say what happened before more than showing you the data :)

**Comment by bencroker** [comment]
Let me know if this comes up again, closing for now.
