### ISSUE TITLE
Bug: percentage maths

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#25]
I believe something is wrong with the percentages in this report 🤓

![image](https://user-images.githubusercontent.com/1475800/46726000-b08fea00-cc7d-11e8-82f7-4257a9d54fb7.png)

**Comment by putyourlightson** [comment]
Haha, how do you figure?!

Thanks, I'll look into this. Is this a campaign report send using an automated or recurring sendout by any chance?

**Comment by phoob** [comment]
:) regular sendout.

**Comment by putyourlightson** [comment]
Fixed in 1.3.4 https://github.com/putyourlightson/craft-campaign/commit/7d4289d39910a2d7d8a2f809b3e81e89e732a9b2
