### ISSUE TITLE
[Question] How to retrieve and handle mailing lists associated other site?

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#252]
### Question
I want to place subscribe forms for a specific mailing list across multi sites.
Is that possible?
If so how the query to get mailing list should be?

**Comment by bencroker** [comment]
As per the docs at https://putyourlightson.com/plugins/campaign#getting-mailing-lists, you can get mailing lists from your templates with `craft.campaign.mailingLists` which returns an Element Query.

```twig
{# Gets all mailing lists in all sites #}
{% set mailingLists = craft.campaign.mailingLists.site('*').all() %}
```

**Comment by watarutmnh** [comment]
@bencroker I got it, thank you!
