### ISSUE TITLE
Issue to save Mailgun Webhook Signing Key

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#253]
### Describe the bug
I can not save Mailgun Webhook Signing Key value.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Campaign > Settings > General Settings
2. Input value on field of Mailgun Webhook Signing Key and press Save button.
3. The value is empty 

### Versions
- Plugin version: 1.20.2
- Craft version: 3.7.10

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/699d4d1d117cb732217b64190f637ca98c3226fa for the next release.

**Comment by bencroker** [comment]
Released in version 1.21.0.
