### ISSUE TITLE
Sendout failed and telling it to resume results in the same error each time.

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#254]
The user has sent out a "Regular" email send to 12,000 recipients and it failed citing this error:

"2021-08-25 16:53:47 [][][info] Sending of the sendout "Aug 23 newsletter" to xxxxxx@gmail.com failed after 3 send attempt(s). Please check that your Campaign email settings are correctly configured and check the error in the Craft log."

There are no errors in the craft log pertaining to this at that time and when I go to resume the send, it says ok and then it stops again and I get another error of the same above.

I really need to resume this send to finish it and not sure what I can do here!

### Versions
- Plugin version: 1.19.1

**Comment by bencroker** [comment]
The logs should contain some details of the errors, but in general a failed sendout indicates that your email delivery service is not accepting send requests, perhaps because you have exceeded the quota or some other reason.

**Comment by johnwbaxter** [comment]
So, the issue was that we had a user in Postmark that had been unsubscribed in Postmark, but the website didn't know about that unsub for whatever reason.

So, to resolve this, I unsubscribed the contact from the Campaign plugin contact list, and then tried the resend and it worked!

Mad thanks for the help and support to the number one playa, Ben Croker!!
