### ISSUE TITLE
Feature request: Approve mailing list membership (moderate requests)

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#26]
Hello!

We have some «privileged mailing lists», where we would need to approve subscription requests. Right now this is solved by people writing us an email applying for membership. But it would be great if it would be possible to do this via this plugin.

Basically, I would like there to be an option in mailinglist type settings to – in addition to mark a mailing list type as double opt-in – to have an additional radio button:

```
*Moderate subscription requests*
Whether a subscription request need to be approved by a mailing list moderator.
```

**Comment by putyourlightson** [comment]
Interesting idea. Sounds like it would require a moderation process for notifying one or more moderators and allowing them to either approve or deny a request, followed by a notification to the subscriber. I have a few higher priority features to ship first, but that you for the suggestion, I'll keep it open for now.

**Comment by putyourlightson** [comment]
I think this is beyond the scope of the Campaign plugin and more suited to a third-party module/plugin. It should be easy to implement using a custom lightswitch field, `subscriptionApproved` for example, and then setting up a segment to check whether the value evaluates to true. 

The events you would need to notify moderators of subscriptions that need approval already exist in the TrackerService:
https://github.com/putyourlightson/craft-campaign/blob/v1/src/services/TrackerService.php#L41

**Comment by phoob** [comment]
Ah, ok that's a good idea! Thanks.
