### ISSUE TITLE
[Question] What is the 'Clicks' in links report?

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#261]
### Question
I have a simple question.
What is the 'Clicks' mean at the Links section in report?

Thanks.

**Comment by watarutmnh** [comment]
![screenshot 2021-09-01 at 16 52 21](https://user-images.githubusercontent.com/6081378/131634728-4b973464-a90f-4327-845d-e8ff9b03e65a.png)

**Comment by bencroker** [comment]
In this report, "Clicked" represents the number of contacts who have clicked on the link, whereas "Clicks" represents the number of times that a link has been clicked. So the value of _Clicks_ will always be equal to or greater than the value of _Clicked_. Make sense?

**Comment by watarutmnh** [comment]
I got it!
thank you for the help!
