### ISSUE TITLE
Automated Sendouts are not triggered

### ISSUE THREAD

**Issue by alexanderbuergin** [putyourlightson/craft-campaign#262]
### Describe the bug
Automated sendouts are not triggered more than once. After setting up an automated sendout, it does work for one time, after sending one campaign to a user it stops doing its job.

### To reproduce
1. A user registers via the form
2. Opt in
3. After the user opt in to list the `ABC`, the sendout `123`  should be sent out instantly.

### Expected behavior
- Every time someone is added to the list `ABC` the automated sendout is not triggered
- The Cron Job is added and triggers 
- The path to the php 7.4 folder for the cron job is correct
- Regular and scheduled sendouts are working fine
- I tested the same campaign as Regular and scheduled sendouts – it works

### Versions
- Plugin version: 1.20.2
- Craft version: 3.7.10

**Comment by bencroker** [comment]
Do you mean that the automated sendout is never sent multiple times for the _same_ contact? Or that after it is sent to one contact, it is never again sent to any _other_ contacts?

**Comment by alexanderbuergin** [comment]
The second one: `Or that after it is sent to one contact, it is never again sent to any other contacts?`

**Comment by bencroker** [comment]
I tested locally and all is working as expected. Note that automated sendouts will only begin to send _after_ the sendout is created. So say a contact subscribed to a mailing list _before_ you created the automated sendout, they would never receive the email. Does that help explain what might be going on?

**Comment by alexanderbuergin** [comment]
That sounds logical to me, with that understanding I ran the test. I will make a screen record and send it to you.

**Comment by alexanderbuergin** [comment]
I send you a screen record to your info putyourlightson email. Hope that helps.

**Comment by bencroker** [comment]
Thanks for the screen recording. I notice that your automated sendouts have the status "Queued", when in fact they should be "Pending".

<img width="371" alt="Screenshot 2021-09-01 at 20 23 24" src="https://user-images.githubusercontent.com/57572400/131723773-0a97a526-68e7-40d2-84e7-59639fd7899b.png">

How are queue jobs being run in your Craft setup? In other words, have you set `runQueueAutomatically` to `false` and do you have a cron job set up to run the queue as per https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically?

Perhaps you could try pausing the Sendout and then starting it again? Also be sure to test with a new test contact each time, to eliminate the possibility that they already received the sendout.

**Comment by alexanderbuergin** [comment]
I send you another screen recording.

`runQueueAutomatically` is set to `true` I saw that one in your doc.

Now all sendouts are set to back to `Pending`. The problem is they were all on `Pending` and changed by them self to `Queued`.

**Comment by bencroker** [comment]
It could be that your cron jobs are running too frequently, can you try changing them to run every 5 or 10 minutes? If the sendouts start to work then just monitor them and let me know how it goes after a few days.

**Comment by bencroker** [comment]
Has this been solved for you @abuerin?

**Comment by alexanderbuergin** [comment]
Currently, everything seems to be running cleanly.

**Comment by bencroker** [comment]
Ok great!

**Comment by alexanderbuergin** [comment]
Hello Ben,

It looks like the problem isn't resolved.

The sendout stands on pennding, but the triggered cronjob dose not trigger a sendout.

Regular sendouts can be send without any problem.

<img width="574" alt="Bildschirmfoto 2021-10-15 um 16 42 43" src="https://user-images.githubusercontent.com/85960512/137506321-77a167e2-f85f-4cb9-a1e2-61952b35ad0f.png">
<img width="348" alt="Bildschirmfoto 2021-10-15 um 16 42 57" src="https://user-images.githubusercontent.com/85960512/137506331-e04f9aa4-dab4-4bf2-aa35-761a055b05a6.png">

**Comment by bencroker** [comment]
The cron job should queue a sendout job and run it. Provided there are new subscriptions, the automated sendout should email the contacts and then go back to a "Pending" state. What exactly is not working for you now?

**Comment by adrianjean** [comment]
Adding my voice here to an old thread. **This is happening to me.** 

- `runQueueAutomatically` is false.
- Had a cron job configured to run every 1 minute, and then every 3 minutes... nothing seems to help
- Ran both campaign and craftcms queue manually nothing
- My automated campaign is saved and set to "Pending"

I did notice that when I paused the automated campaign, and then re-saved and started the automated campaign, any queued messages were sent.

So something is not being triggered. Here's my cron jobs in case they help diagnose. I have run these commands at the CLI and they run without issue:

```
# Campaign mailouts: run every 2 minutes
*/2 * * * * www-data /usr/bin/php /srv/www/website.com/craft campaign/sendouts/run >> /var/log/craft-queue-campaigns.log 2>&1

# Queue runner: run every 4 minutes
*/4 * * * * www-data /usr/bin/php /srv/www/website.com/craft queue/run >> /var/log/craft-queue.log 2>&1

```

**Comment by bencroker** [comment]
This issue is long closed and relates to an old version of the Campaign plugin, @adrianjean.
