### ISSUE TITLE
Single sendout type

### ISSUE THREAD

**Issue by alexanderbuergin** [putyourlightson/craft-campaign#263]
### Is your feature request related to a problem? Please describe.
The addition of a sendout type that can be used to send a campaign to a single contact without having to create an extra list.

### Describe the solution you would like
We use Campaign to send single height quality emails to specific persons.

<img width="982" alt="Bildschirmfoto 2021-09-01 um 17 29 17" src="https://user-images.githubusercontent.com/85960512/131699816-1af3596e-2574-4cef-80ad-d2a510fb22c5.png">

**Comment by bencroker** [comment]
Thanks, we'll consider this feature request.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/8eb4798cde3ac98890d0ec6e904c322666d54b9f for the version 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
