### ISSUE TITLE
Trim spaces from email on import

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#268]
Hey Ben,

We have a client who is importing data into Campaign and have had some "fails".

I looked into it for them, and I can see that in every case, the email was rejected as in the CSV, they had a "space" character after the email address in the cell.

Could you "trim" space left and right when importing emails as space is obviously not a valid char in an email, so there is no harm in doing that?

Cheers!

John :)

**Comment by bencroker** [comment]
Sure, added in https://github.com/putyourlightson/craft-campaign/commit/89deb332cfef73c7e8cb710d115514d95b080815 for the next release.

**Comment by johnwbaxter** [comment]
Cool, thanks Ben!

**Comment by bencroker** [comment]
Released in version 1.21.0.
