### ISSUE TITLE
New field manager for the contact fields

### ISSUE THREAD

**Issue by alexanderbuergin** [putyourlightson/craft-campaign#269]
### Is your feature request related to a problem? Please describe.

It would be great if all the options of the field manager would be available for the contacts.

Means:
- Tabs
- Lines
- Divide fields into columns
- as well as the other options in the Field Manager of Craft 

<img width="719" alt="Bildschirmfoto 2021-09-02 um 16 58 51" src="https://user-images.githubusercontent.com/85960512/131869058-0268da96-a338-48a0-ac25-4ea06c161757.png">

**Comment by bencroker** [comment]
Yes, is this already covered by the feature request in https://github.com/putyourlightson/craft-campaign/issues/163.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/472f61b65060715dfd56226c6c72fa749389a6bd for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
