### ISSUE TITLE
Report pop up not working

### ISSUE THREAD

**Issue by leightonhughes** [putyourlightson/craft-campaign#271]
### Describe the bug
Popups aren't working under contact activity. Only the first page.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Reports and click on a campaign report
2. Click on view all under contact activity
3. The clicked icon popup works for the first page but not any others

### Expected behaviour
Every icon should be clickable. Same issue also happens when changing the amount settings at the top.

### Versions
- Plugin version: 1.20.2
- Craft version: 3.7.13

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/c36726b0219057efecc1e9de5dbd7a1b44bd15bd for the next release, thanks!

**Comment by bencroker** [comment]
Released in version 1.21.0.
