### ISSUE TITLE
Timezone in reports

### ISSUE THREAD

**Issue by leightonhughes** [putyourlightson/craft-campaign#274]
### Question
Not sure if this is a bug or a config setting that I've missed. The graph times aren't the same as the hover times (correct). Do I have to change a setting somewhere.

Craft 3.7.14
Campaign 1.21.0

![image](https://user-images.githubusercontent.com/5158786/138375299-83134d62-dad8-457a-b5b5-59222eb207cd.png)

**Comment by bencroker** [comment]
Thanks for reporting this, I'll look into getting a fix out next week.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/ea1743b06703051f806c112415601af3fab9ccc8 for the next release.

**Comment by bencroker** [comment]
Released in version 1.22.0.
