### ISSUE TITLE
Regular sendout wont send and no error log for why

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#275]
The client did a regular send rather than scheduled (to about 12,000 subscribers) and it sent to about 180 and then stopped. I retried the send, but now it wont send any more, it just fails after 5 minutes (the max execution time is 3000s so not that). There is nothing being logged in craft log files to give me any indication of why, it just wont send and the campaign log just says it hasn't sent and that i should check the logs.

If i do another sendout and change it to a scheduled type this time, will it exclude the 180 that have already received this campaign? Or will it send to all again do you know?

**Comment by johnwbaxter** [comment]
Eugh, i think I have just logged the same bloody bug as before, ignore this!!

**Comment by johnwbaxter** [comment]
Ok so, this is the same issue as before, people are unsubscribing and the website isn't finding out about it from postmark!

Is there some webhook issue here or is that action simply not supported by campaign?

**Comment by bencroker** [comment]
Sorry, is the original issue no longer an issue? If this is a new issue related to unsubscribing then please create a brand new issue to help avoid confusion.

**Comment by johnwbaxter** [comment]
Will do, sorry.
