### ISSUE TITLE
Unsubscribers in Postmark not being fed back into Campaign

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#276]
We are sending out campaigns that stall and stop. I found the reason for this is that some people are in Postmark as unsubscribed, and not in Campaign as unsubscribed.

These postmark unsubscribes aren't being fed back into Campaign (i'm not even sure how they unsub in postmark and not campaign itself tbh)

Is there a a payload that Postmark sends to us when that happens that the plugin isn't processing?

**Comment by bencroker** [comment]
There is. Have you set the webhook URL to the one found under _Settings → General Settings_?

**Comment by johnwbaxter** [comment]
Yep, that is indeed there.

**Comment by bencroker** [comment]
Webhooks exist primarily for bounces and complaints. According to https://postmarkapp.com/email-webhooks:

> Postmark’s webhooks notify your application about key message events such as bounces, deliveries, opens, clicks, and spam complaints.

<img width="408" alt="Screenshot 2021-10-25 at 14 25 05" src="https://user-images.githubusercontent.com/57572400/138694796-1c606a64-67da-4eed-825c-ed2cd078523f.png">

So it is not possible to notify the plugin about unsubscribes. This begs the question, how are contacts even unsubscribing via Postmark? Is Postmark adding an unsubscribe link to emails without your knowledge.

**Comment by johnwbaxter** [comment]
Postmark do indeed add their own unsubscribe link - https://postmarkapp.com/support/article/1217-why-broadcasts-require-an-unsubscribe-link

I must admit, I hadn't realised this was being added :-/

**Comment by bencroker** [comment]
Mystery solved!

**Comment by johnwbaxter** [comment]
Swines.

I see I can start a conversation with them to stop that being added, so I'll go do that!

So, onto my other issue!, how can I mass unsubscribe users from Campaign? If there's a campaing plugin method to unsubscribe someone from any list, I can write my own code to unsub everyone on this suppression list.

Ta!

**Comment by bencroker** [comment]
It looks like there is hope, a subscription change webhook URL can be added:
https://postmarkapp.com/developer/webhooks/subscription-change-webhook

But if you can have the unsubscribe link removed completely then that might be preferable.

**Comment by johnwbaxter** [comment]
I'm asking them to remove it completely!

**Comment by bencroker** [comment]
You can programmatically unsubscribe a contact from a mailing list as follows:

```php
Campaign::$plugin->mailingLists->addContactInteraction($contact, $mailingList, 'unsubscribed'); 
```

Or mark a contact as blocked as follows:

```php
$contact->blocked = new DateTime();
Craft::$app->getElements()->saveElement($contact);
```

**Comment by johnwbaxter** [comment]
Perfect thank you. I've thought about it, and probably the best is just to unsubscribe them rather than block them. If they are just unsubscribed, they can always re-subscribe if they want at a later date.

Thanks Ben!!

**Comment by bencroker** [comment]
Sure thing!
