### ISSUE TITLE
Upload a email address suppression list

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#277]
It would be great if you could upload a csv of email addresses to unsubscribe them from any mailing list they are currently subscribed too.

I have an issue at the moment where I could really do with that ability :)

Cheers Ben!!

**Comment by bencroker** [comment]
It sounds like this is specifically related to the issue you reported in https://github.com/putyourlightson/craft-campaign/issues/276, so let's get that figured out. 

On its own, I don't see bulk unsubscribing via a CSV file as a much needed feature, so will close this out for now.

**Comment by bencroker** [comment]
FYI the ability to import unsubscribed contacts has been added in version 2.7.0, see https://github.com/putyourlightson/craft-campaign/issues/384.
