### ISSUE TITLE
Add to custom fields instead of overwriting

### ISSUE THREAD

**Issue by arnogregorian** [putyourlightson/craft-campaign#279]
I would like to provide the ability for contacts to subscribe to multiple categories, in order to do so I have added a categories field to contacts. Adding a single category to a contact is possible using for example:
`<input type="hidden" name="fields[categories][]" value="{{category.id}}" />`

If the user however subscribes to another category, the same input field overrides the existing categories field value instead of adding to it. Is it possible to change this behaviour and add multiple categories? Thanks in advance!

**Comment by bencroker** [comment]
Where exactly does this `input` field exist and how are you populating it? This issue doesn't seem specific to the Campaign plugin.

**Comment by arnogregorian** [comment]
The input field exists in the subscribe form to a mailinglist, each contact additional to the basic fields of email, first name, etc. also has a categories field that I would like to populate. 

Already working on a solution by creating my own subscription forms.

**Comment by bencroker** [comment]
I imagine something like this would work.

```twig
{% set allCategories = craft.categories.all() %}
{% set contactCategoryIds = contact.categories.ids() %}

{% for category in allCategories %}
    <input type="checkbox" name="fields[categories][]" value="{{ category.id }}" {{ category.id in contactCategoryIds ? 'checked' }}>
    {{ category.title }}
{% endfor %}
```

See the docs at https://craftcms.com/docs/3.x/categories-fields.html#saving-categories-fields
