### ISSUE TITLE
Issues with removing contacts

### ISSUE THREAD

**Issue by tombauer** [putyourlightson/craft-campaign#28]
We are evaluating a solution to send newsletters with Craft CMS. The Plugin (Campaign & Campaign Pro) seam exact what we are looking for. But we have found some issues on it:  

- When we remove a contact (xy@xy.ch) and try to add the same contact (xy@xy.ch) again it says, that the email with xy@xy.ch is already used

- When we sendout a campaign and a contact open this email, it shows the correct report (opend 1). But, when we remove this user, it shows up an error on the report ![error](https://user-images.githubusercontent.com/3863752/47703591-0de5de00-dc21-11e8-9f1e-6510c8f91726.png)

We are running latest Version of Craft/Campaign/Campaign Pro.

Thanks for your help.

Best regards from Switzerland
Thomas

PS: It's great to have a integrated campaign solution in Craft CMS :-)

**Comment by putyourlightson** [comment]
Hi Thomas and thanks for reporting this. It sounds like there is an issue with deleting contacts but I can't replicate either of your issues locally. You say "remove user", am I correct in assuming that you mean you are remving the contact? Can you please walk me through the specific steps you took to get the error message? If you have a staging server that I can access and test on then please send credentials to info@putyourlightson.net and I'll take a closer look. What exact version of Craft are you using?

**Comment by tombauer** [comment]
Thanks again for your Help, with the newest version there are no more problems. I will continue to test it now.

**Comment by putyourlightson** [comment]
Glad to hear it!

**Comment by krizzzly** [comment]
still experiencing this issue, the contact gets deleted from the mailinglist in CP, but it persists in db in "elements" and "campaign_contacts" and "campaign_contacts_mailinglists" and therefore it cannot get added again.

Craft CMS: Pro 3.1.19
Campaign: 1.7.0

**Comment by krizzzly** [comment]
Hallo again, i found the reason for the behaviour in https://github.com/putyourlightson/craft-campaign/issues/52 . But for the business case we have, we will need a hard delete, so i will write a patch, but it would be better to have a functionality for that in future. Thx

**Comment by krizzzly** [comment]
i have found a solution for now which is application-wide:

in general.php, global settings
`        'softDeleteDuration' => 1,`
and in app.php
`    'components' => [
        'gc' => [
            'probability' => 1000000
        ],
    ],`

https://docs.craftcms.com/v3/gc.html

**Comment by putyourlightson** [comment]
Thanks for posting your workaround. We'll add a solution in the next release.
