### ISSUE TITLE
Include failed emails in campaign activity/report

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#280]
### Is your feature request related to a problem? Please describe.
As per https://github.com/putyourlightson/craft-campaign/issues/228#issuecomment-848312448 and https://github.com/putyourlightson/craft-campaign/issues/228#issuecomment-960664585, would it be possible to surface _failed_ email recipients somewhere in a campaign report? Our client wants to be able to check failed recipients for a couple of reasons:

- If one of their customer contacts them to say they are not receiving emails, they can check status
- They can try and contact/fix bounces

**Comment by bencroker** [comment]
What exactly do you mean by failed recipients? Contacts that have (hard) bounced, complained or unsubscribed can already be viewed in reports.

**Comment by iamkeir** [comment]
@bencroker the folks who end up in here from a sendout:
![screenshot_1028](https://user-images.githubusercontent.com/539615/140551761-1a10f667-228c-43d8-a420-bdc0430bbd72.png)

I can double-check with our client but I would guess any/all (bonus if it shows the reason/has a filter).

**Comment by bencroker** [comment]
A failed sendout generally has to do with an email delivery service not accepting a request to send. This can be caused by a malformed email, but is more commonly an issue with the service, such as downtime, throttling or one's quota being exceeded. In other words, more often than not this failure has nothing to do with the recipient but more to do with the email delivery service.

**Comment by iamkeir** [comment]
Thanks for the insight. Could I clarify, is your point here that there is no value in knowing who they are specifically?

**Comment by bencroker** [comment]
My point is that failed sendouts generally have nothing to do with the contact, so yes, there's little value in knowing who it was sending to when it failed.
