### ISSUE TITLE
Contact pagination in mailing list view

### ISSUE THREAD

**Issue by keyurkadam** [putyourlightson/craft-campaign#282]
### Describe the bug
When you view mailing lists you can't scroll through all pages of the mailing list in craft. You also can't search for individuals.

### Screenshots
https://prnt.sc/1zquzjf

### Versions
- Plugin version: 1.21.1
- Craft version: 3.7.20

**Comment by bencroker** [comment]
Yes that's true, but this is intended, not a bug. If you'd like to see all contacts in a mailing list and search on them then you can do that on the contact index page.

<img width="861" alt="Screenshot 2021-11-17 at 08 49 38" src="https://user-images.githubusercontent.com/57572400/142177553-77025810-7eea-4a65-9e98-d52828a35896.png">

**Comment by bencroker** [comment]
Added a link to view all contacts from the mailing list edit page in https://github.com/putyourlightson/craft-campaign/commit/8ebbfbd14a0bdd32beb94ad3f00c44cdf359e2c2, for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
