### ISSUE TITLE
Using own templates for Mailing List types

### ISSUE THREAD

**Issue by whoiscado** [putyourlightson/craft-campaign#283]
### Question
I'm currently working with Campaign and want to use my own templates for my Mailing List type.
I've entered the path to the template in the same way as I did for Craft under Routes. Unfortunately, Campaign never accepts the templates.

The route has been tested in routes and is, for example, "/newsletter/email.twig". However, Campaign still uses the default template.

### Additional context
Changing it to e.g. "newsletter/email" etc. does not help either.
The lite version of Campaign is used.

Can you please tell me how I can use my own templates for "Subscribe Verification Email Template" etc?

Thanks a lot and best regards,

**Comment by bencroker** [comment]
Entering `newsletter/email` should work. What exactly are you seeing that makes you say, "Campaign never accepts the templates"? 

What versions of Campaign and Craft are you running?

**Comment by whoiscado** [comment]
Because it sadly always uses the default template instead of the ones I entered - which I tested in Routes for example and worked there. Currently using `newsletter/mail` but it still uses the default template.

Campaign version is `1.22.1`
Craft version is `Craft Pro 3.7.21`

Thanks for your help!

**Comment by bencroker** [comment]
> Because it sadly always uses the default template instead of the ones I entered.

Please walk me through the steps you are using to test this so I can reproduce this locally.

FYI there is no default template for the "Subscribe Verification Email Template". If none is found then the verification email is sent in plaintext.

**Comment by bencroker** [comment]
FYI there is no default template for the "Subscribe Verification Email Template". If none is found then the verification email is sent in plaintext.

**Comment by whoiscado** [comment]
- Fill in my form
- Press the submit button
- alert: `Thanks bla bla`
- Receive an e-mail
- `Thank you for subscribing to the mailing list. Please verify your email address by clicking on the following link: localhost/actions/campaign/forms/verify-subscribe?pid=PidOfUser`

The mail I receive after submitting the form isn't the default one for `Subscribe Verification Email Template`?

**Comment by bencroker** [comment]
If you start typing into the `Subscribe Verification Email Template` setting, does the field autosuggest `newsletter/mail`? If not then the template must not exist in the main `templates` directory.

**Comment by whoiscado** [comment]
Yes it autosuggests `newsletter/mail`.
It also doesn't work for the other template fields and it autosuggests the correct templates, too. I also don't know why it doesn't work...

**Comment by bencroker** [comment]
In that case you most likely have an error in your template. Check the Craft logs for template errors and/or test with a stripped down template to ensure that the template is being picked up, then build up from there.

**Comment by whoiscado** [comment]
@bencroker Yeah there's an error with the template, thanks. I need to use the `pid` for creating an verficiation link (f.e. `"http://localhost/actions/campaign/forms/verify-subscribe?pid={{ pendingContact.pid }}"`), but the `pendingContact.pid` doesn't work as it seems.
Do you know which var I can use to get the pid entered in the URL like my example?

**Comment by bencroker** [comment]
You should just use `{{ url }}` to output the link.

**Comment by whoiscado** [comment]
Thanks a lot, that fixed it. 
Have a nice day!

**Comment by bencroker** [comment]
Glad to hear it!
