### ISSUE TITLE
Campaign Reports show different values

### ISSUE THREAD

**Issue by tonioseiler** [putyourlightson/craft-campaign#285]
### Describe the bug
When checking the report of a campaign I see different values under "Camaign details" and "Contact Activity - 'Opened'"

### To reproduce
Steps to reproduce the behaviour:
1. Go to "Camaign details" => Opened 889
2. Click on "889" => I see 1030 entries in the list

### Expected behaviour
The number should be the same.

### Versions
- Plugin version: 1.21.1
- Craft version: Craft Pro 3.7.18.2

**Comment by bencroker** [comment]
Thanks for reporting this. I'm able to spot some discrepancies in open reports in one of our sites too, so will make sure we look into what the issue might be.

**Comment by bencroker** [comment]
This has been fixed in https://github.com/putyourlightson/craft-campaign/commit/8cd94c0a204a53f7dc231a84e932c9bd5040bc23 and released in version 2.1.11, which includes a migration that will sync all campaign report data.
