### ISSUE TITLE
List campaigns sent to a specific mailing list

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-campaign#287]
Is it possible to list campaigns (similar to `craft.campaign.campaigns.campaignType()`) that were sent to a specific mailing list?

### Additional context
I have a site that sends campaigns to two different mailing lists. Some campaigns are sent to both lists, some only to one or the other. Now my client wants to list the mailings to one of those lists publicly on the website. 
Do I have to separate those by creating a separate campaign type, or can I somehow filter the campaigns by mailing list?

**Comment by bencroker** [comment]
You should be able to query for all sendouts sent to a specific mailing list and then fetch the campaigns from the resiults, for example (untested):

```twig
{% set sendouts = craft.campaign.sendouts.mailingListId(1).all() %}
{% set campaignIds = sendouts|map(sendout => sendout.campaignId) %}
{% set campaigns = craft.campaign.campaigns.id(campaignIds).all() %}
```

**Comment by luke-nehemedia** [comment]
Worked perfectly! Thank you very much!
