### ISSUE TITLE
Subscribe Success Template not working after confirming email

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#288]
### Describe the bug
In the CP I am seeing this info "This setting is deprecated and will be removed in version 2.0.0. Use the Subscribe Success Template setting instead." regarding this setting "Subscribe Verification Success Template".

I then use "Subscribe Success Template" instead but then I am not redirected to the inputted template after confirming the email. I am instead getting this: https://share.getcloudapp.com/z8ukqEPj

If use the deprecated setting "Subscribe Verification Success Template" it works but if that field is removed in 2.0 then I cannot use this workaround. 

Have I misunderstood something?

### Versions
- Plugin version: 1.22.2
- Craft version: 3.7.26

**Comment by bencroker** [comment]
Is this what you see after clicking the link in the verification email?

**Comment by philipboomy** [comment]
Yes sorry. I should have written that.

**Comment by bencroker** [comment]
Ok, I see the issue. For now, you should set both `Subscribe Verification Success Template` and `Subscribe Success Template` to the same value, that way it will continue working as expected in version 2.0.0.
