### ISSUE TITLE
Fields don't show up in live preview editing panel

### ISSUE THREAD

**Issue by maxcoe** [putyourlightson/craft-campaign#29]
Hello!

Everything worked fine in live preview until the past 3/4 weeks. Now by editing a campaing, fields appear normally in the main editing window, but in live preview they don't show up at all, except for the default "title" field. Maybe is there a problem with the tabs "campaing" / "report" not being selected correctly for the live preview or something like that?

Regards

**Comment by putyourlightson** [comment]
Thanks for reporting this, fixed in 1.4.2 https://github.com/putyourlightson/craft-campaign/commit/f80c997ea25ed9734991d57b7e31cfbafeb5c4a8
