### ISSUE TITLE
Verify Success Page Template

### ISSUE THREAD

**Issue by seantilley** [putyourlightson/craft-campaign#290]
### Is your feature request related to a problem? Please describe.
The first time the user clicks on the verify subscription link the ( if configured ) success page template loads perfectly. The second time the user clicks the link ( or on page refresh ) it loads the default craft message template.

![Screenshot 2022-02-08 at 10 58 13](https://user-images.githubusercontent.com/5632790/152963563-2d9f63d3-6e05-4535-9a7e-d5f3bca1aadb.png)

### Describe the solution you would like
I think it would be logical to load the success page template ( if configured ) even if the user has already confirmed their subscription.

### Describe alternatives you have considered
Another option would be to provide an already subscribed template option.

**Comment by bencroker** [comment]
Thanks, added in https://github.com/putyourlightson/craft-campaign/commit/413c179be3048a104cbd99461439f1e78b7f5b6c for the next release. Note that this change will only apply to subscribe verification links sent _after_ the plugin update is installed.

**Comment by bencroker** [comment]
Released in version 1.22.4.
