### ISSUE TITLE
Allow duplicating of entries

### ISSUE THREAD

**Issue by leightonhughes** [putyourlightson/craft-campaign#292]
### Is your feature request related to a problem? Please describe.
Needing the ability to allow easy duplication of campaign entries so client doesn't have to recreate blocks for every campaign.

### Describe the solution you would like
Following the Craft UI pattern have a duplicate button in the cog dropdown when selecting the entry.

### Additional context
![image](https://user-images.githubusercontent.com/5158786/154821592-4b31a558-bc97-4c70-a22d-2338a25b1ee0.png)
![image](https://user-images.githubusercontent.com/5158786/154821597-6ba1130e-aa33-473b-a2b8-69a8a1d19e1f.png)

**Comment by bencroker** [comment]
Thanks for the feature request. You can already duplicate a campaign by saving "as a new campaign", but we'll consider adding a duplicate action too.

<img width="368" alt="Screenshot 2022-02-19 at 22 49 19" src="https://user-images.githubusercontent.com/57572400/154821767-3818b275-cafa-49fa-be29-3e97651d249a.png">

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/076b4a7cd030fcdd219d23580dd4c1544ebc5eed for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
