### ISSUE TITLE
Modify contact field before save (with Formie integration)

### ISSUE THREAD

**Issue by andreasbecker** [putyourlightson/craft-campaign#293]
I have a Formie form and use the Campaign integration. The form has an email field and a text field. Both fields are mapped to a Campaign contact. So when the form is submitted, a new contact is created in Campaign with both fields filled. What I'm trying to do is the following: if the form is being submitted again with the same email address I want to update the already existing contact in Campaign and concatenate the string in the text field.

How would I accomplish this? Probably, I need to listen to an event. But which one?

**Comment by bencroker** [comment]
The default behaviour will be to override the field value for the existing contact. If you want to _concatenate_ the value onto the existing field value, then you'd probably be best off using the `EVENT_BEFORE_SAVE` event on the `ContactElement` class. Here's an example of how you might do it.

```php
Event::on(ContactElement::class, ContactElement::EVENT_BEFORE_SAVE,
    function (ModelEvent $event) {
        $contact = $event->sender;
        $oldContact =  Campaign::$plugin->contacts->getContactByEmail($contact->email);
        if ($oldContact) {
            $contact->fieldHandle = $oldContact->fieldHandle . $contact->fieldHandle;
        }
    }
);
```

**Comment by andreasbecker** [comment]
Thank you, Ben. This pointed me in the right direction. Since this always concatenates the content to the existing content even if I save the contact in the CP, I ended up with using Formie's `EVENT_MODIFY_FIELD_MAPPING_VALUES` event to achieve what I wanted.

**Comment by bencroker** [comment]
Great!
