### ISSUE TITLE
Exporting contact throws error

### ISSUE THREAD

**Issue by Rommert** [putyourlightson/craft-campaign#297]
### Describe the bug
When exporting (mailinglist) contacts, I get the following error. User fields have radiobuttons, checkboxes, etc.

```Object of class craft\fields\data\MultiOptionsFieldData could not be converted to string```

Temp fix problem: 
File: vendor/putyourlightson/craft-campaign/src/services/ExportsService.php replace line 105

```            
if ($value instanceof MultiOptionsFieldData) {
          $resolvedValue = [];

          foreach ($value as $optionData) {
              $resolvedValue[] = $optionData->label;
          }

          $resolvedValue = implode(',', $resolvedValue);
          $row[] = $resolvedValue;
      }else{
          $row[] = $value;
      }
```

<img width="911" alt="Schermafbeelding 2022-02-24 om 22 01 09" src="https://user-images.githubusercontent.com/2290530/155607374-c6b9fa34-1e61-443e-8a3c-00b52711d6ff.png">

**Comment by bencroker** [comment]
Thanks for reporting this, will aim to get a fix out soon.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/41aff67353f41f693423883101eb6d348d965833 for the next release.
