### ISSUE TITLE
Missing alt-text pixel in tracking image conflicts in mail-tester.com

### ISSUE THREAD

**Issue by Rommert** [putyourlightson/craft-campaign#298]
### Describe the bug
Maybe not a deal breaker. The test report from mail-tester.com shows a message about a 'missing alt-text' of the tracking image. 

```alt=""``` is the most appropriate approach in this case - this tells the screenreader that the image is purely decorative and should be ignored. Since tracking pixels do not visually convey information, they are essentially decorative from this point of view. What do you think, @bencroker ?

```
      $htmlBody .= '<img src="'.$trackingImageUrl.'" width="1" height="1" alt="" />';
```

**Comment by bencroker** [comment]
Thanks, added in https://github.com/putyourlightson/craft-campaign/commit/9d45d1f792fa2357ada44c5ce696f1e6afcab51b for the next release.
