### ISSUE TITLE
Programmaticly send e-mail send e-mail to segment on save event in craft

### ISSUE THREAD

**Issue by stevenvandemoortele** [putyourlightson/craft-campaign#299]
### Question
Hi, Is it possible to use this plugin to send a mail after a new entry is added to a section in craft?
Basicly a sort of "keep me updated" form where a user signs up to a segment for updates and receives a mail with the info as soon as a new entry is posted that matches the segment.

I know I'll need a custom module / plugin to listen to save event in craft, but I'm wondering how to set up the plugin to match what I'm trying to do. Do I need to set up a recurring sendout or would it be easier to programmaticly create a regular sendout when the event is triggered?

**Comment by bencroker** [comment]
It is theoretically possible, but it sounds like a notification is more along the lines of what you're after. See https://github.com/putyourlightson/craft-campaign/issues/102 for a discussion on this.
