### ISSUE TITLE
PHP error when sending test mail from settings panel

### ISSUE THREAD

**Issue by maxcoe** [putyourlightson/craft-campaign#30]
Hello!

When I press the button "Send test mail" in the email settings panel, using the "sendmail" transport type, I get a PHP error saying "Undefined offset: 0" highlighting the line:

`->setFrom([$settings->fromNamesEmails[0][1] => $settings->fromNamesEmails[0][0]])`

Best regards and thank you for your support!

**Comment by putyourlightson** [comment]
Hi there. Sounds like you need to save the from name and email before sending a test email. I'll add better error handling in the next release.

**Comment by maxcoe** [comment]
Unfortunately it shows this error even when the email datas are saved... But I have solved the problem by changing the mentionned line to:

`->setFrom(reset($settings->fromNamesEmails)[1])`

The "reset" fonction takes the very first element of the array "fromNamesEmails", that means the very first element of the emails list in the settings panel. And "[1]" is the email address itself. Now it works fine!

**Comment by putyourlightson** [comment]
Thanks, will add this to the next relelase.
