### ISSUE TITLE
Support for Drafts/Craft revision features

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#301]
### Is your feature request related to a problem? Please describe.

We just had an instance of a lot of work being lost because one user saved over the work of another in Campaign.

### Describe the solution you would like

Support for the Craft standard Drafts/Revisions system - so that in such an instance, we could retrieve the previous version of the Campaign

Thanks for considering!

**Comment by bencroker** [comment]
This is already on the roadmap for version 2, which Craft 4 will make possible.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/db15fa34590196e7bfa4aff4d6055bf4ddc47e02 for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
