### ISSUE TITLE
Subscription status in the contact index page

### ISSUE THREAD

**Issue by keyurkadam** [putyourlightson/craft-campaign#302]
can you anyone tell me why I unsubscribed from the the list titled "test" but is still displays as subscribed here 
https://prnt.sc/kZI_lOYJIUjC

I have unsubscribed 

you can see them unsubscribed here: 
https://prnt.sc/3z7edwymsHGJ

The unsubscribe is working and sendout won't send to those it is just that the list from contacts is the one they are exporting from and is says subscribed when it should be unsubscribed.

**Comment by bencroker** [comment]
It is possible for a contact to unsubscribe from a single mailing list, but remain subscribed to multiple other mailing lists. That is why the contact might be marked as "Subscribed" on the contacts page, and why it is recommended to export from a mailing list rather than from the contact index page. Does that answer your question?

**Comment by keyurkadam** [comment]
How can we export from a mailing list? i can't find any option in mailing list page which can help me to export the contacts.

**Comment by bencroker** [comment]
Contacts → Export

**Comment by keyurkadam** [comment]
I have already tried that option. But it only gives us general informatrion about the mailing list as a whole and won't allow us to filter out any one who unsubscribed. and also is there a way to export from the mailing list as they say is best and still get whether user is subscribed or unsubscribed ?

**Comment by bencroker** [comment]
Exporting a mailing will give you a list of only "subscribed" contacts. Are you trying to get unsubscribed contacts too?

**Comment by keyurkadam** [comment]
Are you trying to get unsubscribed contacts too? --> yes exactly

**Comment by keyurkadam** [comment]
@bencroker any update regarding this?

**Comment by bencroker** [comment]
Not yet, but we will try to get to this at some stage. Since adding unsubscribed contacts to the export _could_ be considered a breaking change, we may add this in version 2.0.0, which is currently under development and which will require Craft 4.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/ef6dcbba889ced75aa69c7ed8286856aeca3afae for the 2.0.0 release.

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
