### ISSUE TITLE
Additional logic for recurring emails

### ISSUE THREAD

**Issue by venturini-dev** [putyourlightson/craft-campaign#305]
Some customers want to send out recurring emails ONLY if new entries have been added since the last check.
It would be great to have this option in the recurring sendout settings.

**Comment by bencroker** [comment]
You could in theory use a Template Segment to specify that contacts should only receive a sendout if the last article's publish date was within the last X number of days. Have you considered that approach?

**Comment by venturini-dev** [comment]
Thanks Ben, that accomplishes the goal I had in mind!
I guess I did not think of implementing logic associated with whether to send a sendout or not with segments, which I thought about as responsible for logic to be run on recipients.
I also see that logic in template segments is run for every contact.
Do you think it is still worthwhile to implement a feature where one could run additional logic _before_ looping through the mailing list?

**Comment by bencroker** [comment]
How would you suggest this be implemented? It would kind of be like a Segment that is applied to sendouts instead of contacts, in which case why not just use what already exists?

**Comment by venturini-dev** [comment]
Yeah, you could have the same concept of the "template condition" field but applied to the sendout. It would just be a way to access and evaluate the global state of craft before iterating through the mailing lists.

As a user, when I create a new sendout I kind of expect all logic for the sendout to be on that page - like time, dates, send multiple times, and then there could be like an additional field for a custom condition.

I can definitely accomplish the same with having the logic in the segment, so it's definitely not a missing feature.

I also want to point out that I may be saying this from a mental model that may not be aligned with the plugin - yet. When I think "segment" I think of logic on recipients, not on other entries, whereas logic for other entries could relate to other concepts like time and date, or other automations that are setup for the automated sendout.

**Comment by bencroker** [comment]
That's a good point, thanks for clarifying! I would like to be able to leverage the new condition builder in Craft 4 but it doesn't really provide the flexibility one might need for a case like this, so I'll consider your suggestion for Campaign 2.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/48728f12b6e0dd752d565f1fbf89a121e0641b9e for the 2.0.0 release.

**Comment by bencroker** [comment]
I ended up adding a condition builder field to the sendout schedule for automated and recurring sendout types, so you can create your own custom condition rules.

<img width="834" alt="Screenshot 2022-04-26 at 19 55 00" src="https://user-images.githubusercontent.com/57572400/165372313-9475351a-ff36-4087-89f5-082566cc9d99.png">

**Comment by venturini-dev** [comment]
Hi Ben,

Thank you, this looks exactly like what I needed in that circumstance.
Looking forward to trying this out.

BTW, I wouldn't have condoned exterminating the squirrels either, they need
a home too..

Ciao!



Ludovico Venturini
*Information designer | Web developer*

*Website   > * venturini.dev
*Mobile     > * +39 351 964 0516


Il giorno mar 26 apr 2022 alle ore 20:57 Ben Croker <
***@***.***> ha scritto:

**Comment by bencroker** [comment]
This has been released in version 2.0.0. 
You can see some examples in https://github.com/putyourlightson/craft-campaign/tree/v2/examples/conditions/sendouts
