### ISSUE TITLE
Question/Feature Request: Customize 'Verify Email' subject

### ISSUE THREAD

**Issue by missmatsuko** [putyourlightson/craft-campaign#31]
I'm working on a bilingual site. 

I've successfully translated the 'Verify Email' content, but the subject is always 'Verify your email address' (English).

I couldn't find anywhere this was set, and I think it seems to be hard-coded here:
https://github.com/putyourlightson/craft-campaign/blob/v1/src/services/ContactsService.php

Is there a way to customize the email subject, or would that be a new feature?
Ideally for my site, I'd like a different subject for each locale, but having both English and French in the subject line would be OK, too.

**Comment by putyourlightson** [comment]
Yes, this is an enhancement. I might take the same approach as system messages in Craft. It would mean moving the email message from a template into the control panel but it would be consistent with the UI. Do you think that would work well?

![screenshot 2018-11-09 at 09 38 38](https://user-images.githubusercontent.com/2318222/48251902-76904000-e403-11e8-93a7-cf3cce3bd544.png)

**Comment by phoob** [comment]
hmm.. I really like being able to customize the subject field, but it's also really nice to be able to have a template.. Couldn't we just have a subject field and a template..?

**Comment by putyourlightson** [comment]
Well the tricky part is having a subject field per site/locale...

**Comment by putyourlightson** [comment]
Oh no, it doesn't!! That's how I'll do it then 😄

**Comment by putyourlightson** [comment]
Coming in 1.5.0...

![screenshot 2018-11-09 at 10 14 40](https://user-images.githubusercontent.com/2318222/48253982-f53bac00-e408-11e8-884e-7e6eb2d815c2.png)

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/80351d02a6cff878950a88bf260b77b6e5e3df40 and released.

**Comment by missmatsuko** [comment]
@putyourlightson Thank you! Very speedy, too! :)
