### ISSUE TITLE
[v2] creating contact on a non primary site throws invalid draft id

### ISSUE THREAD

**Issue by vnali** [putyourlightson/craft-campaign#310]
**Describe the bug**
on a Craft site with two enabled sites, creating a contact on non primary site throws a invalid draft id.

**Comment by bencroker** [comment]
Thanks for reporting, I'm aware of this and awaiting the next Craft beta which resolves a similar issue before releasing a fix.
https://github.com/craftcms/cms/issues/10938

**Comment by bencroker** [comment]
Thanks for reporting, fixed in https://github.com/putyourlightson/craft-campaign/commit/2d7f66ed98994e0000837fc112d74fc8097956b6.
