### ISSUE TITLE
Log viewer in CP like FeedMe

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#311]
It would be really useful to have the log output viewable from the CP by a user like the FeedMe plugin.

The specific use case I have is that sometimes our sendouts fail as there seem to be legacy unsubscribes in our email provider that cause sendouts to fail at times. The only way to fix this is for me to look in log, find email it's failed on and then unsubscribe them from inside Campaign.

If the user could view the log, they could do this without my intervention.

Thanks Ben!!

**Comment by bencroker** [comment]
Thanks for the suggestion, I think we can address this by outputting the details of the failure in the CP in Campaign v2.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/e2f45b08fa3c61ef3b932a1d79483575f43b8ffc for the 2.0.0 release.

<img width="346" alt="Screenshot 2022-04-22 at 14 14 28" src="https://user-images.githubusercontent.com/57572400/164721584-b5c61616-abca-46e2-a5a9-5d55285d6f1f.png">

**Comment by bencroker** [comment]
This has been released in version 2.0.0.
