### ISSUE TITLE
Unsubcribe form issue

### ISSUE THREAD

**Issue by keyurkadam** [putyourlightson/craft-campaign#312]
Apparently my unsubscribe form is not working right now. Take a look at my form code.  https://prnt.sc/J0ldDxhqBI-6 

It shows a message of successfully unsubscribing, but when I check in the admin panel, it still shows as subscribed. 

- craft version ( 3.7.41 )
- campaign version ( 1.23.1 )

**Comment by bencroker** [comment]
Have you enabled the `Unsubscribe Form Allowed` setting for the mailing list in question?

<img width="603" alt="Screenshot 2022-05-12 at 07 21 50" src="https://user-images.githubusercontent.com/57572400/167997690-8c7a8152-1caa-491a-92b4-300a083c8827.png">

Also keep in mind that unsubscribing through a form submission only completes once the email verification link is clicked.

**Comment by keyurkadam** [comment]
https://prnt.sc/pL2i5moVOzmf yes already enabled.

**Comment by bencroker** [comment]
And was the unsubscribe email verification link clicked?

**Comment by keyurkadam** [comment]
Okay, I forgot about that link. It's now working... Thanks :)
