### ISSUE TITLE
How to parse tags from WYSIWYG fields

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#315]
What is the standard? recommended way? of parsing dynamic fields from Craft Fields?

We let our users build their emails from a matrix content builder and we have just been asked to be able to let them use contact data in a **Redactor field** for example.

`Hello {{ contact.firstName }}`

I'd like the above to replace the tag with "John" or whatever.

Is there a recommended way to do this?

Thanks!

**Comment by bencroker** [comment]
I usually put this in the email template, for example:

```twig
<p>Hello {{ contact.firstName }},</p>

{{ campaign.text }}
```

**Comment by johnwbaxter** [comment]
Ah ok, I'm with you.

Not sure I can do that in this case, I'll look to see if I can parse the tags out with something.

Thanks!

**Comment by bencroker** [comment]
You can easily set up your own convention, for example:

```
Hello {firstName}
```

Implemented as:

```twig
{{ campaign.text|replace({'{firstName}': contact.firstName}) }}
```

**Comment by johnwbaxter** [comment]
Yep that's cool, that's exactly what I was doing. Just wasn't sure if there was something cleverer! :)

Thank you Ben.
