### ISSUE TITLE
`Subscribe Success Template` set but no email is sent when there's a successful subscription

### ISSUE THREAD

**Issue by andrewhawkes** [putyourlightson/craft-campaign#317]
I have set a template path for the `Subscribe Success Template` setting on a mailing list type.

When I subscribe to a list, an email isn't sent - is there another setting to get the email to actually send?
I can't see anything being queued and Postmark doesn't get any data. 

I'm not using the `Subscribe Verification Required` option if that helps but I presume these are separate?

**Comment by bencroker** [comment]
What version of the plugin are you running? The success template should display regardless of whether verification is required or not.

**Comment by andrewhawkes** [comment]
2.0.6 
"putyourlightson/craft-campaign": "2.0.6",        
"craftcms/cms": "4.0.5.1", 
"craftcms/postmark": "3.0.0",

**Comment by bencroker** [comment]
Have you verified that your email settings are working in the plugin's email settings by running a test send?

**Comment by andrewhawkes** [comment]
@bencroker yep all good - have sent a test campaign

**Comment by bencroker** [comment]
Oh I think you misunderstood the setting, the `Subscribe Success Template` is the template that is used to display the subscribe success page, it is _not_ sent via email.

**Comment by andrewhawkes** [comment]
@bencroker ahh that would make sense - I am blaming the heat!

**Comment by andrewhawkes** [comment]
@bencroker is it possible to send an email confirmation once someone subscribes to a list? (not verification)

**Comment by bencroker** [comment]
Sure, you can listen for the `EVENT_AFTER_SUBSCRIBE_CONTACT` in a module/plugin and then send an email. Here's some sample code to get you started.

```php
use putyourlightson\campaign\events\SubscribeContactEvent;
use putyourlightson\campaign\services\FormsService;
use yii\base\Event;

Event::on(FormsService::class, FormsService::EVENT_AFTER_SUBSCRIBE_CONTACT,
    function (SubscribeContactEvent $event) {
        $email = $event->contact->email;
        $mailingList = $event->mailingList;
        // Send the email.
    }
);
```
