### ISSUE TITLE
Outputting a number of subscribers

### ISSUE THREAD

**Issue by efedorenko** [putyourlightson/craft-campaign#318]
Hi Ben,

Is there a way to output a total number of "real" subscribers? `craft.campaign.contacts.status('active')|length` seems to exclude bounced and complained subscribers but still includes unsubscribed.

Thank you!

**Comment by bencroker** [comment]
To output subscribers, you can get the `subscribedCount` on the mailing list (that they are subscribed to).

```twig
{# @var mailingList \putyourlightson\campaign\elements\MailingListElement #}
{% for mailingList in craft.campaign.mailingLists.all() %}
    {{ mailingList.title }} : {{ mailingList.subscribedCount }}
{% endfor %}
```

Remember that subscribers are mailing list specific, so the sum of the `subscribedCount`'s may add up to more than the number of contacts.

**Comment by efedorenko** [comment]
Thanks Ben!
