### ISSUE TITLE
Campaign uses default email transport instead of the one in Campaign settings

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#319]
When Campaign sends out emails, either email confirm or test email, it uses my emails settings set in the CMS and not in Campaign email settings. So it uses my PostMark SMTP settings instead of Amazon SES.

Amazon SES 2.0.1 
Campaign 2.1.3
Craft CMS 4.2.0.2

**Comment by bencroker** [comment]
I'm unable to replicate this, can you double check please and provide some steps for me to replicate the issue?

**Comment by philipboomy** [comment]
Hmm I have re-tested both in production and locally just in case. I have resaved Campaign Email settings and still not working.

Here you can see that I am using Amazon SES https://share.getcloudapp.com/jkuXbgx9

It worked fine before upgrading to Craft V4.

I am not sure how I can help reproduce this. I have tested it in 2 ways after I saw a new "Confirm Subscription" email from a real signup in my PostMark logs.

First I tested it with a test email on a campaign and then after that I tested it with a signup to see the confirm subscription email. Both were send with the CMS email settings e.g. SMTP.

**Comment by bencroker** [comment]
Can you check the value of the `sendVerificationEmailsViaCraft` in your `config/project/project.yaml` file?
https://github.com/putyourlightson/craft-campaign/blob/b3857f987d404077a8c33d16921cd5b092b6eee4/src/config.php#L47-L48

**Comment by philipboomy** [comment]
Hi

It is set to false.
`sendVerificationEmailsViaCraft: false`

**Comment by bencroker** [comment]
I'm out of ideas and can't replicate so I think you're going to have to troubleshoot this one yourself, unless you can send me CP access and I'll take a look.

**Comment by bencroker** [comment]
This indeed turned out to be a bug. Thanks for helping me get to the bottom of it, fixed in https://github.com/putyourlightson/craft-campaign/commit/f1eeeae8cb7b2924688493e72fd25a8c7dcf1645 and released in 2.1.4.
