### ISSUE TITLE
Different auto slugs for Mailing Lists and Mailing List Types

### ISSUE THREAD

**Issue by missmatsuko** [putyourlightson/craft-campaign#32]
The auto-generated slugs for Mailing List Types is camelCase and for Mailing Lists is kebab-case. Is there a reason for this? Just tripped me up in templating because I expected the slugs to be formatted the same.

**Comment by putyourlightson** [comment]
This follows the Craft standard of using camel case for handles (for sections, category groups, etc.) and kebab case for slugs (for entries, categories, etc.). Mailing list types similarly have handles, whereas mailing lists have slugs.
