### ISSUE TITLE
Can’t save Subject with Emoji in Sendout

### ISSUE THREAD

**Issue by cquinders** [putyourlightson/craft-campaign#320]
The Subject field will be blank after saving a Sendout with an Emoji in it the Subject.

Craft Campaign 2.1.2
Craft CMS Pro 4.2.0.2

**Comment by bencroker** [comment]
My guess is that you're running into the issue reported in https://github.com/craftcms/cms/issues/8072

It should work just fine with an emoji supported by the [LitEmoji](https://github.com/elvanto/litemoji) library, such as 😀.
