### ISSUE TITLE
Sendouts page get error when creating new sendouts

### ISSUE THREAD

**Issue by watarutmnh** [putyourlightson/craft-campaign#322]
We gets error on sendouts page: Call to undefined function putyourlightson\campaign\set_time_limit()

This occurred after clicking "Save and Preview" when creating new sendouts.
Then all sendouts pages have same error.

Here is the Sentry link: https://sentry.io/share/issue/0d85a3e0ea004e159bec3413c73aef26/

**Comment by watarutmnh** [comment]
The server's set_time_limit function had been disabled and it caused the issue.
No issue after enable the function.

**Comment by bencroker** [comment]
Ok great, I added a check for the `set_time_limit()` function in https://github.com/putyourlightson/craft-campaign/commit/b6c64b36e0e60398b024899424709184e2c339c2 and released in version 2.1.5.
