### ISSUE TITLE
Error when viewing the campaign

### ISSUE THREAD

**Issue by billymedia** [putyourlightson/craft-campaign#323]
When i am editing a campaign, and i click "View" to preview it, i get the following error:

```Getting unknown property: putyourlightson\campaign\elements\CampaignElement::section```

Even when i empty my template just to see if it will return a blank page, i still get the error.

Clicking on preview returns a blank page. With or without the template code in place.

Craft CMS 3.7.46
Plugin 1.23.4

**Comment by bencroker** [comment]
Are you perhaps calling `campaign.section` or something similar in your campaign's template? If that's the case, then campaigns don't have sections, which is likely to be the cause of the error.

**Comment by billymedia** [comment]
I am not using any code other than html, it also throws the error when i emptied my template, so no code at all.

**Comment by bencroker** [comment]
Hmm, can you show me the full error stack trace?

**Comment by billymedia** [comment]
yii\base\UnknownPropertyException: Getting unknown property: putyourlightson\campaign\elements\CampaignElement::section in /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/src/base/Element.php(1767): yii\base\Component->__get('section')
#1 /Users/bp/Sites/fb-hub-v3-dev/plugins/brands/src/Brands.php(293): craft\base\Element->__get('section')
#2 /Users/bp/Sites/fb-hub-v3-dev/plugins/brands/src/Brands.php(159): futurebrand\brands\Brands->_initLoadBrand()
#3 [internal function]: futurebrand\brands\Brands->futurebrand\brands\{closure}(Object(yii\base\Event))
#4 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/base/Component.php(633): call_user_func(Object(Closure), Object(yii\base\Event))
#5 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/src/base/ApplicationTrait.php(1493): yii\base\Component->trigger('init')
#6 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/src/web/Application.php(99): craft\web\Application->_postInit()
#7 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#8 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#9 [internal function]: yii\base\Application->__construct(Array)
#10 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#11 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#12 /Users/bp/Sites/fb-hub-v3-dev/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#13 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/src/Craft.php(61): yii\BaseYii::createObject(Array, Array)
#14 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/bootstrap/bootstrap.php(247): Craft::createObject(Array)
#15 /Users/bp/Sites/fb-hub-v3-dev/vendor/craftcms/cms/bootstrap/web.php(51): require('/Users/billypat...')
#16 /Users/bp/Sites/fb-hub-v3-dev/web/index.php(21): require('/Users/billypat...')
#17 /Users/bp/.composer/vendor/laravel/valet/server.php(234): require('/Users/billypat...')
#18 {main}

**Comment by billymedia** [comment]
Not sure if this is of use, but here are the campaign type settings:

![Screenshot 2022-08-30 at 10 08 26](https://user-images.githubusercontent.com/293540/187397567-90ec8a71-a4b6-4b98-be7b-a491a4c13ed4.png)

**Comment by billymedia** [comment]
I just noticed that the stack trace mentioned a custom plugin, so it might be a naming conflict of some sort. I'll dig a little bit more this end.

**Comment by bencroker** [comment]
Right, it looks like you have a "Brands" plugin that is calling the `section` on the campaign element, which doesn't exist.

> #1 /Users/bp/Sites/fb-hub-v3-dev/plugins/brands/src/Brands.php(293): craft\base\Element->__get('section')
