### ISSUE TITLE
Contact info in content fields? 

### ISSUE THREAD

**Issue by blacksaltstudio** [putyourlightson/craft-campaign#325]
Is it possible to use contact info (i.e firstName and lastName, which are contact fields) in the campaigns content fields. 

I.e in my body text field, I want to use copy such as:

Hi {{contact.firstName}} {{contact.lastName}}, 

I can obviously do it in the email template but i want to use it in the content fields within the CMS. 

Thanks

**Comment by bencroker** [comment]
In theory it is possible using the [template_from_string](https://twig.symfony.com/doc/3.x/functions/template_from_string.html) function, but highly discouraged, as it requires the rendering of user input which is a security no-no. There's an article that explains a safer way to do it, by providing a sandbox mode of rendering, at https://www.raeder.technology/post/allow-craft-cms-editors-to-insert-twig-in-cms-entries

A much better way to get your desired result, in my opinion, is to perform a search-and-replace on the field contents, providing `{firstName}` and `{lastName}` variables, for example.

```twig
{{ campaign.body|replace({ 
    '{firstName}': contact.firstName ?? '', 
    '{lastName}': contact.lastName ?? '',
}) }}
```
