### ISSUE TITLE
Error when previewing sendouts without campaigns

### ISSUE THREAD

**Issue by kringkaste** [putyourlightson/craft-campaign#329]
If you delete a campaign, the sendouts still exists without the related campaign. If you click on the sendout, a 500 will occur because of the missing campaign. Maybe you want to catch this.

**Comment by bencroker** [comment]
Thanks for reporting this, I'll look into it!!

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/289bdc4a98419050e583feb4e84db9b0e97d40f0 and released in version 2.1.7.
