### ISSUE TITLE
Feature request: drop regular sendouts

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#33]
After using the plugin for a while, and it’s working great, our workflow is basically working pretty well. 

When creating a sendout it's really convenient to get campaign name and subject pre-filled when you use the “save campaign and create sendout” option. 

But: we often have to create one internal sendout and one external sendout. The external sendout is usually scheduled. 

When creating a scheduled sendout, you can’t get the campaign info pre-filled.. So here is the question: why don’t drop regular sendouts and only use scheduled sendouts? For what is a regular sendout really if not a sendout that is scheduled for “now”..? 

If that’s not possible, maybe an option for what type of sendout to create when using the “save campaign and create sendout” option..?

Regards, P

**Comment by putyourlightson** [comment]
Yeah you're right, I might just drop the scheduled sendouts and add the ability to schedule regular sendouts for the future. Will add this in the next release, thanks!

**Comment by putyourlightson** [comment]
I've been thinking this over and I feel that there may be some benefit to being able to distinguish between regular and scheduled sendouts after all. So I wonder about the alternative of adding a second option to the save dropdown, so it would be:

- Save campaign and create regular sendout
- Save campaign and create scheduled sendout

Any thoughts?

**Comment by phoob** [comment]
That would be totally fine for us :)

**Comment by putyourlightson** [comment]
Ok I'll add to the next release.

**Comment by putyourlightson** [comment]
Added in 1.5.3.
