### ISSUE TITLE
Using `pendingContact` in "Subscribe Verification Email Template" results in only plain text email being sent

### ISSUE THREAD

**Issue by andrewhawkes** [putyourlightson/craft-campaign#330]
I'm trying to personalise subscription verification emails by including a contact field using `pendingContact`.
However, this always seems to break and results in just the plain text email being sent.

So if I include this in my verification email template:
``` 
{% if pendingContact is defined and pendingContact.fullName %}
    <p style="font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; margin-bottom: 15px;">Hi {{ pendingContact.fullName }},</p>
{% endif %}
```

The template gets ignored and the plain text template gets sent instead.

According to the docs `pendingContact` should be accessible but there isn't anything about custom fields.
But as the data is in the backend I presume it should be?
https://putyourlightson.com/plugins/campaign#subscribe-verification-email-template

**Comment by bencroker** [comment]
Since you're trying to access a custom field, you'll need to access it on the `fieldData` property (just added this to the docs).

```twig
{% if pendingContact is defined and pendingContact.fieldData.fullName %}
```

**Comment by bencroker** [comment]
Oh I think that since you're trying to access a custom field, you'll need to access it on the `fieldData` property.

```twig
{% if pendingContact is defined and pendingContact.fieldData.fullName %}
```

**Comment by andrewhawkes** [comment]
@bencroker thanks I will try that out and get back to you asap.

**Comment by andrewhawkes** [comment]
@bencroker that works thank you!
