### ISSUE TITLE
Sendout fails if a contact is in Postmark's suppressions

### ISSUE THREAD

**Issue by andrewhawkes** [putyourlightson/craft-campaign#331]
I recently spent a fair bit of time working out why a standout had stalled at about 10%.

It turns out it was failing because an email we were trying to send to had unsubscribed via the link Postmark injected into the emails.

_Postmark is supposed to update Campaign via a webhook but we've been having some problems where Campaign returns a 404 to Postmark and the contact isn't updated in Campaign (which we're looking into, might be an issue with our setup)._

Is there any way Campaign can handle this a bit more gracefully rather than not being able to send further emails?
I.e. could Campaign skip the email recipient and then process through the rest of the list?

Also, is there any way to import these impressions so we can clear out any existing contacts that have unsubscribed?

**Comment by bencroker** [comment]
Please see https://github.com/putyourlightson/craft-campaign/issues/286 (and also https://github.com/putyourlightson/craft-campaign/issues/304), which sounds like it should explain what you are experiencing. A fix was applied in version 1.22.3.

The `maxSendFailsAllowed` config setting defines the failed send attempts that are allowed before failing the entire sendout, which defaults to `1`. See the discussion in https://github.com/putyourlightson/craft-campaign/issues/138 on why this was added.
