### ISSUE TITLE
Questions about Notices

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-campaign#335]
Hi Ben,

I'm trying to set up notifications after subscribing / unsubscribing but I'm noticing a couple of things.

When doing this, the `setNotice` is ignored and there's a generic 'Subscription successfully updated.' notice:
```
<input type="hidden" name="action" value="campaign/contacts/unsubscribe-mailing-list" />
{% do craft.app.session.setNotice('This notice won't be seen') %}
```

This works, however, the notice is persisted across the next request. So I get notified twice.
```
<input type="hidden" name="action" value="campaign/forms/subscribe" />
{% do craft.app.session.setNotice('This notice will be seen.') %}
```

I'm doing this in my notification template: `{% set message = craft.app.session.getFlash('notice', null, false) %}`

Probably something I'm doing wrong, but would love to know!

**Comment by bencroker** [comment]
This has to do with how flash messages work in Craft, so is not Campaign specific. If you want to use the notice in the same page request then ou should be able to do this with a regular Twig template variable. Flash notices are intended to be used on subsequent page responses. 
See https://docs.craftcms.com/api/v4/craft-behaviors-sessionbehavior.html#method-setnotice

**Comment by shifuma** [comment]
Thanks, I'll look into that some more.
