### ISSUE TITLE
Can new craft users automatically be imported into lists?

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-campaign#34]
I have a craft user group called **abc**, and a corresponding mailing list called **abc**. I can import users from **abc** into the mailing list without issue, however if I create a new craft user and assign them to **abc**, i have to manually trigger the import into the mailing list **abc** again. Can this be automated?

**Comment by ghost** [comment]
Sorry about this one. I just saw this: https://craftcampaign.com/docs/integrations I assume I can make something work based o that.

**Comment by phoob** [comment]
How about https://github.com/putyourlightson/craft-campaign-pro ? It has automatic user group syncing ;)

**Comment by putyourlightson** [comment]
Yup, user group sync should do what you need, it’s a pro feature:
https://craftcampaign.com/docs/pro-features

**Comment by ghost** [comment]
.. Sorry again, think I found what I needed :)

**Comment by putyourlightson** [comment]
Ok great.

**Comment by ghost** [comment]
Hmm. Is there a bug here?

I tried registering a user through the frontend (register form found in craft docs). New users default to group **abc**, however despite having that setup under Sync, the user did not get synced.

Once I went into the user profile of that user in the craft cp however, and saved again, it synced. Am I missing something?

**Comment by putyourlightson** [comment]
Can you double check that the newly created user was activated? Please create a new bug report issue with the steps to reproduce if the problem persists.
