### ISSUE TITLE
Accessing reports of +3000 can take too long to load

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-campaign#340]
Hi, forgive me if this has been asked already I couldn't see an issue. 

I wish to access a url like this: admin/campaign/reports/campaigns/6223/recipients

One recipient list has 4022 contacts, this takes roughly 2.4min to complete loading the resulting page.
Another recipient list has 7700, this hits a really high timeout of 5min resulting in a 504 error
A CMS admin on the related application wishes to export CSVs of these lists and doesn't necessarily need to see the resulting page.

This app has 900M of php memory reservation in it's related AWS ECS task with lmatching memory limit settings at php and craft levels.

It does seem like these requests are taking longer than they should, can any optimisation be done to load the example URL faster either at my server, application level or can any improvements be made at the plugin level?

Thanks in advance

**Comment by bencroker** [comment]
Those load times are surprising to see. I'll look into this and see whether there are some optimisations that can be made.

**Comment by bencroker** [comment]
FYI we're working on optimising the queries causing the long load times, will have a fix ready in the coming days.

**Comment by bencroker** [comment]
I've added query optimisations in https://github.com/putyourlightson/craft-campaign/commit/f80079a991baba020ceacfe571bd35966f2aa979 that should make a significant improvement. If you'd like to help test then you can change your `putyourlightson/craft-campaign` requirement in `composer.json` to `"dev-develop as 2.2.1"` and run `composer update`.

**Comment by joepagan** [comment]
Hey @bencroker thanks for your work on this! I've got some availability to give this a go next week.

**Comment by bencroker** [comment]
Released in version 2.2.1.

**Comment by joepagan** [comment]
I _may_ have got distracted and forgot to provide an update, can confirm that requests are down from 10 minutes, to round about 3-5 seconds now!

**Comment by bencroker** [comment]
Well that's a decent improvement!
