### ISSUE TITLE
Mailgun Webhook throws error

### ISSUE THREAD

**Issue by tonioseiler** [putyourlightson/craft-campaign#341]
Hi,

We have errors on the Mailgun Webhooks on 2 Installations:
<img width="1268" alt="grafik" src="https://user-images.githubusercontent.com/4467443/199790464-43af6d07-7b74-42a6-a84f-66e106c10dd4.png">

Hope you can resolve soon.

**Comment by bencroker** [comment]
Thanks for reporting this. Are you on the latest version 2.2.0 of the plugin?

**Comment by tonioseiler** [comment]
Yes I just updated….

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by bencroker** [comment]
Perhaps Mailgun's API has changed, I'll look into it later today.

**Comment by bencroker** [comment]
From what I can tell, the `timestamp` is a required part of the Mailgun webhook request and is used for authenticating the request. Could it be that the request that is failing is not an original request from Mailgun, but a spam request?

**Comment by tonioseiler** [comment]
No, this happens when I press on the „Test Webhook“ Button in the Mailgun Backend.
From what I can say, the permanent fail web hooks from the last sendoff did not work neither.

Regards.

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by tonioseiler** [comment]
It seems like this is a bug. I just created a mailing list with 2 invalid email adresses.
I can see the permant failed events in the mailgun logs but I cannot see the bounces or anthing in the craft backend.

**Comment by bencroker** [comment]
Ok, I'll look into it, thanks.

**Comment by tonioseiler** [comment]
Tank you!
–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/8e1fa559362efcabbc60b0ca449e9ad4d219ceda for the next release, expected early next week.

**Comment by bencroker** [comment]
Released in version 2.2.1.

**Comment by tonioseiler** [comment]
Great! Will deploy tomorrow!

–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by tonioseiler** [comment]
Would it be possible to have that fix also for the craft 3 version ?


–––––––––––––––––––
Tonio Seiler
Dipl. Ing. FH Informatik
***@***.***

Furbo GmbH
Rüdigerstrasse 10
8045 Zürich

+41 44 501 85 65
www.furbo.ch

Abwesenheit: Mittwochs

**Comment by bencroker** [comment]
Yes, also fixed in version 1.23.6.
