### ISSUE TITLE
Manual contacts workflow

### ISSUE THREAD

**Issue by wmdhosting** [putyourlightson/craft-campaign#343]
Just idea how to improve manuall creating of contacts

1. Add button that will trigger Ctrl+S   + Tab select..
![Snag_a0f77c3](https://user-images.githubusercontent.com/76176291/203060796-daabc9c3-6c11-422a-b0e4-836de5129cac.png)

2. When contact exits  to List direct link to contact..
![Snag_a0ffe0a](https://user-images.githubusercontent.com/76176291/203060926-7836424b-979c-4da5-b30e-482d4aa278dd.png)

**Comment by bencroker** [comment]
Thanks for the suggestions.

1. If we were to add this, it would be an item in the save button group, so under where it currently says "Save contact". I wonder though how discoverable this really would be.
2. This should be possible to implement, I'll have to look into whether hyperlinks can be added to error messages.

**Comment by wmdhosting** [comment]
1.  if need to be on Save Button Group. 
making that as >> first option.. would suit better from my perspective >> than  Create contact and Finish..
The after first click. change button to >> Save... and finish..

It work allready like that..  .. just need to change that first button..
 

2.  OK thx..

**Comment by bencroker** [comment]
1. I'm not willing to deviate from the Craft convention, so if it would be added then as a second option, "Create and edit mailing lists", for example.

**Comment by wmdhosting** [comment]
OK i understand that..  at least here is not deviation :)

As when you save contact..    or multiple contacts. there is no way to Bulk edit..  . 
or do aynthing else for contacts .  so no point for save and finish.. 
you need to click that  same entry again to relate to mailing list.. 

Like this..  You Create Contact +  and show mailing list option.. 
then click Save button.. and is again on  List screen...

You do similar thing alleready on sendouts..
---------------------------------
With entries  and other elements its different..  you dont need  to anythign else just save them.. 

And Craft have option when writing entry you can relate categories.. assets.. tags.. 
From that  same page..   
no need to go to 
1. tag page.. 
2.  create tag.. 
3. Then go go again to entry and add tag..

**Comment by bencroker** [comment]
It is a deviation, which is why I need to give it more thought. 

Added your second suggestion in https://github.com/putyourlightson/craft-campaign/commit/3a921dd75e4c9a22329dd73968553bb299e5d686.

<img width="524" alt="Screenshot 2022-11-21 at 10 03 06" src="https://user-images.githubusercontent.com/57572400/203089299-e4683d12-b697-40fc-81e7-0ad25724d941.png">

**Comment by wmdhosting** [comment]
OK thx :) 

got another   idea..  :)  and its not deviation :)

As when we enter mail. draft is generated..   
Can you show   Tabs..  after draft is created...

That would resolve workflow..
![Snag_aa85629](https://user-images.githubusercontent.com/76176291/203097006-ebde960f-6c31-47a5-8588-d43187bc4605.png)

**Comment by bencroker** [comment]
After looking into it some more, it turns out we can display all tabs at all times, since a draft ID is automatically assigned immediately. If you can help test then that would be great. To test, change your `composer.json` requirement to `dev-develop as 2.2.2` and run `composer update`.

<img width="991" alt="Screenshot 2022-11-21 at 20 38 49" src="https://user-images.githubusercontent.com/57572400/203195910-dee66992-99cf-431f-94df-9e3d4f755e22.png">

**Comment by wmdhosting** [comment]
Tested  :)

Tabs are here..   just when i click on subscribe. it says contact not found.. 

![Snag_dddba0a](https://user-images.githubusercontent.com/76176291/203242861-09e1b4a2-c38e-47da-b0e9-c4e974cee4cd.png)

![Snag_dddd0bf](https://user-images.githubusercontent.com/76176291/203242876-61fbd0c8-cbc6-46d9-a37c-1f608d7633d4.png)

**Comment by bencroker** [comment]
Fixed a missing assignment in https://github.com/putyourlightson/craft-campaign/commit/cebaa12cb09c1b1171adfe17499c098d5a406825, can you update and try again? Be sure to test with both existing contacts and draft contacts.

**Comment by wmdhosting** [comment]
all OK now :)  thx

**Comment by bencroker** [comment]
Released in version 2.2.2. Thanks for the great suggestions!
