### ISSUE TITLE
Bug in reports - complaints showing the same for multiple sendouts

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#344]
Hey Ben - me again (sorry!)

Found what appears to be a bug.

Looking at recent campaign reports, I noticed the number of complainers was the same for a few recent campaigns.

Looking at it, it's the same 3 people each time - and the notification of the complaint is the same time/date, even for different campaigns.

Am I just misunderstanding those reports? Looking at it, it seems they are included in the complains report for every send-out up until they complain?  Which makes it hard to work out if a particular mailer was 'less popular' and the cause of more complaints.  Is that intentional?  Surely the complaint should be attached to the specific mailer they reported, or whatever??

(We are super conservative with send-outs and get very very few complaints, but on the twice-or-year or so occasions we send out a very 'producty' send-out, I like to re-assure myself we're not irritating our client base....)

I am guessing this is not a bug, rather a gap in my understanding...but if you could set me straight, I'd appreciate it.

**Comment by bencroker** [comment]
This is a good question. When a recipient complains, they do so via their email service provider (ESP). The ESP forwards the complaint to your email delivery service (Mailgun, Amazon SES, etc.), which then sends a webhook request to Campaign's webhook URL. When Campaign receives the webhook payload, it only receives the recipient's email address – there is no way for it to know which sendout or which campaign resulted in a complaint. For that reason, when a complaint is received (the same applies to hard-bounces and unsubscribes via the ESP), the contact is marked as "complained" and any campaigns that they have received, as well as any mailing lists they are subscribed to, are given a "complained" interaction. I hope that helps explain why this is _not_ a bug, but also not ideal behaviour.

**Comment by bossanova808** [comment]
It does indeed explain it Ben.  

I do wonder whether it mightn't make more sense simply to add that interaction to the most recent campaign then?  As that's the most likely.  But that's just another form of inaccurate, I guess.

I shan't lose sleep over it, anyway - it's a rare thing for us, fortunately!

Thanks once again for your time.

**Comment by bencroker** [comment]
I'd like to find a better solution but dislike the idea of switching from one inaccurate solution to another.
