### ISSUE TITLE
Importing contacts with data other than plain text (like categories)

### ISSUE THREAD

**Issue by fthues** [putyourlightson/craft-campaign#345]
I need to import ~11.000 contacts from a CSV (generated by Mailchimp). 

Importing data into _Plain Text_ fields works just fine, but I can't figure out how to populate other fields I have on the contacts, namely fields of type _Category_. I had hoped that it would work like it does in _Feed Me_, where I can just specify a list of IDs in the CSV for one particular _Category_ field, something like:

`"10231,10232,59182"`

But no bueno, the contact's category fields remain empty.

This is a critical issue for us because we base the contents of our campaigns on those contact-specific category relationships.

Am I missing something or is this currently not possible? If so, is there a workaround you can think of?

Thank you!!

**Comment by fthues** [comment]
Doesn't seem to be possible at the moment so I wrote up a quick PR: #346

**Comment by bencroker** [comment]
This is not currently possible but it makes sense to add it. Out of curiosity, how are you mapping the category IDs, especially when Mailchimp is involved?

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/080370f15b83589db046a8dc96a66417a3b68e9d, for the next release.

**Comment by fthues** [comment]
Thanks, that was fast!

> Out of curiosity, how are you mapping the category IDs, especially when Mailchimp is involved?

Nothing too fancy, just wrote a quick Node script with a map of `mailchimpGroupName`s to `genreId`s that processes the exported CSV. So, semi-manually basically.

On a related note: I'm currently importing the 11,000 contacts and seeing an "Updating search indexes" being created after each single record, filling up the queue:

<img width="480" alt="Screenshot 2022-11-25 at 11 38 07" src="https://user-images.githubusercontent.com/455982/203965269-1dac80ae-bfae-4b67-ac23-f16219a26e25.png">

This is what each one looks like:

<img width="752" alt="Screenshot 2022-11-25 at 11 38 31" src="https://user-images.githubusercontent.com/455982/203965356-5ba499ae-1850-48f5-95ff-ceb45e08ed0d.png">

I have no searchable fields on the contact element.

Might it make sense to pass an `updateSearchIndex` argument of `false` into `saveElement` at https://github.com/putyourlightson/craft-campaign/blob/080370f15b83589db046a8dc96a66417a3b68e9d/src/services/ImportsService.php#L302 and then maybe trigger one single index update post-import?

**Comment by bencroker** [comment]
Great idea, added in https://github.com/putyourlightson/craft-campaign/commit/a6c3959c8e88023fa7102ec9f10cafaba3ef8a79.

**Comment by bencroker** [comment]
Released in version 2.2.3.
