### ISSUE TITLE
After Upgrade to Craft CMS 4: Subscribe Form with Ajax Script don't working

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-campaign#348]
After the upgrade to Craft CMS 4.3 the Subscribe Forms don't work any more via an ajax script

Inside the log we have an error, meaning the plugin does get the request.

```
Failed to load resource: the server responded with a status of 400 () in the console
2022-12-03 00:38:24 [web.INFO] [craft\services\Elements::_saveElementInternal] Element not saved due to validation error: Array
(
    [email] => Array
        (
            [0] => E-Mail darf nicht leer sein.
        )

)
 {"memory":5064848} 
2022-12-03 00:38:24 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'campaign/forms/subscribe'
]
```

-

Console Data and HTML Code:

![Bildschirmfoto_2022-12-03_um_01 03 17](https://user-images.githubusercontent.com/69263307/205519478-b345ce35-84de-4c7f-a02c-b564ec9a413f.png)
<img width="717" alt="Bildschirmfoto_2022-12-03_um_01 32 59" src="https://user-images.githubusercontent.com/69263307/205519482-b16bbb59-e7ba-4b82-8191-cf082c0d985d.png">

-

The ajax script

```
function formAjax(formID, formWrapID, thxID, onSub = '') {
	var form		= $(formID);
	var wrap		= $(formWrapID);
	var thx			= $(thxID);
	var subTrigger	= onSub;
	
	var clearErrorsOnInput = function($input) {
		if( $input.parent('fieldset').hasClass( 'hasErrors' ) ) {
			$input.parent('fieldset').removeClass('hasErrors');
			var $errors = $input.siblings('.errors');
			hideErrors($errors);
		}
	};
	var hideErrors = function($errors) {
		$errors.hide();
	};
	
	form.submit(function(ev) {
		ev.preventDefault();

		$(this).find('.errors').remove();
		form.find('.button').addClass('loader').prop('disabled', true );

		$.ajax({
			url : $('input[name=action]').val(),
			type : 'POST',
			data : $(this).serialize(),
			dataType : 'json',
			encode : true
		}).done(function(data) {
			if (data.success == true) {
				
				console.log('success');
				console.log(data);
				thx.fadeIn(200).addClass('show');
				wrap.hide();
				$("html, body").animate({ scrollTop: thx.offset().top - 100 }, 300);
				
				if (typeof subTrigger === 'function') {
					subTrigger();
				}				
			} else {
				console.log('error');
				console.log(data);
				
				form.find('.button').removeClass('loader').prop('disabled', false );
				
				for ( var fieldId in data.errors ) {
					var $errors = $( '<ul class="errors" />' );
					var messages = $.map(data.errors[fieldId], function(message){
						return '<li>' + message + '</li>';
					});
					$errors.append( messages.join( '' ) );

					var $input = form.find('#'+fieldId);
					$input.after($errors);

					$input.parent('fieldset').addClass('hasErrors');
					$input.on('change paste input', function() {
						clearErrorsOnInput($(this));
					});
				}
			}
		});
	});
};
```

**Comment by bencroker** [comment]
Can you please share the raw JSON AJAX response? You'll find it in the Network tab of the browser dev tools.

**Comment by bencroker** [comment]
Ok, I think I see the issue. Whereas the AJAX response used to have a `200` status code with the `data.success` parameter set to `false`, the response now has a `400` status code. This is something that should have been documented, similar to how Craft did at https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#changed-20.

```
The entries/save-entry action now returns a 400 HTTP status for JSON responses when the entry couldn’t be saved.
```

I've added this to Campaign's changelog in https://github.com/putyourlightson/craft-campaign/commit/79333a2099da5591dd72bf03bc6e547b8bc41818.

In terms of your code, you'll likely need to change it to the following.

```js
$.ajax({
    // ...
}).done(function(data) {
    // Success
    console.log(data);
}).fail(function(xhr) {
    // Failure
    console.log(xhr.responseJSON);
});
```

**Comment by bencroker** [comment]
I tracked down some docs that explain this at https://craftcms.com/docs/4.x/dev/controller-actions.html#during-a-post-request

**Comment by alexanderloewe** [comment]
I have noticed other things in the behavior of the forms. Previously, all fields that were necessary were validated by Campain, now this no longer seems to be the case. No matter if sent via post or ajax.

**Comment by bencroker** [comment]
Ok, I'll look into this as well.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/af3bd6e90b5cee709f1b9115c65be1dea9e816da and released in version 2.3.0.

**Comment by alexanderloewe** [comment]
Yeaa, everything works fine now! Thanks!

**Comment by bencroker** [comment]
Great, thanks for helping me troubleshoot!
