### ISSUE TITLE
Syncing craft users to mailing lists doesn't work

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-campaign#35]
Steps to reproduce

1) Allow public registrations and assign any registrations to a default group
2) Sync default group with Campaign
3) Register user via frontend (the user is activated)

Expected result: Registered user should appear in synced Campaign group, but does not.

Actual result: I did notice now that the user is synced as a contact in Campaign, but it's incomplete, because the user is not assigned to the mailing list Campaign is set to sync with.

I made a video of the whole thing here: https://drive.google.com/open?id=1REj3dMS9urR1mI2Hypl81XIABpy6-GVd

**Edit:**
Campaign 1.5.0
Campaign Pro 1.0.0

**Comment by putyourlightson** [comment]
Thanks for reporting this! Fixed in v1.5.1.
