### ISSUE TITLE
Cannot open COntact in a multi site environment

### ISSUE THREAD

**Issue by tonioseiler** [putyourlightson/craft-campaign#351]
I have a multisite environment with multiple mailinglist types etc, For users with limited acces on one site, the opening of a contact throws an error: Redirect Error, too many redirects.
<img width="867" alt="grafik" src="https://user-images.githubusercontent.com/4467443/207180800-1f6c37c6-36fc-4876-a010-1682e3138790.png">
Happens in FF and in Chrome

**Comment by bencroker** [comment]
Thanks for reporting this. What versions of Craft and Campaign are you running?

**Comment by bencroker** [comment]
Closing due to no response.
