### ISSUE TITLE
Sendout recuring- Edit

### ISSUE THREAD

**Issue by wmdhosting** [putyourlightson/craft-campaign#352]
If you want to edit or change recuring sendout.. 
Now you can only do that if you pause sendout.. 

But first you need to get Idea that edit work like that :)

So it will be great if there is Edit button..  
ON Recuring Sendouts.

**Comment by bencroker** [comment]
Would changing the button to read "Pause & Edit" be along the lines of what you were thinking?

**Comment by wmdhosting** [comment]
yes :)

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/647caa4724a589c16adceb1a98e59bb9a89b1f57 for the next release.

**Comment by bencroker** [comment]
Released in version 2.3.2.
