### ISSUE TITLE
Craft mail setting changed Campaign settings

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#353]
First off I am not 100% if this happened because of this but I am fairly certain it did.

I had to change to AWS for Craft due to Postmarkapp was having issues. Luckily I had your AWE SES plugin installed as I am using it for Campaign.

1) Locally I changed my Craft email settings to AWS SES and pushed my project config up to server.
2) After postmark fixed their issue I changed Craft local email settings back to SMTP and pushed project config up to server.
3) Today I noticed that Campaign sent emails using postmark SMTP and when I checked locally what Campaign email settings were it was SMTP but I never changed those.

I believe when I changed from AWS to STMP in Craft email settings it changed Campaign. Not sure if this has anything to do with this issue #321 

Amazon SES 	2.0.1
Campaign 	2.3.1
Craft Pro 4.3.5

**Comment by bencroker** [comment]
Assuming this is all going through project config, shouldn't you be able to track down when what was changed in the git commit history?

> Not sure if this has anything to do with this issue https://github.com/putyourlightson/craft-campaign/issues/321

This is only a feature request, so no.

**Comment by philipboomy** [comment]
Looking at the commits it looks like Craft Campaign changed the settings and not me.

![manually-changed-campaign](https://user-images.githubusercontent.com/29286831/208370206-c8e47f8d-76fe-4a1d-b341-fa3bcc700929.jpg)
![changed-craft-back](https://user-images.githubusercontent.com/29286831/208370212-fccc5a35-8d78-4af0-82b2-cd30da3055d6.jpg)
![changed-craft](https://user-images.githubusercontent.com/29286831/208370213-c6b79883-5fea-4ff1-8f7c-7c362ef744b7.jpg)

**Comment by bencroker** [comment]
So are you saying that the second screenshot above was a change that the Campaign plugin made on its own? I don't see anything in the code that could do that. What are the timings of those changes?

**Comment by philipboomy** [comment]
These screenshots shows what the changes were in project config and as you can see there was not a time where I pushed up a change to Campaign settings.

**Comment by bencroker** [comment]
> as you can see there was not a time where I pushed up a change to Campaign settings.

How can I see that exactly? I'm not seeing any commit messages so don't know when or by whom these changes were made.

**Comment by philipboomy** [comment]
What do you want exactly?

**Comment by philipboomy** [comment]
I tried to replicate and I can't. So will close. Hopefully a user error. Sorry about that.
