### ISSUE TITLE
Show open rate metrics in reports view

### ISSUE THREAD

**Issue by siebird** [putyourlightson/craft-campaign#354]
It's a pretty common pattern to see open rates for email campaign performances. A nice feature would be to add this metric to the `admin/campaign/reports/campaigns` report view 

- There could be an overall open rate at the top which would be running average for all campaigns
- At the table view add a column to easily scan each campaigns open rate performance

**Comment by bencroker** [comment]
Thanks for the suggestion. I've added “Open Rate” to campaign reports and as an available column in the campaign element index page in https://github.com/putyourlightson/craft-campaign/commit/c3ba8d1361d6a803212ece06ce6ce7dc740f0624, for the next release.

**Comment by siebird** [comment]
That was quick! Thanks, Ben.

**Comment by bencroker** [comment]
Released in version 2.4.0.
