### ISSUE TITLE
FR: Allow for dynamically generated Campaign title

### ISSUE THREAD

**Issue by pl-mnm** [putyourlightson/craft-campaign#355]
We are using regular entries to compose our emails, and are using an `entry` field to pull it into our Campaign. Ideally the Campaign title could use the existing entries' title:

```{entryField.one.title}```

Furthermore, when creating a Sendout, it would be great to be able to re-use the Campaign title as an email subject instead of manually having to enter it again.

**Comment by bencroker** [comment]
Thanks for the suggestion, we'll consider it for a future release.

Please refer to https://github.com/putyourlightson/craft-campaign/issues/356 for the Sendout subject.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/84fb410e0bf3963b74583b5b3dd5cada3a1f73e0 for the next release.

**Comment by bencroker** [comment]
Released in version 2.5.0.
