### ISSUE TITLE
FR: Re-use Campaign title in Sendout email subject

### ISSUE THREAD

**Issue by pl-mnm** [putyourlightson/craft-campaign#356]
We would like to improve the author experience by having the Campaign title being the email subject, and not have to enter it twice or come up with different titles.

**Comment by bencroker** [comment]
You can already have the Sendout subject auto-populated by clicking on `Save and create new regular sendout` when editing a campaign.

<img width="418" alt="Screenshot 2023-01-12 at 08 44 28" src="https://user-images.githubusercontent.com/57572400/212097193-41f79b07-36bc-4ae1-a9eb-2f08c26b8f6a.png">

I'll keep this open though and explore the possibility of populating the subject when a new campaign is selected.

**Comment by bencroker** [comment]
Added this, as well as the ability to hide the title field in sendouts, in https://github.com/putyourlightson/craft-campaign/commit/7541af7acc01a082342d380ce2c941a9331b1a08 for the next release.

**Comment by bencroker** [comment]
Released in version 2.5.0.
