### ISSUE TITLE
yii\base\InvalidArgumentException - Invalid path alias: @putyourlightson/blitz/icon-mask.svg

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#357]
1. Navigate to control-panel/utilities
2. Exception is thrown

![kép](https://user-images.githubusercontent.com/9061795/212395416-0b8d0a8a-7925-465e-837a-0aae22d583bd.png)

Craft Campaign 2.4.0 is installed, Blitz is not.

**Comment by bencroker** [comment]
Thanks for reporting that. Fixed in https://github.com/putyourlightson/craft-campaign/commit/9000574f79c728eb59905fe313b3eefaacc07ff1 and released in version 2.4.1.
