### ISSUE TITLE
How to get url and pendingContact in Subscribe Verification Email Template

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-campaign#358]
i am trying to make my own Subscribe Verification Email Template but cannot
get the Name of the user ( {{ pendingContact }} ) who wants to gets subscribed and 
the url for the user to verify his email. ( {{ url }} ).

i tried with setting the maillinglist 
`{% set mailingList = craft.campaign.mailingLists.slug('newsletter-privat-customers').one() %}`

and then
`{{ mailingList.url}}`

but this did not work.

I read the [docs](https://putyourlightson.com/plugins/campaign#subscribe-verification-email-template) and i should be able to use pendingContact. But it tells me "Variable "pendingContact" does not exist."
As far as i understand it, i have no custom field or are fields in the contact settings considered as custom fields?
I haven't really understood where custom field could be.

Craft: 3.7.59
Campaign: 1.23.5

**Comment by bencroker** [comment]
As per the docs, the following variables are available: `message`, `url`, `mailingList`, `pendingContact`

So an example template would be:

```twig
Hello {{ pendingContact.fieldData.firstName }},

Please verify your email address by clicking on the following link:
{{ url }}
```

https://github.com/putyourlightson/craft-campaign/blob/aaf78990a8fe6504d5a3d73463f74e640d0d630b/src/services/FormsService.php#L104-L109

**Comment by hhentschel** [comment]
Thanks!
now it's working. And now it all makes sense.

(url was working all the time i guess, did not realize it, because of inline css styles i set before) 

very happy about the plugin.

**Comment by bencroker** [comment]
Glad to hear it!
