### ISSUE TITLE
How to fetch data from contacts dynamically

### ISSUE THREAD

**Issue by samuelreichor** [putyourlightson/craft-campaign#359]
Hello, I would like to send personalized emails. It is about a newsletter and I want to send it simultaneously to all contacts in a mailing list.  For this I have created fields in the contacts (firstname, lastname, gender) and I would like to use this data in the email template.

I followed the docs [here](https://putyourlightson.com/plugins/campaign#getting-contacts) and managed to fetch a contact with : 
```
{% set contact = craft.campaign.contacts.email('jim@bean.com').one() %}

{% if contact %}
  <p>{{ contact.firstname }}</p>
  <p>{{ contact.lastname }}</p>
{% endif %}

```

Logically I can't hardcode the Email, so I'm looking for a way to retrieve the data dynamically and insert it into the template. 

Any ideas or solutions?

**Comment by bencroker** [comment]
The `contact` variable will be available in your campaign emails already, so you can just do it as follows.

```twig
<p>{{ contact.firstname }}</p>
<p>{{ contact.lastname }}</p>
```

**Comment by samuelreichor** [comment]
I already tried that, unfortunately it didn't work with `contact.handleOfTheField`.

**Comment by bencroker** [comment]
Please provide some details of what "didn't work" so I can help you.

**Comment by samuelreichor** [comment]
Got it now thank you :)
