### ISSUE TITLE
Error importing anything after deleting a mailing list 

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-campaign#36]
Steps to reproduce

1) Go to Campaign > Settings > Mailing Lists
2) Delete a mailing list (no error so far)
3) Go to Campaign > Contacts > Import

Clicking the Import tab in step 3 produces the following error. See video: https://drive.google.com/open?id=1WlifmxyvDIpaYFAen5dhF-pGmmZNTJQE

**Edit:**
Campaign 1.5.0
Campaign Pro 1.0.0

**Comment by putyourlightson** [comment]
Thanks for reporting this! Fixed in v1.5.1.
