### ISSUE TITLE
Server error in the segments panel

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#367]
Please provide a clear and concise description of what the bug is, including:
- Steps to reproduce the issue.
The following problem occurs only on my production server (some kind of database corruption?).

Create a "Regular" Segment
Add some conditions and save it.
Notice the "Sever error" message
The newly created segment does not appear in the segments list.
Althought, it appears in the contact  panel and in the sendout panel.

- A clear and concise description of what you expected to happen.
All the "regular" segments should be correctly displayed in the segments panel
- If applicable, add screenshots to help explain your problem.
![CleanShot 2023-02-20 at 23 51 18@2x](https://user-images.githubusercontent.com/1114307/220209616-349af277-2837-4081-8bbe-99aa1a64a68a.png)
![CleanShot 2023-02-20 at 23 28 14@2x](https://user-images.githubusercontent.com/1114307/220207540-fbd66fd1-0ab7-4217-a859-e6927d14b8d9.png)
![CleanShot 2023-02-20 at 23 39 54@2x](https://user-images.githubusercontent.com/1114307/220208472-c4550031-8131-41d2-8c8d-1f3fcc93348a.png)
- The plugin and Craft version numbers.
Craft Pro 4.3.10
Campaign 2.5.3

**Comment by bencroker** [comment]
Can you show me the segment edit screen please, so I can see what conditions are included?

**Comment by scandella** [comment]
Hi Ben,
Unfortunately, I can’t show you the edit section of the saved segments, because they do not appear in the segments panel anymore after their saving.
But here is a picture of the kind of segment I’ve created.

Best,

<img width="1128" alt="CleanShot 2023-02-21 at 07 49 54@2x" src="https://user-images.githubusercontent.com/1114307/220269911-497c1edc-7af4-49e3-aba7-4cbe0b7f65c2.png">

**Comment by bencroker** [comment]
Thanks, that looks just fine. Can you please check the log files for the error stack trace, or email to info@putyourlightson.com?

**Comment by scandella** [comment]
Ben,
Here's the errors log. Is this what you need?
Seem to have a template error:
`Next Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Unable to register extension "putyourlightson\campaign\twigextensions\CampaignTwigExtension" as extensions have already been initialized."). in /home/www/manufacture.scandella.fr/htdocs/vendor/craftcms/cms/src/templates/_layouts/base.twig:60`

Best,
[phperrors.log](https://github.com/putyourlightson/craft-campaign/files/10795301/phperrors.log)

**Comment by bencroker** [comment]
No, this looks unrelated. I'll need to see the latest `web` log file.

**Comment by scandella** [comment]
[OK, the web log file is there](https://navette.scandella.fr/4RxqIG4X)

Best,

**Comment by bencroker** [comment]
Thanks, here's the part I was looking for.

```
2023-02-21 06:56:47 [web.ERROR] [TypeError] craft\fields\conditions\OptionsFieldConditionRule::elementQueryParam(): Return value must be of type array, null returned {"trace":["#0 /home/www/manufacture.scandella.fr/htdocs/vendor/craftcms/cms/src/fields/conditions/FieldConditionRuleTrait.php(115): craft\\fields\\conditions\\OptionsFieldConditionRule->elementQueryParam()","#1 /home/www/manufacture.scandella.fr/htdocs/vendor/craftcms/cms/src/elements/conditions/ElementCondition.php(181): craft\\fields\\conditions\\OptionsFieldConditionRule->modifyQuery()","#2 /home/www/manufacture.scandella.fr/htdocs/vendor/putyourlightson/craft-campaign/src/services/SegmentsService.php(142): craft\\elements\\conditions\\ElementCondition->modifyQuery()"
```

This appears to be a bug in Craft, which I've submitted a fix for in https://github.com/craftcms/cms/pull/12713. In the meantime you can avoid this by ensuring that the condition has at least one value selected.
