### ISSUE TITLE
Logical operator in the "Regular" segments type

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#368]
Hi,
Using the "Regular" segments type, it seems there is no way to combine some "OR" conditions.
All the conditions seems to be chained with "AND" logic.
In the "Legacy" conditions builder, the segment can be added with some "OR" or "AND" operator.
But in your doc, you mention that the "Legacy" type is going to be removed.

So will it be possible to create some segments with "OR" and "AND" operator in the futur ?   
Is there a way to dot it right now within the "Regular" segment?

Thanks for your help.

**Comment by bencroker** [comment]
Regular segments use the condition builder which does not _yet_ support OR logic, although it is planned, see https://github.com/craftcms/cms/discussions/11287.

That's the main reason we kept the Legacy sendout type around. If you have a specific condition type in mind, then you can create and register your own condition rules using a custom plugin or module. There's an example at https://github.com/putyourlightson/craft-campaign/blob/develop/examples/conditions/segments/ContactIsUserConditionRule.php.
