### ISSUE TITLE
Possible to duplicate a campaign

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-campaign#369]
Is it possible to duplicate a campaign?

I have a customer who sends out a campaign each month, 
one to private clients and one to business ones.
The only major difference are the prices of products. 

( I would make this possible with two different fields for products,
and then depending on the field output the prices in the newsletter template)

So for the customer it would be easy to duplicate an existing campaign and
choose a different product field.

I tried copying fields (like native craft fields) to a campaign, but that's not possible.

**Comment by bencroker** [comment]
Duplicating a campaign is possible via the action menu on the index page.

<img width="311" alt="Screenshot 2023-03-03 at 08 00 48" src="https://user-images.githubusercontent.com/57572400/222739259-926b4a24-54b8-453b-8832-3eb04cfe5270.png">

> I tried copying fields (like native craft fields) to a campaign, but that's not possible.

What exactly are you trying to do?

**Comment by hhentschel** [comment]
Ah, looks like it's not possible with my plugin version (1), respectively the craft version (still 3).

![Bildschirm­foto 2023-03-03 um 15 25 46](https://user-images.githubusercontent.com/2101975/222745982-f0ac7372-3287-4c69-9d0c-ccfba2623b10.png)

upgrade is planned anyway.
...
as a workaround for duplicating a campaign, i thought i could copy fields to a new campaign, so the customer does not have to fill in all the fields again.

**Comment by bencroker** [comment]
If you‘re on Campaign v1, then you can still use the “Save as a new campaign” option on the campaign edit screen.

<img width="470" alt="Screenshot 2023-03-03 at 08 44 25" src="https://user-images.githubusercontent.com/57572400/222749957-716f9ea7-9bb5-4beb-a43a-91c2e6e177cf.png">

**Comment by hhentschel** [comment]
Thanks! Great.
Forgot about this dropdown.
