### ISSUE TITLE
When synced users change email, a new contact is created, with only the synced mailinglist subscription activated

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#37]
**Steps to reproduce:**

1. Create a user group with some users
2. Create a couple of mailing lists, and make one of them sync with the user group
3. Add some additional subscriptions to a user
4. Change user's email

**Expected outcome:**

The synced user's campaign contact's email is changed, and all subscriptions are kept.

**What happens:**

* a new contact is created, which is synced to the synced mailing list (and only that list).
* the now "orphan" contact is kept, with all subscriptions, except the synced mailing list. This contact's email will probably stop working, the contact will bounce, and the new address won't get the expected emails. 

Makes sense?

Regards, 

Peter

**Comment by putyourlightson** [comment]
Thanks Peter. I'm guessing this is happening because contacts and users are coupled by email address alone. I'll look into fixing this soon.

**Comment by putyourlightson** [comment]
Peter, just wanted to let you know that this is still on our priority list and I hope to have a permanent fix for you soon, thanks for your patience.

**Comment by putyourlightson** [comment]
Fixed in version 1.6.5.
