### ISSUE TITLE
Placeholder for Campaign sendouts

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-campaign#370]
We want to send a newsletter using Campaign. However, we were wondering if it's possible to access Craft's global variables in a Campaign template (similar to the `contact` template variable)? We'd like to create a footer with dynamic contact values that should be read / injected from a Craft global field on send.

Thanks in advance for your answer!

**Comment by bencroker** [comment]
That should be possible, are you finding otherwise and with what global variables specifically?

**Comment by martinhellwagner** [comment]
@bencroker 

It was more a general question, since I didn't find anything about that in the docs. This is our current footer:

```
<mj-column>
    <mj-text padding="0" font-size="12px">
        <img width="80" height="24" src="..." alt="JobRad">
        <p>
            JobRad Österreich GmbH | at.jobrad.org
        </p>

        Am Belvedere 10, 7. OG, Top 9 | 1100 Wien <br>
        Geschäftsführung: Edwin Ronald de Jong; Sitz der Gesellschaft: Wien<br>
        Firmenbuchgericht: Handelsgericht Wien; FN 549031z; UID: ATU 76509459
    </mj-text>
</mj-column>
```

I'm thinking something along the lines of:

```
<mj-column>
    <mj-text padding="0" font-size="12px">
        <img width="80" height="24" src="..." alt="JobRad">
        <p>
            {{ contact.globalName }} | {{ contact.globalUrl }}
        </p>

        {{ contact.address }} | {{ contact.postalCode }} {{ contact.city }} <br>
        Geschäftsführung: Edwin Ronald de Jong; Sitz der Gesellschaft: Wien<br>
        Firmenbuchgericht: Handelsgericht Wien; FN 549031z; UID: ATU 76509459
    </mj-text>
</mj-column>
```

Would that work just like accessing global variables in a Twig template?

**Comment by bencroker** [comment]
Yes, that should work, assuming that those fields exist on contacts.

**Comment by martinhellwagner** [comment]
Great, that answers my question. Thanks! 🙏🏼

**Comment by bencroker** [comment]
Great, just remember to output the contact data conditionally so that previews continue to work.

```twig
{% if contact is not null %}
    ...
{% endif %}
```

Or:
```twig
{{ contact.globalName ?? 'Contact global name placeholder' }}
```

**Comment by martinhellwagner** [comment]
Yeah, I would have worked with placeholders (those being the currently hardcoded data points).
