### ISSUE TITLE
Reports view defaults to the primary site event though the primary site is not one of the options

### ISSUE THREAD

**Issue by NathanBate** [putyourlightson/craft-campaign#373]
I restricted a user group to one specific site in Campaign. 
- When I log in as that user and go to the Campaign reports, all the reports show from the primary site in the CraftCMS sites list. 
- When I click on the site switcher, the primary site isn't even an option and only the assigned site is an option. 
- When I click the assigned site for this user then the primary site reports are no longer available (which is the way it should have originally been).

![CleanShot 2023-03-25 at 10 08 45@2x](https://user-images.githubusercontent.com/103517525/227722298-8aba902b-60cf-442b-beff-2c9e6c8a990a.png)

<img width="460" alt="CleanShot 2023-03-25 at 10 10 08@2x" src="https://user-images.githubusercontent.com/103517525/227722315-70e42532-1f81-402f-b064-81cfd5d30dee.png">

<img width="1363" alt="CleanShot 2023-03-25 at 10 10 42@2x" src="https://user-images.githubusercontent.com/103517525/227722341-7d335166-2ab7-4f80-adce-a200a87d56cd.png">

The expected behavior would be for only the site that was assigned as available would show up when the user clicks on reports.

I am on Campaign Lite 2.5.5
I am on CraftCMS 4.4.5

**Comment by bencroker** [comment]
> I restricted a user group to one specific site in Campaign.

How specifically did you do this? I assume you mean that you restricted a user group to _editing_ a specific site under the _Sites_ user permission, is that correct?

I can replicate the site switcher issue so will address this bug.

**Comment by NathanBate** [comment]
@bencroker, Yes, that is how I restricted the user to a specific site - through the Sites user permission. Thank you for looking at this.

**Comment by bencroker** [comment]
Thanks for the bug report. Fixed in https://github.com/putyourlightson/craft-campaign/commit/d9c2ab72b81001e49e7118f4327787a75cca8d70 for the next release.

**Comment by NathanBate** [comment]
Thanks Ben!

**Comment by bencroker** [comment]
Released in version 2.6.0.

**Comment by NathanBate** [comment]
@bencroker I just installed 2.6.0, and it is working great. Thank you! There is one other way where a CraftCMS user restricted to one site can view all the reports on another site: Campaign --> Reports --> Contacts Tab --> Click on a contact --> All reports are available for viewing.

I understand this may not be within your scope, but I thought I would check just in case. It would be nice if the user does not have contact edit permissions that they could not click into that contact (like on the Campaign --> Contacts screen).

**Comment by bencroker** [comment]
The site permissions are not quite as specific as you seem to be interpreting them, however, the Campaign plugin permissions are. If a user does not have permission to “Manage contacts” then they should not be able to access the contacts. Are you seeing otherwise?

**Comment by NathanBate** [comment]
I suspected that I may be interpreting things too narrow for your scope. Here are some screenshots.

They can view the contacts on the contacts page but not edit them (because I have that permission turned off)

![CleanShot 2023-04-04 at 18 46 56@2x](https://user-images.githubusercontent.com/103517525/229939308-a14ea115-484c-46ac-8ba0-d8e9dbb38222.png)

They can view a list of contacts on the reports screen and click on an individual contact. It is on this screen that I wondered if they should be able to click into or not if they are not supposed to be able to edit a contact.

![CleanShot 2023-04-04 at 18 48 48@2x](https://user-images.githubusercontent.com/103517525/229939336-afc32a2e-3220-4df4-aa3a-8b14cdc4a60d.png)

They can view the individual contact's activity history on the report contacts screen.

![CleanShot 2023-04-04 at 18 49 33@2x](https://user-images.githubusercontent.com/103517525/229939352-2c60540e-1d47-4169-b1cc-e87d7df8ab76.png)

**Comment by bencroker** [comment]
They cannot _edit_ contacts, but they can _view_ them, presumably because the “View reports” permission is enabled.

**Comment by NathanBate** [comment]
Got it, yes. "View reports" is enabled.
