### ISSUE TITLE
Sendout fails on a number of e-mail addresses

### ISSUE THREAD

**Issue by mathieuser** [putyourlightson/craft-campaign#377]
I'm sending to a list of 1100 e-mail addresses from my website. I'm using the basic SMTP server from my hosting, and i seem to be able to reach about 950 contacts of the 1100. I've played with the settings maxSendFailuresAllowed and maxSendAttempts to no avail. The error i get I've read about here, but I can't seem to wrap my head around it... From other posts, I understand that this could be due to limitation of the SMTP server, but it fails always at exact the same e-mail addresses. From these addresses, I know at least some of these are working as i've mailed with these people in the last weeks. So, it is a bit unclear on how to proceed. Could this be solved using a SMTP service like Mailgun? Or am I doing something wrong?

Also: I was able to send it to 950 contacts unsubscribing e-mail addresses along the way on which the sendout failed. But, knowing some of these email addresses just work fine, this seems like the wrong way to go.

This is the error i receive. When upping the maxSendFailuresAllowed, I just get more like these until it fails again.
[2023-04-14 09:16:03] Sending of the sendout "Cas-co NEWS: April" to [xxxx@xxxx.com](mailto:xxxx@xxxx.com) failed after 5 send attempt(s). Please check that your Campaign email settings are correctly configured and check the error in the Craft log.

**Comment by bencroker** [comment]
That error does indeed seem to indicate that your SMTP server is blocking requests. SMTP servers commonly throttle email requests or block them completely if a quota is exceeded. An email delivery service would make this much easier to troubleshoot as they handle this kind of reporting. With an SMTP server, you’re kind of left on your own to manage and troubleshoot issues (which is exactly why we discourage them).
