### ISSUE TITLE
Add contact with the "New Contact" is not authorized

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#378]
Hi,
Using Craft-Campaign 2.6.0 in Craft Pro 4.4.7, I have given all the authorizations to a group of users, although the users are not authorized to add a contact via the "New Contact" button. It triggers a "User not authorized to edit this element."

Thanks for your help.

<img width="300" alt="CleanShot 2023-04-14 at 20 44 30@2x" src="https://user-images.githubusercontent.com/1114307/232130515-1d477102-ad98-49dc-99ad-ce639644dbf4.png">

**Comment by bencroker** [comment]
Do users have edit permission for the primary site?

<img width="633" alt="Screenshot 2023-04-14 at 15 14 56" src="https://user-images.githubusercontent.com/57572400/232146404-ac8293ca-cbcf-4dc7-aea7-a4afb04b3d9c.png">

**Comment by scandella** [comment]
Ben,
This is not a Craft multiple-site system. There is only one site in this system.
So I don't see the option you have highlighted.
The option I have looks like the one in the attached screenshot.

![CleanShot 2023-04-14 at 20 44 30@2x](https://user-images.githubusercontent.com/1114307/232160492-fa8c93ea-2bbe-481d-b2bb-bc5c25cbdfd2.png)

**Comment by bencroker** [comment]
You don’t see it because the French translation has not yet been added. Can you please double check that users have permission to edit the site?

<img width="680" alt="Screenshot 2023-04-14 at 18 07 14" src="https://user-images.githubusercontent.com/57572400/232168682-fa3bd755-d764-42d3-b335-d95d7d725d3e.png">

**Comment by bencroker** [comment]
Any update on this, @scandella?

**Comment by mathieuser** [comment]
Hi Ben,

Just chiming in here as I have the same problem.

It seems if you only have one site, you cannot give these edit permissions, and so it seems my user should be admin to be able to add contacts, and that's not ideal as I don't want them to have this access.

**Comment by scandella** [comment]
Hi Ben,
Sorry for the delay, I was away from my computer for a while.
Same as @mathieuser , this is a one-site Craft system, so there is no checkmark for the user to edit the site as you mentioned in your previous answer.
Although, the users can edit every part of the site that I give them access to, except for the contact in the campaign plugin.

**Comment by bencroker** [comment]
Ok I’ve found and fixed the issue in https://github.com/putyourlightson/craft-campaign/commit/8ff218a4fe7738ce3bdedd9f018d98350fc181bd and released in version 2.6.2.
