### ISSUE TITLE
Sendouts don't remember from name/email after pause/resume 

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-campaign#38]
If you have two or more `From Names and Emails` under `Settings`, then start a sendout using one of the names/emails not on the top of the list, then pause the sendout, then resume it again, the sendout doesn't remember which from name/email you selected, and reverts to using whichever one is the topmost.

**Comment by putyourlightson** [comment]
Thanks, will fix this in the next release.

**Comment by putyourlightson** [comment]
Fixed in 1.5.2.
