### ISSUE TITLE
How to properly set up with Sendgrid webhook

### ISSUE THREAD

**Issue by mathieuser** [putyourlightson/craft-campaign#381]
Hi,

I've started to use Sendgrid with Campaign, but the bounces/complaints are not being fed to the webhook. I've set-up the Sendgrid Event Webhook with the deliverability data checked and copy-pasted the webhook from the Campaign dashboard, and tested a sendout with 2 e-mails: myself and a email that i've made up. The last one shows as bounced in Sendgrid, but 0 bounces in Campaign. Am I doing something wrong?

Thank you!

**Comment by bencroker** [comment]
What version of Campaign are you running? And are you seeing any errors or warnings in the `storage/logs/campaign.log` files?

**Comment by mathieuser** [comment]
Hi Ben!

No errors, just 

[2023-05-03 12:00:54] Sendout "Test sendout" initiated by "casco_adm".

I'm running 2.6.0

**Comment by bencroker** [comment]
Can you show me your SendGrid event setup (hiding any sensitive data)?

**Comment by mathieuser** [comment]
Sure!

This is the 'Event Webhook' setup. When I press the test button, I dont really know what to look for in Campaign.

<img width="621" alt="Schermafbeelding 2023-05-03 om 14 56 58" src="https://user-images.githubusercontent.com/6756174/235922805-192cc172-086d-4df0-8603-a0328ae9feac.png">

Anything else I can provide?

**Comment by bencroker** [comment]
If the webhook request worked then you should see it logged to `campaign.log`. If there is an error then it should be logged to `web.log`. Can you check both those files after testing? This assumes the site is at a publicly available URL and switched on.

**Comment by mathieuser** [comment]
Hi Ben,

I will as soon as sendgrid approoves my account (to make sure this is not the issue). I will get back to you in the next days! Thank you for your help.

**Comment by bencroker** [comment]
Ok, sounds good.

**Comment by bencroker** [comment]
Any update on this @mathieuser?

**Comment by mathieuser** [comment]
Hey Ben,
No not yet, its been a ridiculous trajectory with sengrid, my account is now suspended because I didnt reply for 2 weekend days with addittional info, and I have not gotten a reply back... I'll keep you posted when the account finally comes through

**Comment by bencroker** [comment]
Sheesh. I moved away from Sendgrid years ago and am very happy with the services of both Mailgun and Postmark, in case that’s an option for you.

**Comment by mathieuser** [comment]
Yeah that would be. I'll check out Postmark tonight, might go a little faster than this ;) Thank you! I'll drop you a line if I decided between them tomorrow, and if so this can be closed then.

**Comment by bencroker** [comment]
Sounds good!

**Comment by mathieuser** [comment]
Hey Ben!

thanks for the tip on postmark. Was approoved in 15 minutes! 

I have a small question about the webhook, but im not sure if you’d like me to open another issue and close this one? I’m just getting a 400 error response when im using the postmark webhook and test it in the postmark control panel. Not sure what i’m doing wrong. Thank you!

**Comment by bencroker** [comment]
Great! Please create a new issue for the webhook issue with more details and I’ll take a look.
