### ISSUE TITLE
Add `campaign.subject` variable in templates

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#386]
Forgive me if this already exists, but it would be helpful to be able to access the Subject line text from the Sendout in the template, especially when Title field is enabled and there is a separate Subject field.

**Comment by bencroker** [comment]
The subject is tied to the sendout, so `{{ sendout.subject}}` should do what you're after.

**Comment by adrianjean** [comment]
Ah ok yes — that variable works on testing the sendout in an actual email — thank you!
One note tho, the variable doesn't seem to show in the sendout preview tab.

**Comment by bencroker** [comment]
You’re right. I just changed that behaviour in https://github.com/putyourlightson/craft-campaign/commit/e34e24947d7e09e957b80f83a4175c124373903d for the next release.

**Comment by bencroker** [comment]
Released in version 2.7.1.
