### ISSUE TITLE
Delete contact on unsubscribe

### ISSUE THREAD

**Issue by green17** [putyourlightson/craft-campaign#387]
When a contact unsubscribes from a mailing list, is it possible to also delete them programmatically?

**Comment by bencroker** [comment]
Yes it is, but doing so is not advised. By keeping them as an unsubscribed contact, you can ensure that if their email is imported again in future, it will not be unintentionally resubscribed. Also, it gives you more accountability for what contacts took what actions.

**Comment by green17** [comment]
Thanks @bencroker, our main concern would be from a GDPR perspective. We wouldn't be importing contacts so I don't think that would be an issue, we are looking for a way to hop onto the unsubscribe event and delete the contact if they are not subscribed to any other list. We have tried a few ways of doing this but none seem to delete the contact. Are you able to advise on how we might check, when a contact unsubscribes, whether the contact is subscribed to anything else, and delete if not?

**Comment by bencroker** [comment]
The following code should work. Setting the second parameter on the `deleteElement()` method to `true` will hard-delete the contact, rather than the default soft-delete behaviour.

```php
use Craft;
use putyourlightson\campaign\events\UnsubscribeContactEvent;
use putyourlightson\campaign\services\TrackerService;
use yii\base\Event;

Event::on(
    TrackerService::class, TrackerService::EVENT_AFTER_UNSUBSCRIBE_CONTACT,
    function(UnsubscribeContactEvent $event) {
        Craft::$app->elements->deleteElement($event->contact, true);
    }
);
```

**Comment by green17** [comment]
Thank you @bencroker, that works great.

**Comment by bencroker** [comment]
Sure thing.
