### ISSUE TITLE
Testing webhook in postmark returns error 400

### ISSUE THREAD

**Issue by mathieuser** [putyourlightson/craft-campaign#388]
When I use the webhook in Postmark, and I test it from there, it returns a 400 error. I have a hard time understanding what's up.

Thanks for your help!

<img width="627" alt="Schermafbeelding 2023-05-24 om 12 00 57" src="https://github.com/putyourlightson/craft-campaign/assets/6756174/fce73f1d-8a1d-4ff2-adc3-c4ddfc543b98">

**Comment by bencroker** [comment]
Can you check the `/logs/campaign.log` file for any clues?

**Comment by mathieuser** [comment]
I cleared the logs, hen logged in so a web.log was created, then I sent the request from postmark again, but no campaign.log got created apparently... So I don't think it gets into Craft CMS at all

**Comment by mathieuser** [comment]
Hmm so when I send a bounce the campaign.log file is created and it receives it, though still getting the 400 error in Postmark.

`[2023-05-24 12:31:15] Webhook request: {   "Metadata": {     "example": "value",     "example_2": "value"   },   "RecordType": "Bounce",   "ID": 42,   "Type": "HardBounce",   "TypeCode": 1,   "Name": "Hard bounce",   "Tag": "Test",   "MessageID": "00000000-0000-0000-0000-000000000000",   "ServerID": 1234,   "MessageStream": "outbound",  "Description": "The server was unable to deliver your message (ex: unknown user, mailbox not found).", "Details": "Test bounce details",   "Email": "john@example.com",   "From": "sender@example.com", "BouncedAt": "2023-05-24T10:31:14Z",   "DumpAvailable": true,   "Inactive": true,   "CanActivate": true,   "Subject": "Test subject" }`

**Comment by bencroker** [comment]
Are you running the latest 2.7.0 version of Campaign?

**Comment by mathieuser** [comment]
I just updated to 2.7.0, but no changes on this regard so it seems!

**Comment by mathieuser** [comment]
I've done a test through RequestBin, with the same JSON data as in postmark, and i'm getting this response:

<img width="866" alt="Schermafbeelding 2023-05-24 om 17 10 33" src="https://github.com/putyourlightson/craft-campaign/assets/6756174/38685c61-0c1a-4eb3-ac8c-66d4dd785267">

**Comment by bencroker** [comment]
> I've done a test through RequestBin, with the same JSON data as in postmark, and i'm getting this response:

That error is to be expected, since the request came from an IP address other than one of [Postmark’s designated IPs](https://postmarkapp.com/support/article/800-ips-for-firewalls#webhooks).

The issue turned out to be that `john@example.com` is not a valid contact in the system. I changed this behaviour so that a successful response is returned, regardless of whether the contact exists, in https://github.com/putyourlightson/craft-campaign/commit/bb7cc6bae94f45495e6638237db4713cc17ff3f5 and released in version 2.7.1.
