### ISSUE TITLE
Ability to select multiple Categories in condition builder

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#393]
**Setup:**
- My email contacts have an "Interests" field that is of a Category field type with no limit on how many categories you can select. 
- I want to use these categories for segmentation.

**Issue:**
- In the Segment builder, using the "Regular" segment type, I can select the "Interests" field, but I am only able to select one category. 
- It would be great to be able to select multiple categories to segment my audiences by — or be able to add another Condition for the same field (right now fields can only be added once as a Condition.)

**Comment by bencroker** [comment]
This is a restriction currently placed on the condition builder by Craft, so there’s not much we can do about it. See the discussion at https://github.com/craftcms/cms/discussions/12538.

**Comment by adrianjean** [comment]
Ah — Ok maybe as a workaround I'll use a Multi Select field instead of a Categories field — seems to work.

**Edit:**
Using Multi Select field is an option, however it returns results as if the operator between terms was "OR" not "AND" — so selecting "Donors" as well as "Volunteers" in a Multi Select Field, returns all contacts with either term, not just those with only both terms.

**Comment by bencroker** [comment]
> Using Multi Select field is an option, however it returns results as if the operator between terms was "OR" not "AND"

Again, Craft core is defining this behaviour, not the Campaign plugin.
