### ISSUE TITLE
Add "Is all of" operator to Multi Select Fields in Condition Builder

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#394]
Would it be possible to add another operator (`Is all of`) to the Condition Builder for `Multi Select` fields?
It would allow me to segment contact by all the terms selected, as opposed to any of the terms selected.

Right now there are only two operators:  `Is none of` and `Is one of`

**Comment by bencroker** [comment]
As with https://github.com/putyourlightson/craft-campaign/issues/393, Craft core is defining this condition builder behaviour, not the Campaign plugin.

**Comment by adrianjean** [comment]
Ack! — ok roger that.
