### ISSUE TITLE
Error updating search indexes

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#397]
I'm getting this error for the a task in the queue.

LitEmoji\LitEmoji::unicodeToShortcode(): Argument #1 ($content) must be of type string, null given, called in /home/ploi/www.website.co.uk/vendor/putyourlightson/craft-campaign/src/elements/SendoutElement.php on line 1085

PHP: 8.0.29
Campaign: 2.7.2
Craft: 4.4.13

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-campaign/commit/d55d19f77cca09d7be7b6406df884a5ed53bf2a4 for the next release.

**Comment by bencroker** [comment]
Released in version [2.8.3](https://github.com/putyourlightson/craft-campaign/releases/tag/2.8.3).
