### ISSUE TITLE
Ability to resend sendouts

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#399]
Recently we had an error where our live Craft site was in DEV mode so sendouts where going to test emails instead of real ones (d'oh). As such, we wanted to be able to resend those sendouts that were affected by this issue.

Granted, we worked around this by creating new sendouts, but was a slow process - would have been useful to be able to group-select sendouts and resend.

Appreciate we may not have considered any pitfalls to this.

**Comment by bencroker** [comment]
Did you consider duplicating the sendouts? That would likely be my recommendation if this was ever to happen again.

<img width="331" alt="Screenshot 2023-06-29 at 22 04 40" src="https://github.com/putyourlightson/craft-campaign/assets/57572400/8e33375a-f6ad-4e92-a9c5-3e0c08996372">

**Comment by iamkeir** [comment]
@bencroker interesting, we have all those options except "duplicate". v1.24.2

**Comment by bencroker** [comment]
It was added in [2.0.0](https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md#200---2022-05-04).
