### ISSUE TITLE
Multiple templates

### ISSUE THREAD

**Issue by stovepot** [putyourlightson/craft-campaign#4]
Would it be possible to configure a campaign so it uses a (tabled) html template for the sendout, but it uses a different entry template to display to contents on the site. (Bootstrap responsive) 

Could "Routes" provide a solution?

**Comment by putyourlightson** [comment]
You generally create a "view in browser" link in your campaign template, and you can link that to any URL, including your custom responsive template. In your template, you'll just have to fetch the correct campaign as follows:
```
// Assuming the campaign slug is in the second segment
{% set slug = craft.app.request.segment(2) %}
{% set campaign = craft.campaign.campaigns.slug(slug).one() %}
```

Or, as you suggest, using a route, you would just need the last line above. Make sense?

![screen shot 2018-03-30 at 09 35 23](https://user-images.githubusercontent.com/2318222/38129081-be585776-33fd-11e8-8620-45b7b4e5ebda.png)

**Comment by putyourlightson** [comment]
Just wondering if this turned out to be a valid solution for your use case?
