### ISSUE TITLE
Sendouts fail because of invalid emails

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-campaign#40]
My sendout just reported `Failed Sending to ***@icloud.ocm failed. Please check your email settings."

Maybe instead of halting the entire sendout there could be a check that simply skip invalid emails and continue sending without requiring a manual resume?

**Comment by putyourlightson** [comment]
Yeah I guess that would make more sense. The idea behind the current functionality is that you have the opportunity to either fix the email address or remove it before carrying on. But I agree that it probably shouldn't halt the entire sendout.

**Comment by verbeeksteven** [comment]
Any update on this?

**Comment by putyourlightson** [comment]
We have made a start on this but haven't released it yet. I'll bring it to the top of the list. Have you also experienced this issue @verbeeksteven?

**Comment by verbeeksteven** [comment]
Yup, I imported a larger contact list and did an initial send and had to restart a tonnnnnnn of times due to invalid emails and stuff.

**Comment by putyourlightson** [comment]
Ah invalid emails, I might consider adding a warning if invalid emails are detected in an import.

**Comment by putyourlightson** [comment]
@stianmandarin @verbeeksteven I'm trying to figure out the best way to make this work. The reason a failed sendout stops the sending process is to give you a chance to check your email settings. Perhaps there is an issue with the credentials or you have gone over a sending quota. If the sendout kept going then you could potentially hundreds of failed sends. 

I guess the sendout could keep going unless it noticed a sendout failing X number of times in a row, which could be a config setting. Does that sounds like a reasonable solution or do you have any other suggestions?

**Comment by verbeeksteven** [comment]
As long as the sendout does not stop due to invalid emails. I am fine.

Not sending due to an error such as send quota, or email settings makes complete sense. Stopping to send due to having an invalid email is not normal.

**Comment by putyourlightson** [comment]
The strange thing is that the import job should validate all imported emails. Were the emails that failed obviously invalid addresses? Can you give an example of one, redacted of course?

**Comment by verbeeksteven** [comment]
Okay, I will do some investigation today and get back too you! Maybe there is something else going on.

**Comment by putyourlightson** [comment]
Ok, I need to clarify something. A sendout will _not_ fail simply because an email address fails. A sendout fails when it gets an error back from the mailer component. So if the connection to the SMTP server was refused for example, or if the host only allows X number of emails to be sent per hour. This is the primary reason that a sendout will stop sending, to give you an opportunity to either fix the issue, or to allow time to pass before trying to send again.

What might make sense is for the sendout to fail only after 3 failed attempts. Plus I think it would be helpful to clarify the wording of the fail message and perhaps provide more info to help troubleshoot the reason it happened.

**Comment by cromerog** [comment]
Same bug here... tried to send a 2000 email batch, had to restart the sendout like 100 times ...

**Comment by cromerog** [comment]
BTW, emails seemed valid...

**Comment by putyourlightson** [comment]
Please read my last message again, in which I said:

> A sendout will _not_ fail simply because an email address fails. A sendout fails when it gets an error back from the mailer component. So if the connection to the SMTP server was refused for example, or if the host only allows X number of emails to be sent per hour. This is the primary reason that a sendout will stop sending, to give you an opportunity to either fix the issue, or to allow time to pass before trying to send again.

It sounds like your web host has limited how many emails you are allowed to send.The next release of the plugin will change the language of the failure to help clarify this.

**Comment by putyourlightson** [comment]
Reworded in 1.7.4.
