### ISSUE TITLE
Class "craft\feedme\services\Elements" not found

### ISSUE THREAD

**Issue by migmake** [putyourlightson/craft-campaign#400]
I just broke my craft install with the last update through composer.
I can see the error in devmode:
Class "craft\feedme\services\Elements" not found

It is coming from the campaign plugin.
![CleanShot 2023-07-01 at 18 24 29@2x](https://github.com/putyourlightson/craft-campaign/assets/3531623/fd3c9bc1-e56a-4fac-8229-4b3ba819493e)

**Comment by bencroker** [comment]
Thanks for reporting this. It sounds like the the Feed Me package may have been removed without uninstalling the plugin. You can resolve this by requiring the Feed Me plugin via composer, then uninstalling it via Craft, and then removing it completely.

I’ve also fixed the issue in https://github.com/putyourlightson/craft-campaign/commit/0af8ea4e8e63cfd6169afc27cbdd26ea584da940 for the next release.

**Comment by migmake** [comment]
OK great thanks.

**Comment by bencroker** [comment]
Released in version [2.8.3](https://github.com/putyourlightson/craft-campaign/releases/tag/2.8.3).
