### ISSUE TITLE
On 'Singular' Sendout emails, the unsubscribe URL throws an error, which prevents users from unsubscribing

### ISSUE THREAD

**Issue by KasimMahroof** [putyourlightson/craft-campaign#405]
On our site, we've set up a Campaign type in which the email template outputs the 'unsubscribeUrl' twig variable.

The unsubscribe URL outputs correctly, but when a user clicks on it, they are shown this error:
![Screenshot 2023-08-11 at 15 37 39](https://github.com/putyourlightson/craft-campaign/assets/29715207/aa42e3d5-f2f1-40a0-8a74-fd42b4c2bfb3)

It would appear that the 'Mailing List ID' is not being associated with the contact when the Campaign is 'Singular'.

Ideally, the unsubscribe url would work when the user clicks on the URL.

Versions:
"craftcms/cms": "4.4.17",
"putyourlightson/craft-campaign": "2.8.3",

**Comment by bencroker** [comment]
Thanks for reporting this! Will work on a fix for it in the coming days.

**Comment by bencroker** [comment]
The issue was that singular sendouts are not sent to a mailing list, so there’s nothing to unsubscribe from. 
Fixed the error in https://github.com/putyourlightson/craft-campaign/commit/1760069460a3912685799d9d2da1c4b476264029 for the next release.

**Comment by bencroker** [comment]
Released in version 2.8.4.
