### ISSUE TITLE
Postmark Unsubscribe link

### ISSUE THREAD

**Issue by StuartMcD** [putyourlightson/craft-campaign#406]
Craft 4.4.1.6.1
Campaign 2.8.3

We're a club, using members email addresses to communicate, all good. 

Have just noted that Postmark puts an "unsubscribe" link on broadcast emails. No drama, they offer the ability to add custom unsubscribe message  - weird format is {{{ pm.unsubscribe }}} - when I throw that in template as per: 
`<a href="{{{ pm:unsubscribe }}}" style="color:grey; font-weight: bold;">Custom msg</a>`

It renders as `http://Array`

Is this a plugin, craft, twig or Postmark issue?

Postmark docs: https://postmarkapp.com/support/article/1208-how-to-add-an-unsubscribe-link

**Comment by StuartMcD** [comment]
Solved it by using a twig function:

`{% verbatim %}{{{ pm:unsubscribe }}}{% endverbatim %}`

**Comment by StuartMcD** [comment]
Solved it by using a twig function:

`{% verbatim %}{{{ pm:unsubscribe }}}{% endverbatim %}`

**Comment by bencroker** [comment]
I recommend removing Postmark’s unsubscribe link to avoid issues like https://github.com/putyourlightson/craft-campaign/issues/286, https://github.com/putyourlightson/craft-campaign/issues/304 and https://github.com/putyourlightson/craft-campaign/issues/331. 

You have to contact them directly to have it removed, as per the last paragraph in this article: 
https://postmarkapp.com/support/article/1208-how-to-add-an-unsubscribe-link
