### ISSUE TITLE
Craft 3.7 regular segment with empty condition on custom field

### ISSUE THREAD

**Issue by BAM-Dennis** [putyourlightson/craft-campaign#407]
Please provide a clear and concise description of what the bug is, including:
- Steps to reproduce the issue.
  - create segment with condition on custom field "test (plain text)"
  - add condition for: "test is equal to" value: empty
  - add condition for: "test is not equal to" value: empty
- A clear and concise description of what you expected to happen.
  - find exact amount of user count as in contact count because everyone has either empty textfield or filled textfield
  - the "is empty textfield" rule is ignored
- If applicable, add screenshots to help explain your problem.
- The plugin and Craft version numbers.
  - craft 3.7.39
  - campaign 1.24.1

**Comment by BAM-Dennis** [comment]
in other words, what do i need to put in this textfield, if want to check the "Job Title" is emtpy:
![image](https://github.com/putyourlightson/craft-campaign/assets/73120920/f3a0717f-e728-4c69-b617-6324b6cc1ed4)

**Comment by bencroker** [comment]
Thanks for reporting. I can confirm that this is happening, will look into a fix or workaround and let you know what I find.

**Comment by bencroker** [comment]
Added the `has a value` and `is empty` options to segment conditions in https://github.com/putyourlightson/craft-campaign/commit/d59fc19f6fd09366db90be39e178673bafa3882e. You can test this by running `composer require putyourlightson/craft-campaign:v1.x-dev as 1.24.3`.

**Comment by bencroker** [comment]
Released in versions 1.24.3 and 2.8.5.
