### ISSUE TITLE
Daily reports over email

### ISSUE THREAD

**Issue by efedorenko** [putyourlightson/craft-campaign#408]
Hi there! Is there a built-in way or an existing integration for sending myself daily reports on the status of the mailing lists? How many people subscribed, unsubscribed, complained, bounced, etc. Similar to what Mailchimp sends by default. Sometimes I miss important spikes of activity until I'm sending the next issue of my newsletter just because there is no transparent way to see them. Thank you!

**Comment by bencroker** [comment]
The “Mailing List Stats” dashboard widget, added in version 2.4.0, allows you to see those stats for a given time period. There is no feature to email these reports but it would be possible to do so via a custom plugin/module. Let me know if you’d like me to send you some sample code as a starting point.

<img width="418" alt="Screenshot 2023-08-21 at 08 42 36" src="https://github.com/putyourlightson/craft-campaign/assets/57572400/07ab2a48-71f9-4d55-84eb-a396122df698">

**Comment by efedorenko** [comment]
Ah, I'm still on Craft 3 and Campaign v1. Didn't realize there is a v2.

Any sample code or a starting point would be appreciated! Going to prioritize the upgrade now.

**Comment by bencroker** [comment]
You’ve missed out on over a year’s worth of updates!!
https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md

**Comment by bencroker** [comment]
Most of the logic from this can be found in the in MailingListStatsWidget class here:
https://github.com/putyourlightson/craft-campaign/blob/20044dee124ef964684176a6a101ebf9f0dc4363/src/widgets/MailingListStatsWidget.php#L95-L122

Here’s some sample code to fetch the stats and email them, which you could put into a console controller and trigger once per day using a cron job.

```php
use Craft;
use craft\helpers\Db;
use DateTime;
use putyourlightson\campaign\records\ContactMailingListRecord;

$now = new DateTime();
$contactMailingListQuery = ContactMailingListRecord::find()
    ->andWhere([
        'and',
        ['<', 'subscribed', Db::prepareDateForDb($now)],
        ['>=', 'subscribed', Db::prepareDateForDb($now->modify('-1 day'))],
    ]);

$subscribed = (clone $contactMailingListQuery)->andWhere(['subscriptionStatus' => 'subscribed'])->count();
$unsubscribed = (clone $contactMailingListQuery)->andWhere(['subscriptionStatus' => 'unsubscribed'])->count();
$complained = (clone $contactMailingListQuery)->andWhere(['subscriptionStatus' => 'complained'])->count();
$bounced = (clone $contactMailingListQuery)->andWhere(['subscriptionStatus' => 'bounced'])->count();

Craft::$app->getMailer()->compose()
    ->setTo('me@domain.com')
    ->setSubject('Daily subscriber report')
    ->setHtmlBody('...')
    ->send();
```
