### ISSUE TITLE
Contact field labels don't show up in Segments

### ISSUE THREAD

**Issue by pl-mnm** [putyourlightson/craft-campaign#409]
We are re-using and re-naming a bunch of exsiting fields for _Contacts_, but when creating a new _Segment_ the old field labels are showing in the _Add A Rule_ dropdown.

So for example we have a field called _Venue_, which we are renaming to _Address_ in Contacts, but still appears as _Venue_ in Segments. Is this a way to re-use the new label?

Craft 4.4.14
Campaign 2.8.5

Thanks in advance.

**Comment by bencroker** [comment]
Thanks for reporting this. I can confirm that it is indeed an issue and will work on a fix for it.

**Comment by bencroker** [comment]
Having looked at the source code and compared to the entry condition builder (see screenshot below), I’m not sure there is any way of achieving this natively. It looks like the original field name is always going to be used in the condition builder.

<img width="972" alt="Screenshot 2023-08-24 at 08 41 06" src="https://github.com/putyourlightson/craft-campaign/assets/57572400/70a705ca-81b3-41d8-9c6b-7aee6d586805">

You’re welcome to create a new discussion at https://github.com/craftcms/cms/discussions, tagging this issue and asking whether this could be introduced into the core condition builder functionality.

**Comment by pl-mnm** [comment]
Ok, thanks for taking a look.
