### ISSUE TITLE
Reporting Calculations Off?

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#410]
I just sent a campaign out and was watching the numbers roll into the report. After the send was complete I looked at the report in Craft Campaign, and compared it to the report I get from SendGrid and noticed that Campaign was only recording half the traffic.

In the attached screenshot, you can see the graph is showing higher numbers (these numbers jive with SendGrid) but if you look at the calculated numbers below, they are far lower, almost half as much as the chart.

For example, in the graph I see there were 902 opens within the first hour alone... yet in the calculated value below (which I assume is the aggregate) I see only 861 opens. Same thing with clicked, etc.

Is it possible there is a bug in the calculated values? 

<img width="889" alt="Screenshot 2023-08-23 at 3 50 13 PM" src="https://github.com/putyourlightson/craft-campaign/assets/3161182/b36d6efd-5d4f-4ef7-bba1-759171bae285">

**Comment by bencroker** [comment]
Can you please provide the plugin and Craft version numbers that your site is running? 

The reason I ask is that [2.1.11](https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md#2111---2022-10-18) fixed a bug in which inconsistencies could occur in campaign reports and [2.4.0](https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md#240---2023-01-12) added the `campaign/reports/sync` console command that syncs campaign reports.

**Comment by adrianjean** [comment]
Ack! — forgot to add that. Here you go:

CraftCMS Pro: 4.4.17
Campaign: 2.8.4

AHA! — I ran `php craft campaign/reports/sync` and that solved it!!

**Comment by bencroker** [comment]
Great! The stats can get out of sync, although I’ve taken measures to avoid that as much as possible. If it happens again then please do let me know and I’ll revisit it.

**Comment by adrianjean** [comment]
Will do! — Thank you!!
