### ISSUE TITLE
Import contact data from entries

### ISSUE THREAD

**Issue by robinbeatty** [putyourlightson/craft-campaign#411]
Would be really useful to be able to programmatically map data from e.g. contact details stored on an entry to campaign contacts, as we can with users.

**Comment by bencroker** [comment]
For one-time imports, using CSV imports or Feed Me is recommended. I don’t see a common use-case for importing from entries, but thanks for the suggestion.

**Comment by robinbeatty** [comment]
> 

In our application we collect contact details as entries from various headless sites. Would be great for authors to be able to 'sync' contacts from the submissions into Campaign from within the CP. – I guess (in lieu of current GraphQL support) we can ajax the contact into campaign contacts at the time of submission.

**Comment by bencroker** [comment]
This should be relatively straightforward using a custom module/plugin and the [`FormsService::createAndSubscribeContact`](https://github.com/putyourlightson/craft-campaign/blob/20044dee124ef964684176a6a101ebf9f0dc4363/src/services/FormsService.php#L153) method that the Campaign plugin provides. This is how plugins like Formie and FreeForm create contacts from form submissions, so you should be able to reference their code too, in case it’s helpful.

**Comment by robinbeatty** [comment]
Many thanks Ben!
