### ISSUE TITLE
MailerSend webhook integration

### ISSUE THREAD

**Issue by a-rbsn** [putyourlightson/craft-campaign#415]
Hey there,

We are using mailersend.com for our client as they include 3000 free emails per month — we've had an issue recently where a sendout wouldn't send because it failed an email address 3 times, I believe this contact has bounced but because we have no webhook url for mailersend it doesn't automatically mark as bounced/complained.

To save from having to manually mark a contact as bounced/complained — would it be possible to include mailersend in the webhook urls?

Best,
Andy

**Comment by bencroker** [comment]
I’m unfamiliar with MailerSend’s service, although it looks like they do have Webhook functionality for this purpose:
https://www.mailersend.com/help/webhooks
https://developers.mailersend.com/api/v1/webhooks.html

I’ll have to research their service a bit more before being able to make a decision. What has been your experience so far?

In case this is something you need urgently, this can be achieved with a custom module/plugin by replicating some of the functionality in the [`WebhookController`](https://github.com/putyourlightson/craft-campaign/blob/develop/src/controllers/WebhookController.php) class.

**Comment by a-rbsn** [comment]
@bencroker thanks for your response — we're just using this for a small client because of their generous free tier, but so far so good! It's only for one email per month to a small list so not _super_ urgent, it would be great if it could be added, if not I'll look into adding the custom module.

**Comment by bencroker** [comment]
I’ll keep this feature request open, but you’re the first person to ever ask for it so in the meantime it is low priority.

**Comment by janhenckens** [comment]
We're probably going to propose Campaign + MailerSend for an upcoming project as well. We've been testing the service on a couple of smaller projects as well and no issues so far.

We still have to build the site so we don't currently have this issue but I wanted to put a vote down for MailerSend :)

Note: I also created a Mail Adapter for the service, soon to be on the store https://github.com/studioespresso/craft-mailersend

**Comment by bencroker** [comment]
Sounds good, @janhenckens. I’ll prioritise this and aim for a release soon.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/77b1c0b6d05097fca47824f0bfdbfe6ccbb2bf5b for the next release.

You can test this by running `composer require "putyourlightson/craft-campaign:dev-feature/mailersend-webhook as 2.10.0"`.

**Comment by bencroker** [comment]
Released in [2.10.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.10.0).

**Comment by janhenckens** [comment]
Thanks @bencroker!

**Comment by a-rbsn** [comment]
Really appreciate you implementing this @bencroker
