### ISSUE TITLE
Wrong status for sendouts in "Scheduled" tab

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-campaign#416]
It seems that the status of a Scheduled sendout is not updating in the "Scheduled" tab after the campaign has been sent out. Filtering works for the "Sent" (1 result, as expected) and "Pending" (0 results, as expected) stati, as well as the detailed view of the sendout.

- Craft CMS 3.7.39
- Campaign 1.24.3

![Screenshot 2023-09-19 at 13 22 07](https://github.com/putyourlightson/craft-campaign/assets/19146752/0b0b42a9-7cbc-41d5-8e14-4dd27ba41eff)

![Screenshot 2023-09-19 at 13 22 32](https://github.com/putyourlightson/craft-campaign/assets/19146752/324d6914-90d2-447c-ae0d-7ccc2f3dedab)

![Screenshot 2023-09-19 at 13 22 38](https://github.com/putyourlightson/craft-campaign/assets/19146752/fc9564ce-1855-48cb-b4f3-5d31bec70772)

![Screenshot 2023-09-19 at 13 22 17](https://github.com/putyourlightson/craft-campaign/assets/19146752/f1203fe6-b809-483d-97f2-b53fc281aaaf)

**Comment by bencroker** [comment]
Thanks for reporting this. Fixed in https://github.com/putyourlightson/craft-campaign/commit/9ecf7574eb5477c4975b585f9520c9e911cd2358 and released in version 1.24.4.

**Comment by martinhellwagner** [comment]
@bencroker 

Thanks for the quick reply, and the fix! 🚀
