### ISSUE TITLE
Filtering in campaigns in sendouts not working in

### ISSUE THREAD

**Issue by joostclevis** [putyourlightson/craft-campaign#419]
When you go to sendouts, choose new sendout, click on Choose a campaign and then filter (for example pending campaigns) the filter shows all the campaigns in stead of the pendig campaigns.

![Scherm­afbeelding 2023-09-28 om 19 53 12](https://github.com/putyourlightson/craft-campaign/assets/58426012/32eeae95-a9b8-446d-9ccf-054726b91ee2)

Craft: 3.9.4
Campaign: 1.24.4

**Comment by bencroker** [comment]
Thanks for reporting this, I can confirm that it is indeed a bug. I’ll work on a fix for the next release.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/8e34bf4c14db67935e6a2278aeca402748802b39 for the next release.

**Comment by bencroker** [comment]
Released in version [2.9.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.0) and [1.24.5](https://github.com/putyourlightson/craft-campaign/releases/tag/1.24.5).
