### ISSUE TITLE
Saving Settings -> Contact Settings, Deletes Transport Type API Key Setting

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#421]
When I save the "Contact Settings" page `/admin/campaign/settings/contact`

It clears out the "Transport Type", API key setting under "Email Settings" `admin/campaign/settings/email`

I am using an environment variable for my API key, and SendGrid as my Transport Type.

Versions:
- CraftCMS:  4.5.6.1
- Campaign:   2.8.7
- PHP:  8.1.2
- MySQL:  8.0.30

**Comment by bencroker** [comment]
Please always provide the plugin version number in bug reports.

**Comment by adrianjean** [comment]
Ack! — apologies, I totally forgot. Added to the OP.

**Comment by bencroker** [comment]
Thanks! Fixed in https://github.com/putyourlightson/craft-campaign/commit/0497cadfd7dfa10d59f9a4e2d37c1e75bd55eb7c for the next release.

**Comment by bencroker** [comment]
Released in version [2.9.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.0).
