### ISSUE TITLE
Possibility to set Priority for SendoutJobs

### ISSUE THREAD

**Issue by mnlmaier** [putyourlightson/craft-campaign#422]
Hi, thanks for the nice work on the Plugin.

First of all: I am not quite sure if this question is more of a Support Request or a Feature Request, but here goes.

We are running the Campaign plugin in a very large Craft instance with dozens of Sites. The project includes several scheduled tasks which import large chunks of data, which in turn trigger several quite extensive Caching Jobs.

The Campaign plugin itself is running smoothly, no complaints there. In the full project context though, we have an issue with delayed sendouts, which are caused by the (admittedly pretty busy) Queue being occupied with running all other tasks — which absolutely makes sense from a logical standpoint, but is not the most Editor-friendly solution for our content team, which would prefer for sendouts to happen (ideally) instantly or within a reasonable timespan.

Once we are forcing a higher priority to the Job directly in the database, obviously the Sendout is triggered immediately.

What I am missing is basically a way to set a default priority for SendoutJobs (https://github.com/putyourlightson/craft-campaign/blob/18f056c5d1f032be38fb09a6c682a19161dc3d35/src/services/SendoutsService.php#L158).

Is there a way to achieve this, or might this be a relevant feature to be implemented in the near future?

Thanks in advance!

**Comment by bencroker** [comment]
That sounds like a reasonable feature request, I'll add it for the next release.

**Comment by mnlmaier** [comment]
@bencroker Awesome, thanks for the quick response! Any ETA on the next release? :)

**Comment by bencroker** [comment]
Likely some time this month.

**Comment by bencroker** [comment]
Added the `sendoutJobPriority` config setting that allows changing the priority of sendout jobs in https://github.com/putyourlightson/craft-campaign/commit/3c0a201c048f2f93c62b295b081a108f6210d0ab. 

You can test this by running `composer require "putyourlightson/craft-campaign:dev-develop as 2.9.0"`.

**Comment by bencroker** [comment]
Released in version [2.9.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.0).

**Comment by mnlmaier** [comment]
Thanks a lot!
