### ISSUE TITLE
Import from Group: Request missing required body param

### ISSUE THREAD

**Issue by apitel** [putyourlightson/craft-campaign#425]
Hi Ben,

I'm using Campaign 2.9.1. I am encountering an issue where I am unable to import from a Craft User Group. I can import from a .csv without issue, but it throws the following error when trying to import from Craft User Group: "Bad Request: Request missing required body param"

I am keeping it very simple and there is only one user in the User Group. Below is a dump from the error log. 

Any help you can provide on this issue would be greatly appreciated. Thank you!

yii\web\BadRequestHttpException: Request missing required body param in /Users/apitel/Sites/mpe/vendor/craftcms/cms/src/web/Request.php:913
Stack trace:
#0 /Users/apitel/Sites/mpe/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php(300): craft\web\Request->getRequiredBodyParam('assetId')
#1 /Users/apitel/Sites/mpe/vendor/putyourlightson/craft-campaign/src/controllers/ImportsController.php(187): putyourlightson\campaign\controllers\ImportsController->_getImportModelFromParams('field_')
#2 [internal function]: putyourlightson\campaign\controllers\ImportsController->actionImportUserGroup()
#3 /Users/apitel/Sites/mpe/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /Users/apitel/Sites/mpe/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#5 /Users/apitel/Sites/mpe/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('import-user-gro...', Array)
#6 /Users/apitel/Sites/mpe/vendor/craftcms/cms/src/web/Application.php(304): yii\base\Module->runAction('campaign/import...', Array)
#7 /Users/apitel/Sites/mpe/vendor/craftcms/cms/src/web/Application.php(607): craft\web\Application->runAction('campaign/import...', Array)
#8 /Users/apitel/Sites/mpe/vendor/craftcms/cms/src/web/Application.php(283): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#9 /Users/apitel/Sites/mpe/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#10 /Users/apitel/Sites/mpe/public/index.php(12): yii\base\Application->run()
#11 /Users/apitel/.composer/vendor/laravel/valet/server.php(234): require('/Users/apitel/S...')
#12 {main}

**Comment by bencroker** [comment]
Thanks for the bug report. I can confirm that this is indeed an issue and should be able to release a fix in the next day or two.

**Comment by bencroker** [comment]
I’ve fixed this issue in https://github.com/putyourlightson/craft-campaign/commit/321478b644656296f9707f410f3243ec4366237f for the next release.

You can test this by running `composer require "putyourlightson/craft-campaign:dev-develop as 2.9.2"`.

**Comment by bencroker** [comment]
Released in [2.9.2](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.2).

**Comment by mathieuser** [comment]
Hi Ben, I've stumbled on this error as well. I've updated, but I get another error now when trying to sync users: I'm getting:

`foreach() argument must be of type array|object, null given`

This seems to happen in the foreach loop where firstName and lastName are being requested...
Is this something you can replicate, or might this be a bug on my side?

Thanks!

**Comment by bencroker** [comment]
Since this issue is closed and may be different, please create a new issue with more details and a full stack trace from the logs, if there is one.
