### ISSUE TITLE
Using emojis as subject breaks the sendout campaign

### ISSUE THREAD

**Issue by tomfischerNL** [putyourlightson/craft-campaign#426]
When using emojis in the subject line, like this:
Subject line here ☕ 🌿 😌

And activating the sendout gives an error:
![Error](https://github.com/putyourlightson/craft-campaign/assets/2330195/f23996c3-0d3e-47d6-bd7b-231feec076b1)

Craft version: 4.5.5
Campaign version pro: 2.9.1

**Comment by tomfischerNL** [comment]
It seems, that when updating the sending time, like 4 minutes ahead, that it works. So only if the time has passed, it fails.

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-campaign/commit/5ff819491a3ab5c95de09c355dace997f6326313 for the next release.

You can test this by running `composer require "putyourlightson/craft-campaign:dev-develop as 2.9.2"`.

**Comment by bencroker** [comment]
Released in [2.9.2](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.2).

**Comment by tomfischerNL** [comment]
Thanks @bencroker  ;)
