### ISSUE TITLE
Return value must be of type string, null returned

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#429]
I am seeing this error `putyourlightson\campaign\helpers\SendoutHelper::decodeEmojis(): Return value must be of type string, null returned` when visiting /campaign/sendouts

It is happening after updating to 2.9.2

Thanks

**Comment by bencroker** [comment]
Thanks for reporting this. Fixed in https://github.com/putyourlightson/craft-campaign/commit/cabd214ef9ab165c44248fce55c416c99b0c3339 and released in [2.9.3](https://github.com/putyourlightson/craft-campaign/releases/tag/2.9.3).

**Comment by philipboomy** [comment]
Boom that was fast :P Its working now.
