### ISSUE TITLE
Fail to send campaign

### ISSUE THREAD

**Issue by StuartMcD** [putyourlightson/craft-campaign#430]
Using the latest Craft Pro 4.5.9 and Campaign 2.9.1

Is it my understanding that when sending to a a full list ~250 recipients,  if there's a malformed email or maybe the email account doesn't exist, the system tries 3 times then fails and stops sending the rest of the emails.

Should it continue to sending to the remainder of the list or is this a 'feature' and not a bug?

**Comment by StuartMcD** [comment]
More info, I've found the problematic email, they've previously 'unsubscribed' via Postmark. 

Unsure of the sending/hand-off methodology but shouldn't CM just take the feedback and 'simply' skip onto the next one?

**Comment by bencroker** [comment]
> Should it continue to sending to the remainder of the list or is this a 'feature' and not a bug?

This is indeed a feature. If the email service provider is unwilling to send an email then there are various things that could be wrong and it is safer to stop that to keep hammering it with requests that will all fail.

You can, however, increase the number of failed attempts to send to contacts that are allowed before failing the entire sendout, using the [`maxSendFailuresAllowed`](https://github.com/putyourlightson/craft-campaign/blob/cabd214ef9ab165c44248fce55c416c99b0c3339/src/config.php#L90) config setting.

Have you set up webhooks to handle bounce and complain notifications for Postmark as explained at https://putyourlightson.com/plugins/campaign#bounce-and-complaint-handling ?

See also the note about contacting Postmark directly to have its unsubscribe link removed.

**Comment by StuartMcD** [comment]
Things you learn. 
Done the bounce/complain/unsubscribe thing so thats squared away. 

The campaign.php /config things new, hopefully it will help, thx.
