### ISSUE TITLE
Add TTR for ImportJob

### ISSUE THREAD

**Issue by vandres** [putyourlightson/craft-campaign#432]
We are having a big list of contacts to import (~20k). The default queue runtime is not enough, to import all of them.

Could you please allow to configure the TTL for the ImportJob or make it work in batches?

**Comment by bencroker** [comment]
This sounds more like an issue with the queue runner you are using. Are you able to run queue jobs via a daemon or console command?

**Comment by vandres** [comment]
Our queue runs via cron and has a default TTL of 300

**Comment by bencroker** [comment]
Hmm I wonder what the issue could be, in that case. The TTR should only come into effect when a queue job becomes unresponsive.

**Comment by vandres** [comment]
I found this cookbook regarding the topic. https://servd.host/docs/increasing-crafts-queue-ttr

We really would like to avoid increasing the TTL of all our jobs. I think you're already using the "proper" way, for the SendoutJob

**Comment by bencroker** [comment]
I’ve added `importJobTtr` and `syncJobTtr` settings in https://github.com/putyourlightson/craft-campaign/commit/01368bd17bcb57fa1c03006be528afe9317f35b3.

You can test this by running `composer require "putyourlightson/craft-campaign:dev-feature/import-sync-job-ttr as 2.10.0"`.

**Comment by vandres** [comment]
That was quick. Thank you very much!

**Comment by bencroker** [comment]
Sure thing! Let me know if that solves it for you.

**Comment by vandres** [comment]
The importTtr configuration is working. Excuse the German.

In my opinon, I would not like retrying this long running job. If it fails once, it will fail the other times, too. Maybe...the retry count should be decoupled from the sendout retry count.

![grafik](https://github.com/putyourlightson/craft-campaign/assets/1436383/630abb5c-8bae-4cef-8c12-3b19a663dff0)

**Comment by bencroker** [comment]
Yes, you’re probably right. I’ve disallowed retrying import and sync jobs in https://github.com/putyourlightson/craft-campaign/commit/dd5dcf3af12af0385728a2965e0f35ab753a35f2

The next major version of Campaign will use queue job batching, which Craft introduced in version [4.4.0](https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#440---2023-03-08).

**Comment by bencroker** [comment]
Released in [2.10.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.10.0).
