### ISSUE TITLE
Follow-Up: Possibility to set Priority for SendoutJobs in Craft 3 Projects

### ISSUE THREAD

**Issue by mnlmaier** [putyourlightson/craft-campaign#433]
Hi,

I'm referring to issue https://github.com/putyourlightson/craft-campaign/issues/422, which resulted in your implementation of queue job priorities in Campaign v2. Thank you so much for the prompt response and implementation!

We are now encountering a similar issue in a Craft 3 project that, for various reasons, cannot be updated to Craft 4 in the near term. An upgrade is on our agenda, but it is not scheduled until next year.

As we are now planning the best way to proceed, I wanted to check in with you regarding the extent of support for Campaign v1. Am I correct in assuming that further updates to Campaign v1 are now limited to bug fixes only, and that, for this specific project, creating a fork / composer patch on our end will be necessary?

Thanks in advance and all the best!

**Comment by bencroker** [comment]
Normally this would not be possible, but I’ve made an exception for you and added this in https://github.com/putyourlightson/craft-campaign/commit/a675bf37fd7a3a9b8724482d612371fec402ca2d for the next release.

You can test this by running `composer require "putyourlightson/craft-campaign:v1.x-dev as 1.25.0"`.

**Comment by mnlmaier** [comment]
@bencroker Awesome! :) Thanks a lot. Will test this asap!

**Comment by mnlmaier** [comment]
@bencroker Reporting back: Works like a charm. Thanks for the quick implementation, very much appreciated.

**Comment by bencroker** [comment]
Thanks for confirming! Released in [1.25.0](https://github.com/putyourlightson/craft-campaign/releases/tag/1.25.0).
