### ISSUE TITLE
[1.x] - Provide a `cp.campaigns.edit.details` hook

### ISSUE THREAD

**Issue by khalwat** [putyourlightson/craft-campaign#434]
There's an issue with the Campaign integration for SEOmatic for Craft 3.x:

https://github.com/nystudio107/craft-seomatic/issues/1377

The mistake is mine; the event `EVENT_DEFINE_SIDEBAR_HTML` doesn't exist until Craft 3.7.x -- but in order to fix it either:

1. I need to remove the sidebar preview entirely for the Campaign plugin if they are running Craft CMS 3.x earlier than 3.7.x
2. You need to add a `cp.campaigns.edit.details` template hook

If you do decide to add it, you'd want something like what Craft does for Entries:

https://github.com/craftcms/cms/blob/v3/src/templates/entries/_edit.html#L146

...and add `{% hook 'cp.campaigns.edit.details' %}` at the bottom of your `{% block details %}`:

https://github.com/putyourlightson/craft-campaign/blob/v1/src/templates/campaigns/_edit.html#L184

**Comment by bencroker** [comment]
No plans to add the hook. The issue is that you’re using an event without conditionally checking that it exists, which you already know ;)
