### ISSUE TITLE
Data in All Contacts table and the preferences of the actual contact is not consistent

### ISSUE THREAD

**Issue by D3VM4TT** [putyourlightson/craft-campaign#435]
Hi,

We are currently using the Campaign plugin for one of our clients.

Users can sign up to a campaign via a form rendered on our websites front end.

The form has several preferences the user can enter which we use as conditions for sending emails via the campaign plugin.

We are experiencing a issue where the data being displayed in the /admin/campaign/contacts/view?source=* contacts table and for a specified user and the data in the preferences for the user admin/campaign/contacts/58116#tab02--preferences are not the same.

See attached screenshots of the table and the user preferences for an example.

![Screenshot_20231113_105538-1](https://github.com/putyourlightson/craft-campaign/assets/88676927/d85443ef-f273-442f-8227-0d44dc61d1a1)

![Screenshot_20231113_105636](https://github.com/putyourlightson/craft-campaign/assets/88676927/d2229cd1-9606-4bab-96e5-e754932e8540)

```
"craftcms/cms": "4.5.5",
"putyourlightson/craft-campaign": "2.8.6",
```

**Comment by bencroker** [comment]
That sounds like it may be caused by query caching on Craft’s side. Can you try saving the contact in the CP and then check whether the index view is updated?

**Comment by bencroker** [comment]
Any update on this, @D3VM4TT?

**Comment by bencroker** [comment]
I cannot replicate this using Campaign 2.9.4 and Craft 4.5.10. If saving the contact doesn’t solve the issue then please update to the latest versions, on which it should not be an issue.
