### ISSUE TITLE
Certain custom fields not saving as contact preferences.

### ISSUE THREAD

**Issue by D3VM4TT** [putyourlightson/craft-campaign#436]
Hi, we are currently using the Campaign Plugin for one of our clients & we have noticed some of the custom fields are not saving.

Please provide a clear and concise description of what the bug is, including:
**- Steps to reproduce the issue.**
We currently have a Job Notification sign up form that is posting to `campaign/forms/subscribe`. Most of the fields are saving and being reflected in the contact preferences, however there are currently two fields that are not being saved.

One of the fields being the Job Sectors field. This is a Multi-select field with the handle of `jobSectors`.
Currently we are rendering the checkbox fields in the form as per below:

```
<div class="form-checkbox">
		<label>
			<span>Administration</span>
			<input class="form-field " type="checkbox" name="field[jobSectors][]" value="administration" data-label="Administration">
		</label>
	</div>
```
```
<div class="form-checkbox">
		<label>
			<span>Advice and information</span>
			<input class="form-field " type="checkbox" name="field[jobSectors][]" value="adviceAndInformation" data-label="Advice and information">
		</label>
	</div>
```

This same field is added to the Campaign Contacts Preferences.

We have several other Multi-Select fields rendered in the same way in Sign Up form and the are all saving as expected - however the the selected `jobSectors` are not being saved to the contacts preferences for some reason.

I have checked the payload being sent to `campaign/forms/subscribe` & I can confirm the jobSectors fields are included in the form-data as per below:

```
feld[jobSectors][]: administration
field[jobSectors][]: adviceAndInformation
field[jobSectors][]: advocacy
field[jobSectors][]: artsCultureAndHeritage
field[jobSectors][]: campaigningAndFundraisin  

```
Front end form with Job Sectors
![Screenshot_20231113_115325](https://github.com/putyourlightson/craft-campaign/assets/88676927/dd7b59a9-3ff9-4223-b07d-46f5050a0bff)

Job Sectors field added to contact preferences
![Screenshot_20231113_115402](https://github.com/putyourlightson/craft-campaign/assets/88676927/daed1a9b-526e-4070-bbab-a6fbb6e95b29)

jobSectors field in Craft
![Screenshot_20231113_115439](https://github.com/putyourlightson/craft-campaign/assets/88676927/e95d2077-982e-417c-88a5-5d18a25c6ea1)

jobSectors field in contact prefences
![Screenshot_20231113_115510](https://github.com/putyourlightson/craft-campaign/assets/88676927/f4aad903-6a01-4bc5-b24b-90a1e00cb46f)

```
		"putyourlightson/craft-campaign": "2.9.4",
		"craftcms/cms": "4.5.5",
```

**Comment by bencroker** [comment]
Are you sure that the field name is correct? I would think that it should be `fields[jobSectors][]`, so `fields` instead of `field`.

**Comment by D3VM4TT** [comment]
So right. Cant believe I missed that. Thanks @bencroker
