### ISSUE TITLE
Should not show 'Unsaved Changes' after sending tests

### ISSUE THREAD

**Issue by bossanova808** [putyourlightson/craft-campaign#437]
Hey Ben

Very minor but I think it would be much better UX if Craft didn't show a 'showing unsaved changes' warning every time you send an email test (i.e. when there are no other changes).

Not sure if this is something you can control, though!  But I do know it confuses our day to day editors each time the send a test but have not made other changes...

Hope you're well!

**Comment by bencroker** [comment]
Thanks, I'll take a look.

**Comment by bencroker** [comment]
Unfortunately, this is currently not possible to prevent. Craft checks whether the value of the serialized form has changed, and since the test email field exists within the form, its value is included in the condition.
Reference: https://github.com/craftcms/cms/blob/b8f30d07cd487c5fbaa140743816e6eb7020e55d/src/web/assets/cp/src/js/ElementEditor.js#L1164C11-L1171

You could create a feature request for this behaviour to be changed in Craft core, so that parts of the DOM can be marked as ignorable, if you like.

**Comment by bossanova808** [comment]
@bencroker Does Brandon's answer work for you - https://github.com/craftcms/cms/discussions/13936#discussioncomment-7581688?

**Comment by bencroker** [comment]
Yes, I should be able make that work with minimal changes, thanks!

**Comment by bencroker** [comment]
Implemented in https://github.com/putyourlightson/craft-campaign/commit/0df879dd11bf2b8add9e9c3e9631d1938b6658ba for the next release. For the record, that was only happening when adding or removing test contacts, not when sending a test. I generally add default test contacts, which I why I rarely noticed the issue.

You can test this by running `composer require "putyourlightson/craft-campaign:dev-develop as 2.10.0"`.

**Comment by bencroker** [comment]
Released in [2.10.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.10.0).

**Comment by bossanova808** [comment]
Thanks Ben, appreciated, working as expected/desired now.  

However, makes me notice a little bug - based on the text here I have been leaving this blank:

![image](https://github.com/putyourlightson/craft-campaign/assets/731309/74bb8aa7-8f17-4bad-985a-72822159efd1)

However this always results in:

![image](https://github.com/putyourlightson/craft-campaign/assets/731309/ad629d6d-259e-4528-8dac-4bb8003a8f22)

And the message 'At least one contact must be selected' when hitting the Send Test button (as one would expect).  

That should be pre-filled in with my details, shouldn't it?

**Comment by bencroker** [comment]
Yes, it should. That was only an issue on the campaign edit page but not on the sendout preview page, it seems.

Fixed in https://github.com/putyourlightson/craft-campaign/commit/038111ec7625d001fa92caf3c64ae98e4695a816 for the next release.

**Comment by bencroker** [comment]
Released in [2.11.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.11.0).
