### ISSUE TITLE
Is there an inbound end-point to create/update a contact?

### ISSUE THREAD

**Issue by sg-modlab** [putyourlightson/craft-campaign#442]
Please provide a clear and concise question. We are diligent about documentation, so please check whether your question is answered by the plugin docs before submitting.

Tried to find in docs and seems a custom module would be needed, but thought I'd check in case I missed something. Is there a backed in end-point that I could say tap into with Zapier that would allow me to integrate my contact database to create/update contacts in Campaign? I'd like to be able to offer managing different contact data that would be leveraged in segments without having to log in to the website to manually do it.

Thanks,
Seth

**Comment by bencroker** [comment]
There is no API endpoint for creating contacts, you are correct that you’d a custom module/plugin to handle this. It might be possible to use Feed Me to import contacts but I’m not sure that will meet your requirements of a public API.
