### ISSUE TITLE
Subscribing contacts through a console command

### ISSUE THREAD

**Issue by mathieuser** [putyourlightson/craft-campaign#443]
Hey Ben,

For a website I'm developing I'd like to automatically populate a list of subscribers on a yearly basis (These contacts are renters, and I need a auto populated list of renters who's contract expire before the end of the year). I would do this by making a console command and have this command called each year with a cron job. 

I have set up all the logic, but I cant find the needed info on the createAndSubscribeContact function. It looks like Craft::$app->getRequest()->getBodyParam('fields') and Craft::$app->getRequest()->getReferrer() are not available in the console, which is logical. Is there a way around this?

Thank you!

**Comment by bencroker** [comment]
The `FormsService::createAndSubscribeContact` method should work, provided you pass in the `$fieldValues` parameter as an array, which will prevent the field values being fetched from a web request. Let me know if that works for you.
