### ISSUE TITLE
Filtering is returning all contacts and not a filtered results

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-campaign#446]
Apologies if this will double post. My first issue failed to submit I think.

When I got to contacts and then click the filtering icon in the search box and select "Latest Activity" and set to "Today" and hit "Apply" it fires an Ajax request but returns all results. It does not filter the contacts.

Thanks.

**Comment by bencroker** [comment]
Thanks for reporting this. Fixed in https://github.com/putyourlightson/craft-campaign/commit/57821052b816ba315048a52a854031165f32a245 and released in [2.12.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.12.0).
