### ISSUE TITLE
Enhance anti-spam measures by supporting services like Cloudflare Turnstile

### ISSUE THREAD

**Issue by iparr** [putyourlightson/craft-campaign#447]
I'm aware that two anti-spam solutions exist for this plugin: _reCAPTCHA_ and your own _[Snaptcha](https://putyourlightson.com/plugins/snaptcha)_ plugin.

However, ideally I would like to use a third service: Cloudflare Turnstile (for which there exists a [corresponding plugin](https://github.com/billmn/craft-turnstile)). I've been able to get this working for the [Contact Form plugin](https://github.com/craftcms/contact-form) but not with the Campaign registration / sign-up form. I had to write some custom module code (not ideal) and wondered if similar was possible when used with Craft Campaign? I was wondering if anti-spam measures on Craft Campaign could be broadened?

Advantages of Turnstile over reCAPTCHA:
- It isn't Google so it's more privacy-friendly
- It doesn't force unwanted "protected by reCAPTCHA" banners onto every page used

<small>(both of these two are dealbreakers in the EU, imho)</small>

Advantages of Turnstile over Snaptcha plugin:
- Cloudflare provide a nice interface to monitor / analyse spam and address any false-positives
- It's free. Avoid any plugin licensing costs (sorry guys, budget is tight on some projects!)
- Widening anti-spam solutions may be useful as the sophistication of spammers evolves (remember when a honeypot would work wonders? Good times!)

Context: I've ran Campaign sign-up forms on websites without any anti-spam measures and it's not been problematic. However I launched a small/medium website recently and the quantity of unconfirmed spammy sign-ups has been substantial and so a solid anti-spam measure is no-longer optional.

**Comment by bencroker** [comment]
That’s a great idea, I’ll consider adding this in Campaign v3.

In the meantime, here’s some sample code to get you started integrating the Turnstile plugin with the subscribe form.

```php
use putyourlightson\campaign\controllers\FormsController;
use yii\base\ActionEvent;
use yii\base\Event;

Event::on(FormsController::class, FormsController::EVENT_BEFORE_ACTION,
    function(ActionEvent $event) {
        if ($event->action->id === 'subscribe') {
            $event->isValid = Turnstile::getInstance()->validator->passes();
        }
    }
);
```

**Comment by iparr** [comment]
My module-fu is pretty weak, but I think I've implemented your suggestion and this is working well.

Thanks for your help. Glad to hear further integration is being considered.

**Comment by bencroker** [comment]
Added Turnstile support in [2.16.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.16.0) and [3.2.0](https://github.com/putyourlightson/craft-campaign/releases/tag/3.2.0).
