### ISSUE TITLE
MailerSend webhooks

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-campaign#448]
Hi, 

I have a hard time setting up the webhooks in mailersend

In mailersend I've configured the webhooks to recieve all webhook events the following way: 

<img width="851" alt="Bildschirmfoto 2024-01-16 um 13 16 16" src="https://github.com/putyourlightson/craft-campaign/assets/145828/1d0915c4-8f5a-4f7f-9166-31512396eda3">

In Campaign I've added the signing secret of sendermail: 

<img width="843" alt="Bildschirmfoto 2024-01-16 um 13 18 28" src="https://github.com/putyourlightson/craft-campaign/assets/145828/9319864c-d2c8-4bfb-a38f-b4a18fbcaa44">

Checking the logs I see the following errors: 

	[2024-01-16 12:23:12] Event type `activity.opened` not found.
	[2024-01-16 14:05:25] Event type `activity.soft_bounced` not found.
	[2024-01-16 14:05:37] Event type `activity.soft_bounced` not found.
	[2024-01-16 14:07:13] Event type `activity.opened_unique` not found.
	[2024-01-16 14:07:17] Event type `activity.soft_bounced` not found.
	[2024-01-16 14:17:40] Event type `activity.sent` not found.

These are the tests I've sent from mailersend. 

All webhook events seem to be blocked or not found. 

How can I debug further? 

PHP version	8.2.13
OS version	Linux 3.10.0-962.3.2.lve1.5.70.el7.x86_64
Database driver & version	MariaDB 10.5.23
Image driver & version	Imagick 3.7.0 (ImageMagick 7.1.1-19)
Craft edition & version	Craft Pro 4.5.13
Yii version	2.0.48.1
Twig version	v3.4.3
Guzzle version	7.8.1
Plug-ins
Campaign	2.12.0
MailerSend 	 1.0.1

Edit: added MailerSend Plugin Version

**Comment by bencroker** [comment]
Only `activity.spam_complaint` and `activity.hard_bounced` are registered by Campaign. The other activities are not used and can be removed from your MailerSend events list.

**Comment by outline4** [comment]
Ok thanks a lot. That works! 

Is that in the docs somewhere?

**Comment by bencroker** [comment]
Only this, which is a bit vague, but implies hard bounces and spam complaints. The other events are not required, since Campaign already tracks opens, clicks, etc.

> Campaign includes webhooks to handle bounce and complain notifications for the following services

Source: https://putyourlightson.com/plugins/campaign#bounce-and-complaint-handling

**Comment by outline4** [comment]
Ok, thanks!

**Comment by outline4** [comment]
I ran into this issue again, but this time, even I knew that there's a catch, I coudn't find it in the docs. 

**Campaign includes webhooks to handle hard bounce and spam complain notifications...**

It would be nice if this was somewhere in the docs.

**Comment by bencroker** [comment]
Thanks, I improved the wording under https://putyourlightson.com/plugins/campaign#bounce-complaint-handling

**Comment by outline4** [comment]
thanks a lot! 

btw: I love campaign and since mailchimp "code your own" templates don't work with the free tier, I try to move as many to campaign as possible! 

cheers  
Stefan

**Comment by bencroker** [comment]
Glad to hear it, and let me know if you have any suggestions for improvement.

**Comment by outline4** [comment]
Hi Ben, 

The only thing that my customers don't really get, is the difference between campaigns and sendings.  
IMHO they could be combined. 

If that's technically not feasible, at least the title and subject in the sending should come from the campaign. Having to give it a second name feels awkward and unnecessary. 

Maybe it would be enough if you put a button: "send this campaign" and forward the user to the sending tab with the campaign already pre-filled. I guess that would help a lot. 

CHeers  
Stefan

**Comment by bencroker** [comment]
> The only thing that my customers don't really get, is the difference between campaigns and sendings.

This is something I carefully considered when planning out the plugin initially. By having “campaigns” _and_ “sendouts”, the process of creating content (the campaign) is distinct from the process of sending it out (the sendout). The benefit of this is that a campaign can be sent multiple times (once per sendout), which would otherwise not be possible.

> If that's technically not feasible, at least the title and subject in the sending should come from the campaign.

That is what already happens when the `Show Title Field` setting is disabled.

![screenshot-GX9nj6fm@2x](https://github.com/user-attachments/assets/4d367a01-da4c-4be3-baa8-e7c43cf636ed)

Also, FYI, the quickest way to save and send a campaign is to click on the `Save and create new regular sendout` menu item, which creates a sendout pre-populated with the campaign.

![screenshot-RTCjhSMB 2@2x](https://github.com/user-attachments/assets/a750c3a3-bc28-4ab1-8c65-7406ae2bf82e)

**Comment by outline4** [comment]
ohh... so everything is there 😊

thanks for pointing out these two things!

**Comment by outline4** [comment]
Just one more thing: 

It would be nice to have an internal spam prevention (something like a honeypot field) that doesn't require an external subscription. 

P.s. I've just eliminated the title field in the settings and created a new sendout via the save dialog: it's just perfect. It's a bit hidden, but once you know it, it's clearly the way to go!

**Comment by bencroker** [comment]
Honeypots are practically useless at protecting against spam these days. Campaign works seamlessly with [Snaptcha](https://putyourlightson.com/plugins/snaptcha) and supports both reCAPTCHA and Turnstile, as well as making it possible to add other external services.

**Comment by outline4** [comment]
Ok, thanks for the info. I was looking for a non API approach, but I guess you are right. 

There's one more thing that would facilitate the sending of a newsletter:

If there was a "Default Mailinglist" Option within the "Campaign Types", that would help a lot. At least in our case.   
Much like the default test contacts, that is also very helpful.

**Comment by bencroker** [comment]
> If there was a "Default Mailinglist" Option within the "Campaign Types", that would help a lot.

Can you please explain what you mean?

**Comment by outline4** [comment]
Don’t they say an image says more than 1000 words? 

<img width="1004" alt="default-mailinglist" src="https://github.com/user-attachments/assets/6591c669-1283-4a95-8251-2a8be9eda736">

**Comment by bencroker** [comment]
Thanks for the image! A default mailing list isn’t feasible, since the mailing list and campaign are selected in the same step when creating a sendout (unlike the test send field, which only exists on the sendout preview page).

![screenshot-bqF7nlXE 2@2x](https://github.com/user-attachments/assets/02dd119b-156e-4575-9395-3ecc99d41adc)

**Comment by outline4** [comment]
I thought of it as when selecting "save and create new sendout" from the campaign. So it would fill out the campaign and the mailinglist in one go. 

It could also be possible to prepopulate the "To" Mailinglist when choosing a campaign within a sendout (I wasn't after that). 

Sometimes clients are stupid and if things don't need to be manually chosen it helps them a lot (and I don't get emails or phone calls). Particularly in projects which changes staff a lot...

**Comment by bencroker** [comment]
I know what you mean but it doesn’t feel like a good fit to me with the current sendout creation flow.

**Comment by outline4** [comment]
ok, no worries. 
Maybe it's something for the future. 

Anyways: I love campaign. it's a really great plugin! 
In combination with mailersend it's much more affordable and streamlined than mailchimp.
