### ISSUE TITLE
Welcome: Image overlaps link

### ISSUE THREAD

**Issue by tricki** [putyourlightson/craft-campaign#449]
Please provide a clear and concise description of what the bug is, including:
- Install the plugin
- On the welcome page (`/admin/campaign/welcome`), try to click the "Plugin Settings"
- Nothing happens

Craft CMS Pro 4.6.0
Campaign 2.12.0

Screenshot when inspecting in Chrome, the cursor is hovering the link:

<img width="1336" alt="image" src="https://github.com/putyourlightson/craft-campaign/assets/523154/ce204dca-a717-4e6d-a7c5-1ba0313ccbf3">

**Comment by bencroker** [comment]
Thanks for reporting this! It appears to only be an issue in WebKit browsers. I'll fix for the next release.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/98e61114148e3659cf68fe4a3dfdfba890ad9354

**Comment by bencroker** [comment]
Released in [2.12.1](https://github.com/putyourlightson/craft-campaign/releases/tag/2.12.1).
