### ISSUE TITLE
When synching a user group to a mailing-list, you cannot choose fullName - only firstname or lastname.

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-campaign#452]
Hi, 

We have Craft 4.5.13 with only fullNames in user profiles. 

Now when we synch a user group to a mailing list we get uncomplete names, because we can only choose either firstname or lastname.
 
For instance one user was telling us that instead of "Guten Tag Alpines Museum der Schweiz" he got a newsletter with "Guten Tag Schweiz". Which is funny, but not apparently not appreciated by them. 

It would be nice if in the dropdown there was "Full Name" option: 

<img width="262" alt="Bildschirmfoto 2024-02-07 um 08 36 33" src="https://github.com/putyourlightson/craft-campaign/assets/145828/096a7a37-8936-4bbe-b82b-15b362cd3d82">

Campaign is on version 2.12.0

Cheers  
Stefan

**Comment by bencroker** [comment]
Wow, that’s a funny coincidence! I assume that is because of the “der” in the name. So does that mean you were only outputting the last name? You should still be able to output the first name followed by the last name, which will be equivalent to the full name.

**Comment by outline4** [comment]
My specific problem is the we only have one name field in the mailing List. So synching the full name would be a great option. 

Also, we don't have firstname and lastname in the user section anymore. Just one name field. 

<img width="609" alt="Bildschirmfoto 2024-02-07 um 13 56 11" src="https://github.com/putyourlightson/craft-campaign/assets/145828/e8fee766-778e-4b21-b4c9-f196b8279db9">

So it would make sense to have a "full name" synch option. Woudn't it? 

Otherwise I could add a second name field that holds the firstname, only for the user group synch? hm?

Cheers  
Stefan

**Comment by bencroker** [comment]
Yes, but the first and last name still exist on a user, even if you can’t see them. Craft breaks the full name into two segments on save. So outputting a synced first and last name should still work. Can you please confirm?

**Comment by outline4** [comment]
No, it doesn't do it correctly. 

	{{ user.fullName }}
	
	vs.
	
	{{ user.firstName }} {{ user.lastName }}


E.g.  "Amt für Umwelt und Energie, Kanton Bern" will become "Amt Kanton Energie".
or "Alpines Museum der Schweiz" will become "Alpines der Schweiz"
or "APUS BIRDING / Orthoptera.ch" becomes "Apus Orthoptera.Ch"

I guess it takes the first two words as `firstName` and the last word as `lastName`

**Comment by bencroker** [comment]
That’s interesting! I guess it can be controlled using the config settings listed here: https://craftcms.com/docs/4.x/config/general.html#users

Nevertheless, I’ve added syncing of the `fullName` field from users to contacts, provided it exists on the contact field layout in https://github.com/putyourlightson/craft-campaign/commit/36a80c36cc671eb63797ed3b1781230eef7b9f20 and released in [2.12.1](https://github.com/putyourlightson/craft-campaign/releases/tag/2.12.1). Note that you’ll need to create a `fullName` field and assign it to contacts.

**Comment by outline4** [comment]
Thanks a lot for this! 

It all works out ♥️
