### ISSUE TITLE
Sendout and Campaign Status

### ISSUE THREAD

**Issue by billymedia** [putyourlightson/craft-campaign#457]
I know this is probably me missing something, but when i create a recurring sendout, no matter what i try it remains in a Draft status. And the campaign remains in pending status.

Therefore when i execute a sendout via the url, no emails are sent. Ive read the docs but im stuck.

**Comment by billymedia** [comment]
Update: When i clicked on Save and Preview, there was an error in my template, i fixed this, but subsequent save and previews wouldnt take it out of draft.

**Comment by bencroker** [comment]
So is it working for you now?

**Comment by billymedia** [comment]
yeh its working now, i had to delete the sendout, fix the template issue then recreate the sendout.
