### ISSUE TITLE
Campaign editor - autofill test email contact with current user

### ISSUE THREAD

**Issue by paolocoppo** [putyourlightson/craft-campaign#458]
When editing a campaign, we would like to automatically add the current user in the "Test email" block.

**Comment by bencroker** [comment]
That is already the case, if no test contact is selected. The only thing to be aware of is that a contact must already exist with the same email address as the current user. I’ve improved the wording of this for the next release in https://github.com/putyourlightson/craft-campaign/commit/3d05e9bcc1f6549d152a4b0557897cd641079091.

![screenshot-nTKAdtpo@2x](https://github.com/putyourlightson/craft-campaign/assets/57572400/dc742e9e-0fc2-4e83-bc61-a89232b83213)
