### ISSUE TITLE
Segment index fails to list segments after the first one has been created.

### ISSUE THREAD

**Issue by ellefsen** [putyourlightson/craft-campaign#46]
When the CP tries to fetch from "?p=admin/actions/element-indexes/get-elements" a 500 error is returned: "Class 'putyourlightson\campaign\services\Db' not found"

I created a new segment with a name and a rule that selects all users created after 01.01.2019. This causes the listing at /admin/campaign/segments to fail.

Probably just a missing import, but I could not locate where it's missing from the error message.

**Comment by putyourlightson** [comment]
Thanks for reporting this, we'll look into it and let you knwo what we find.

**Comment by putyourlightson** [comment]
Fixed in version 1.5.7.
