### ISSUE TITLE
Remove contact from list in stead of unsubscribing

### ISSUE THREAD

**Issue by mathieuser** [putyourlightson/craft-campaign#460]
Hi Ben/Campaign team!

I was wondering if it's possible to programmatically remove a contact from a list in stead of unsubscribing them. I have a system where there are users subscribed to lists based on a drop-down field (with a status). These will be in the hundreds, so the 'unsubscribed' contacts that stay behind kind of prevent a clear overview.

To be clear: I dont want to delete the user as in #387 , but only want to remove them from the list, leaving the contact in other lists.

Thanks in advance!

**Comment by bencroker** [comment]
Using a similar example, here’s how you can delete a contact’s subscription from a mailing list, without deleting the contact.

```php

use putyourlightson\campaign\Campaign;
use putyourlightson\campaign\events\UnsubscribeContactEvent;
use putyourlightson\campaign\services\TrackerService;
use yii\base\Event;

Event::on(
    TrackerService::class, TrackerService::EVENT_AFTER_UNSUBSCRIBE_CONTACT,
    function(UnsubscribeContactEvent $event) {
        Campaign::$plugin->mailingLists->deleteContactSubscription($event->contact, $event->mailingList);
    }
);
```
