### ISSUE TITLE
Scheduled campaigns get stuck in a sending loop despite 100% progress

### ISSUE THREAD

**Issue by acantes** [putyourlightson/craft-campaign#465]
### Bug Report

I have just migrated my client's website to Craft CMS v4 from v3, along with plugins. It's on the same server, but now upgraded from PHP 7.4 to 8.1.

My client has noticed that **scheduled** campaigns never complete to a status of Sent. They remain active despite having a progress of 100%. I have tried pausing the sendout and then re-activating the last batch which is always "to be sent to 0 recipients in [X] mailing lists". 

There is a looping task in the queue manager where it tries to continue to send to that last 0 person forever it seems, unless I spot this happening and pause the campaign and clear the queue.

I use AsyncQueue on the website.

I am happy to provide any files you may need to test this, and if you have any suggestions on what I should try please advise.

![screenshot1](https://github.com/putyourlightson/craft-campaign/assets/25502116/6ab0cf6e-2844-43ae-8e65-24fb91c07628)

![screenshot2](https://github.com/putyourlightson/craft-campaign/assets/25502116/1f1d59fa-256d-45b5-9fef-e0155910ece8)

![screenshot3](https://github.com/putyourlightson/craft-campaign/assets/25502116/177bf7e4-f9ef-49f4-a340-61d9d24deb22)

### Plugin Version

2.13.1

### Craft CMS Version

4.8.6

### PHP Version

8.1

**Comment by bencroker** [comment]
First of all, please update to the latest version of the plugin. Also, I highly discourage you from using the Async Queue plugin. It is known to cause all sorts of issues, including queue jobs not completing. I recommend a daemonised queue runner whenever possible, see https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms

**Comment by acantes** [comment]
Thanks Ben, I will have a read through and will update the plugin and how I manage the queue. This site has "just worked" until now so I have some catching up to do with regards to best practices. Feel free to close this issue. Thanks again.

**Comment by bencroker** [comment]
I’ll keep this open until you determine whether this solves the issue for you, which it may or may not.

**Comment by bencroker** [comment]
Any update on this, @acantes?

**Comment by acantes** [comment]
Not yet I'm afraid, but I will be pushing a big update to the client's website next Monday/Tuesday which will include changes to the queue running. If you can leave open for a further week please I'll have time to come back to this ticket then.

**Comment by bencroker** [comment]
Any update on this, @acantes?

**Comment by acantes** [comment]
Sorry for the update Ben. I finally went live with the website changes this morning and Campaign is working and sending all batches fine and completing sendouts as it should. Thanks for checking in on this.

**Comment by bencroker** [comment]
Glad to hear it!
