### ISSUE TITLE
Translations default to control panel language instead of site language

### ISSUE THREAD

**Issue by ellefsen** [putyourlightson/craft-campaign#47]
I've looked through the source and found reference to the current site being set in the getBody() method when generating a view for the email. It seems though that the correct language is not being set. Only if I change the CP language the correct language file is applied.

Is this just in my case or should the correct language be set based on the primary site?

**Comment by putyourlightson** [comment]
Thanks for reporting this. Are you seeing this happening on a front-end request or in the control panel?

**Comment by ellefsen** [comment]
With front-end requests and the CP the correct language is applied. When the email is sent the language falls back to "en" or whatever is set in the defaultCpLanguage general config

**Comment by putyourlightson** [comment]
Ok thanks, will look into fixing this soon.

**Comment by putyourlightson** [comment]
Another question, how are you seeing that the language is incorrent? Are you using the translate filter in your campaign email templates?

**Comment by ellefsen** [comment]
Yes, I'm using the `|t` filter for twig to show translations. If I try to display the current language with `{{ craft.app.language }}` I get `sv` on the frontend and `en` in my mailbox.

**Comment by putyourlightson** [comment]
Are you able to test locally? Adding this one line should hopefully fix it, which we will add in the next release.
https://github.com/putyourlightson/craft-campaign/blob/b6cc1ef125c3faf5b007fe8c99ebab8a7d760a0e/src/elements/CampaignElement.php#L609

**Comment by ellefsen** [comment]
It does reflect in `{{ craft.app.language }}` when I call it from the template, but the translations still look for values in /en/site.php rather than /sv/site.php. Perhaps it needs to be done earlier in the lifecycle?

**Comment by putyourlightson** [comment]
Your translated text is in the email template, correct? That is rendered just a few lines down...
https://github.com/putyourlightson/craft-campaign/blob/b6cc1ef125c3faf5b007fe8c99ebab8a7d760a0e/src/elements/CampaignElement.php#L612

**Comment by ellefsen** [comment]
Correct. It also runs through an mjml filter from superbig's plugin, but that should be irrelevant.

**Comment by putyourlightson** [comment]
Ok I'll do a local test and see what results I get.

**Comment by putyourlightson** [comment]
Just tested locally and it is working fine for me with the change I suggested applied. Can you double check your site's language is set to `sv` and that your translation file is set up correctly? If the issue persists then message me on slack or send an email with details to info@putyourlightson.net and I'll help with troubleshooting.

**Comment by ellefsen** [comment]
Resolved as of version 1.5.8
