### ISSUE TITLE
Localization after migration issue

### ISSUE THREAD

**Issue by atelierbim** [putyourlightson/craft-campaign#470]
### Bug Report

After updating to craft 5 + Campaign PRO 3.1.1, only the default language (english) remained ok.
The other languages are behaving strange:
- The title of the campaign is gone, the CKeditor field is empty.
- The Segment title in contact is "blank"
- In Segments the title is named "Segment + an ID number"
- Mailing list title is "untitled mailing list"
- Sendouts are named "Sendouts and an ID Number"

See screenshots

<img width="1301" alt="Capture d’écran 2024-05-02 à 09 07 57" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/96f8ab10-979c-43e8-bc3a-83785efc0625">
<img width="1224" alt="Capture d’écran 2024-05-02 à 09 08 09" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/889ffd6f-b52f-414a-9ac7-4ce0353016c5">
<img width="1125" alt="Capture d’écran 2024-05-02 à 09 08 19" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/739150f1-b73a-4081-864f-8303e2bcf53e">
<img width="463" alt="Capture d’écran 2024-05-02 à 09 10 31" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/8e32bf32-95c6-471c-b846-a3df70c8249f">
<img width="722" alt="Capture d’écran 2024-05-02 à 09 10 57" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/418f0d93-9150-4bc0-a80d-50f1c1e71ef3">
<img width="367" alt="Capture d’écran 2024-05-02 à 09 45 23" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/7ba244b8-9a3b-42a8-87ab-85f88581132e">
<img width="629" alt="Capture d’écran 2024-05-02 à 09 46 03" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/064b4c59-8528-4094-9ffd-8d6d747e9482">
<img width="462" alt="Capture d’écran 2024-05-02 à 09 46 23" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/5d88a261-5d00-4e3c-b37b-1f7e8cd919a6">
<img width="547" alt="Capture d’écran 2024-05-02 à 09 46 36" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/c0a5b11d-fd76-431c-8e55-c417f4275c76">
<img width="1406" alt="Capture d’écran 2024-05-02 à 09 46 50" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/92a083d2-d357-43c4-906c-141afe7b10dc">
<img width="879" alt="Capture d’écran 2024-05-02 à 09 47 08" src="https://github.com/putyourlightson/craft-campaign/assets/64537972/d60698b0-12dc-4b80-9488-26cd47308fb9">

### Plugin Version

3.1.1

### Craft CMS Version

5.1.0

### PHP Version

8.2

**Comment by bencroker** [comment]
Thanks for reporting this unusual behaviour. I’ll revisit the upgrade process using Craft 5.1.0 and see if I can fix this all up.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/813051b6096a12c6be8a1a56ef0b0a282e1bc0fb and released in [3.1.2](https://github.com/putyourlightson/craft-campaign/releases/tag/3.1.2). Let me know if that resolves all of the issues for you.
