### ISSUE TITLE
List segments in separate list

### ISSUE THREAD

**Issue by robinbeatty** [putyourlightson/craft-campaign#471]
### Feature Request

We have a lot of segments... 50+
Finding them in the sidebar is pretty awkward. Any chance we could look at moving segments to a list view (which is searchable) and opens a separate nested list of contacts?

**Comment by bencroker** [comment]
Segments are listed in an element index view, which is paginated and searchable. Do you perhaps mean the segments that are visible on the contact index page?

Having 50+ segments sounds very edge-case. Where exactly do you suggest they are listed?

**Comment by bencroker** [comment]
I thought about this some more, and it is pretty much the equivalent of having 50+ sections (sources) on the entry index page. Since this is a UI issue on the part of Craft, I’m going to suggest you open a feature request in https://github.com/craftcms/cms/discussions.
