### ISSUE TITLE
jQuery error with non-admin user: no content loading

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#472]
### Bug Report

I have added a non-admin user with all the correct permissions. However, the user doesn't see any content (no entries, no commerce orders,…), can't click the dropdown arrow in the sidebar, can't click the avatar to change user settings. The Chrome debug console says:
```
Uncaught SyntaxError: Unexpected token ';'
```
Followed by lots of other errors. The first error is this line:
```
window.Craft.canEditSegments = ;
```

### Plugin Version

3.1.2 Lite

### Craft CMS Version

5.1.1

### PHP Version

8.3.3

**Comment by bencroker** [comment]
Thanks for reporting that! Fixed in https://github.com/putyourlightson/craft-campaign/commit/8ca2d04cad3e20869a2d4250cd58f5249152c7a8 and released in [3.1.3](https://github.com/putyourlightson/craft-campaign/releases/tag/3.1.3).
