### ISSUE TITLE
Scheduled sendout only sending if another sendout is scheduled

### ISSUE THREAD

**Issue by a-rbsn** [putyourlightson/craft-campaign#477]
### Bug Report

The process goes as follows:

- We schedule a sendout for a campaign
- The sendout doesn't send
- But — if we schedule another sendout, the previous sendout is then triggered

If there are any logs or anything I can post to help, please let me know.

### Plugin Version

2.15.3

### Craft CMS Version

4.8.8

### PHP Version

8.2.19

**Comment by bencroker** [comment]
Have you created a cron job to run pending sendouts at regular intervals?
https://putyourlightson.com/plugins/campaign#running-pending-sendouts 

As per the docs at https://putyourlightson.com/plugins/campaign#scheduled:

> Scheduled sendouts require that you create a cron job as described in Settings → General Settings.

**Comment by a-rbsn** [comment]
@bencroker I swear I read the manual — thank you for pointing me in the right direction 🙌
