### ISSUE TITLE
Allow negated segmenting on campaign activity

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#482]
### Feature Request

Love that Campaign has the ability to segment on Campaign Activity (https://github.com/putyourlightson/craft-campaign/issues/244)

But today I was trying to create a segment of people who have NOT opened or clicked on a campaign so I can re-target them  incase they missed the first email, or need a reminder. 

Right now I export the list, export the segment and then in spreadsheet software manually determine who didn't have any activity and re-import the contacts into a new list, which is a bit involved.

Would it be possible to add this feature in a future release?

### Plugin Version

3.2.0 (pro)

**Comment by bencroker** [comment]
Thanks for the suggestion, I’ll look into adding this.

**Comment by bencroker** [comment]
How does this look to you? I’m assuming that “never opened” covers your use-case. One thing to keep in mind is that opens are not 100% reliable, since some email clients may block fetching images (which is how open tracking works).

![screenshot-8n3PQ80j@2x](https://github.com/putyourlightson/craft-campaign/assets/57572400/dcfbf387-0753-480b-8457-7f029bee56bf)

**Comment by adrianjean** [comment]
Ohhh — that would be fantastic! 
Agreed, it's not going to be 100% accurate (Email in general is a total guessing game), but that would be the case with my manual CSV approach as well, this saves me the CSV round trips!!

**Comment by bencroker** [comment]
Released in [3.3.0](https://github.com/putyourlightson/craft-campaign/releases/tag/3.3.0). Thanks again for the suggestion!

**Comment by johnwbaxter** [comment]
@bencroker Is there any chance this feature could be added to the Craft 4 compatible branch at all?

**Comment by bencroker** [comment]
Campaign 2 isn’t getting new features, but I’ve made an exception for you and added this in [2.18.0](https://github.com/putyourlightson/craft-campaign/releases/tag/2.18.0).

**Comment by johnwbaxter** [comment]
@bencroker You are the greatest human being of all time! Thank you! We've done the upgrade to Craft 5 on these sites in dev so we'll be moving onto the latest version later this year!
