### ISSUE TITLE
Segments show inconsistent number of contacts

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-campaign#484]
### Bug Report

Not sure what the issue is, but I'll describe what I'm seeing:
- I have a total contact list of 2,700 emails.
- I have a campaign (called "Launch follow-up") that I sent, and it had an open rate of about 45%. Which means 1215 opened the email and 1485 didn't
- I have other sent campaigns in the system as well, from previous sendouts.

In Segments:
- I create a new segment
- I select `Campaign Activity`
- I select `Opened the campaign`
- I select the "Launch follow-up" campaign
- I save the segment. 

<img width="760" alt="Screenshot 2024-07-14 at 8 12 13 AM" src="https://github.com/user-attachments/assets/63f29938-0f8b-4f35-b1a4-d7b69498b1e0">

When I look at the number of contacts returned by the segment, it's not only well above the 1215 I would have expected. It's something like 2,412. 

If I use the new feature in segments to filter the number of people who have NOT opened the campaign — using the same settings as above, I get an even larger number: 2,937 — this is more contacts than I have in the system.

So it feels like the segment is not scoping down to the campaign that I selected, and seems to be pulling in data from other campaigns?

If I scope the segment down to say activity within the last 7 days (the email was send out 3 days ago) I get a super small number like 63.

Help?

<img width="799" alt="Screenshot 2024-07-14 at 8 12 22 AM" src="https://github.com/user-attachments/assets/23c2cc39-7b04-4fdc-a63f-c004cff81377">

### Plugin Version

3.4.0 pro

### Craft CMS Version

Craft Pro 5.2.5

### PHP Version

8.3.9

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed the display issue in https://github.com/putyourlightson/craft-campaign/commit/67a725069e0f371460c731267aa9fac3de9992c7, for the next release. 

You can test it by running `composer require "putyourlightson/craft-campaign:dev-develop as 3.4.1"`.

**Comment by adrianjean** [comment]
Confirmed!!! - works great. Thank you for such a quick fix!

**Comment by bencroker** [comment]
Released in [3.4.1](https://github.com/putyourlightson/craft-campaign/releases/tag/3.4.1).

**Comment by bencroker** [comment]
Released in [3.4.1](https://github.com/putyourlightson/craft-campaign/releases/tag/3.4.1).
