### ISSUE TITLE
Emoji in subject

### ISSUE THREAD

**Issue by StuartMcD** [putyourlightson/craft-campaign#486]
### Bug Report

Unsure if its a you or them issue but I've just upgraded to craft 5 and now I can no longer add emoji to the subject. 

Whilst I can add them, on save, they're replaced with `????`

With my limited understanding, could it relate to charset referenced here: https://craftcms.com/docs/5.x/upgrade.html#configuration ?

### Plugin Version

3.4.1

### Craft CMS Version

5.2.9

### PHP Version

8.2

**Comment by bencroker** [comment]
What specific emoji are you using? I tested locally and it’s working fine with the emojis I tried. Can you ensure that your character set is `utf8mb4` and collation is `utf8mb4_0900_ai_ci` (or `utf8mb4_unicode_ci` for MariaDB) in the database, specifically the `title` column of the `elements_sites` table? If not then perhaps you missed a step in the Craft 4 → 5 upgrade process.

**Comment by StuartMcD** [comment]
No expert but it appears to meet the requirements. Some work others are replaced 😎 = ???? , ⚽ = ⚽,  💩 = ????,  😂 = ????,  🍷= 🍷

**Comment by bencroker** [comment]
Can you show me where they are replaced? And what database and version are you running? Here’s what it looks like when I test locally.

![screenshot-6ifUv70J@2x](https://github.com/user-attachments/assets/b130bcd7-8b21-4cda-a32a-2fc361ef00cb)

**Comment by StuartMcD** [comment]
![Screenshot_20240802-180553](https://github.com/user-attachments/assets/d13b68aa-6a11-48ad-bbce-2c13d7112615)
![Screenshot_20240802-180529](https://github.com/user-attachments/assets/d44ce0d6-379c-4d9e-9132-1ff71a956f97)

Before save and after save. On mobile ATM, images are back to front

**Comment by bencroker** [comment]
Can you test the same emojis in the title of an entry to help narrow down if this is a general issue with your setup? And what database and version are you running?

**Comment by StuartMcD** [comment]
It's system wide, it's night time here, so bear with me.

![Screenshot_20240802-182736](https://github.com/user-attachments/assets/47e5f7f2-eedf-4ef8-a6a9-8cd0391d652b)

**Comment by StuartMcD** [comment]
Feels like a system something, knee jerk, first mail out after upgrade 4 > 5 and I noticed it.
Park it for now to free up your time for other stuff. Thx so much for assist to date.

**Comment by bencroker** [comment]
Ok, this likely to be something Craft support can help you with. I see you’re using MariaDB which may have something to do with it.
