### ISSUE TITLE
Import fails beceause of not required field not being used

### ISSUE THREAD

**Issue by joostclevis** [putyourlightson/craft-campaign#487]
### Bug Report

When importing a new list of contacts, there is only one required field (email). 
There are other fields, but they are not required.

If i import a list it will not import the contacts. In the logs i get the error Fieldname_XXX is invalid.
The Fieldname_XXX is a dropdownlist with a couple of options.

### Plugin Version

3.4.1

### Craft CMS Version

5.2.7

### PHP Version

8.2.22

**Comment by bencroker** [comment]
Can you show me the format you’re using for the dropdown field values? And are all contacts failing to import or just a few specific ones?

**Comment by joostclevis** [comment]
@bencroker All the contacts fail except the ones that are already in the system and have already chosen an option.

This is the dropdown field:

<img width="590" alt="Screenshot 2024-08-20 at 13 47 48" src="https://github.com/user-attachments/assets/e3b76c4c-99ef-49b7-a3e9-33f799437805">

**Comment by bencroker** [comment]
The dropdown field doesn't appear to accept a blank string. Does selecting a default option make any difference? If not, then adding a blank value as one of the options should work.

**Comment by joostclevis** [comment]
@bencroker Adding a deafault selected option or adding a blank option makes the import work.

**Comment by bencroker** [comment]
Glad to hear that worked!
