### ISSUE TITLE
Can you create a campaign programmatically?

### ISSUE THREAD

**Issue by ajhaupt7** [putyourlightson/craft-campaign#49]
Is it possible to create campaigns programmatically like you can with contacts (i.e. using `$contact = new ContactElement();`)? I'm building a newsletter that needs to take its content from an Entry rather than simply creating new Campaigns. So I was thinking I could write a plugin that converts an Entry to a Campaign rather than having to copy/paste.

**Comment by putyourlightson** [comment]
Sure, you'd do it just like any other element.
```
$campaign = new CampaignElement();
$campaign->campaignTypeId = 5;
$campaign->title = $entry->title;
...
Craft::$app->elements->saveElement($campaign);
```

A better approach might be to add an entries field to your campaign type and limit it to 1 entry. Then in your newsletter template you'd simply get the entry and output its fields.
```
{% set entry = campaign.myEntryField.one() %}
{% if entry %}
    {{ entry.title }}
{% endif %}
```

**Comment by ajhaupt7** [comment]
Fantastic -- thanks for your help!
