### ISSUE TITLE
Documentation: add "designer.sendune.com" to the Designing Templates section

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#491]
### Feature Request

You might want to add [SENDUNE, a HTML email designer](https://designer.sendune.com/) [open source project](https://github.com/SendWithSES/Drag-and-Drop-Email-Designer), which is very good, to the "Designing Templates" section documentation.

### Plugin Version

2.15.3

**Comment by bencroker** [comment]
Thanks for the suggestion! Added to https://putyourlightson.com/plugins/campaign#tools
