### ISSUE TITLE
Improve translation

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#492]
### Support Request

Here are some parts of the plugin that I can't find in the translation file (I might be wrong).
![CleanShot 2024-09-01 at 11 50 36@2x](https://github.com/user-attachments/assets/25b9c0b5-5c73-40b8-8d1d-8c10a96a85eb)
![CleanShot 2024-09-01 at 11 53 21@2x](https://github.com/user-attachments/assets/760e6028-52e4-4a64-8675-1455b2a671f7)
![CleanShot 2024-09-01 at 11 54 42@2x](https://github.com/user-attachments/assets/c2c2975f-7c40-403e-8bfe-1c74c5d09e7c)
![CleanShot 2024-09-01 at 11 57 12@2x](https://github.com/user-attachments/assets/5a05bf18-20b2-4bdb-8c76-169e06906dc7)

### Plugin Version

2.15.3

**Comment by bencroker** [comment]
Thanks, I added the missing translation placeholders.
