### ISSUE TITLE
Subscription status not showing

### ISSUE THREAD

**Issue by joostclevis** [putyourlightson/craft-campaign#494]
### Bug Report

When i add a contact to a mailing list, i get the notification that the contact is subscribed and i see the subscription status change from none to subscribed. If i reload the page, the status says none. If i try to subscribe to contact again, i get the following error message:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '301226-219361' for key 'idx_fakcaygyicgsxcbhexsritkrmfcnqxtrxkxd' The SQL being executed was: INSERT INTO `campaign_contacts_mailinglists` (`contactId`, `mailingListId`, `subscribed`, `sourceType`, `source`, `subscriptionStatus`, `dateCreated`, `dateUpdated`, `uid`) VALUES (301226, 219361, '2024-09-10 07:28:26', 'user', '1', 'subscribed', '2024-09-10 07:28:26', '2024-09-10 07:28:26', '1f62e88f-6e2f-4018-9d6a-a6b2f41e5b1e')

### Plugin Version

3.4.3

### Craft CMS Version

5.3.5

### PHP Version

8.2.23

**Comment by bencroker** [comment]
I’m unable to reproduce. The `Integrity constraint violation` error appears to imply that the contact is already subscribed to the mailing list, but I’m not sure why the status says `none` on reloading the page. Can you please check for errors in the browser console and network tabs?

**Comment by joostclevis** [comment]
@bencroker this is when i try to add an address again:

XHRPOST
[https://www.domainname.com/index.php?p=admin/actions/campaign/contacts/subscribe-mailing-list&site=default&v=1725966415025](https://www.domainname.com/index.php?p=admin%2Factions%2Fcampaign%2Fcontacts%2Fsubscribe-mailing-list&site=default&v=1725966415025)

POST
	https://www.domainname.com/index.php?p=admin/actions/campaign/contacts/subscribe-mailing-list&site=default&v=1725966415025

When i add it for the first time there are no error.

**Comment by bencroker** [comment]
I’m not really seeing anything useful in those URLs. Might a video with the network tab open with the response show more?

**Comment by joostclevis** [comment]
@bencroker I can sent you a link to a google drive file with a video. I couldn't add support@​putyourlightson.​com as a viewer to the file. What email address should i use?

**Comment by bencroker** [comment]
Please email a shareable link to support@​putyourlightson.​com.

**Comment by joostclevis** [comment]
Done!

**Comment by bencroker** [comment]
Thanks for the sending the video! This turned out to be an issue that only affected draft contacts. Existing contacts are unaffected by it.

Fixed in https://github.com/putyourlightson/craft-campaign/commit/9dcbd7b64b61edd14c5421f5c4a6c2d613c6f649 for the next release, which should be early next week.

**Comment by bencroker** [comment]
Release in [3.5.0](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.0).
