### ISSUE TITLE
Possible bug when exporting contacts

### ISSUE THREAD

**Issue by fancy-pug** [putyourlightson/craft-campaign#495]
### Bug Report

I am not sure if this is a bug or caused by other plugins. 
When I try to export a member list as csv, the csv file contains other data than the members.

What could effect the export function?

![1-download](https://github.com/user-attachments/assets/f7f1a222-c020-4c04-973e-9ed6e9b23917)
![2-csv-file](https://github.com/user-attachments/assets/19b727e4-210c-4c93-a5a3-01bf841ac2ee)

### Plugin Version

2.17.3

### Craft CMS Version

4.11.5

### PHP Version

8.2

**Comment by bencroker** [comment]
The exported CSV file should contain all of the contacts subscribed to the currently selected mailing list (including all custom fields on the contacts). What kind of extra data are you seeing?

**Comment by bencroker** [comment]
Thanks for reporting this, I'll test exporting a mailing list locally and let you know what I find.

**Comment by fancy-pug** [comment]
I attached a screenshot of the csv file opened in libre office. There is only one row without user data

**Comment by bencroker** [comment]
Can you please check whether there is a contact that is a draft or that is trashed? I suspect that may be the source of the row in question.

![screenshot-2lyHdMco@2x](https://github.com/user-attachments/assets/c6bbc09c-29ea-469c-adeb-9641864b441b)

**Comment by fancy-pug** [comment]
There are 0 drafts  and 0 trashed and 1089 active contacts.

**Comment by fancy-pug** [comment]
In which php class does the export process start?

**Comment by bencroker** [comment]
Oh, I see it now. You’ve exported a mailing list called “Medlemmer”. If you want to export contacts subscribed to a mailing list, you’ll need to do that from the contact element index page.
