### ISSUE TITLE
Project config issues

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#496]
### Bug Report

I'm setting up a website with Campaign. I just setup some campaign types and mailing list types. However, when I push these to my staging server, I notice they are not being pushed with project config. Is there no project config support? On the staging and/or live server, I'm not allowing admin changes so the menu option Campaign > Settings is not there. How can I get my campaign and mailing list types from local to staging to live?

### Plugin Version

3.4.3

### Craft CMS Version

5.4.3

### PHP Version

8.3.8

**Comment by bencroker** [comment]
Both campaign types and mailing list types are stored in project config. Can you double check whether they exist in your local project config files? If not, perhaps running the console command `project-config/write` will force project config to be written to the YAML files. Be sure to run `project-config/apply` (or a command that implicitly applies it) in your staging/production environment to apply project config changes after deploying.

**Comment by bartrylant** [comment]
It seems that at first there were no yaml files created, the second time there were yaml files, the third time I did `project-config/write` and `craft up` which caused an sql error. Anyway, it seems to be fixed now and indeed the types are in project config files.

**Comment by bencroker** [comment]
Ok, glad to hear it’s working now.
