### ISSUE TITLE
Sync users automatically

### ISSUE THREAD

**Issue by livingtech** [putyourlightson/craft-campaign#498]
### Support Request

Hello,

I am trying your Campaign plugin for craft and I would like to know the following. I enabled the user registration and created a register page with the template that Craft CMS gives us (https://craftcms.com/knowledge-base/front-end-user-accounts). After loggin in, the user should be redirected to his profile page, where he has the fields for name, e-mail, telefon and so on, that he can change. On the same page I would like to display the mailing lists, where he can choose what mailing list he would like to subscribe or unsubscribe. Now, for that to work, he needs a CID and UID and to do that, we need to go in back-end and sync the users group. The question is, can that be done automatically, as soon as the user registers on the website? Without us having to go in back-end and sync it manually?

Greetings

**Comment by livingtech** [comment]
I created a new user now and I noticed it subscribed to both my test mailing lists. So that would be just perfect, but in the documentation, it says the admin has to sync them in back-end. But now I think I understood, the sync has to be done once, between the user group and the mailing list and in the future will stay syncronized. We don't have to do it every time a user registers.

**Comment by bencroker** [comment]
> But now I think I understood, the sync has to be done once, between the user group and the mailing list and in the future will stay syncronized. We don't have to do it every time a user registers.

That's correct, you'll only need to manually sync the user group and mailing list and the rest will happen automatically when users are assigned to one or more user groups.
