### ISSUE TITLE
Improve French translation

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-campaign#499]
### Feature Request

Sorry, I've found a few more messages that need translation. 
![CleanShot 2024-09-29 at 17 55 10@2x](https://github.com/user-attachments/assets/7e925e75-3473-40f5-9afc-8e9b8c35fd97)
![CleanShot 2024-09-29 at 17 50 35@2x](https://github.com/user-attachments/assets/902eecf2-f659-4c09-8b04-c0a3005cf705)
![CleanShot 2024-09-29 at 17 59 53@2x](https://github.com/user-attachments/assets/e55b608b-8f67-4bb1-be5e-bb9893a945c5)

**Comment by bencroker** [comment]
Most if not all of those should already be prepared for translation. Please create a pull request for specific translations into French.

**Comment by scandella** [comment]
Sorry, I can't find any entry in the translation file for this drop-down menu.
![CleanShot 2024-09-29 at 17 55 10@2x](https://github.com/user-attachments/assets/0168f073-26bd-47a5-805f-025fb643f1c4)

**Comment by scandella** [comment]
And for these "Subscribed" and "unsubscribed" messages, they are translated when we edit the contact, like in the attached picture, but not when we display the contact.
![CleanShot 2024-09-29 at 18 14 23@2x](https://github.com/user-attachments/assets/da0eebde-fc7d-4394-9631-1b24a6deb26f)

**Comment by bencroker** [comment]
Ok, thanks for the clarification, I’ll take a look.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-campaign/commit/c114322afc09536c059274d0d8b733df2db11ffe. Please provide translations via a pull request to the develop branch.

**Comment by bencroker** [comment]
Released in [3.5.1](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.1).
