### ISSUE TITLE
Error upon opening campaign

### ISSUE THREAD

**Issue by Geestig** [putyourlightson/craft-campaign#5]
After making a new campaign I seem to be unable to save the campaign except for when I have the preview window open. Even though I get an error it still saves and I can use the campaign for sendouts. However when I try to reopen the campaign to edit something I get the following error.

![afbeelding](https://user-images.githubusercontent.com/9035369/39426036-730afc62-4c7e-11e8-9696-79c24c79ded1.png)

I was wondering what could be causing this issue.

EDIT:
by removing the 'clicked desc' part in ReportsService.php:235 it works as intended. However i'm not sure what this might break in the future.

**Comment by putyourlightson** [comment]
This is a known bug and was fixed for beta 12, which is not quite ready. In the meantime I've updated to beta 11.1 to fix this issue for you.

**Comment by Geestig** [comment]
Thanks man, awesome plugin btw!

**Comment by putyourlightson** [comment]
Thanks, any suggestions welcome! The stable release should be out in the next week or so.
