### ISSUE TITLE
Sendouts fails to complete if there are emoticons in htmlBody

### ISSUE THREAD

**Issue by ellefsen** [putyourlightson/craft-campaign#50]
We've encountered an issue where sendouts fail to achieve sent state. It's likely because the insertion of htmlBody in craft_campaign_sendouts fail when the html contains certain emoticons. 

To replicate try using camera  with flash 📸 or tangerine 🍊. Umbrella and the older ones seem to work fine.

```2019-01-27 18:05:07 [-][276][-][error][craft\queue\QueueLogBehavior::afterError]  [6938] Sending "Nyhetsbrev 2" sendout [batch 5] (attempt: 9) - Error (time: 0.309s): SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x93\xB8 <...' for column `craftcms`.`craft_campaign_sendouts`.`htmlBody` at row 1```

**Comment by putyourlightson** [comment]
As you correctly observed, this was only happening with emojis that are made up of 4 byte Unicode characters. They need to be encoded when using MySQL without a `utf8mb4` character set. 

Added a fix for this in v1.6.1.
