### ISSUE TITLE
Make the "From names and emails" section accept ENV vars

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-campaign#503]
### Feature Request

Honestly, I don't know why people seem to want to be able to change this or have different options, but they do, so although I'm sure I've asked this before I cannot recall your response (:grimacing: ) so I'm once again humbly asking if we can please make the From email data options accept ENV vars as below in my fictional scenario?

![image](https://github.com/user-attachments/assets/4288fada-d23f-42fe-a865-fdc68d114a19)

Thank you!!

### Plugin Version

Version 2.17.6 (we're still on craft 4 for the very short term on this client)

**Comment by bencroker** [comment]
Added and released in versions [2.17.7](https://github.com/putyourlightson/craft-campaign/releases/tag/2.17.7) and [3.5.6](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.6).
