### ISSUE TITLE
Can't enter existing sendout.  Key "color" for sequence/mapping with keys "label" does not exist.

### ISSUE THREAD

**Issue by okolvik-avento** [putyourlightson/craft-campaign#507]
### Bug Report

I can't enter sendouts that have the status "Pending". It doesn't seem to have a color assigned.

https://github.com/putyourlightson/craft-campaign/blob/cdd594269cfe5300369250bd6ac0cd6334f77ad0/src/elements/SendoutElement.php#L220

![image](https://github.com/user-attachments/assets/22850c9f-4a7a-4692-9061-dab2c67d0301)

### Plugin Version

3.5.7

### Craft CMS Version

5.5.5

### PHP Version

8.2

**Comment by bencroker** [comment]
Thanks for reporting that! Fixed in https://github.com/putyourlightson/craft-campaign/commit/35ed35fdb3db282eb8c602e4fe6e27220bb38883 for the next release.
