### ISSUE TITLE
Icon confused me

### ISSUE THREAD

**Issue by djamieson33** [putyourlightson/craft-campaign#509]
### Bug Report

Hello,

I was going to use a field but then saw the icon in there in the dropdown and thought it was just a text field. Any chance you can update this?  I know it's nothing critical, but it would help me properly identify what kind of field it is.

<img width="342" alt="Screenshot 2024-12-12 at 12 46 02" src="https://github.com/user-attachments/assets/23c938dc-19b0-43a4-a704-1afcce51d9a0" />

Thanks,
Dwayne

### Plugin Version

3.5.8

### Craft CMS Version

Craft Pro 5.5.6.1

### PHP Version

8.3.14

**Comment by bencroker** [comment]
Thanks for reporting this! I’ve changed the icons in https://github.com/putyourlightson/craft-campaign/commit/6cfb4245b1e5c641269df6c95284ca02e306b713, for the next release.

![screenshot-pgeXgRpW@2x](https://github.com/user-attachments/assets/cab7734f-de34-46a5-9a9e-6540206fd88d)

**Comment by djamieson33** [comment]
Thanks Ben! By the way, I love the product.

**Comment by bencroker** [comment]
Released in [3.5.9](https://github.com/putyourlightson/craft-campaign/releases/tag/3.5.9).
