### ISSUE TITLE
Programmatically send e-mail to single user on certain date which is provided by Calendar plugin

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-campaign#51]
We plan to use a Calendar plugin but we need to have the option to send e-mail notifications on certain events or dates.
For example, in birthday calendar, to send birthday cards on the date of users birthday.
Or, in a business calendar, we would send an e-mail notification or a reminder for an upcoming meeting.

Does Campaign Pro have the option to programmatically send e-mail to users at certain time which is provided by Calendar plugin?

How would we go about it?

Thanks!

**Comment by putyourlightson** [comment]
Yes it does and the process can be done with just a few lines of code. Still though, it will require a custom module or plugin to listen for the calendar events, compose the email and activate the sending. If you'd like some pointers then I can get you some sample code and if you need help with the custom functionality then feel free to email details to info@putyourlightson.net and we can discuss in more detail.
