### ISSUE TITLE
Resend campaign/sendout to specific recipient/s

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#510]
### Support Request

We had a user accidentally mark our emails as spam. We removed his email from the Mailgun suppression list on his request, but would ideally like to be able to resend the campaign/sendout just to him.

Is the only way to do this duplicating the campaign and doing a new sendout just to him?

### Plugin Version

1.26.0

**Comment by bencroker** [comment]
You can send them a [Singular sendout](https://putyourlightson.com/plugins/campaign#singular), added in Campaign 2.0.0 for the Pro edition. If you’re stuck on Campaign 1 then a new regular sendout to a mailing list with just their email address would work.
