### ISSUE TITLE
Contacts will not delete

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#52]
Craft CMS 3.1.15
Campaign 1.6.7
Campaign Pro 1.0.0

Deleting a user does not remove them from database.

Video here http://cloud.johnhenry.ie/b9bb84ad146f

**Comment by putyourlightson** [comment]
Since Craft 3.1, deleting any element will soft delete it, meaning that it is trashed for 30 days. That is why you are still seeing the contact in the database and if you filter contacts by "Trashed".

**Comment by john-henry** [comment]
ah so obvious now thanks Ben
