### ISSUE TITLE
Fields do not map for Contacts after Import or Sync

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#53]
Craft CMS 3.1.15
Campaign 1.6.7
Campaign Pro 1.0.0

If I either Import or Sync from a User group to Contact, no fields I have added map any data

See video here http://cloud.johnhenry.ie/b947d22b9859

Fields include a date field, lightswitch and a dropdown

**Comment by putyourlightson** [comment]
Thanks for the video John! This appears to be working when syncing from a user group. Fixed when importing from a user group in version 1.6.8.
