### ISSUE TITLE
Question: If I have to manually map a field on import will it fail in Sync?

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#54]
So I have a few fields named with an ampersand

For example '**Egg & Sausage**' and field handle would be `eggSausage`

The field was added to Contact Settings

In initial import for users to contacts I have to manually map the field as it doesn't automatically pick it up. Other fields are fine

My concern is that now that I have set up a Sync, that this field will not update correctly if it didnt catch it in Import.

Would I have reason to be concerned?

**Comment by putyourlightson** [comment]
Syncing is not quite the same as importing, as only the custom fields used for the users are synced to the contacts. In other words you shouldn't have to worry about fields not updating.

As a side note, if you are syncing a user group to a mailing list then there is no need to perform an import. Make sense?

**Comment by john-henry** [comment]
Ok great. Yes understood on import but as first install thats what Im gonna do first to test it out!
