### ISSUE TITLE
Keep getting “can’t invoke one() on null variable” errors

### ISSUE THREAD

**Issue by phoob** [putyourlightson/craft-campaign#56]
I just can’t figure out where it goes wrong.. see message here:

https://sentry.dfo.no/share/issue/546a669f7f39481cb7a7046e1622665d/

**Comment by phoob** [comment]
Hmm.. nevermind. I believe it might be due to an error in my plaintext email template.. Edited it, and it seems it might have solved the problem.

**Comment by a-rbsn** [comment]
@phoob would you be able to give any detail on how you fixed this issue? My email is working fine in the email template but not in plaintext.

**Comment by bencroker** [comment]
Glad to hear it!

**Comment by phoob** [comment]
> @phoob would you be able to give any detail on how you fixed this issue? My email is working fine in the email template but not in plaintext.

Sorry, @a-rbsn , this was so long ago I don't remember.

**Comment by bencroker** [comment]
@a-rbsn you can test your code in a regular template with `devMode` enabled, which should make it easier to catch any errors.
