### ISSUE TITLE
Event on mailing list subscription

### ISSUE THREAD

**Issue by ockam** [putyourlightson/craft-campaign#6]
Is there an event or another way to track when a user has subscribed to a mailing list?

I need to forward each subscriber to an external CRM.

**Comment by putyourlightson** [comment]
No, but I'll add this in the next release. When would you ideally need this by?

**Comment by ockam** [comment]
Hi Ben,

thank so much for the prompt response and this generous offer.

The client has not approved the project yet and when she does, we’ll have a few weeks ahead of us.

Anyway, if you plan to add this feature, I’ll take it when it’s ready. :)

**Comment by putyourlightson** [comment]
Ok, it'll be in the next release.

**Comment by putyourlightson** [comment]
Here you go:
https://github.com/putyourlightson/craft-campaign/blob/1.1.3/src/services/TrackerService.php#L157
