### ISSUE TITLE
Segment contact plain text fields are missing

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#60]
My contacts have a lot of fields. All very simple and the bulk just plain text.

http://cloud.johnhenry.ie/1699f0e6c7f0

When I goto create a segment, all that shows are dropdown fields, email and a date field.

http://cloud.johnhenry.ie/591f32b678a4

Plain text fields seem to be missing

Craft CMS 3.1.19

Campaign Pro 1.7.2

**Comment by john-henry** [comment]
@putyourlightson I think I know the issue. They are Incognito fields , set to render pain text but non-the less probably not supported by Campaign

**Comment by john-henry** [comment]
Other though are native dropdowns and the don't work either

**Comment by putyourlightson** [comment]
The supported fieldtypes for segments as of version 1.7.2 are:

- Plaintext
- Number
- Date
- Lightswitch

I'll add the following to the next release:

- Dropdown
- Email
- URL

Should that suffice for your use case?

**Comment by john-henry** [comment]
Yes great thanks. Ill try and hack in the Incognito field for now

**Comment by putyourlightson** [comment]
I'll add a config setting for you to easily add extra fields.

**Comment by putyourlightson** [comment]
Just released 1.7.3. There is a config setting that will allow you to add the Incognito field as follows:


    // Extra fields and their operators that should be available to segments
    'extraSegmentFieldOperators' => [
        'mmikkel\incognitofield\fields\IncognitoFieldType' => [
            '=' => 'is',
            '!=' => 'is not',
            'like' => 'contains',
            'not like' => 'does not contain',
            'like v%' => 'starts with',
            'not like v%' => 'does not start with',
            'like %v' => 'ends with',
            'not like %v' => 'does not end with',
        ]
    ],

**Comment by john-henry** [comment]
@putyourlightson Thats amazing support. Trying it out later on.

**Comment by john-henry** [comment]
Works great. Closing
