### ISSUE TITLE
FR: Can dropdown field in segments show original dropdown field

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#61]
This is a feature request.

When creating a segment and if a dropdown is used can the value field switch to a dropdown showing values of said field? 

I can't trust client (or myself) to type correct label/value(?) from dropdown field

I know there are already conditions in place for Date and Lightswitch field. Hoping that can be extended to Dropdown.

**Comment by putyourlightson** [comment]
I like it! I'll have to consider if and how to still allow custom values in addition to what is available in the dropdown field so that regular expression functionality is not lost.

**Comment by putyourlightson** [comment]
Added in 1.8.0.
