### ISSUE TITLE
FR: Can I use unsubscribeUrl in regular template?

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#62]
Would you consider doing the same as you have for https://craftcampaign.com/docs/mailing-lists#mailing-list-subscribe-form and creating a Mailing List Unsubscribe form?

Also a way of checking whether somebody is subscribed to a Mailing list or not so you can create logic to show either form in templates. The user would be logged in for this.

Alternatively beign able to use `unsubscribeUrl` in a template same as an email template

**Comment by putyourlightson** [comment]
Here is how you can get the subscribed mailing lists for a logged in user.

```
{% set contact = craft.campaign.contacts.userId(currentUser.id).one() %}
{% set mailingLists = contact.getMailingLists() %}
```

Then to unsubscribe, create a form and post to the controller action using an AJAX request:

```
<form id="unsubscribe-form" method="post" action="">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="campaign/contacts/unsubscribeMailingList" />
    <input type="hidden" name="contactId" value="{{ contact.id }}" />
    <input type="hidden" name="mailingListId" value="{{ mailingList.id }}" />
</form>

<script>
    // Get data by serializing the form 
    var data = $('#unsubscribe-form').serialize();

    $.post('', data, function(response) {
        if (response.success) {
            alert('Successfully unsubscribed.');
        }
        else {
            alert(response.error);
        }
    });
</script>
```

**Comment by john-henry** [comment]
Great thanks
