### ISSUE TITLE
Ability to set reply-to address

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#64]
It would be cool if there would be a way to set a reply-to email address. According to Mailgun, it is best-practice to send from a subdomain (like mailgun.domain.com), but at the same time you should use that domain as your "from" domain, so e.g. info@mailgun.domain.com. It would be nice if we were able to add a reply-to address, so we can use the subdomain for sending, and e.g. info@domain.com as the reply-to address.

**Comment by putyourlightson** [comment]
Thanks for the suggestion. I remember that Gmail had an issue where it was failing to reply to _reply-to_ email addresses. I'll need to look into whether that was resolved and will then consider adding this ability.

**Comment by putyourlightson** [comment]
Added in 1.8.0.
