### ISSUE TITLE
How to create unsubscribe link ?

### ISSUE THREAD

**Issue by domin97** [putyourlightson/craft-campaign#65]
How to create unsubscribe link to remove email from the mail list (for example if someone got  a newsletter should be possibility to remove this email from mail list after click in any link)?

**Comment by putyourlightson** [comment]
You can use `{{ unsubscribeUrl }}` to create a URL in a campaign that when clicked will unsubscribe a contact from the mailing list.

See the docs: https://craftcampaign.com/docs/email-templates

**Comment by domin97** [comment]
Thanks
