### ISSUE TITLE
cannot resume a sendout

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#66]
Hello,

after a have clicked "Pause" oder "Pause and Edit", it seams i am not able to resume the sendout.
![Bildschirmfoto 2019-04-18 um 09 21 20](https://user-images.githubusercontent.com/48832704/56344784-93a11a00-61be-11e9-8c55-d996e7217f80.png)

Additionally, after a sendout is scheduled, i get an error in browser console, and the "Expected Recipients" never get shown again.

![Bildschirmfoto 2019-04-18 um 09 45 59](https://user-images.githubusercontent.com/48832704/56345042-188c3380-61bf-11e9-9c22-9d26a0995739.png)

Kind regards

**Comment by krizzzly** [comment]
might be in vendor/putyourlightson/craft-campaign/src/resources/js/SendoutEdit.js

```
        getPendingRecipientCount: function() {
            if ($('.pendingRecipientCount').length) {
                $('.preflight .message').html(
                    $('.preflight .message').html().replace('{recipients}', '<span class="pendingRecipientCount"></span>')
                );

                var url = Craft.getActionUrl('campaign/sendouts/get-pending-recipient-count');
                var sendoutId = $('input[name=sendoutId]').val();

                $.get(url, {sendoutId: sendoutId}, function(data) {
                    $('.pendingRecipientCount').replaceWith(data);
                });
            }
        },
```

It tries to update the modal, but at this stage the Sendout Modal is not there anymore

**Comment by putyourlightson** [comment]
Thanks, I'll fix the Javascript error in the next release. 

To resume sending a paused sendout, you need to click on _Save and Preview_ and follow the process once more.

<img width="341" alt="Screenshot 2019-04-18 at 22 34 36" src="https://user-images.githubusercontent.com/2318222/56389565-2cb94a80-622a-11e9-9963-ae03c62ed2aa.png">

**Comment by thijskaspers** [comment]
Just to be sure, after resuming a paused sendout, it won't send the email again to recipients that have already received the email?

**Comment by bencroker** [comment]
Yes, that is correct.
