### ISSUE TITLE
Automated Sendout not sending and webhook 500 error

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-campaign#67]
Not sure where to start or if this is all related.

I have a **campaign** for a welcome email when a contact is automatically subscribed when synced. This is orange and **pending** as I presume all campaigns associated with automated sendouts are?

I have the **automated sendout** set-up to send when subscriber is added but it never sends.

I have cron task setup and tested according to your docs

Issue is that new contacts do not get this welcome email. A pending task is created in control panel but just goes on and on. Im using Queue Manger and also AsyncQueue

In our Mailgun logs I see a ton of these

`Will retry in 3600 seconds: postmaster@skillssummary.ie → https://www.mydomain.com/actions/campaign/webhook/mailgun?key=VyliRDDNXR2h6L2b5Q Server response: 500`

When I visit that URL I get 

> Bad Request
> Post request required

The key matches what I have in control panel.

Any help would be appreciated

**Comment by putyourlightson** [comment]
I don't think the two are related. I will investigate the Mailgun webhook issues separately.

> A pending task is created in control panel but just goes on and on.

Do you mean a queue job or a pending sendout? Have you tried manually queuing pending sendouts using the Campaign Utility?

**Comment by john-henry** [comment]
Yes have tried manual pending sendouts. I mean a queue job with a pending send-out. it goes from pending to reserved and then disappears after a while. Ill make a video and send it to you privately

**Comment by putyourlightson** [comment]
Sounds good.

**Comment by putyourlightson** [comment]
Turns out the automated sendout was stuck in a status of _Sending_. Pausing and restarting the sendout resolved the issue.
