### ISSUE TITLE
Wrong site when requesting entries for new campaign

### ISSUE THREAD

**Issue by krizzzly** [putyourlightson/craft-campaign#68]
Hello, we have added a matrix field to a campaign type, so the user can add entries, e.g. news entries.
Whenever we are on the english site, and do: "new campaign", we get a selection of news entries from another language site. We have to save the campaign and afterwards we can reopen it and get the right english news entries shown in the selection.

**Comment by krizzzly** [comment]
i guess its related to this craft cms [bug](https://github.com/craftcms/cms/issues/3954)

**Comment by putyourlightson** [comment]
Is this still happening in Craft 3.1.26? A bugfix was released to the issue you referenced above.

**Comment by krizzzly** [comment]
i guess 'yes', because i just updated to 3.1.26 and experience the same issue.

**Comment by putyourlightson** [comment]
Ok, I'll look into this, thanks.

**Comment by putyourlightson** [comment]
Fixed for the next release.
