### ISSUE TITLE
Update of Campaign: "Trying to get property 'name' of non-object"

### ISSUE THREAD

**Issue by webdevotion** [putyourlightson/craft-campaign#69]
When updating the plugin I'm met with:

> **One of Campaign’s migrations failed.** 
> `yii\base\ErrorException: Trying to get property 'name' of non-object`

Then I go back to the CP and am asked if I want to continue
with the pending changes to the database. I click continue
and am all up to date.

```
PHP 7.2.15
Craft Pro 3.1.26
Yii 2.0.17
```

**Comment by putyourlightson** [comment]
Thanks for reporting this. Do you know which version of the Campaign plugin you were previously on?
