### ISSUE TITLE
Contact import from user group fails

### ISSUE THREAD

**Issue by jcdarwin** [putyourlightson/craft-campaign#7]
When trying to import contacts from a user group, the task in the Craft admin UI show "Importing CSV file     Failed" (even though the import was via a user group, and not a CSV file).

The craft `storage/logs/queue.log` shows:

```
2018-05-17 22:26:47 [172.19.0.1][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [5] Importing CSV file. (attempt: 1) - Started
2018-05-17 22:26:48 [172.19.0.1][1][-][error][craft\queue\QueueLogBehavior::afterError]  [5] Importing CSV file. (attempt: 1) - Error (time: 0.202s): Invalid argument supplied for foreach()
```
Nothing of consequence in the `storage/logs/phperrors.log` or `storage/logs/web.log`

Note that this error is happening when the Campaign (1.1.2) and Campaign Pro (1.1.0) plugins are installed as trials -- would this have anything to do with the error? It's not clear in the plugins what is / isn't allowed in trial mode.

**Comment by putyourlightson** [comment]
I can't replicate this on my end. Do you have users in the user group and are you selecting any fields besides the required email field?

Trial mode should allow all functionality so it might be a bug, or at least could use a better error message.

**Comment by jcdarwin** [comment]
The problem seems to be that the contacts import failed because I didn't have any custom fields defined in the contact settings. When I defined a single custom field, I could then import all users from the specified user group.

Specifically, [the line that errors](https://github.com/putyourlightson/craft-campaign/blob/v1/src/services/ImportsService.php#L273) is the `foreach` in `importRow`.

**Comment by putyourlightson** [comment]
Thanks, I tracked this bug down and fixed in https://github.com/putyourlightson/craft-campaign/commit/9f05819b9c714d745524898ff57536f572d1a8f3
