### ISSUE TITLE
Unable to use emoji in subject field

### ISSUE THREAD

**Issue by ellefsen** [putyourlightson/craft-campaign#71]
Currently it throws a 500 error if you try to put next gen emojis in the subject field. Is it a limitation of Craft? I noticed you can't put emojis in entry titles either, but for an email subject it's a hot commodity.

**Comment by putyourlightson** [comment]
Just started writing a long message about how this isn't part of core blah blah blah...

And then added for the next release 😉

**Comment by ellefsen** [comment]
Thanks Ben!

**Comment by putyourlightson** [comment]
Thank you for the nudge!
