### ISSUE TITLE
Updated Plugin: Error Creating New Mailing List  'Trying to get property of non-object'

### ISSUE THREAD

**Issue by we-do** [putyourlightson/craft-campaign#72]
Updated the plugin this morning and noticed error when creating a mailing list and when viewing an existing list's entry page.

`yii\base\ErrorException: Trying to get property of non-object in /vendor/putyourlightson/craft-campaign/src/controllers/MailingListsController.php:69
Stack trace:
#0 /vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/wedo/Sit...', 69)
#1 /site/vendor/putyourlightson/craft-campaign/src/controllers/MailingListsController.php(69): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/Users/dev/Sit...', 69, Array)
#2 [internal function]: putyourlightson\campaign\controllers\MailingListsController->actionEditMailingList('newsletterSubsc...', NULL, NULL)
#3 /vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-mailing-li...', Array)
#6 /site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-mailing-li...', Array)
#7 /site/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('campaign/mailin...', Array)
#8 /vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('campaign/mailin...', Array)
#9 /site/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#10 /site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /site/web/index.php(21): yii\base\Application->run()
#12 {main}`

**Comment by putyourlightson** [comment]
Thanks for reporting this, we're working on a fix.

**Comment by putyourlightson** [comment]
Just released 1.9.1 with the fix, thanks again!

**Comment by we-do** [comment]
Thanks Ben! That was probably the fastest bugfix I've ever submitted :P

**Comment by putyourlightson** [comment]
You got me at a good time ;)
