### ISSUE TITLE
Feature Request: Work with Spoon

### ISSUE THREAD

**Issue by jmcgaha** [putyourlightson/craft-campaign#73]
I recently set up a new campaign type and I was unable to do the "Group block types" thing that the Spoon plugin offers to customize what blocks would show. It would be great if this feature was available.

I'm not sure if this is really a Spoon request or a Campaign request, so I'm going to post this on both repos.

https://github.com/angell-co/Spoon

**Comment by putyourlightson** [comment]
This is a Spoon request :)
https://github.com/angell-co/Spoon/issues/62#issuecomment-493570978
