### ISSUE TITLE
Contacts not saving category field

### ISSUE THREAD

**Issue by JustJarethB** [putyourlightson/craft-campaign#75]
Maybe I'm a noob but I can't see what I've done wrong in this code. Text fields are saving, but categories is not
```
{% for eventType in craft.categories.group('eventType').all() %}
        <label for="event" class="">
          <input id="event" type="hidden" name="fields[events][]" value="{{eventType.id}}" /> 
        </label>
 {% endfor %}
```
I've also tried using a Select but also no success

**Comment by putyourlightson** [comment]
It looks correct, can you show me the full form code? Also is the category field handle `events`?

**Comment by JustJarethB** [comment]
Sure, Here is the full form with labels etc.. removed. The field's slug is `events` and has been added to the contact field layout
```
{% set mailingList = craft.campaign.mailingLists.slug('signup-form').one() %}
<form id="subscribe-form" method="post" class="find_event text-white" action="">
    {{ csrfInput() }}
    <input type="hidden" name="action" value="campaign/t/subscribe" />
    <input type="hidden" name="mailingList" value="{{ mailingList.slug }}" />
    <input type="hidden" name="redirect" value="{{ '?subscribe-success=true'|hash }}" />

    <h3><label for="email"><span class="required">Email</span></label></h3>
    <input placeholder="example@mail.com" id="email" class="text-white appearance-none bg-transparent border-b-2 w-full mb-3 py-1 px-2" type="email" name="email" value="" required />

    <input placeholder="Jane" id="name" class="text-white appearance-none bg-transparent border-b-2 w-full mb-3 py-1 px-2" type="text" name="fields[firstName]" value="" required />

    <input placeholder="Smith" id="name" class="text-white appearance-none bg-transparent border-b-2 w-full mb-3 py-1 px-2" type="text" name="fields[lastName]" value="" required />

    <input id="event" type="hidden" name="fields[events]" />
    <div class="w-full flex flex-wrap mb-4">
      {% for eventType in craft.categories.group('eventType').all() %}
      <div class="w-1/2 lg:w-1/3 py-2">
        <label for="event" class="">
          <input id="event" type="checkbox" name="fields[events]" value="{{eventType.id}}" /> {{eventType.title}}
        </label>
      </div>
      {% endfor %}
    </div>
    <input type="submit" class="block bg-transparent mt-4 border-white text-sm border-2 text-white py-1 px-2 rounded mx-4 lg:mx-0 md:mx-0" value="Subscribe" />
</form>

```

**Comment by putyourlightson** [comment]
Ok I think I see the issue. Is this happening with a mailing list type that has _Double Opt-In_ enabled?

**Comment by JustJarethB** [comment]
Yes that is correct. Is there some thing where only email fName and lName are saved before a user confirms email or so?

**Comment by putyourlightson** [comment]
No, it is an issue with how relation fields are temporarily stored. We're working on a fix.

**Comment by JustJarethB** [comment]
Okay thanks. Is there any temporary work around? I tried removing the double opt-in and now the contact isn't saving at all
EDIT: The URL is still redirected to the success URL

**Comment by putyourlightson** [comment]
Remove the category field :)

**Comment by putyourlightson** [comment]
In my tests the contact saves as expected with double opt-in disabled. Can you please double check?

**Comment by JustJarethB** [comment]
Haha well sure, that could do it but then we wouldn't know what to put in the emails :(

Also, ignore the above message. It seems it was not adding an email address I had previously deleted, but did add a fresh email address

**Comment by JustJarethB** [comment]
Yes Ben, I can confirm the categories saved as expected with double opt-in disabled. Thanks for your help!

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/66a4d9d97b4772681aa0cd31ccfe140e3192e2f2
