### ISSUE TITLE
Craft Campaign settings are available when `allowAdminChanges` is set to `false`

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#77]
Title says it all. To reproduce: 

1. Disable admin changes: `'allowAdminChanges' => false,`
2. Navigate to domain.tld/`{{ cpTrigger }}`/campaign/settings

**Comment by putyourlightson** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-campaign/commit/062c0498e868ff8b390090f8a74999fdf40ac342.
