### ISSUE TITLE
Secrets are exposed if they are configured from code

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#78]
While configuring as per #76, I stumbled into the following issue: the secrets are revealed if I use a code snippet something like this: 

```
return [
    '*' => [
        'transportType' => craft\mail\transportadapters\Smtp::class,
        'transportSettings' => [
            'host' => getenv('SMTP_HOST'),
            'port' => getenv('SMTP_PORT'),
            'username' => getenv('SMTP_USERNAME'),
            'password' => getenv('SMTP_PASSWORD')
        ]
    ]
];
```

See the image below: 

![kepernyokep_20190609_214059](https://user-images.githubusercontent.com/9061795/59163315-9dc90000-8aff-11e9-802f-df691b26e30f.jpg)

**Comment by putyourlightson** [comment]
That is because you are parsing the variables using `getenv`. This should work and keep your environment variables secret.

```
return [
    '*' => [
        'transportType' => craft\mail\transportadapters\Smtp::class,
        'transportSettings' => [
            'host' => '$SMTP_HOST',
            'port' => '$SMTP_PORT',
            'username' => '$SMTP_USERNAME',
            'password' => '$SMTP_PASSWORD'
        ]
    ]
];
```

**Comment by Saboteur777** [comment]
Yes, it works that way, thanks! (although the former example seems more "Craft"-y to me)

The `$VARIABLE_NAME` doesn't work everywhere as expected: if the input field type is not `text`, then I still had to use `getenv()`, as e.g. `useAuthentication` always resulted in true except if the env value was 0 (`SMTP_USE_AUTHENTICATION=0`) and I used `getenv('SMTP_USE_AUTHENTICATION')`;

So I use this config for now: 

```
return [
    'dev' => [
        'transportType' => craft\mail\transportadapters\Smtp::class,
        'transportSettings' => [
            'host' => '$SMTP_HOST',
            'port' => '$SMTP_PORT',
            'useAuthentication' => getenv('SMTP_USE_AUTHENTICATION'),
            'encryptionMethod' => getenv('SMTP_ENCRYPTION_METHOD'),
            'username' => '$SMTP_USERNAME',
            'password' => '$SMTP_PASSWORD'
        ]
    ],

    'production' => [
        'transportType' => craft\mailgun\MailgunAdapter::class,
        'transportSettings' => [
            'apiKey' => '$MAILGUN_API_KEY',
            'domain' => '$MAILGUN_DOMAIN',
            'endpoint' => '$MAILGUN_API_ENDPOINT',
        ]
    ]
];
```

**Comment by putyourlightson** [comment]
This is the expected behaviour. Using a variable name is only possible in fields which state as such.

<img width="579" alt="Screenshot 2019-06-09 at 22 21 29" src="https://user-images.githubusercontent.com/2318222/59163724-f4850880-8b04-11e9-8f47-93a40da61491.png">

**Comment by Saboteur777** [comment]
"Using a variable name is only possible in fields which state as such." 

Well, that's why there is no blue text under the other fields. :) 
I could control those (dropdowns and checkbox) with env variables, too, though.

**Comment by putyourlightson** [comment]
Correct, they are not automatically parsed for environment variables, hence `getenv` is explicitly required. Alternatively you could hard-code them in.

```
'useAuthentication' => true,
```
