### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by josueochoa** [putyourlightson/craft-campaign#79]
Hey,

I'm running Craft locally on a Vagrant machine, i've set up multiple Syncs but none of the Users are being passed to the lists when updating/creating, also i tried importing them manually to no avail, all i get is a message in the top "successfully queued for importing". 

I have the Queue Manager plugin installed and i don't see any Queue pending/running, could this be a issue with my local server setup? is there any server requirements this plugin requires in order to get sync/import working correctly?

**Comment by putyourlightson** [comment]
There are no server requirements beyond what Craft requires. Can you please double check that the user group you are importing/syncing has users in it? Otherwise you can email details of your setup to info@putyourlightson.net and we'll try to help.
