### ISSUE TITLE
Double debug toolbar on live preview

### ISSUE THREAD

**Issue by piotrpog** [putyourlightson/craft-campaign#80]
If in my account settings i have debug toolbar set to both frontend and backend, it will show up in two instances if i enter live preview for email.

This was big once in craft cms itself but it was fixed some time ago:

https://github.com/craftcms/cms/issues/3347

**Comment by putyourlightson** [comment]
I'm unable to replicate this. What version of Craft/Campaign are you on and can you please send me a screenshot of what you are seeing? Also, are you sure that the debug toolbar isn't somehow being cached?

**Comment by piotrpog** [comment]
I have blitz cache installed. This might be it.

**Comment by putyourlightson** [comment]
It could be, can you test it?

**Comment by piotrpog** [comment]
@putyourlightson 
Hi, sorry for late reply. I will be able to test it on monday.

**Comment by piotrpog** [comment]
@putyourlightson 
Sorry for delay.
After disabling blitz and removing all cached pages, double debug toolbar still appeared.
It appeared ONLY when i had both displaying debug toolbar in control panel and frontend enabled.
One of debug toolbar appeared second or two after first appeared.

**Comment by putyourlightson** [comment]
I suppose this is actually expected behaviour. You are seeing the debug toolbar once in the CP and another time, after the delay, in the iframe (front-end).

**Comment by putyourlightson** [comment]
In saying that, I'm still not experiencing this issue locally.
