### ISSUE TITLE
Unsubscribe form with opt-out e-mail

### ISSUE THREAD

**Issue by disco666** [putyourlightson/craft-campaign#81]
Hi there, for some reason our clients needs to send his campaigns with the companies own software-solution but still needs to collect contacts via Craft/Campaign. What we are looking for is a form which creates a personal opt-out e-mail with an unsubscribe-link. Is that possible?

Thanks,
Lars

**Comment by putyourlightson** [comment]
Hi Lars, I think I'm following but I'd like to be sure. Can you please explain where the form should exist and what the user flow would be? 

-Ben

**Comment by disco666** [comment]
Hi Ben,
thanks for your reply. The form should inside a common template and be called at www.domain.name/newsletter-unsubscribe for example. This page should be accessible all the time to allow people to unsubscribe who registered before. As we have to send out the campaigns with another software we need another approach and a general unsubscribe-link for people to unsubscribe.
After submitting the e-mail-address the users should receive an e-mail with a personal unsubscribe link.

Cheers,
Lars

**Comment by putyourlightson** [comment]
Ok I see, thanks for the clarification. We have a feature in the works that will make this easier, but you'll likely still need a custom script to send the email. I'll post an update here soon with more details.

**Comment by putyourlightson** [comment]
I'm marking this as a feature request. Hopefully this will make what you are trying to do work natively. Will post an update when it is ready for release.

**Comment by disco666** [comment]
Great, thanks!

**Comment by putyourlightson** [comment]
FYI we have yet to document this but it is available as of version 1.10.0.

**Comment by putyourlightson** [comment]
Keeping this open until documented.

**Comment by disco666** [comment]
Hi Ben, thanks for your effort. When will the docs be ready? I'm on vacation from tomorrow and would like to implement the unsubscribe function before.

**Comment by putyourlightson** [comment]
Later this week. Until then, here's a code sample.

    <form method="post" action="">
        {{ csrfInput() }}
        <input type="hidden" name="action" value="campaign/forms/unsubscribe">
        <input type="hidden" name="mailingList" value="mailingListHandle">
        <label for="email">Email</label>
        <input type="email" name="email" value="">
        <input type="submit" value="Submit">
    </form>

**Comment by putyourlightson** [comment]
Docs here: https://craftcampaign.com/docs/front-end-forms

**Comment by disco666** [comment]
Thanks, it works exactly as needed.
