### ISSUE TITLE
Documentation for the include Google analytics toggle

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-campaign#83]
When configuring a sendout, there is a lightswitch for including Google analytics. It would be helpful if there was documentation on the expected output for each query string parameter, if those can be linked to specific fields, etc.

As an organization, we have specific naming conventions for our tracking string parameters. It would be great to have control over how the query string is generated. If not, we can generate our own strings at the template level to be included on all mailings, but would need a way to hide the lightswitch on the sendout configuration page.

**Comment by putyourlightson** [comment]
You're right that this is not documented. The query string parameters are:

```
utm_source=campaign-plugin&utm_medium=email&utm_campaign={sendoutSubject}
```

Good idea about making them cusomisable, I'll add this to the next release. Are the 3 parameters above sufficient for your use-case?

**Comment by raptureaid** [comment]
Yes, we would use `utm_source`, `utm_medium` and `utm_campaign`

One issue with using `{sendoutSubject}` to identify the campaign is it prevents the ability segment sendouts to a mailing list to A/B test a campaign - there's no way to identify the variants without using separate subject lines.

Using either the sendout or campaign title for `utm_campaign` would allow for better control in relating the tracking to specific campaigns/sendouts. That said, to best enforce naming conventions when multiple authors have permissions to add/edit/send campaigns it would be great if those titles could be set dynamically in the same manner Craft entries, etc. can be set.

**Comment by raptureaid** [comment]
Also, when using the include Google analytics lightswitch is this only updating the links as the email is sent out, or is there a way to include these on a web version of the campaign?

**Comment by putyourlightson** [comment]
Makes sense. So what variables would you ideally have access to when defining a dynamic `utm_campaign` parameter?

The lightswitch only appends the query string parameters to the clicked links in the emails that are sent out. The web version might benefit from having its own values to help differentiate from links clicked from actual emails.

**Comment by putyourlightson** [comment]
I'm considering removing the lightswitch field completely and making it possible to define query string parameters to append to all clicked links in the campaign. The value would be parsed and the `campaign` and `sendout` twig tags would be made available. Any thoughts on this approach?

<img width="633" alt="Screenshot 2019-07-25 at 22 06 07" src="https://user-images.githubusercontent.com/2318222/61905084-8071b900-af28-11e9-9bcb-83d61561dd13.png">

I should also clarify that the query string parameters are only appended to links that are clicked on in the email.

**Comment by raptureaid** [comment]
Yes, that would be fantastic. That would allow something like the following?

```
utm_source=campaign&utm_medium=email&utm_campaign={{ sendout.subject }}-{{ campaign.myCustomField }}
```

Any consideration about allowing this to be set globally for campaigns as part of the campaign type settings with an option to expose an override field on the individual campaign/sendout? Some users just can't be trusted to set that fields correctly...

**Comment by putyourlightson** [comment]
Yes, your use-case would be possible and it would be set on the campaign type, so non-admin users would not have any extra manual steps.

**Comment by putyourlightson** [comment]
Added the `Query String Parameters` field to campaign types and removed the `Google Analytics` lightswitch field from sendouts in version 1.10.0.
