### ISSUE TITLE
Is it possible to subscribe users via an API call? 

### ISSUE THREAD

**Issue by Saboteur777** [putyourlightson/craft-campaign#84]

**Comment by putyourlightson** [comment]
There is no public API to subscribe users, but you do it by sending a POST request from your site using the fields in the subscribe form:
https://craftcampaign.com/docs/mailing-lists#mailing-list-subscribe-form

**Comment by Saboteur777** [comment]
Thanks, will look into it!

**Comment by putyourlightson** [comment]
FYI some new controller methods are coming in version 1.10.0 that might be of interest.

**Comment by Saboteur777** [comment]
Thanks! :+1:
