### ISSUE TITLE
reCAPTCHA Multiple Renders

### ISSUE THREAD

**Issue by JustJarethB** [putyourlightson/craft-campaign#86]
It seems reCAPTCHA has some issues with being rendered multiple times on a single page. The following JS error occurs:
```Uncaught Error: reCAPTCHA has already been rendered in this element```

The `{{ craft.campaign.recaptcha }}` code has only been used once in the form, however the form has been rendered multiple times.

**Comment by putyourlightson** [comment]
Thanks for reporting this, we'll look into it and let you know what we find.

**Comment by putyourlightson** [comment]
Fixed in version 1.11.0.
