### ISSUE TITLE
Cannot create new contact if contact has been deleted

### ISSUE THREAD

**Issue by torgeirbeyer** [putyourlightson/craft-campaign#89]
After delelting one user we are not able to create a user with the same email adress again. 
![Skjermbilde 2019-10-03 kl  12 16 22](https://user-images.githubusercontent.com/43992745/66118839-a2965000-e5d7-11e9-927b-75e4343e07ec.png)

**Comment by john-henry** [comment]
Hey @torgeirbeyer It's likely still in **Trashed** after being deleted. Filter by that status and you will see it.
More on Craft CMS Garbage collection here https://docs.craftcms.com/v3/gc.html

For ref https://github.com/putyourlightson/craft-campaign/issues/52

**Comment by putyourlightson** [comment]
Precisely, thanks @john-henry!
