### ISSUE TITLE
Error when creating a new sendout

### ISSUE THREAD

**Issue by johnnyhawley** [putyourlightson/craft-campaign#90]
I'm getting an error:  "Undefined Offset: 2" when trying to create a new sendout.
https://sentry.io/share/issue/80dd177e982f462c8cbb27de66984a41/

**Comment by putyourlightson** [comment]
Can you go to the plugin's _Email Settings_ and save them before trying again? that should hopefully fix the issue, otherwise we'll need to release a fix for this.

**Comment by putyourlightson** [comment]
Fixed in version 1.12.1, thanks for reporting this!
