### ISSUE TITLE
Filter import based on user status

### ISSUE THREAD

**Issue by PixelGarden** [putyourlightson/craft-campaign#91]
It would be very helpful to be able to import (and sync) the user status from CraftCMS. 

For example -> when sending out mailings to users with an **_active_** status only and not to the ones with status _**pending/suspended**_.

**Comment by putyourlightson** [comment]
Thanks for the suggestion, we'll consider this a feature request.

**Comment by bencroker** [comment]
Just looked into this and currently only _active_ users are imported and synced. Is there any use-case for wanting to imort or sync non-active users?

**Comment by Saboteur777** [comment]
@bencroker There might be a use-case for this: if you manually subscribe users to a list during their registration and account verification is required. In this case the new user account is in pending status, but the contact is already enabled. 

@PixelGarden I think you can use the following segment code to filter out the active users: 


```
{% set userId = contact.userId %}
{% if userId %}
  {{ craft.users.id(userId).status('active').one() ? true : false }}
{% else %}
  {{ false }}
{% endif %}
```

The same for pending users: 

```
{% set userId = contact.userId %}
{% if userId %}
  {{ craft.users.id(userId).status('pending').one() ? true : false }}
{% else %}
  {{ false }}
{% endif %}
```

**Comment by bencroker** [comment]
Thanks for this solution @Saboteur777, I think it is sufficient.
