### ISSUE TITLE
Using categories as segment filter

### ISSUE THREAD

**Issue by PixelGarden** [putyourlightson/craft-campaign#92]
Segments is a great way to decide exactly which users to send mails to, but one functionality I am missing is to be able to add segments based on categories.

Adding the category field as possible segment filter would be really helpful.

**Comment by putyourlightson** [comment]
Thanks for the suggestion. What operators do you see being most important, for example, "is", "contains", etc. since a category field can contain zero or more categories.

**Comment by PixelGarden** [comment]
Thanks for getting back to me. 

I would like to be able to use it similar to the relatedTo condition in a query.

So let's say we have some category fields attached to the user object in Craft. Then I add the same category fields to Contacts in Campaign. 

After importing & syncing users the category fields are successfully copied/populated from the Craft users -> Campaign contacts. 

Then, when setting up the segments I would choose a category to filter on and select a category (or multiple) value as filter.

I created a mock-up to visualise it. If I would choose Subscription as segment filter and select a value (in this case "Launch promo", it would select only the contacts which have a "Launch promo subscription".

![Category_select](https://user-images.githubusercontent.com/4749777/67786172-ba45e480-fa6e-11e9-9114-bd184de01fb8.jpg)

Does that make sense?

**Comment by putyourlightson** [comment]
That doesn't quite answer the question, but makes sense in general, thanks for clarifying.

**Comment by bencroker** [comment]
Just an FYI that this is possible to achieve using conditions in Campaign 2.
