### ISSUE TITLE
Feature Request: Mailing List Field Type

### ISSUE THREAD

**Issue by JustJarethB** [putyourlightson/craft-campaign#93]
## Description
Request for an additional field type which lists the mailing lists available in the current site.
It could have similar filtering such as assets, where you can select which mailing list types are available. The output on the templates should be the list itself rather than a slug or id.

## Use Case
Say we have a modular page content setup, and want to include a (un/)subscription form to the list relevant to the content being mentioned, this would allow us to do so without creating additional templates or getting funky with dropdowns

**Comment by putyourlightson** [comment]
Thanks for submitting, we'll look into adding this.

**Comment by bencroker** [comment]
Added custom relation field types for campaigns, contacts and mailing lists in 1.13.0.
https://github.com/putyourlightson/craft-campaign/blob/develop/CHANGELOG.md#1130---2020-01-07
