### ISSUE TITLE
How to change default test email within all templates, including new ones

### ISSUE THREAD

**Issue by j2is** [putyourlightson/craft-campaign#94]
### Question
How do you change the default test email where it says "Send Test"?

### Additional context
You can click the cross to remove the email that's default and attach a new one, but how to set the default one that is present here even when creating a new template?

**Comment by bencroker** [comment]
The default email address for test emails is not fixed. Instead, it looks for a contact that matches the email address of the currently logged in user. So if user A is logged in then it will default to `userA@email.com` and `userB@email.com` if user B is logged in.

So I guess the answer to the question of how to change the default test email address is to change the email address in your account. Make sense?

**Comment by j2is** [comment]
Sounds good, I knew it would be something simple, thank you

**Comment by bencroker** [comment]
Sure thing!
