### ISSUE TITLE
FR: Only send recurring sendouts when there is new content

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-campaign#95]
I wouldn't know the best solution for this right away, but it would be very nice if recurring sendouts would only get sent when there is new content to show. E.g. you have a campaign that lists all the articles posted that day. It gets sent every day. Now suppose there is a day where no-one posted a new article on the website. As it is now, the recurring sendout will send a mail anyway, but won't have any articles to show. It would be cool if there was no mail being sent at all in this scenario.

**Comment by bencroker** [comment]
This is an interesting use-case. I suppose you could already achieve what you are describing with a template segment, for example:
```
{{ craft.entries.section('articles').count > 0 ? 1 : 0 }}
```
This returns `1` (true) only if there are one or more articles. So in the case that there are zero, there will be no recipients to send to in the sendout.

**Comment by arnogregorian** [comment]
Any updates on the enhancement? Would love to implement this, can I for example trigger a sendout from a module based on the logic as described by @bartrylant?

**Comment by bencroker** [comment]
@arnogregorian This issue has been closed for over 2 years. It might be possible to use a module to trigger sendouts, but it's not something that is trivial to do.
