### ISSUE TITLE
"Couldn't save campaign" error message

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#96]
### Describe the bug
When creating a second new campaign, receive `Couldn’t save campaign` error message.

### To reproduce
Steps to reproduce the behaviour:
1. Go to `Create a new campaign`
2. Enter title and click `save`
3. Campaign created
4. Go to `Create a new campaign` again
5. Error message `Couldn’t save campaign`

### Expected behaviour
I would expect the new campaign to save as per the previous one - or show an error message that explains the problem and how to fix it.

### Screenshots
Video of problem: https://jmp.sh/TmyPrlj

### Versions
- Plugin version: 1.12.2
- Craft version: Craft Pro 3.3.16.3

**Comment by bencroker** [comment]
Thanks for the thorough description and video! Can you please check what the values are for the `Campaign URI Format` fields in the campaign settings?

**Comment by iamkeir** [comment]
@bencroker thanks for getting back to me - this is actually a point of query I emailed separately about... I don't know what should go into those fields so they are currently `what/is/this/for?`

If you don't mind letting me know what they're for/what _should_ go in them, this might make the error go away :)

**Comment by bencroker** [comment]
Think of it the same way you'd think of the `Entry URI Format` for a section. It is how the URI will look when people access the campaign in the browser, so it could be `campaign/{slug}` for example. The error you are getting is because the URI is not unique (since you've set it to a fixed value).

**Comment by iamkeir** [comment]
@bencroker Thanks Ben, that's fixed it. Do I need a twig template for the `campaign/{slug}` view, or does it simply use the HTML email template?

**Comment by bencroker** [comment]
It will use the HTML template.
