### ISSUE TITLE
Mailing List Type field layout won't save

### ISSUE THREAD

**Issue by iamkeir** [putyourlightson/craft-campaign#97]
### Describe the bug
When adding custom fields to the field layout of a Mailing List Type, the fields do not save/persist.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Campaign > Settings > Mailing List Types
2. Add a new mailing list type (or edit existing)
3. Add one or more custom fields to the field layout
4. Click save
5. Edit the mailing list type you just created
6. Notice the field/s are no longer in the field layout

### Expected behaviour
Would expect to see the custom field/s in the field layout.

### Screenshots
Video of problem: https://jmp.sh/ntPvFIi

### Versions
- Plugin version: 1.12.2
- Craft version: Craft Pro 3.3.16.3

**Comment by bencroker** [comment]
Thanks, I can confirm this is indeed a bug and will work on a fix for the next release.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-campaign/commit/bcc71fb9cb8b2b264c4d5d526db876d437b0f879.

**Comment by iamkeir** [comment]
Do you have a timeframe on next release so I can keep an eye out?

**Comment by bencroker** [comment]
Likely today, I'll drop you a note.

**Comment by bencroker** [comment]
Just released 1.12.3.
